apache/apisix

- t/control/healthcheck.t
> test: ensure health check is run completely

- apisix/balancer.lua
- apisix/cli/ngx_tpl.lua
- apisix/schema_def.lua
- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
- t/APISIX.pm
- t/node/upstream-keepalive-pool.t
> feat: allow setting separate keepalive pool

- docs/en/latest/plugins/http-logger.md
- docs/en/latest/plugins/kafka-logger.md
- docs/zh/latest/plugins/http-logger.md
- docs/zh/latest/plugins/kafka-logger.md
> docs: clarify where the value comes from

- README.md
- docs/en/latest/how-to-build.md
- docs/zh/latest/README.md
- docs/zh/latest/how-to-build.md
> docs: don't repeat the same doc in the README

- .github/workflows/fuzzing-ci.yaml
- .gitignore
- t/fuzzing/requirements.txt
> test: make fuzzing-ci pass again

- apisix/admin/init.lua
Since it's part of the CLI, better print error on CLI compared to just in log
> chore: print error in CLI when json decode failed

- docs/en/latest/admin-api.md
fix: [399](https://github.com/apache/apisix-website/issues/399)
> docs: fix incorrect link

- apisix/cli/ngx_tpl.lua
- t/APISIX.pm
> chore: dismiss warning "load balancing method redefined"

- apisix/init.lua
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>
Fixes upstream serialization. Without it, it would fail due to circular references.
> chore: force encode upstream to avoid circular reference nesting

- docs/en/latest/FAQ.md
This PR will fix a description problem in our FAQ in English. 
- It helps explain how APISIX and APISIX Dashboard are related. Before this fix, the 'console interface' and 'web interface' are essentially describing a 'user interface' in different terms. So I decided to replace these phrases with 'user interface'. In this way, it is more straightforward. 
- According to the description in APISIX Dashboard, it is an experimental feature as of now. It is always good to remind potential users that this is an experimental feature.
- Replace 'APISIX' with 'Apache APISIX'
> docs: update EN FAQ

- docs/en/latest/install-dependencies.md
- docs/zh/latest/install-dependencies.md
fix: https://github.com/apache/apisix/issues/3236
> docs(install-dependencies): add stop the openresty after installed

- t/fuzzing/public.py
- t/fuzzing/serverless_route_test.py
- t/fuzzing/simpleroute_test.py
- t/fuzzing/vars_route_test.py
> test: avoid `from moudle_name import *`

- .gitignore
- t/fuzzing/requirements.txt
- t/fuzzing/serverless_route_test.py
- t/fuzzing/simpleroute_test.py
- t/fuzzing/upstream/nginx.conf
- t/fuzzing/vars_route_test.py
> test: use latest boofuzz

- apisix/plugins/ext-plugin/init.lua
> feat: increase ext-plugin timeout to 60s

- powered-by.md
Updated by July 9, 2021 User logo, and sorted by English name A-Z
> docs: update powered-by file

- docs/en/latest/FAQ.md
- docs/zh/latest/FAQ.md
> docs: How to fix `unable to get local issuer certificate` error

- apisix/schema_def.lua
- t/admin/upstream-array-nodes.t
- t/admin/upstream.t
It is required by:
https://lists.apache.org/thread.html/r59f6104cb683288367b99724e2c39a028a83d80077fbeed30f9e55a3%40%3Cdev.apisix.apache.org%3E
> feat: allow additional properties in upstream

- docs/en/latest/admin-api.md
**modify nodes property description of the upstream object config, the previous config desc is not a correct json format.**
modify here:
[https://github.com/apache/apisix/blob/master/docs/zh/latest/admin-api.md](url)
`# 等价于 "nodes": { {"host":"host", "port":80, "weight": 100} },`
> docs: modify the nodes property description

- docs/zh/latest/admin-api.md
**modify nodes property description of the upstream object config, the previous config desc is not a correct json format.**
modify here：
[https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md](url)
`# is the same as "nodes": { {"host": "host", "port": 80, "weight": 100} },`
> docs: modify nodes property description

- powered-by.md
> docs: update powered-by.md

- conf/config-default.yaml
> fix: invalid discovery servers setting in config-default.yaml

- .gitignore
- t/fuzzing/public.py
- t/fuzzing/requirements.txt
> test: avoid hardcode in the fuzzing test

- docs/en/latest/stand-alone.md
- docs/zh/latest/stand-alone.md
> docs: fix standalone mode yaml config

- conf/config-default.yaml
> chore: prevent people to submit an issue before updating the yaml lib

- docs/en/latest/plugin-develop.md
- docs/zh/latest/plugin-develop.md
> docs: don't need to modify config-default.yaml to add your plugin

- t/cli/test_etcd_healthcheck.sh
fix https://github.com/apache/apisix/runs/3057036474
> test: ensure apisix containers recover in test_etcd_healthcheck.t

- apisix/discovery/consul_kv.lua
- apisix/schema_def.lua
- apisix/upstream.lua
- t/node/upstream-discovery.t
> feat(discovery): check node format

- apisix/cli/ngx_tpl.lua
- apisix/core/config_etcd.lua
- conf/config-default.yaml
> fix(stream): missing shdict to store etcd health check info

- t/misc/patch.t
> test: update request to adapt server's change

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
This change is required because it changes the rankings of installation methods mentioned in "How to build Apache APISIX" page. It follows the original pattern of listing the installation methods, reference: http://apisix.apache.org/docs/apisix/how-to-build#2-install-apache-apisix.
> docs: adjust installation options

- docs/en/latest/install-dependencies.md
- docs/zh/latest/install-dependencies.md
> docs: remove unnecessary tls step on Mac

- apisix/discovery/nacos.lua
> fix: host pattern for nacos host

- .github/workflows/fuzzing-ci.yaml
- t/fuzzing/client_abort.py
- t/fuzzing/public.py
- t/fuzzing/upstream/nginx.conf
> test: check leak for client abort

- Makefile
- apisix/plugins/ip-restriction/init.lua
- apisix/stream/plugins/ip-restriction.lua
- conf/config-default.yaml
- t/stream-plugin/ip-restriction.t
> feat(stream): add ip-restriction

- t/misc/patch.t
>  test: update request to adapt server's change again

- apisix/plugins/gzip.lua
- conf/config-default.yaml
- docs/en/latest/config.json
- docs/en/latest/plugins/gzip.md
- t/admin/plugins.t
- t/debug/debug-mode.t
- t/lib/server.lua
- t/plugin/gzip.t
> feat: add gzip plugin

- apisix/cli/ngx_tpl.lua
- t/cli/test_stream_config.sh
> feat(stream): allow to set trust certificate

- docs/zh/latest/certificate.md
Fixes the wrong description in `certificate.md.`
Fixes #4639
Hi @Yiyiyimu  @mytsing520 @spacewander, how does this look?
Let me know if this needs any changes.
Thanks
> docs: fix wrong description in certificate.md

- t/admin/proto.t
> test: make t/admin/proto.t stable

- apisix/admin/proto.lua
- apisix/admin/routes.lua
- apisix/admin/ssl.lua
- apisix/admin/stream_routes.lua
- apisix/admin/upstreams.lua
1. replace duplicate content with already declared variables
2. clean up unused code
> chore: replace duplicate content with already declared variables

- README.md
- docs/es/latest/README.md
- docs/zh/latest/README.md
added new user case of Sina Weibo
> feat: added Sina Weibo usercase to README file category

- docs/en/latest/how-to-build.md
make the doc desc consistent with the case
> docs: make the doc desc consistent with the case

- docs/en/latest/FAQ.md
- docs/zh/latest/FAQ.md
Collate some common questions from the community and issue
> docs: Add some questions and answers to the FAQ

- docs/en/latest/mtls.md
- docs/zh/latest/mtls.md
Add about setting CA certificate for etcd in `mtls.md`.
> docs: Set the CA certificate for etcd in mtls.md

- docs/en/latest/getting-started.md
- docs/en/latest/how-to-build.md
- docs/en/latest/plugins/gzip.md
- docs/zh/latest/getting-started.md
- docs/zh/latest/how-to-build.md
Add clarifications for note blocks.
https://github.com/apache/apisix/pull/4660#pullrequestreview-715542762
> docs: add Note clarifications

- apisix/core/config_etcd.lua
- apisix/core/etcd.lua
refactor the logic of getting etcd_cli and remove duplicate code
> refactor: refactor the logic of getting etcd_cli

- .github/workflows/chaos.yml
Since still got no luck in #4654 to figure out the reason of the unstable chaos test, I'll fix tmate misconfiguration in this PR to avoid further inconvience.
> ci: fix tmate action config error in chaos test

- docs/en/latest/getting-started.md
- docs/zh/latest/getting-started.md
> docs: change key in example

- t/APISIX.pm
- t/lib/test_admin.lua
> test: save a port in the test framework

- apisix/plugins/zipkin.lua
> chore(zipkin): don't refer to a released ctx

- apisix/core/ctx.lua
- t/core/ctx2.t
> fix: the _graphql was incorrectly cached under ctx.var but not ctx

- .github/workflows/centos7-ci.yml
- .github/workflows/chaos.yml
- .github/workflows/fuzzing-ci.yaml
> ci: fix more concurrency problem

- apisix/admin/consumers.lua
- apisix/admin/global_rules.lua
- apisix/admin/init.lua
- apisix/admin/plugin_config.lua
- apisix/admin/plugin_metadata.lua
- apisix/admin/proto.lua
- apisix/admin/routes.lua
- apisix/admin/services.lua
- apisix/admin/ssl.lua
- apisix/admin/stream_routes.lua
- apisix/admin/upstreams.lua
- apisix/upstream.lua
- t/node/not-exist-upstream.t
Let's migrate the existing code from 500 to 503.
> chore: avoid using 500 as it will be captured as APISIX's bug

- apisix/init.lua
- t/admin/api.t
> feat(admin): set Server header to APISIX

- utils/check-category.py
See https://github.com/apache/apisix/pull/4710#issuecomment-890888265
> ci: guide contributor to fix the category

- README.md
- docs/ar/README.md
- docs/es/latest/README.md
- docs/zh/latest/README.md
update expired user case links
> docs: update 360 user case link.

- apisix/plugins/cors.lua
- t/config-center-yaml/global-rule.t
- t/plugin/cors.t
- t/plugin/cors2.t
> feat(cors): validate allow_origins

- docs/en/latest/getting-started.md
- docs/zh/latest/getting-started.md
update getting started, remove the note APISIX Dashboard is an experimental feature for now, for it can be used actually
> chore: remove note APISIX Dashboard is an experimental feature for now

- powered-by.md
> docs: fix markdown render with image

- apisix/balancer/chash.lua
- apisix/core/utils.lua
- t/core/utils.t
- t/node/chash-hashon.t
> fix(balancer): ensure fallback for chash balancer with vars_combinations can work

- apisix/plugins/consumer-restriction.lua
- docs/en/latest/plugins/consumer-restriction.md
- docs/zh/latest/plugins/consumer-restriction.md
- t/plugin/consumer-restriction.t
Fix https://github.com/apache/apisix/issues/4755
> feat(consumer-restriction): add route_id type support

- apisix/core/utils.lua
- t/core/utils.t
> feat: parse_addr supports IPv6 without brackets

- docs/zh/latest/install-dependencies.md
> docs: sync install-dependencies.md

- apisix/plugins/ext-plugin/init.lua
> perf(ext-plugin): use new API to improve setting body

- docs/en/latest/customize-nginx-configuration.md
- docs/zh/latest/customize-nginx-configuration.md
**Related issues**
fix/resolve: https://github.com/apache/apisix/issues/4828
> docs: update file path of the ngx_tpl.lua

- apisix/cli/ngx_tpl.lua
- conf/config-default.yaml
- t/cli/test_core_config.sh
> feat(cli): add options to configure max timers

- .github/workflows/fuzzing-ci.yaml
- t/fuzzing/public.py
- t/fuzzing/simple_http.py
> test: fuzz with the simple http case

- .asf.yaml
> ci: protect release branches from deleted

- .github/ISSUE_TEMPLATE/bug_report.yml
> ci: only confirmed bug can use 'bug' label

- .github/stale.yml
> ci: add stale bot

- conf/config-default.yaml
The original number is too low. The same settings are also used by Kong.
> feat: increase timers limitation

- apisix/core/string.lua
- apisix/core/utils.lua
- apisix/plugins/real-ip.lua
- t/plugin/real-ip.t
This logic is the same with Nginx's ngx_http_realip_module.
> feat(real-ip): add special handling to X-Forwarded-For

- apisix/plugins/uri-blocker.lua
- docs/en/latest/plugins/uri-blocker.md
- docs/zh/latest/plugins/uri-blocker.md
- t/plugin/uri-blocker.t
Add custom rejected message for uri-blocker plugin.
> feat(uri-blocker): add custom rejected message

- apisix/core.lua
- apisix/core/ip.lua
- apisix/plugins/ip-restriction/init.lua
- apisix/plugins/real-ip.lua
- docs/en/latest/plugins/real-ip.md
- t/plugin/real-ip.t
> feat(real-ip): support specifying trusted addresses

- apisix/plugins/uri-blocker.lua
- docs/en/latest/plugins/uri-blocker.md
- docs/zh/latest/plugins/uri-blocker.md
- t/plugin/uri-blocker.t
> feat(uri-blocker): add case insensitive switch

- apisix/plugins/ip-restriction/init.lua
They are guaranteed by the schema check.
> chore(ip-restriction): remove redundant length check

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
The project provides docker file / build scripts to build APISIX OpenResty
Fix #4912.
> docs: refer to the whole apisix-build-tools project for building APISIX OpenResty

- README.md
fix: [515](https://github.com/apache/apisix-website/issues/515)
> docs: update Readme File

- apisix/plugins/http-logger.lua
- apisix/plugins/kafka-logger.lua
- apisix/plugins/udp-logger.lua
- apisix/utils/batch-processor.lua
unify some return type in logger handlers, rather than mix nil with false.
> style: unify some return type in logger handlers

- apisix/plugin_config.lua
- t/node/plugin-configs.t
fix the bug: 
route plugin cannot update when the plugin_config changed in the second time
> fix(plugin_config): recover plugin when plugin_config changed

- docs/en/latest/stream-proxy.md
- docs/zh/latest/stream-proxy.md
> docs: we support mTLS on L4

- apisix/plugins/kafka-logger.lua
- docs/en/latest/plugins/kafka-logger.md
- t/plugin/kafka-logger.t
1. add brokers info to log
2. update docs
> chore(kafka-logger): add brokers info to log and update docs

- t/cli/test_prometheus.sh
> test: correct the assertion message in prometheus test

- apisix/admin/plugins.lua
- apisix/control/v1.lua
- apisix/plugin.lua
- apisix/plugins/ip-restriction.lua
- apisix/stream/plugins/ip-restriction.lua
- docs/en/latest/admin-api.md
- docs/en/latest/control-api.md
- docs/zh/latest/admin-api.md
- t/admin/plugins.t
- t/control/schema.t
> feat(admin): return stream plugin info

- README.md
- docs/en/latest/external-plugin.md
add python plugin runner link address.
> docs: add python plugin runner link.

- apisix/core/response.lua
- apisix/init.lua
- apisix/plugin.lua
- t/debug/debug-mode.t
- t/plugin/example.t
> feat(debug): deduplicate response headers

- docs/zh/latest/plugins/openid-connect.md
add Authentication through OIDC Relying Party flow description
> docs(openid-connect): add Authentication through OIDC Relying Party flow description

- README.md
- docs/zh/latest/README.md
Due to ASF's Slack limitation, the invitation link is unavailable, so I have to update the Slack invitation description
> docs: update Slack invitation description

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
> chore(ci): remove unnecessary github env var

- apisix/admin/plugin_metadata.lua
- apisix/api_router.lua
> chore: avoid injecting ip-restriction twice to interceptors_schema

- docs/zh/latest/config.json
- docs/zh/latest/discovery/eureka.md
- docs/zh/latest/discovery/nacos.md
> docs(discovery): add eureka and nacos

- docs/en/latest/control-api.md
See https://github.com/apache/apisix/pull/5019#issuecomment-915722678
> docs(control): make it clear

- t/chaos/utils/setup_chaos_utils.sh
> test: pin the version of k8s to support chaos mesh

- apisix/control/v1.lua
- docs/en/latest/control-api.md
- t/control/routes.t
Add new API for dumping config in control api
> feat(control): add new dump route config api for control api

- docs/en/latest/discovery/dns.md
See https://github.com/apache/apisix/pull/5023/files#r705594923
> docs(discovery): make dns query order clear

- docs/en/latest/discovery/nacos.md
- docs/en/latest/internal/testing-framework.md
> docs: correct example and description

- README.md
- docs/zh/latest/README.md
> docs: add casbin and keycloak in README.

- docs/zh/latest/config.json
- docs/zh/latest/control-api.md
- docs/zh/latest/health-check.md
- docs/zh/latest/plugin-develop.md
- docs/zh/latest/plugins/server-info.md
this PR adds a Chinese version of control-API.md
resolve #5006
> docs: add Chinese version of control-api.md

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/request_help.yml
> chore: ask for the version of plugin runner

- t/config-center-yaml/plugin.t
- t/debug/hook.t
> chore: avoid defining read_file repeatedly

- apisix/plugins/gzip.lua
- t/plugin/gzip.t
> fix(gzip): schema typo

- t/plugin/gzip.t
> test: gzip test may fail because size may be validated before number

- docs/en/latest/external-plugin.md
- docs/zh/latest/external-plugin.md
Add a link to javascript plugin runner.
https://github.com/apache/apisix/issues/5106
> docs(external-plugin): add a link to javascript plugin runner

- docs/zh/latest/config.json
- docs/zh/latest/router-radixtree.md
add router-radixtree chinese document
> docs: add router-radixtree chinese document.

- apisix/http/router/radixtree_host_uri.lua
- t/router/radixtree-host-uri3.t
> fix(radixtree_host_uri): correct matched host

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
Fix https://github.com/apache/apisix/issues/4902
> docs(stream_routes): now support CIDR to match addr

- apisix/admin/plugins.lua
- apisix/control/v1.lua
- apisix/plugins/batch-requests.lua
- apisix/plugins/error-log-logger.lua
- apisix/plugins/log-rotate.lua
- apisix/plugins/node-status.lua
- apisix/plugins/server-info.lua
- benchmark/server/conf/nginx.conf
- docs/en/latest/plugins/node-status.md
- docs/zh/latest/plugins/node-status.md
- t/admin/plugins.t
- t/control/schema.t
> chore(plugin): add scope equals to global attribute for some plugins

- docs/en/latest/plugins/skywalking.md
- docs/zh/latest/plugins/skywalking.md
This PR cleans up and enhances en/zh documentation of the SkyWalking Plugin .
- Fixes grammar/vocab error
- Bumps up the SkyWalking version mentioned
> chore: clean up SkyWalking docs

- apisix/plugins/request-validation.lua
- docs/en/latest/plugins/request-validation.md
- docs/zh/latest/plugins/request-validation.md
- t/plugin/request-validation.t
> feat: add rejected_message support for plugin request-validation

- .asf.yaml
- .github/workflows/centos7-ci.yml
- .gitignore
- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/config.json
- docs/en/latest/how-to-build.md
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/config.json
- docs/zh/latest/how-to-build.md
- rockspec/apisix-2.10.0-0.rockspec
> feat: release 2.10.0

- docs/zh/latest/config.json
- docs/zh/latest/plugins/gzip.md
- docs/zh/latest/plugins/real-ip.md
https://github.com/apache/apisix-website/issues/544
> docs: add gzip and real-ip zh docs

- apisix/cli/ops.lua
- ci/linux_apisix_current_luarocks_runner.sh
Also remove the unnecessary sudo
> test: dismiss the ulimit too small warn

- t/plugin/skywalking.t
* [] Have you added corresponding test cases?
> test: make t/plugin/skywalking.t stable

- docs/zh/latest/architecture-design/upstream.md
fix: bind route to correct upstream_id
> docs: bind route to correct upstream_id in the example

- CONTRIBUTING.md
- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
1. User-facing documents about testing are not concise and contain unnecessary internal details. So remove it.
2. Add more links to the document of the testing framework. So people can find their way to it easier.
> docs: improve docs about testing

- docs/en/latest/architecture-design/upstream.md
- docs/zh/latest/architecture-design/upstream.md
> docs: fix the code block language

- docs/en/latest/install-dependencies.md
- docs/zh/latest/install-dependencies.md
- utils/install-dependencies.sh
Adopt the installation script so that it can works on archlinux.
Signed-off-by: Yujia Qiao <rapiz3142@gmail.com>
> feat: Support installation on arch

- .github/PULL_REQUEST_TEMPLATE.md
> docs: document the PR manners of APISIX

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
Along with the release of apisix 2.10.1, the relevant rpm artifact for el7 has also been supported. This PR is going to update the installation guide for the new rpm.
> docs: Update RPM installation guide for apisix 2.10.1

- t/APISIX.pm
- t/node/grpc-proxy-unary.t
Avoid occasional "failed to find any SSL certificate by SNI: test.com"
error. See apache/apisix/runs/4059734404?check_suite_focus=true
> test: the http2 is missing which causes weird result

- docs/en/latest/plugins/response-rewrite.md
- docs/zh/latest/plugins/response-rewrite.md
Fix https://github.com/apache/apisix/issues/5370
> docs: fix vars description about response-rewrite examples

- .github/workflows/fuzzing-ci.yaml
- ci/centos7-ci.sh
- ci/common.sh
- ci/linux_apisix_current_luarocks_runner.sh
- ci/linux_apisix_master_luarocks_runner.sh
- t/cli/common.sh
> test: show error.log once the CLI test failed

- t/core/config_etcd.t
> test: remove unused conf & make t/core/config_etcd.t stable

- .github/workflows/lint.yml
> ci: no need to exclude submodule explicitly

- apisix/stream/plugins/limit-conn.lua
- docs/en/latest/plugins/limit-conn.md
- docs/en/latest/plugins/limit-req.md
- docs/zh/latest/plugins/limit-conn.md
- docs/zh/latest/plugins/limit-req.md
- t/admin/plugins.t
- t/stream-plugin/limit-conn.t
> feat(limit-conn): support multiple variables as key in L4

- apisix/plugins/basic-auth.lua
- t/plugin/basic-auth.t
> fix: add handler for invalid basic auth header values

- docs/zh/latest/plugins/gzip.md
- docs/zh/latest/plugins/real-ip.md
fix broken link with wrong path
> docs: fix broken link with wrong path

- docs/zh/latest/config.json
- docs/zh/latest/plugins/client-control.md
translate client-control from EN into ZH
> docs(localization): translate client-control from EN into ZH

- docs/zh/latest/config.json
- docs/zh/latest/plugins/ext-plugin-pre-req.md
translate ext-plugin-pre-req from EN into ZH
> docs(localization): translate ext-plugin-pre-req from EN into ZH

- docs/zh/latest/config.json
- docs/zh/latest/plugins/ext-plugin-post-req.md
translate `ext-plugin-post-req` from EN into ZH
> docs(localization): translate ext-plugin-post-req from EN into ZH

- docs/en/latest/plugins/hmac-auth.md
- docs/zh/latest/plugins/hmac-auth.md
Fix https://github.com/apache/apisix/issues/5431
> docs: fix the wrong secret in hmac-auth.md

- docs/zh/latest/plugins/limit-req.md
word spelling mistake of burst
> docs: update limit-req.md

- apisix/utils/log-util.lua
- t/plugin/http-logger-log-format.t
> change: log insensitive consumer info only

- README.md
> docs: add Datadog in README.md.

- docs/en/latest/config.json
- docs/zh/latest/config.json
> docs: prepare for the upcoming Faas plugins

- apisix/core/ctx.lua
- apisix/init.lua
- t/plugin/uri-blocker.t
Thanks to Marcin Niemiec for the report.
> fix: prevent being hacked by untrusted request_uri

- t/APISIX.pm
- t/node/grpc-proxy-mtls.t
- t/node/grpc-proxy-stream.t
- t/node/grpc-proxy-unary.t
This PR adds a new section `--- exec` into APISIX testing suite that lets the developers to execute any shell script from the test file and check the output in `--- request_body`
This also migrates existing gRPC tests from ngx_pipe to exec
> test: introducing ---exec & --- stdin section to run cmd

- apisix/core/request.lua
- apisix/plugins/example-plugin.lua
- apisix/plugins/limit-req.lua
- apisix/plugins/proxy-rewrite.lua
The latest LuaJIT can compile pairs
> chore: clean up outdated comments

- apisix/plugins/hmac-auth.lua
- t/plugin/hmac-auth.t
> fix(hmac-auth): check if the X-HMAC-ALGORITHM header is missing

- apisix/upstream.lua
- t/node/least_conn2.t
Fix https://github.com/apache/apisix/issues/5330
Thanks to Yong Nie for the advice.
> fix(upstream): load imbalance when it's referred by multiple routes

- apisix/cli/ops.lua
- apisix/plugins/batch-requests.lua
- docs/en/latest/plugins/batch-requests.md
- docs/zh/latest/plugins/batch-requests.md
- t/cli/test_validate_config.sh
- t/plugin/batch-requests.t
- t/plugin/batch-requests2.t
Also disable batch-requests by default to reduce attack vector
> fix(batch-requests): correct the client ip in the pipeline

- docs/en/latest/FAQ.md
- docs/zh/latest/FAQ.md
Signed-off-by: leslie <leslie.tsang@icloud.com>
Fix #5469
> docs: fix borken link in `FAQ.md`

- README.md
- docs/zh/latest/README.md
> docs: remove duplicate Dubbo entry

- .github/workflows/centos7-ci.yml
> ci: rpm is published by build tools now

- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/config.json
- docs/en/latest/how-to-build.md
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/config.json
- docs/zh/latest/how-to-build.md
- rockspec/apisix-2.10.2-0.rockspec
> feat: release 2.10.2

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
- .github/workflows/chaos.yml
- .github/workflows/cli.yml
- .github/workflows/code-lint.yml
- .github/workflows/doc-lint.yml
- .github/workflows/fuzzing-ci.yaml
- .github/workflows/license-checker.yml
> ci: run CI on PR to release/** branch

- docs/zh/latest/how-to-build.md
docs:For step 3, we should replace "make" with "apisix"
> docs: for step 3, we should replace "make" with "apisix"

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
refer to: https://github.com/apache/apisix/pull/5515
> chore: remove ldap on release 2.10.2

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
> chore: remove unnecessary backport PR in CHANGELOG.md

- apisix/wasm.lua
- docs/en/latest/wasm.md
- t/wasm/route.t
> fix(wasm): the conf can't be empty

- apisix/core/request.lua
- t/core/request.t
> chore: check the error from get_post_args

- docs/en/latest/plugins/kafka-logger.md
- docs/zh/latest/plugins/kafka-logger.md
> docs(kafka-logger): explain when the request body can't be logged

- apisix/plugins/request-validation.lua
- docs/en/latest/plugins/request-validation.md
- docs/zh/latest/plugins/request-validation.md
- t/plugin/request-validation.t
add custom rejected code in request-validation plugin.
> feat(request-validation): add custom rejected_code

- MAINTAIN.md
https://github.com/apache/apisix/issues/5564
> docs: update the MAINTAIN.md  to use correct website configuration link

- apisix/plugins/request-validation.lua
- docs/en/latest/plugins/request-validation.md
- docs/zh/latest/plugins/request-validation.md
- t/plugin/request-validation.t
Also avoid using 500 as the response code
> feat(request-validation): default code is 400

- MAINTAIN.md
> docs: update MAINTAIN.md

- MAINTAIN.md
> docs: update MAINTAIN.md for update APISIX docker

- docs/en/latest/plugins/skywalking-logger.md
> docs(skywalking-logger): fix typo

- docs/zh/latest/README.md
docs: update the docs/zh/latest/README.md
Fix #5575
> docs: update the docs/zh/latest/README.md

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
Private node addresses should not appear in official documents
> docs: update admin ip example node ip

- .github/workflows/centos7-ci.yml
- utils/set-dns.sh
Improve the script to modify DNS configuration in CI environment to adapt to `Netplan` + `systemd-networkd` + `systemd-resolve` environment in Ubuntu. The current method of overwriting `/etc/resolv.conf` directly may not work in some extreme cases.
> ci: improve dns configures override

- README.md
- docs/zh/latest/README.md
The OpenWhisk plugin is currently available for integration with Apache APISIX. We can add it to the Serverless section of the project's README.md for viewing.
> docs: add OpenWhisk plugin to README

- docs/en/latest/internal/testing-framework.md
> docs: exec code block for shell commands in Test Nginx

- docs/en/latest/plugins/dubbo-proxy.md
- docs/zh/latest/plugins/dubbo-proxy.md
Signed-off-by: Soham Banerjee <sohambanerjee4abc@hotmail.com>
The path of the example is fixed as per request in issue #5617 
This PR Fixes #5617
> docs: Path of example is corrected

- MAINTAIN.md
> docs: remember to register release info

- .asf.yaml
- .github/workflows/build.yml
- CHANGELOG.md
- Makefile
- apisix/core/version.lua
- docs/en/latest/config.json
- docs/en/latest/how-to-build.md
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/config.json
- docs/zh/latest/how-to-build.md
- rockspec/apisix-2.11.0-0.rockspec
> feat: release 2.11.0

- apisix/plugins/azure-functions.lua
- apisix/plugins/serverless/generic-upstream.lua
- t/plugin/azure-functions.t
This PR is based on the idea of creating a single generic upstream where each faas plugin implements an authorization schema and perform the header processing.
GOAL: Reduce the same code over multiple plugins (mainly faas)
**How developers should write new (faas) plugins:**
1. They should define plugin-specific authorization schema & metadata schema(if required)
2. Write a `request_processor` function on the plugin lua file that take `plugin conf, ngx context and the URL params (that contains headers, body, urlpath, query params etc. etc.)". The function can perform a series of operations including update/adding the necessary authorization headers, performing encoding/decoding (base64 or anything) on the body.
3. And yes, that's it. (see the azure-functions Lua code for example)
> feat: faas plugin refactoring with url path forwarding

- t/admin/plugins.t
Suggestion from: https://github.com/apache/apisix/pull/5594#discussion_r758167136
> refactor: plugins list test representation

- apisix/core/ctx.lua
> refactor: exact APISIX vars

- apisix/cli/ops.lua
- apisix/discovery/consul_kv/init.lua
- apisix/discovery/consul_kv/schema.lua
- apisix/discovery/dns/init.lua
- apisix/discovery/dns/schema.lua
- apisix/discovery/eureka/init.lua
- apisix/discovery/eureka/schema.lua
- apisix/discovery/nacos/init.lua
- apisix/discovery/nacos/schema.lua
- docs/en/latest/discovery.md
- docs/zh/latest/discovery.md
- t/cli/test_validate_config.sh
- t/discovery/dns/sanity.t
Fix https://github.com/apache/apisix/issues/5277
> feat(discovery): check schema before starting

- apisix/cli/etcd.lua
> feat: report error when use etcd client cert auth

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
> docs(how-to-build): remove the APISIX RPM package installation

- README.md
> docs: add aws lambda plugin to readme

- docs/en/latest/plugins/serverless.md
- docs/zh/latest/plugins/serverless.md
serverless plugin example format error
> docs: update serverless example format error

- docs/zh/latest/plugins/prometheus.md
https://github.com/apache/apisix-website/issues/782
> docs(prometheus): Fix docs broken link

- docs/en/latest/plugins/aws-lambda.md
- docs/en/latest/plugins/azure-functions.md
> docs: documenting url path forwarding for faas plugins

- apisix/cli/env.lua
> chore(cli): update error command prompt

- apisix/plugins/ext-plugin/init.lua
> chore(ext-plugin): we already handled extraInfo

- README.md
- docs/zh/latest/README.md
> docs: update README.md 

- apisix/cli/ops.lua
- apisix/cli/schema.lua
- apisix/core/config_local.lua
- apisix/discovery/consul_kv/init.lua
- apisix/discovery/dns/init.lua
- apisix/discovery/eureka/init.lua
- apisix/discovery/nacos/init.lua
- apisix/init.lua
- apisix/wasm.lua
- docs/en/latest/wasm.md
- t/wasm/route.t
> feat(wasm): allow running in the rewrite phase

- apisix/core/response.lua
> chore: delete expired inspiration statements

- t/plugin/kafka-logger.t
- t/plugin/kafka-logger2.t
> test(kafka-logger): reduce duplicate sections

- .github/workflows/centos7-ci.yml
- utils/linux-install-openresty.sh
> chore: bump apisix-build-tools to v2.6.0

- apisix/plugins/log-rotate.lua
- t/misc/patch.t
- t/plugin/log-rotate.t
- t/plugin/log-rotate2.t
- t/plugin/traffic-split.t
(cherry picked from commit 139c3972898f1e45c6d5b1f40143c504116b3486)
> fix(log-rotate): after enabling compression collect log exceptions

- t/plugin/rocketmq-logger.t
- t/plugin/rocketmq-logger2.t
> test(rocketmq-logger): reduce duplicate sections

- docs/zh/latest/FAQ.md
> docs: remove duplicated word

- utils/install-dependencies.sh
> chore: depend apisix-base in Centos

- apisix/plugins/datadog.lua
- apisix/plugins/google-cloud-logging.lua
- apisix/plugins/http-logger.lua
- apisix/plugins/kafka-logger.lua
- apisix/plugins/rocketmq-logger.lua
- apisix/plugins/skywalking-logger.lua
- apisix/plugins/sls-logger.lua
- apisix/plugins/syslog.lua
- apisix/plugins/tcp-logger.lua
- apisix/plugins/udp-logger.lua
- apisix/utils/batch-processor-manager.lua
- apisix/utils/batch-processor.lua
- docs/en/latest/batch-processor.md
- docs/zh/latest/batch-processor.md
- t/plugin/error-log-logger-skywalking.t
- t/plugin/http-logger2.t
> refactor: use manager to manage batch processor

- docs/zh/latest/plugins/mqtt-proxy.md
Sync en docs to zh docs, Ref to #5787
> docs: sync mqtt-proxy change to zh docs

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
> docs: refactor Installation Guide

- .github/PULL_REQUEST_TEMPLATE.md
> chore: don't use rebase to resolve merge conflicts

- docs/en/latest/plugins/google-cloud-logging.md
- docs/zh/latest/plugins/google-cloud-logging.md
> docs(google-cloud-logging): update document format and description

- docs/en/latest/plugins/api-breaker.md
There's a typo in the documentation.
> docs: Fix typo in documentation

- docs/en/latest/how-to-build.md
> docs: fix typo introduced in the refactor

- docs/en/latest/plugins/request-id.md
- docs/zh/latest/plugins/request-id.md
fix typo in snowflake documents
> docs: Fix typo in request-id plugin documents.

- .github/workflows/fuzzing-ci.yaml
- Makefile
- ci/common.sh
- ci/linux_apisix_current_luarocks_runner.sh
- ci/linux_apisix_master_luarocks_runner.sh
- docs/en/latest/FAQ.md
- docs/zh/latest/FAQ.md
- utils/linux-install-luarocks.sh
The Luarocks 2.x is already broken.
> feat: upgrade luarocks to 3.8.0 which converts git:// to https://

- apisix/plugins/ua-restriction.lua
- t/plugin/ua-restriction.t
fix: [5724](https://github.com/apache/apisix/issues/5724)
> fix(ua-restriction): refine plugin configuration check logic

- docs/en/latest/FAQ.md
> docs: remove duplicate words in FAQ

- utils/install-dependencies.sh
This PR make it  easy to install deps on a mini install OS.
> chore: improve installation experience

- t/plugin/serverless.t
> test: make t/plugin/serverless.t stable

- apisix/plugins/cors.lua
- t/plugin/cors.t
In some scenarios, if you modify the origin using proxy_rewrite plugin, the cors will not be handled correctly
> fix(cors): compatible with scenarios where origin is modified

- .github/workflows/lint.yml
> ci: the trailing whitespace check is already covered by editconfig

- apisix/plugins/proxy-rewrite.lua
- t/plugin/proxy-rewrite2.t
> fix(proxy-rewrite): make sure proxy-rewrite update the core.request.header cache

- docs/en/latest/plugin-develop.md
- docs/zh/latest/plugin-develop.md
> docs: fix the title level of API sections

- docs/en/latest/FAQ.md
- docs/en/latest/grpc-proxy.md
- docs/en/latest/plugins/grpc-transcode.md
- docs/en/latest/router-radixtree.md
- docs/zh/latest/README.md
- docs/zh/latest/plugins/grpc-transcode.md
- docs/zh/latest/router-radixtree.md
update document reference link
> docs: update document reference link

- apisix/plugins/prometheus/exporter.lua
- conf/config-default.yaml
- t/cli/test_prometheus.sh
Make it configurable for prometheus metric prefix
> feat(prometheus): Add metric prefix attr

- ci/centos7-ci.sh
- ci/common.sh
- ci/linux_openresty_common_runner.sh
> ci: rerun flaky tests

- apisix/plugins/datadog.lua
- docs/en/latest/plugins/datadog.md
- t/plugin/datadog.t
Use the default batch processor arguments and allow no retry.
> fix(datadog): keep consistent with the other logger

- t/cli/test_access_log.sh
See https://github.com/apache/apisix/runs/4684173371?check_suite_focus=true
> test(UDP): use longer timeout to avoid 'echo: write error: Broken pipe'

- docs/en/latest/apisix-variable.md
- docs/en/latest/config.json
- docs/en/latest/plugins/http-logger.md
- docs/en/latest/plugins/kafka-logger.md
- docs/en/latest/plugins/rocketmq-logger.md
- docs/zh/latest/plugins/http-logger.md
- docs/zh/latest/plugins/kafka-logger.md
- docs/zh/latest/plugins/rocketmq-logger.md
> docs: list APISIX variable in a separate page

- rockspec/apisix-2.10.3-0.rockspec
Add an rockspec for version `2.10.3`, which should have cherrypicked into this branch after the PR (`feat: release 2.10.3`) merge on the master branch, but didn't because of some `CHANGELOG` content differences, so I'll add a rockspec for it alone.
**Tips, this is part of the 2.10.3 release.**
> chore: add 2.10.3 rockspec for release

- t/APISIX.pm
> test: add missing shdict

- docs/en/latest/config.json
- docs/en/latest/plugins/opa.md
Add documentation for the OPA plugin.
> docs: add OPA plugin document

- NOTICE
> chore: update year to 2022

- docs/zh/latest/plugins/mqtt-proxy.md
Sync #5888 , update Chinese version of mqtt proxy docs
> docs: update some explanations for the usage of the mqtt proxy (zh)

- docs/en/latest/internal/testing-framework.md
- t/APISIX.pm
- t/debug/debug-mode.t
- t/stream-node/sanity.t
- t/stream-node/sni.t
- t/stream-plugin/ip-restriction.t
- t/stream-plugin/mqtt-proxy.t
> test: doc & simpify stream part of the test framework

- apisix/admin/init.lua
> refactor(admin): handle stream_routes like the other resources

- apisix/plugins/proxy-mirror.lua
> chore(proxy-mirror): remove useless code

- apisix/plugins/grpc-web.lua
- t/plugin/grpc-web.t
update mime of response to mime of request
> chore(grpc-web): update mime of response to mime of request

- apisix/plugins/serverless/generic-upstream.lua
- apisix/plugins/wolf-rbac.lua
be linked: https://github.com/apache/apisix/pull/6037#discussion_r779988474
> chore: update use resty-http syntax question

- apisix/plugins/openwhisk.lua
- ci/linux-ci-init-service.sh
- ci/linux_openresty_common_runner.sh
- t/plugin/openwhisk.t
This PR added openwhisk response parsing mechanism, implementing issue #5756. As of now, user defined openwhisk package action, status code and body are supported.
Fix #5756
> feat: support custom package, headers and body in openwhisk plugin

- t/plugin/basic-auth.t
ref: https://github.com/apache/apisix/pull/6039#issuecomment-1011864512
> chore: reindex format of basic_auth.t

- apisix/core/ctx.lua
- apisix/stream/plugins/mqtt-proxy.lua
- docs/en/latest/apisix-variable.md
- docs/en/latest/plugins/mqtt-proxy.md
- docs/zh/latest/plugins/mqtt-proxy.md
- t/stream-plugin/mqtt-proxy.t
> feat(mqtt): balance by client id

- apisix/plugins/forward-auth.lua
- docs/en/latest/plugins/forward-auth.md
- t/plugin/forward-auth.t
Modify the `host` parameter in the `forward-auth` plugin to `address` to avoid misunderstanding.
> chore: update forward-auth address schema

- apisix/plugins/forward-auth.lua
- docs/en/latest/plugins/forward-auth.md
- t/plugin/forward-auth.t
> chore(forward-auth): rename address to uri

- CONTRIBUTING.md
add contributor t-shirt instruction
> docs: add contributor t-shirt instruction

- README.md
- docs/en/latest/plugins/jwt-auth.md
Signed-off-by: Bisakh Mondal <bisakhmondal00@gmail.com>
#6118
> docs: add vault support into readme

- ci/common.sh
See https://github.com/apache/apisix/pull/6092#issuecomment-1014215106
> test: fix the CI failure detection when rerunning the tests

- README.md
- docs/zh/latest/README.md
refer https://github.com/apache/apisix/pull/5727#issuecomment-1015253594
> docs: add CSRF plugin info to README

- .github/workflows/chaos.yml
fix chaos test's etcd error
```text
got malformed key-put message: "{"error":"etcdserver: user name is empty","code":3,"message":"etcdserver: user name is empty"}" from etcd "http://etcd.default.svc.cluster.local:2379/v3/kv/put"
```
> ci: fix chaos etcd rbac error

- apisix/admin/upstreams.lua
As the size of Nginx log is limited, we can't log all the routes, so I remove it in this PR.
https://github.com/apache/apisix/pull/6092#discussion_r785434259
> chore: remove log routes info

- Makefile
> fix(makefile): fix Makefile `install` don't install discovery folder

- README.md
- docs/zh/latest/README.md
> docs: add grpc-web to README

- t/plugin/http-logger-log-format.t
> test: ensure custom variable can be used in log format

- .github/workflows/build.yml
- docs/en/latest/wasm.md
- t/cli/test_admin.sh
- t/wasm/forward-auth.go
- t/wasm/forward-auth.t
> docs(wasm): add forward-auth example

- apisix/core/ctx.lua
- apisix/core/request.lua
- t/core/request.t
- t/router/graphql.t
> fix(GraphQL): no request body error

- docs/en/latest/internal/testing-framework.md
- t/plugin/public-api.t
> docs: add missing } in the example

- .asf.yaml
- CHANGELOG.md
- Makefile
- apisix/core/version.lua
- docs/en/latest/config.json
- docs/en/latest/how-to-build.md
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/config.json
- docs/zh/latest/how-to-build.md
- rockspec/apisix-2.12.0-0.rockspec
> feat: release 2.12.0

- docs/en/latest/plugins/consumer-restriction.md
- docs/zh/latest/plugins/consumer-restriction.md
consumer-restiction has allowed_by_methods，but doc need to improment.
> docs: fix consumer-restriction plugin

- ci/linux_apisix_master_luarocks_runner.sh
> test: ensure all Lua code is installed

- .github/workflows/chaos.yml
- conf/config-default.yaml
- t/admin/plugins.t
- t/debug/debug-mode.t
> fix(batch-requests): should be disabled by default (#6204)

- docs/en/latest/plugins/api-breaker.md
- docs/zh/latest/plugins/api-breaker.md
resolve https://github.com/apache/apisix/issues/6175
> docs: optimizing api-breaker documentation

- ci/common.sh
- t/plugin/limit-count-redis-cluster.t
- t/plugin/limit-count-redis.t
- t/plugin/limit-count.t
> test(limit-count): fix title & simpify the cases

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
enhance user guide to install apisix from source
> docs: solution for lualdap when install failed with luarocks

- .github/workflows/doc-lint.yml
- utils/fix-zh-doc-segment.py
> ci: fix broken newline check with code block syntax

- docs/en/latest/control-api.md
- docs/en/latest/plugins/prometheus.md
> docs: data panel => data plane

- docs/en/latest/discovery/nacos.md
> docs(nacos): remove experimental tag

- Makefile
- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
`make uninstall` on no need of the runtime
Fix #5225
> build: make uninstall related files of runtime

- MAINTAIN.md
Update the `patch` section of the `MAINTAIN.md` document to add more process descriptions.
> docs: update MAINTAIN.md patch section

- apisix/plugins/batch-requests.lua
- t/plugin/batch-requests2.t
> fix(batch-requests): real ip header should be overridden

- CHANGELOG.md
- apisix/core/version.lua
- apisix/plugins/batch-requests.lua
- docs/en/latest/config.json
- docs/en/latest/how-to-build.md
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/config.json
- docs/zh/latest/how-to-build.md
- rockspec/apisix-2.10.4-0.rockspec
- t/plugin/batch-requests2.t
> feat: release 2.10.4

- Makefile
> chore: ensure installed Lua directories sorted

- CONTRIBUTING.md
- README.md
- docs/zh/latest/README.md
the original group was nearly full
> chore: enable new QQ group

- apisix/core/ctx.lua
- apisix/stream/plugins/mqtt-proxy.lua
- docs/en/latest/apisix-variable.md
Also remove the register check so the plugin can be hot reloaded.
> refactor: mv the var mqtt_client_id to plugin level

- apisix/discovery/nacos/schema.lua
- t/discovery/nacos2.t
> fix(nacos): add complex password support for nacos `host_pattern` match rule

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
> docs: added installation mode for LTS version

- docs/zh/latest/config.json
- docs/zh/latest/plugins/forward-auth.md
> docs: add forward-auth zh document

- rockspec/apisix-master-0.rockspec
Action for https://github.com/apache/apisix/pull/5999#discussion_r777844345
> chore: upgrade lua-resty-dns-client to the latest

- utils/install-dependencies.sh
> build: correct "surported" to "supported" in install-dependencies.sh

- docs/en/latest/plugins/prometheus.md
- docs/zh/latest/plugins/prometheus.md
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
https://github.com/apache/apisix/issues/6276#issuecomment-1034495761
closes: https://github.com/apache/apisix/issues/6276
> docs: clearer description for Prometheus plugin

- apisix/plugins/loggly.lua
- docs/en/latest/plugins/loggly.md
- t/plugin/loggly.t
> feat(loggly): support HTTP response code to SYSLOG severity mapping

- t/core/utils.t
> test(core): fix test cases in `t/core/utils.t`

- .github/ISSUE_TEMPLATE/feature_request.yml
> feat: Add feature request template

- .github/workflows/performance.yml
> ci: fix flamegraph CI trigger condition

- t/admin/plugins.t
- t/admin/upstream2.t
- t/core/ctx2.t
- t/misc/patch.t
- t/node/plugin-configs.t
- t/plugin/batch-requests2.t
- t/plugin/ext-plugin/conf_token.t
- t/plugin/ext-plugin/sanity.t
- t/plugin/jwt-auth-vault.t
- t/plugin/jwt-auth.t
- t/plugin/ldap-auth.t
- t/plugin/limit-conn2.t
- t/plugin/plugin.t
- t/plugin/prometheus3.t
- t/plugin/rocketmq-logger.t
- t/plugin/traffic-split2.t
- t/plugin/traffic-split5.t
> test: remove duplicate --- no_error_log & --- request sections

- .github/workflows/chaos.yml
- .gitmodules
This action only serves for the debug purpose. Actually, no one uses it
for these days.
> ci: remove unnecessary tmate action

- docs/en/latest/config.json
- docs/zh/latest/config.json
Adjust the directory structure of documents that are related to observability.
the new directory structure:
- plugins
- observability
- tracers
- metrics
- loggers
> doc: adjust the directory structure of observability's documents

- docs/zh/latest/plugins/skywalking-logger.md
docs: polishing skywalking-logger plugin's docs
docs: polishing skywalking-logger plugin's docs,Update Chinese documents
> docs: polishing skywalking-logger plugin's docs

- docs/en/latest/config.json
- docs/zh/latest/config.json
Fix incorrect link in the document configuration file. The error was introduced in PR #6391.
> docs: fix configuration file typo

- .github/workflows/doc-lint.yml
- docs/zh/latest/config.json
> docs(cn): remove datadog from sidebar & fix doc lint conf

- docs/en/latest/admin-api.md
fix For L7 proxy -> For L4 proxy
Fix https://github.com/apache/apisix/issues/6421
> docs: fix For L7 proxy -> For L4 proxy

- docs/en/latest/discovery/consul_kv.md
- Use the word "Consul KV" in the official document of Consul to replace "consul key value"
- Adjust the expression of some text
> docs: improve consul_kv.md

- docs/zh/latest/admin-api.md
- docs/zh/latest/mtls.md
- docs/zh/latest/plugins/dubbo-proxy.md
- docs/zh/latest/plugins/gzip.md
- docs/zh/latest/plugins/proxy-control.md
- docs/zh/latest/plugins/real-ip.md
> docs: fix openresty doc link

- apisix/plugins/http-logger.lua
- docs/en/latest/plugins/http-logger.md
- docs/zh/latest/plugins/http-logger.md
- t/plugin/http-logger.t
Fix: http-logger always use `false` on function `httpc:ssl_handshake`
> feat(http-logger): allow verifying ssl cert

- t/lib/dubbo-backend/dubbo-backend-provider/src/main/resources/META-INF/spring/dubbo-demo-provider.xml
- t/plugin/dubbo-proxy/route.t
- t/plugin/dubbo-proxy/upstream.t
> test(dubbo-proxy): check service version

- README.md
> docs:  update users of Apache APISIX 

- apisix/schema_def.lua
> chore(schema): remove array length limitation

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
- .gitmodules
- apisix/plugins/api-breaker.lua
- ci/centos7-ci.sh
- ci/linux_openresty_common_runner.sh
> ci: split the full CI into two parts (running t/plugin and the other)

- apisix/cli/ops.lua
When reading apisix code, I found that there are some duplicated codes in `ops.lua` (see the changes) and want to make the code cleaner.
> chore: remove some dumplicated code in ops.lua

- apisix/cli/ngx_tpl.lua
- apisix/cli/ops.lua
- apisix/plugin.lua
- t/cli/test_http_config.sh
- t/cli/test_main.sh
- t/cli/test_stream_config.sh
> chore: reduce shdict if we disable the plugin

- apisix/upstream.lua
> chore: clean up outdated code

- ci/centos7-ci.sh
- ci/linux_openresty_common_runner.sh
- docs/en/latest/how-to-build.md
- docs/en/latest/internal/testing-framework.md
- docs/zh/latest/how-to-build.md
- t/APISIX.pm
- t/discovery/consul_kv.t
- t/plugin/jwt-auth-vault.t
- t/plugin/traffic-split2.t
> test: switch back to openresty/test-nginx

- apisix/wasm.lua
- t/wasm/request-body.t
> fix(wasm): ensure the process body flag is independent

- docs/en/latest/mtls.md
- docs/zh/latest/mtls.md
When there are only four parameters, the script should also work properly
> docs: fix python script bug

- apisix/cli/ngx_tpl.lua
- apisix/wasm.lua
- docs/en/latest/wasm.md
- t/APISIX.pm
- t/wasm/response-rewrite.t
- t/wasm/response-rewrite/main.go
> feat(Wasm): get response body

- powered-by.md
> docs: update  prowered-by.md

- apisix/plugins/proxy-mirror.lua
- t/plugin/proxy-mirror.t
> fix(proxy-mirror): pattern validation

- README.md
> docs: added the invite link of Slack.

- utils/linux-install-luarocks.sh
remove `luarocks` downloaded tar file
1. successfully install it, no need to reserve it.
2. install script remove the untar files (line#45)[https://github.com/apache/apisix/blob/master/utils/linux-install-luarocks.sh#L45], so remove the tar file simultaneously.
> build: rm luarocks tar file behind successful installation

- README.md
- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
> docs: additional description to download different versions of APISIX

- t/discovery/nacos2.t
resolve #6522 
Now the test case will change the nacos server default password to verify if the auth work as expected.
> test(nacos): enrich nacos test case

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
- utils/install-dependencies.sh
> docs: rewrite "Installation via Source"

- utils/install-dependencies.sh
support to install dependencies in ubuntu under arm64 architecture.
fix #6589
> feat: support to install dependencies under arm64

- t/plugin/redirect2.t
> test(redirect): add use regex_uri redirect and enable append_query_string case

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/improve_docs.yml
- .github/ISSUE_TEMPLATE/request_help.yml
- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the issue and PR templates and makes it consistent.
Fixes #6583
> docs: update issue and pr templates

- apisix/admin/global_rules.lua
- apisix/admin/plugin_config.lua
- apisix/admin/routes.lua
- apisix/admin/services.lua
- apisix/admin/ssl.lua
- apisix/admin/upstreams.lua
- apisix/balancer/chash.lua
- apisix/plugins/limit-conn/init.lua
- apisix/plugins/limit-count.lua
- apisix/plugins/limit-req.lua
> chore: remove redundant semicolons

- THREAT_MODEL.md
Fix https://github.com/apache/apisix/issues/6238
> docs: add threat model

- t/plugin/traffic-split.t
- t/plugin/traffic-split2.t
- t/plugin/traffic-split3.t
- t/plugin/traffic-split4.t
> test: change the string to lua table

- t/plugin/log-rotate2.t
See:
https://github.com/apache/apisix/runs/5594782682?check_suite_focus=true
https://github.com/apache/apisix/runs/5579301588?check_suite_focus=true
> test: make plugin/log-rotate2.t stable

- apisix/cli/ngx_tpl.lua
- apisix/cli/ops.lua
- apisix/discovery/kubernetes/informer_factory.lua
- apisix/discovery/kubernetes/init.lua
- conf/config-default.yaml
- docs/en/latest/config.json
- docs/en/latest/discovery/kubernetes.md
- docs/zh/latest/discovery/kubernetes.md
- t/APISIX.pm
Fix #6661 
1. add  en discovery/kubernetes.md
2. improve zh discovery/kubernetes.md
3. use ngx.shared.kubernets instead ngx.shared.discovery
> feat: improve kubernetes discovery

- apisix/api_router.lua
- t/plugin/batch-requests2.t
> fix(public api): ensure the content-type is correct

- docs/zh/latest/plugins/zipkin.md
> chore: remove zipkin.md special character

- docs/en/latest/plugin-develop.md
- docs/zh/latest/plugin-develop.md
- utils/check-plugins-code.sh
> ci: should check ngx.redirect & stream plugins

- docs/zh/latest/plugins/clickhouse-logger.md
- docs/zh/latest/plugins/file-logger.md
- docs/zh/latest/plugins/kafka-logger.md
- docs/zh/latest/plugins/rocketmq-logger.md
- docs/zh/latest/plugins/skywalking-logger.md
fix kakfa-logger plugin.md metadata description
fix file-logger plugin.md metadata description
fix clickhouse-logger plugin.md metadata description
Fixes #6657
> docs: fix some logger plugin metadata description

- docs/zh/latest/plugins/skywalking-logger.md
> docs: fix skywalking-logger typo

- docs/en/latest/FAQ.md
This PR updates the FAQ section to be more readable and consistent. 
Fixes #6594
> docs: update FAQ docs

- .github/workflows/kubernetes-ci.yml
- .github/workflows/tars-ci.yml
> ci: remove unnecessary step

- .github/workflows/lint.yml
- apisix/utils/batch-processor.lua
- utils/check-merge-conflict.sh
Avoid resolving part of the conflict.
> ci: should check the `>>> master` too

- apisix/plugins/file-logger.lua
- t/plugin/file-logger-reopen.t
> feat(file-logger): cache & reopen file handler

- apisix/core/request.lua
- t/plugin/ext-plugin/http-req-call.t
> fix: need to invalidate req hdr cache properly

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
- rockspec/apisix-2.10.5-0.rockspec
> feat: release 2.10.5

- .github/workflows/centos7-ci.yml
- ci/centos7-ci.sh
> ci: use latest version of build tools

- docs/en/latest/plugins/error-log-logger.md
- docs/zh/latest/plugins/error-log-logger.md
fix error-log-logger.md format
> docs: fix error-log-logger.md format

- docs/zh/latest/plugins/forward-auth.md
> docs: fix forward-auth typo

- README.md
- docs/en/latest/discovery.md
- docs/zh/latest/README.md
- docs/zh/latest/discovery.md
1. APISIX is widely used in many platforms. There is no need to list
some outdated OS.
2. we already list the discoveries in the sidebar.
> docs: remove OS/discovery list

- README.md
- docs/zh/latest/README.md
1. some methods are actually for authorization
2. OpenID Connect != OAuth2
3. add casdoor
> docs: improve authentication/authorization methods

- apisix/plugins/authz-keycloak.lua
- t/plugin/authz-keycloak3.t
> fix(authz-keycloak): add missing path for access_denied_redirect_uri

- apisix/stream/router/ip_port.lua
> chore: fix confusing var name

- t/plugin/forward-auth.t
See https://github.com/apache/apisix/runs/5967259868?check_suite_focus=true
> test: rewrite test to bypass "missing the closing long bracket" err

- .github/workflows/centos7-ci.yml
Running xds tests in Centos7 CI
> test(xds): add Centos7 CI

- .github/workflows/build.yml
- Makefile
- apisix/init.lua
- apisix/schema_def.lua
- apisix/stream/router/ip_port.lua
- apisix/stream/xrpc.lua
- apisix/stream/xrpc/runner.lua
- conf/config-default.yaml
- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
- t/APISIX.pm
- t/admin/stream-routes.t
- t/plugin/forward-auth.t
- t/xrpc/apisix/stream/xrpc/protocols/pingpong/init.lua
- t/xrpc/apisix/stream/xrpc/protocols/pingpong/schema.lua
- t/xrpc/pingpong.t
> feat(xRPC): add Admin API support

- ci/pod/docker-compose.yml
- t/plugin/limit-count-redis.t
- t/plugin/limit-count-redis2.t
> ci: upgrade ancient redis image

- docs/zh/latest/how-to-build.md
> chore: modify links

- apisix/stream/xrpc/runner.lua
- t/xrpc/apisix/stream/xrpc/protocols/pingpong/init.lua
- t/xrpc/pingpong.t
> feat(xrpc): add unary structure

- README.md
- docs/zh/latest/README.md
Add zookeeper discovery to README.md
> docs(zookeeper): add zookeeper discovery to README

- apisix/plugins/hmac-auth.lua
- t/APISIX.pm
- t/plugin/hmac-auth-custom.t
- t/plugin/hmac-auth.t
- t/plugin/hmac-auth2.t
- t/plugin/hmac-auth3.t
> fix(hmac-auth): don't let client know why it is rejected

- apisix/plugins/serverless/init.lua
- t/plugin/serverless.t
- [] I have explained the need for this PR and the problem it solves
> feat(serverless): return like other plugins

- Makefile
- apisix/stream/xrpc/protocols/redis/init.lua
- apisix/stream/xrpc/protocols/redis/schema.lua
- apisix/stream/xrpc/runner.lua
- apisix/stream/xrpc/sdk.lua
- t/xrpc/redis.t
> feat(xRPC): simple redis support

- docs/en/latest/internal/testing-framework.md
> docs: we don't use our fork anymore

- apisix/stream/xrpc/protocols/redis/init.lua
- t/xrpc/redis.t
> chore(redis): avoid recording big value

- powered-by.md
Thanks to the community, great job!
> docs: update prowered-by.md

- docs/en/latest/plugins/ua-restriction.md
Updates the documentation of the "ua-restriction" Plugin.
> docs: update "ua-restriction" Plugin docs

- docs/en/latest/plugins/uri-blocker.md
Updates the documentation of the "uri-blocker" Plugin.
> docs: update "uri-blocker" Plugin docs

- apisix/upstream.lua
- t/stream-node/sanity.t
> chore: don't report upstream http host check error in stream subsystem

- apisix/plugins/authz-casbin.lua
- apisix/plugins/hmac-auth.lua
- apisix/plugins/jwt-auth.lua
- t/plugin/hmac-auth3.t
> chore: replace get_headers and get_uri_args with the function in core.request

- docs/zh/latest/plugins/mocking.md
I encountered a "Test and deploy" CI check failure in https://github.com/apache/apisix-website/pull/1059. While preview works as expected, the check failed for the following reason.
```
Error while parsing Markdown frontmatter.
This can happen if you use special characters in frontmatter values (try using double quotes around that value).
Can't process doc metadatas for doc at path "/home/runner/work/apisix-website/apisix-website/website/i18n/zh/docusaurus-plugin-content-docs-docs-apisix/current/plugins/mocking.md" in version "current"
Loading of version failed for version "current"
Unable to build website for locale "zh".
YAMLException: bad indentation of a mapping entry at line 8, column 3:
description: 本文介绍了关于 Apache APIS ... 
```
I did not change anything in …
> docs: fix description format in mocking doc

- docs/en/latest/plugins/consumer-restriction.md
- docs/en/latest/plugins/csrf.md
- docs/en/latest/plugins/public-api.md
- docs/en/latest/plugins/referer-restriction.md
Updates the documentation of the "referer-restriction", "consumer-restriction", "csrf" and "public-api" Plugins.
> docs: update "Security" docs

- docs/en/latest/config.json
- docs/en/latest/xrpc.md
> docs(xRPC): add the main entry

- .asf.yaml
See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#about-branch-protection-rules
> ci: use wildcard to protect branches

- apisix/plugins/ext-plugin/init.lua
delete REWRITTEN_BY_EXT_PLUGIN
> chore: remove redundant code

- apisix/stream/xrpc/protocols/redis/init.lua
- t/xrpc/redis.t
> feat(redis): support pipeline

- docs/en/latest/how-to-build.md
This PR updates the installation guide to be comprehensive and simple.
Note that this PR currently removes the development installation instructions. These could be moved to the apisix GitHub repo or any other relevant page in the documentation. This change can be tracked in a separate issue and could be updated in a separate PR.
Please suggest if there needs to be any updations, additions or notes.
See the comment below for a screenshot of the change as there is no deploy preview.
> docs: update "Installation" guide

- README.md
> docs: update plugin concept link in README

- docs/en/latest/FAQ.md
- docs/zh/latest/FAQ.md
fix error link in /docs/en/latest/FAQ.md and /docs/zh/latest/FAQ.md
Fixes #6920
> feat(doc): fix FAQ page error link

- CODE_STYLE.md
Hey, 
I've noticed a missing space here, hope you dont mind!
Just some missing space!
- [x ] I have explained the need for this PR and the problem it solves
- [x ] I have explained the changes or the new features added to this PR
- [x ] I have added tests corresponding to this change
- [ x] I have updated the documentation to reflect this change
- [ x] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)
> docs: updated CODE_STYLE.md

- README.md
- docs/zh/latest/README.md
This PR updates description of how to join the Slack channel, as many community users complain that it's hard to find the correct channel after joining. I choose to link it to the website description.
> docs: update description of how to join slack

- apisix/stream/xrpc/runner.lua
- t/xrpc/apisix/stream/xrpc/protocols/pingpong/init.lua
- t/xrpc/pingpong.t
Otherwise the resource might not be released.
> fix(xRPC): log down unfinished request

- docs/en/latest/getting-started.md
- docs/zh/latest/getting-started.md
- docs/zh/latest/how-to-build.md
Fixed punctuation issues in the installation document.
Update Chinese getting started docs, This PR is only responsible for the internationalization and synchronization of English changes from https://github.com/apache/apisix/pull/6929.
preview link: http://silly-stamp.surge.sh/zh/docs/apisix/next/getting-started/
> docs: update Chinese getting started doc

- apisix/stream/xrpc/protocols/redis/init.lua
- t/APISIX.pm
- t/xrpc/redis.t
> feat(redis): support pubsub

- conf/config-default.yaml
- docs/en/latest/FAQ.md
- docs/en/latest/admin-api.md
- docs/en/latest/mtls.md
- docs/en/latest/plugins/client-control.md
- docs/en/latest/plugins/gzip.md
- docs/en/latest/plugins/proxy-control.md
- docs/en/latest/plugins/real-ip.md
- docs/en/latest/wasm.md
- docs/en/latest/xrpc/redis.md
- docs/zh/latest/FAQ.md
- docs/zh/latest/admin-api.md
- docs/zh/latest/mtls.md
- docs/zh/latest/plugins/client-control.md
- docs/zh/latest/plugins/gzip.md
- docs/zh/latest/plugins/proxy-control.md
- docs/zh/latest/plugins/real-ip.md
Since we updated the how to build docs, step 6 has been removed, as links referring to step 6 will be wrong in the next version. 
So I moved the content of step 6 to the FAQ, and modified all documents that referenced the link from step 6.
> docs: update apisix-base link.

- apisix/init.lua
- apisix/ssl/router/radixtree_sni.lua
- bin/apisix
- t/node/client-mtls.t
- t/plugin/traffic-split.t
- utils/linux-install-luarocks.sh
> ci: make it pass under OpenResty 1.21 (#7067)

- rockspec/apisix-master-0.rockspec
Signed-off-by: starsz <starszcan@gmail.com>
Orignal PR: https://github.com/apache/apisix/pull/7062
> backport: update casbin version to 1.41.1

- docs/en/latest/FAQ.md
- docs/zh/latest/FAQ.md
Fix link of hot-reload in docs
> docs: fix link of hot-reload in docs

- apisix/init.lua
- apisix/ssl/router/radixtree_sni.lua
- bin/apisix
- t/node/client-mtls.t
- t/plugin/traffic-split.t
- utils/linux-install-luarocks.sh
- utils/linux-install-openresty.sh
Signed-off-by: spacewander <spacewanderlzx@gmail.com>### Description
> backport: make it pass under OpenResty 1.21

- docs/en/latest/plugins/aws-lambda.md
- docs/en/latest/plugins/azure-functions.md
- docs/en/latest/plugins/openwhisk.md
- docs/en/latest/plugins/serverless.md
Updates the documentation of the "Serverless" Plugins.
> docs: update "Serverless" Plugins

- docs/en/latest/plugins/opentelemetry.md
- docs/en/latest/plugins/skywalking.md
- docs/en/latest/plugins/zipkin.md
Updates the documentation of the "Observability/Tracers" Plugins.
> docs: update "Tracers" Plugins

- .github/workflows/build.yml
- .github/workflows/cli-master.yml
- .github/workflows/cli.yml
- .github/workflows/kubernetes-ci.yml
- .github/workflows/tars-ci.yml
- CHANGELOG.md
- apisix/cli/ops.lua
- apisix/core/version.lua
- ci/common.sh
- ci/linux_apisix_current_luarocks_runner.sh
- ci/linux_apisix_master_luarocks_runner.sh
- ci/linux_openresty_common_runner.sh
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/config.json
- rockspec/apisix-2.14.1-0.rockspec
- t/cli/test_validate_config.sh
> feat: release 2.14.1 

- utils/linux-install-openresty.sh
> chore(ci): use the latest build script for apisix-base

- utils/linux-install-etcd-client.sh
- utils/linux-install-openresty.sh
support to install dependencies under arm64
> chore(script): support to install dependencies under arm64

- apisix/plugins/grpc-transcode.lua
- apisix/plugins/grpc-transcode/request.lua
- apisix/plugins/grpc-transcode/response.lua
- apisix/plugins/grpc-transcode/util.lua
- t/plugin/grpc-transcode2.t
> fix(grpc-transcode): pb_option should be set on the route

- docs/en/latest/plugins/zipkin.md
- docs/zh/latest/plugins/zipkin.md
> docs: update zipkin Chinese doc

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
- .gitignore
- apisix/core/config_xds.lua
- t/xds-library/export.go
- t/xds-library/main.go
- t/xds-library/xds.h
It causes the CI error:
https: //github.com/apache/apisix/runs/6643228643?check_suite_focus=true
> fix(xds): handle removed symbol in apisix-base

- docs/en/latest/FAQ.md
> docs: updated links of slack and mailing list.

- docs/zh/latest/config.json
- docs/zh/latest/plugins/openwhisk.md
Signed-off-by: penghuima <2992426202@qq.com>
docs: add openwhisk CN document
> docs: add openwhisk CN document

- README.md
> docs: updated slack link.

- docs/zh/latest/config.json
- docs/zh/latest/discovery/zookeeper.md
Signed-off-by: penghuima <2992426202@qq.com>
add zookeeper
> docs: add zookeeper CN document

- docs/en/latest/plugins/prometheus.md
- docs/zh/latest/plugins/prometheus.md
> docs(prometheus): need to enable prometheus stream plugin first

- docs/en/latest/plugins/http-logger.md
- docs/en/latest/plugins/skywalking-logger.md
- docs/en/latest/plugins/tcp-logger.md
Updates the documentation of the "Observability/Loggers" Plugins (1/n).
> docs: update "Loggers" Plugins 1/n

- apisix/init.lua
- t/router/radixtree-sni2.t
- t/stream-node/tls.t
> perf: reuse ctx in ssl phase

- docs/en/latest/plugins/skywalking.md
- docs/en/latest/plugins/zipkin.md
- docs/zh/latest/plugins/skywalking.md
update skywalking Chinese doc.
> docs: update skywalking Chinese doc

- apisix/init.lua
> fix: remove deprecated upstream.enable_websocket

- t/admin/plugin-configs.t
- t/admin/proto.t
- t/admin/stream-routes.t
- t/cli/test_main.sh
- t/plugin/grpc-transcode2.t
- t/xrpc/pingpong2.t
- t/xrpc/redis.t
- t/xrpc/redis2.t
They are introduced by Copy & Paste
> test: remove unused required etcd

- README.md
> "Weibo.com" redirects here. For China-based microblogs (weibos), see [Microblogging in China](https://en.wikipedia.org/wiki/Microblogging_in_China). For other things named "weibo", see [Weibo](https://en.wikipedia.org/wiki/Weibo_(disambiguation)). --From wiki
Summary, make company more preciser.
> docs: make company on README more preciser

- .github/workflows/chaos.yml
- apisix/cli/schema.lua
- t/chaos/utils/Dockerfile
- t/cli/test_validate_config.sh
> chore: validate etcd conf strictly

- docs/en/latest/health-check.md
- docs/zh/latest/health-check.md
> docs: correct the repo url

- ci/centos7-ci.sh
- ci/pod/docker-compose.common.yml
- docs/en/latest/installation-guide.md
- docs/zh/latest/installation-guide.md
- utils/linux-install-etcd-client.sh
> chore(ci): upgrade etcd version to 3.5.4

- apisix/cli/ops.lua
display test option when help
Fixes #7148
> feat(cli): display test option when help

- apisix/plugins/traffic-split.lua
- t/plugin/traffic-split5.t
> fix(traffic-split): the default timeout doesn't match the one in Nginx

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
- apisix/cli/file.lua
- apisix/cli/ngx_tpl.lua
- apisix/cli/ops.lua
- apisix/cli/schema.lua
- apisix/cli/snippet.lua
- apisix/core/etcd.lua
- t/bin/gen_snippet.lua
- t/cli/test_deployment_traditional.sh
- t/deployment/conf_server.t
> feat(deployment): support connecting to etcd via https

- apisix/core/config_xds.lua
- apisix/core/os.lua
- t/core/os.t
> fix: the argument to usleep should be integer

- apisix/plugins/error-log-logger.lua
- apisix/plugins/skywalking-logger.lua
- t/plugin/skywalking-logger.t
> fix(skywalking-logger, error-log-logger): skywalking service_instance_name $hostname is supported

- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/config.json
- docs/en/latest/how-to-build.md
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/config.json
- docs/zh/latest/how-to-build.md
- rockspec/apisix-2.13.2-0.rockspec
> feat: release 2.13.2

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
> docs: 2.14.1 isn't a LTS version

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
- rockspec/apisix-2.13.2-0.rockspec
> feat: ready to release 2.13.2

- docs/en/latest/plugins/clickhouse-logger.md
- docs/en/latest/plugins/log-rotate.md
- docs/en/latest/plugins/syslog.md
Updates the documentation of the "Observability/Loggers" Plugins (3/n).
> docs: update "Loggers" Plugins 3/n

- apisix/cli/snippet.lua
- apisix/conf_server.lua
- apisix/init.lua
- t/deployment/conf_server.t
> feat(deployment): select backend & retry

- apisix/init.lua
- t/plugin/proxy-rewrite2.t
> backport: commits to release/2.13

- apisix/plugins/sls-logger.lua
- docs/en/latest/plugins/sls-logger.md
- docs/zh/latest/plugins/sls-logger.md
- t/plugin/sls-logger.t
> feat(sls-logger): support custom log format

- apisix/plugin.lua
- t/config-center-yaml/plugin-metadata.t
> feat: config center will check plugin_metadata

- apisix/core/config_etcd.lua
- apisix/core/etcd.lua
> chore: adjust etcd max_fails for the admin api and add comments

- apisix/cli/snippet.lua
- apisix/conf_server.lua
- t/deployment/conf_server.t
> feat(deployment): send the right Host & SNI

- .licenserc.yaml
update the license location threshold. This should avoid errors thrown in PRs like these https://github.com/apache/apisix/runs/7065329491?check_suite_focus=true
See https://github.com/apache/apisix/pull/6775#discussion_r845818022 for context.
> chore: update the license location threshold.

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
- docs/zh/latest/plugins/basic-auth.md
> docs: fix typo and syntax

- docs/en/latest/building-apisix.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
add building apisix Chinese doc. sync https://github.com/apache/apisix/pull/7219/
> docs: add building apisix Chinese doc.

- conf/config-default.yaml
- docs/en/latest/admin-api.md
- docs/en/latest/mtls.md
- docs/en/latest/plugins/gzip.md
- docs/en/latest/plugins/real-ip.md
- docs/en/latest/wasm.md
- docs/en/latest/xrpc/redis.md
- docs/zh/latest/admin-api.md
- docs/zh/latest/mtls.md
- docs/zh/latest/plugins/client-control.md
- docs/zh/latest/plugins/gzip.md
- docs/zh/latest/plugins/proxy-control.md
- docs/zh/latest/plugins/real-ip.md
There is a "?" after the URI, preventing the link from jumping to the correct topic.
> docs: fix error link.

- docs/en/latest/installation-guide.md
- docs/zh/latest/installation-guide.md
docs: add source build apisix link.
> docs: add source build apisix link.

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
- .github/workflows/chaos.yml
- .github/workflows/cli-master.yml
- .github/workflows/cli.yml
- .github/workflows/code-lint.yml
- .github/workflows/doc-lint.yml
- .github/workflows/fuzzing-ci.yaml
- .github/workflows/kubernetes-ci.yml
- .github/workflows/license-checker.yml
- .github/workflows/tars-ci.yml
> ci: add next branche to CI coverage

- apisix/cli/file.lua
- apisix/core/etcd.lua
- t/cli/test_deployment_control_plane.sh
> feat(deployment): override existing etcd/enable_admin configurations

- apisix/core/etcd.lua
- t/core/etcd.t
> fix: error handling in core.etcd.server_version

- apisix/admin/utils.lua
- apisix/core/etcd.lua
- conf/config-default.yaml
- t/admin/response_body_format.t
1. remove action field in response body, it is useless
2. make the response body format simpler for list of object 
Fixes #7320
> feat: response body format

- docs/zh/latest/architecture-design/apisix.md
- docs/zh/latest/installation-guide.md
add "configuring APISIX" section to Installation docs
sync https://github.com/apache/apisix/pull/7362
> docs: add "configuring APISIX" section to Installation docs

- apisix/cli/schema.lua
- apisix/cli/snippet.lua
- apisix/core/config_etcd.lua
- apisix/core/etcd.lua
- docs/en/latest/architecture-design/deployment-role.md
- t/cli/test_deployment_control_plane_customed_nginx.sh
- t/deployment/conf_server.t
- t/deployment/mtls.t
> feat(deployment): control plane connects to conf server

- docs/en/latest/install-dependencies.md
- docs/zh/latest/install-dependencies.md
As we no longer support them since 15 months ago.
> docs: people don't need to care about OpenResty < 1.17.8

- docs/en/latest/plugins/node-status.md
- docs/zh/latest/plugins/node-status.md
refactor node-status Chinese doc and Update the English document format
> docs: update node-status doc

- docs/en/latest/plugins/ip-restriction.md
- docs/zh/latest/plugins/ip-restriction.md
update document under `docs/zh/latest/plugins/` and `docs/en/latest/plugins/`
> docs: refactor ip-restriction.md

- apisix/cli/schema.lua
- conf/config-default.yaml
- t/deployment/conf_server.t
> feat(deployment): set default timeout for every etcd conf

- apisix/cli/ngx_tpl.lua
> chore: make sure the http subsys with stream-only uses the correct path

- docs/en/latest/plugins/clickhouse-logger.md
- docs/zh/latest/plugins/clickhouse-logger.md
… error has no service_id
Fixes #7415
> docs: add service_id for the clickhouse create table SQL

- docs/en/latest/discovery.md
- docs/zh/latest/discovery.md
> docs: fix link error in service discovery documentation

- apisix/plugins/grpc-transcode.lua
Base on google doc: https://cloud.google.com/apis/design/errors#handling_errors
> change(grpc): add the correspondence between grpc code and http code

- docs/en/latest/plugins/mqtt-proxy.md
Added instructions on how to enable mTLS with the mqtt-proxy plugin at mqtt-proxy.md
> docs: enable mTLS with the mqtt-proxy plugin

- conf/config-default.yaml
add nacos, consul_kv, kubernetes configuration snippets in config-default.yaml 
Fixes #6969
> docs: add nacos, consul_kv, kubernetes configuration snippets in config-default.yaml (#6969)

- apisix/cli/file.lua
- apisix/cli/schema.lua
- t/cli/test_standalone.sh
> feat(deployment): support standalone

- apisix/cli/env.lua
> fix(typo): Modify error message

- apisix/cli/apisix.lua
feat: As a user, I want to run apisix init in directory other than /usr/local/apisix
Fixes #7390
> feat: run `apisix init` in directory other than /usr/local/apisix

- apisix/core/table.lua
- apisix/plugin.lua
> chore: someone's plugin needs to be initialized after prometheus

- docs/en/latest/plugins/ua-restriction.md
- docs/zh/latest/plugins/ua-restriction.md
> docs: refactor ua-restriction.md

- docs/en/latest/plugins/api-breaker.md
- docs/zh/latest/plugins/api-breaker.md
> docs:fix unhealthy.failures attribute description of api-breaker plugin

- docs/en/latest/control-api.md
> docs(control-api): fix introduced versions

- .asf.yaml
> docs: add labels in asf.yaml for GitHub.

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
- rockspec/apisix-2.15.0-0.rockspec
> feat: release 2.15.0

- docs/en/latest/plugins/csrf.md
- docs/zh/latest/plugins/csrf.md
> docs: refactor csrf.md

- docs/en/latest/certificate.md
- docs/zh/latest/certificate.md
> docs: set up multiple CA certificates

- docs/en/latest/plugins/consumer-restriction.md
- docs/zh/latest/plugins/consumer-restriction.md
> docs: refactor consumer-restriction.md

- .github/workflows/fuzzing-ci.yaml
Address broken fuzzing CI like
https://github.com/apache/apisix/runs/7625185369?check_suite_focus=true
https://github.com/apache/apisix/runs/7625351307?check_suite_focus=true
> ci: make sure the correct version of click is installed

- docs/en/latest/plugins/http-logger.md
- docs/zh/latest/plugins/http-logger.md
- docs/zh/latest/plugins/mqtt-proxy.md
refactor http-logger plugin doc
> docs: refactor http-logger plugin doc 

- .github/workflows/fuzzing-ci.yaml
- t/fuzzing/http_upstream.py
- t/fuzzing/upstream/nginx.conf
It can detect the bug fixed in 7b6b30f4aa84e7d91e2a62280c27b5fab3fce46a
> test: check if the connection reuse works well

- docs/en/latest/plugins/limit-conn.md
- docs/zh/latest/plugins/limit-conn.md
> docs: add websocket rate limit example

- docs/en/latest/plugins/mqtt-proxy.md
- docs/zh/latest/plugins/mqtt-proxy.md
refactor maqtt-proxy Chinese doc
> docs: refactor mqtt-proxy Chinese doc

- docs/zh/latest/plugins/skywalking-logger.md
refactor skywalking-logger plugin zh docs.
> docs: refactor skywalking-logger plugin docs

- docs/zh/latest/plugins/tcp-logger.md
docs: refactor tcp-logger plugin doc
> docs: refactor tcp-logger plugin Chinese doc

- Vision-and-Milestones.md
> docs: add vision and milestones for APISIX.

- docs/en/latest/plugin-develop.md
fix plugin-develop.md broken link
> docs: fix plugin-develop.md broken link

- apisix/cli/ngx_tpl.lua
- apisix/cli/ops.lua
- t/cli/test_deployment_control_plane.sh
> feat(deployment): disable request proxy in control plane

- README.md
- docs/zh/latest/README.md
> docs: update case studies link

- docs/en/latest/plugins/proxy-control.md
- docs/zh/latest/plugins/proxy-control.md
> docs: refactor proxy-control

- docs/en/latest/plugins/client-control.md
- docs/zh/latest/plugins/client-control.md
> docs: refactor client-control

- docs/zh/latest/plugins/client-control.md
update error details in client_control doc
> docs: update error details in client_control doc

- docs/en/latest/plugins/openwhisk.md
add the lost part to openwhish doc
> docs: add the lost part to openwhisk doc

- t/plugin/prometheus2.t
fix test case with not escaped bracket
> test: fix test case with not escaped bracket

- apisix/cli/ngx_tpl.lua
- apisix/cli/ops.lua
- t/cli/test_http_config.sh
> change: remove deprecated lua_shared_dicts

- docs/zh/latest/stream-proxy.md
> docs: update stream-proxy.md test case link

- apisix/init.lua
- apisix/schema_def.lua
- t/node/grpc-proxy-unary.t
- t/node/grpc-proxy.t
- t/plugin/grpc-transcode.t
> change: remove deprecated service_protocol in route

- apisix/cli/ngx_tpl.lua
> change: remove deprecated apisix.real_ip_header

- apisix/stream/plugins/mqtt-proxy.lua
- docs/en/latest/plugins/mqtt-proxy.md
- docs/en/latest/stand-alone.md
- docs/zh/latest/plugins/mqtt-proxy.md
- docs/zh/latest/stand-alone.md
- t/admin/stream-routes.t
- t/config-center-yaml/stream-route.t
- t/debug/debug-mode.t
- t/stream-plugin/mqtt-proxy.t
- t/stream-plugin/mqtt-proxy2.t
> change(mqtt-proxy):  remove deprecated upstream

- Makefile
> chore: the directories in Makefile should be listed in alphabetical order

- README.md
Update Expired Slack Link, this link will be expired in 30 days.
> docs: update expired Slack link

- apisix/init.lua
- t/APISIX.pm
- t/error_page/error_page.t
> fix: the phases after proxy should run when 500 happens before proxy

- apisix/cli/ops.lua
- apisix/cli/schema.lua
- conf/config-default.yaml
- docs/en/latest/FAQ.md
- docs/en/latest/admin-api.md
- docs/en/latest/certificate.md
- docs/en/latest/mtls.md
- docs/zh/latest/FAQ.md
- docs/zh/latest/admin-api.md
- docs/zh/latest/certificate.md
- docs/zh/latest/mtls.md
- t/cli/test_access_log.sh
- t/cli/test_admin.sh
- t/cli/test_admin_mtls.sh
- t/cli/test_main.sh
- t/cli/test_snippet.sh
- t/cli/test_validate_config.sh
> change: drop support for port_admin

- README.md
docs: fix the name to 'Apache APISIX'
> docs: fix README.md file and the name should be Apache APISIX

- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/config.json
- docs/en/latest/how-to-build.md
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/config.json
- docs/zh/latest/how-to-build.md
- rockspec/apisix-2.13.3-0.rockspec
> feat: release 2.13.3

- .asf.yaml
Prevent error msg like:
An error occurred while running github feature in .asf.yaml!:
422 {"message": "Validation Failed", "errors": ["A repository cannot have more than 20 topics."], "documentation_url": "https://docs.github.com/rest/reference/repos#replace-all-repository-topics"}
from ASF infra
> chore: ensure the total topics are <= 20

- docs/zh/latest/plugins/kafka-logger.md
> docs: refactor kafka-logger plugin doc

- docs/zh/latest/plugins/rocketmq-logger.md
> docs: refactor rocketmq-logger plugin doc

- .github/workflows/build.yml
- .github/workflows/cli-master.yml
- .github/workflows/cli.yml
- .github/workflows/kubernetes-ci.yml
- .github/workflows/performance.yml
- .github/workflows/tars-ci.yml
ref: https://github.com/actions/runner-images/issues/6002
> ci: update Ubuntu to 20.04 as 18.04 was deprecated

- docs/en/latest/plugins/request-id.md
- docs/zh/latest/plugins/request-id.md
update documents under `docs/zh/latest/plugins/` along with `docs/en/latest/plugins/`
> docs(plugin): refactor request-id.md

- docs/en/latest/terminology/plugin.md
- docs/zh/latest/terminology/plugin.md
> docs: add missing priority of the plugins in Plugin Config

- apisix/plugins/limit-count.lua
- t/plugin/limit-count3.t
> fix(limit-count): different route with same conf should not share counter

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
Use get method for query resources.
> docs: use get method for query resources

- docs/en/latest/deployment-modes.md
> docs(deployment): fix typo

- docs/en/latest/internal/testing-framework.md
- utils/gen-vote-contents.sh
Also update the link in gen-vote-contents.sh
> docs: correct the test-nginx description

- apisix/plugins/zipkin.lua
- t/plugin/zipkin2.t
> fix(zipkin): send trace IDs with a reject sampling decision

- t/cli/test_upstream_mtls.sh
sleep more time to ensure test pass.
> test: sleep 1 second in t/cli/test_upstream_mtls.sh

- apisix/plugins/response-rewrite.lua
- t/plugin/response-rewrite.t
Fixes  https://github.com/apache/apisix/issues/7722
> fix: response-rewrite plugin might cause Apache AIPSIX hanging

- apisix/cli/ngx_tpl.lua
- t/APISIX.pm
set constants.apisix_lua_home for used by plugins.
> feat: set constants.apisix_lua_home for used by plugins

- README.md
According to https://github.com/apache/apisix-website/pull/1318, updated Slack's invite link and add a Slack badge
> docs: change slack invitation link & add the badge

- .github/workflows/chaos.yml
- t/chaos/killetcd/killetcd.go
and upgrade go version to 1.17
> test(chaos): in deployment mode, after all etcd nodes are down, upsream gets 502

- docs/en/latest/config.json
- docs/en/latest/how-to-guides/observe-your-api.md
Added How-To guide section with the first guide for Observe your APIs which shows use cases of observability plugins. 
Fixes #7854
> docs: Add How-to guides section with the first guide

- docs/en/latest/plugins/basic-auth.md
- docs/en/latest/plugins/forward-auth.md
- docs/en/latest/plugins/ldap-auth.md
- docs/en/latest/plugins/opa.md
- docs/zh/latest/plugins/opa.md
> docs: use 9180 as Admin API's port and add X-API-KEY

- conf/config-default.yaml
- docs/en/latest/discovery/kubernetes.md
- docs/zh/latest/discovery/kubernetes.md
> docs: refactor kubernetes discovery

- .github/workflows/doc-lint.yml
- .github/workflows/lint.yml
> ci: enable lint on push

- ci/common.sh
> ci: fix npm registry error

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
> docs: fix response fmt & curl cmd

- docs/en/latest/discovery/kubernetes.md
- docs/zh/latest/discovery/kubernetes.md
Update https://github.com/apache/apisix/pull/7944 formatting problem
> docs: update discovery Kubernetes doc formatting

- docs/en/latest/config.json
- docs/en/latest/tutorials/expose-api.md
- docs/en/latest/tutorials/observe-your-api.md
- docs/en/latest/tutorials/protect-api.md
- docs/zh/latest/config.json
- docs/zh/latest/terminology/plugin-config.md
- docs/zh/latest/tutorials/expose-api.md
- docs/zh/latest/tutorials/observe-your-api.md
- docs/zh/latest/tutorials/protect-api.md
Fixes [7854](https://github.com/apache/apisix/issues/7854)
> docs: add tutorials docs and fix others docs

- t/cli/test_admin.sh
- t/config-center-yaml/plugin.t
> test: fix broken test introduced in #7926

- .github/workflows/chaos.yml
- ci/pod/nacos/service/Dockerfile
- t/chaos/killetcd/killetcd.go
(cherry picked from commit bc6cd4fd6a33314f176906a93fa6dd7ed0e31f91)
> ci: change base JDK images to eclipse-temurin as openjdk is being deprecated

- .asf.yaml
> docs: redirect homepage to blog of apisix.a.o.

- .github/workflows/build.yml
- .github/workflows/chaos.yml
- .github/workflows/fuzzing-ci.yaml
- .gitmodules
- t/chaos/killetcd/killetcd.go
- t/chaos/utils/Dockerfile
(cherry picked from commit 17338b9)### Description
> ci: backport some high version changes to make CI pass

- t/cli/test_cmd.sh
- t/cli/test_main.sh
> test: fix flaky test 'failed: should find no corresponding process'

- apisix/init.lua
- t/core/grpc-openresty.t
> fix: ensure the core.grpc is nil under vanilla OpenResty

- docs/en/latest/plugins/ext-plugin-post-resp.md
- docs/en/latest/plugins/ext-plugin-pre-req.md
- docs/zh/latest/plugins/ext-plugin-post-resp.md
- docs/zh/latest/plugins/ext-plugin-pre-req.md
> docs: fix sample configuration formatting errors

- .github/workflows/centos7-ci.yml
- ci/common.sh
1、Cache deps for centos7 ci.
2、Fixes post cache deps failed:
```
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstdmt -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/apisix/apisix --files-from manifest.txt
/usr/bin/tar: deps/lib/luarocks/rocks-5.1/lrexlib-pcre/[2](https://github.com/apache/apisix/actions/runs/3209507732/jobs/5247107335#step:34:2).9.1-1/doc/SciTE.properties: Cannot open: Permission denied
/usr/bin/tar: deps/lib/luarocks/rocks-5.1/lrexlib-pcre/2.9.1-1/doc/lrexlib.css: Cannot open: Permission denied
/usr/bin/tar: deps/lib/luarocks/rocks-5.1/lrexlib-pcre/2.9.1-1/doc/html[4](https://github.com/apache/apisix/actions/runs/3209507732/jobs/5247107335#step:34:4)css1.css: Cannot open: Permission denied
/usr/bin/tar: …
```
> fix(ci): post cache deps failed

- apisix/core/response.lua
- t/core/response.t
> chore: update hold_body_chunk to avoid unexpected behavior

- .github/workflows/performance.yml
> ci: update the trigger of performance test

- docs/en/latest/deployment-modes.md
Fixes # (https://github.com/apache/apisix/issues/8067)
> docs: fix typo and add `prefix`

- apisix/cli/ngx_tpl.lua
- apisix/init.lua
- t/APISIX.pm
- t/error_page/error_page.t
- t/node/upstream-status-5xx.t
- t/node/upstream-status-all.t
Performance info:
wrk2 -U -d 30 --timeout 10s -c 100 -t 5 -R 5000 http://127.0.0.1:9080/hello
Before:
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     4.15ms    9.57ms  86.21ms   94.70%
Req/Sec     1.00k     7.98     1.04k    91.21%
After:
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     2.39ms    2.20ms  44.13ms   98.86%
Req/Sec     1.05k   186.67     2.22k    79.22%
wrk -d 30 --timeout 10s -c 100 -t 5 http://127.0.0.1:9080/hello
Before:
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    16.29ms   10.12ms 343.24ms   99.07%
Req/Sec     1.28k   133.95     2.63k    90.79%
After:
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    17.81ms   26.67ms 711.64ms   98.38%
Req/Sec     1.29k   179.37     2.32k    90.25%
Signed-off-by: spacewander …
> perf: move the APISIX error page to apisix-base

- docs/en/latest/config.json
- docs/en/latest/tutorials/cache-api-responses.md
I added new tutorial about Cache API responses under Tutorials section
> docs: Add new tutorial cache API responses

- apisix/core/ctx.lua
- t/core/ctx2.t
> feat(core): add no_cacheable option to custom variable

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
> docs: correct the query syntax and preserve the response data structure

- apisix/plugins/workflow.lua
- t/plugin/workflow.t
workflow plugin should support operator, now only support array
> fix: workflow plugin should support operator

- apisix/core/config_etcd.lua
> chore: don't implement "server_version" twice

- apisix/plugins/ai.lua
- t/plugin/ai.t
- t/plugin/ai2.t
- t/plugin/ai3.t
> fix(ai): typo key name

- t/plugin/ai4.t
> test: add test cases for ai module

- t/plugin/skywalking.t
> test: fix plugin disable syntax

- t/plugin/zipkin2.t
See
https: //github.com/apache/apisix/actions/runs/3431404849/jobs/5723606878
https: //github.com/apache/apisix/actions/runs/3431404870/jobs/5723606995
> test: fix test fails randomly caused by the order

- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
- rockspec/apisix-2.15.1-0.rockspec
> feat: release 2.15.1

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
- rockspec/apisix-2.15.1-0.rockspec
> feat: ready to release 2.15.1

- utils/gen-vote-contents.sh
> chore: update the link in gen-vote-contents.sh 

- apisix/admin/v3_adapter.lua
- t/admin/api.t
> fix: v3_adapter.filter(data) causes some API response body empty when disabling v3 admin API

- apisix/plugins/proxy-mirror.lua
- t/plugin/proxy-mirror.t
> feat: proxy-mirror plugin resolve host (#7861)

- docs/en/latest/tutorials/expose-api.md
- docs/zh/latest/tutorials/expose-api.md
> docs: fix expose-api doc

- apisix/core/env.lua
> refactor(env): rename funtion name

- apisix/kms/vault.lua
> chore: add some comment for make_request_to_vault function

- docs/zh/latest/config.json
- docs/zh/latest/mtls.md
- docs/zh/latest/tutorials/client-to-apisix-mtls.md
- docs/zh/latest/tutorials/route-mtls.md
Currently, our mTLS documentation is not user-friendly and users cannot quickly configure mTLS based on the documentation. We need to optimize it to make it clearer.
https://github.com/apache/apisix/blob/master/docs/en/latest/mtls.md
Added tutorial on how to configure mTLS between the client and APISIX
> docs: added tutorial on how to configure mTLS between the client and APISIX

- docs/en/latest/config.json
- docs/en/latest/mtls.md
- docs/en/latest/tutorials/client-to-apisix-mtls.md
Translation #8440 
Added tutorial on how to configure mTLS between the client and APISIX
> docs: add Configure mTLS for client to APISIX (EN)

- docs/zh/latest/admin-api.md
fix https://apisix.apache.org/zh/docs/apisix/next/admin-api/#consumer, use `username` instead of `id` for consumers api
> docs: a consumer is identified by a `username` property, not `id`

- README.md
Cause APISIX has added some enterprise users, update the relevant details.
> docs: update README APISIX users part

- README.md
- docs/zh/latest/README.md
Replace the multi-lang-support image in doc with the newer
> docs: replace the multi-lang-support image with the newer

- .github/workflows/gm-cron.yaml
Now the CI can pass again. The result can be found at https://github.com/spacewander/incubator-apisix/actions/runs/3747415680/jobs/6363616743
> ci: add missing file in GM cron test

- docs/en/latest/config.json
- docs/en/latest/tutorials/add-multiple-api-versions.md
Added a new tutorial about publishing and managing multiple API versions.
> docs: Add new tutorial for managing multiple API version

- apisix/inspect/init.lua
- docs/en/latest/plugins/inspect.md
Fix log level and module path.
> fix: inspect plugin log level and module path

- CONTRIBUTING.md
Because the content is a bit outdated, some details need to be updated.
Before:
After:
> docs: update Contributing details about gifts part

- CONTRIBUTING.md
Update Contributing gift content details
> docs: update Contributing gift details

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
- rockspec/apisix-3.1.0-0.rockspec
> feat: release APISIX 3.1.0

- apisix/control/v1.lua
- t/control/schema.t
support export consumer group schema
> feat: support export consumer group schema

- docs/en/latest/stand-alone.md
- docs/zh/latest/stand-alone.md
This PR is a backport of https://github.com/apache/apisix/pull/8242
> docs: update standalone docs for change in SSL parameter (#8242)

- docs/en/latest/router-radixtree.md
There was ambiguity in line 170 regarding the statement. Hence I use the “if” statement to make it more understandable. Moreover, in line 273 the “out” was not used appropriately. It should be either used after the “filter” or we should not use it.
Talking about changes, only grammatical errors are being updated because they were creating some ambiguity in the documentation. The motivation behind this change is that any user who came to read the documentation should understand at once what this code is doing and what the documentation is saying.
> docs: fix typo and grammatical error

- apisix/plugin.lua
- t/plugin/plugin2.t
> fix: use previous way to disable plugins

- .github/workflows/centos7-ci.yml
> ci: use fixed os version of ubuntu (#8438)

- docs/en/latest/tutorials/observe-your-api.md
> docs: fix observe-your-api.md

- docs/en/latest/discovery/control-plane-service-discovery.md
- docs/zh/latest/discovery/control-plane-service-discovery.md
fix error link about nacos deployment tutorial 
Fixes #8657
> docs: fix error link about nacos deployment tutorial 

- rockspec/apisix-master-0.rockspec
refer:
https://github.com/casbin/lua-casbin/pull/140
> fix: upgrade casbin to 1.41.3 to improve performance

- docs/en/latest/certificate.md
- docs/zh/latest/certificate.md
Fixes # https://github.com/apache/apisix/issues/8698, update ZH/EN docs link
> docs: fix deployment doc links

- apisix/core/pubsub.lua
by using the power in new version of lua-protobuf
> refactor(pubsub): simpify the get_cmd implementation

- NOTICE
> chore: hi 2023

- rockspec/apisix-master-0.rockspec
> chore: upgrade `casbin` to `1.41.5` (#8744)

- t/lib/server.lua
- t/plugin/sls-logger.t
use operator # instead of string.len
> chore: use operator # instead of string.len

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
- rockspec/apisix-2.15.2-0.rockspec
> feat: ready to release 2.15.2

- docs/en/latest/terminology/global-rule.md
- docs/zh/latest/terminology/global-rule.md
fix global-rule.md wrong curl address
> docs: fix global-rule.md wrong curl address

- .github/workflows/doc-lint.yml
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/FAQ.md
- docs/zh/latest/README.md
- docs/zh/latest/control-api.md
- docs/zh/latest/debug-mode.md
- docs/zh/latest/discovery.md
- docs/zh/latest/external-plugin.md
- docs/zh/latest/grpc-proxy.md
- docs/zh/latest/install-dependencies.md
- docs/zh/latest/plugin-develop.md
- docs/zh/latest/router-radixtree.md
- docs/zh/latest/stream-proxy.md
The new version of AutoCorrect can check the invalid whitespaces and punctuations.
> ci: Improve autocorrect lint check.

- docs/zh/latest/plugins/elasticsearch-logger.md
> docs: fix elasticsearch-logger

- apisix/admin/consumers.lua
- apisix/admin/init.lua
- apisix/admin/plugin_metadata.lua
- apisix/admin/resource.lua
- apisix/admin/ssl.lua
> refactor(admin): refactor admin consumers/plugin_metadata

- docs/en/latest/admin-api.md
Fix in master, the code block syntax error of the `admin-api.md` documentation
> docs(admin-api.md): code block syntax

- docs/en/latest/admin-api.md
Fix in version 3.1, the code block syntax error of the `admin-api.md` documentation
> docs(admin-api.md): code block syntax (v3.1)

- docs/zh/latest/architecture-design/apisix.md
update chinese architecture design doc
Fixes #8739
> docs: update the chinese architecture design doc

- docs/en/latest/plugin-develop.md
Fixes #8796 
cc - @moonming @navendu-pottekkat
> docs: fix indent in encrypted-storage-fields

- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
- rockspec/apisix-2.15.3-0.rockspec
> feat: release APISIX 2.15.3

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
- rockspec/apisix-2.15.3-0.rockspec
> feat: ready to release 2.15.3

- .github/workflows/centos7-ci.yml
- .github/workflows/fips.yml
- .github/workflows/gm-cron.yaml
- apisix/consumer.lua
- t/node/consumer-plugin2.t
- t/plugin/udp-logger.t
> fix(consumer): work if the etcd connection failed during starting

- docs/en/latest/getting-started.md
Corrected doc grammar by changing: "With the Route has created" to "With the Route being created"
> docs: Fixed doc wording

- docs/en/latest/plugins/openid-connect.md
> docs: Fixed typo

- docs/en/latest/plugins/consumer-restriction.md
Test: https://gist.github.com/kayx23/4c29d608991f5b9216c71d6c45c68d01
Relevant PR: https://github.com/api7/docs/pull/130
> docs: updated consumer-restriction plugin use with Global Rule

- apisix/plugins/forward-auth.lua
- docs/en/latest/plugins/forward-auth.md
- docs/zh/latest/plugins/forward-auth.md
- t/plugin/forward-auth.t
> feat: allow degradation

- docs/zh/latest/tutorials/observe-your-api.md
update png and add filter condition.
> docs: update png and add filter condition

- docs/zh/latest/CHANGELOG.md
Fixes https://github.com/apache/apisix/issues/9410
actually. this PR is generated by
```shell
$ autocorrect --fix  ./docs/zh/latest/
```
> docs: CHANGELOG.md Chinese docs lint

- docs/zh/latest/tutorials/observe-your-api.md
> docs: update plugin node-status link

- docs/en/latest/plugins/grpc-transcode.md
- docs/zh/latest/plugins/grpc-transcode.md
Fixes https://github.com/apache/apisix/issues/9405
> docs: use shell instead of Python to configure protos resources

- docs/zh/latest/tutorials/observe-your-api.md
> docs: Remove unused access links

- docs/en/latest/building-apisix.md
Current doc at: https://apisix.apache.org/docs/apisix/next/building-apisix/
Made some improvements to doc as I built from source.
> docs: Improve Building APISIX from source

- docs/en/latest/plugins/opa.md
OPA is used for authorization not authentication. Updated the description.
> docs: updated description for OPA plugin

- docs/en/latest/installation-guide.md
Update the link of "Getting Started"
Fixes #9500
> docs: Update the link of "Getting Started"

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
- t/admin/stream-routes.t
> test: clarify the support for IPV6

- docs/zh/latest/terminology/secret.md
> docs: fix typo in secret docs

- docs/en/latest/admin-api.md
Fixes #9404 
* I have verified the `Request Methods` through local testing. This endpoint does not support `PATCH` method. 
* You may notice wordings in `Description` are not consistent with the others. IMO the other ones need fixings. 
* Please help me make sure the relative links are correct
> docs: add Protos endpoint to Admin API

- .github/workflows/build.yml
- ci/init-plugin-test-service.sh
- ci/pod/docker-compose.plugin.yml
- t/plugin/clickhouse-logger.t
> chore(ci): use real clickhouse server in ci

- t/plugin/udp-logger.t
> ci: fix eclint error

- docs/en/latest/plugins/clickhouse-logger.md
- docs/zh/latest/plugins/clickhouse-logger.md
> docs: improve clickhouse logger docs

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
- rockspec/apisix-3.2.1-0.rockspec
> feat: ready to release 3.2.1

- docs/zh/latest/admin-api.md
fix  header "使用环境变量" . 
Refer to other header styles for modifications ， and  replace ”$“ with "#" 
> docs: Update admin-api.md

- apisix/cli/ops.lua
Updated help command message for APISIX CLI for relevant documentation.
No functional change.
> refactor: update help command message for APISIX CLI

- docs/en/latest/FAQ.md
> docs: add missing triple backtick

- docs/en/latest/building-apisix.md
- docs/en/latest/discovery/kubernetes.md
- docs/en/latest/plugin-develop.md
- docs/en/latest/plugins/elasticsearch-logger.md
- docs/zh/latest/README.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/discovery/kubernetes.md
- docs/zh/latest/plugin-develop.md
- docs/zh/latest/plugins/elasticsearch-logger.md
> docs: replace some urls that point to github with relative paths

- docs/en/latest/installation-guide.md
Reference: https://openresty.org/en/linux-packages.html#debian
> docs: add correct link for openresty arm64 repo

- t/xds-library/config_xds.t
fix https://github.com/apache/apisix/issues/9551
Fixes XDS failures on CI. Code changes from on the file `t/xds-library/config_xds.t` were missing from PR #9559. Those changes have been added.
> fix(ci): fix XDS test case

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
- rockspec/apisix-3.4.0-0.rockspec
> feat: release APISIX 3.4.0

- docs/en/latest/plugins/batch-requests.md
- docs/zh/latest/plugins/batch-requests.md
explain in more details for the batch-requests plugin
> docs: explain in more details for the batch-requests plugin

- docs/zh/latest/admin-api.md
Provide Chinese documentation for Admin API Secret.
https://apisix.apache.org/docs/apisix/admin-api/#secret
Fixes #9520
> docs: add Secret chinese document to Admin API

- README.md
- docs/en/latest/deployment-modes.md
- docs/en/latest/terminology/plugin.md
- docs/zh/latest/plugins/openwhisk.md
Updated text found as stand-alone and replaced with `standalone`
Fixes #9599
> chore(update): replaced stand-alone with standalone

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
> docs: correct the wrong link in CHANGELOG.md

- apisix/plugins/workflow.lua
- t/plugin/workflow2.t
Fixes https://github.com/apache/apisix/issues/9777
> fix(workflow): enhance schema check

- ci/common.sh
> fix(ci): ldap build failure

- t/xrpc/redis2.t
> fix(ci): regex does not match err.log for xrpc

- apisix/plugins/consumer-restriction.lua
- t/plugin/consumer-restriction.t
- t/plugin/consumer-restriction2.t
Fixes  https://github.com/apache/apisix/issues/9761 and fix some test cases
> refactor(consumer-restriction): optimize the error log when the corresponding resource is not fetched

- apisix/cli/file.lua
- apisix/cli/ops.lua
- apisix/cli/util.lua
- apisix/core/profile.lua
- t/cli/test_cmd.sh
Fixes https://github.com/apache/apisix/issues/9171
Discussion in https://github.com/apache/apisix/pull/9521#discussion_r1201718431
> refactor: access customized config directly

- docs/zh/latest/terminology/upstream.md
Fix docs displaying Markdown content
> docs: fix displaying code block

- rockspec/apisix-master-0.rockspec
> fix: update penlight to 1.13.1

- apisix/core/config_etcd.lua
- t/core/config_etcd.t
Fixes https://github.com/apache/apisix/issues/9951
> fix: can't sync etcd data if key has special character

- docs/zh/latest/ssl-protocol.md
> docs(ssl-protocol): fix chinese doc

- apisix/wasm.lua
- t/wasm/request-body.t
- t/wasm/route.t
This is an optimization of the previous PR
Fixes #10072
> refactor: optimization wasm plugin config check

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- ci/centos7-ci.sh
- ci/redhat-ci.sh
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
- rockspec/apisix-3.5.0-0.rockspec
- t/chaos/utils/Dockerfile
- t/core/etcd.t
- t/node/upstream-websocket.t
- t/plugin/ext-plugin/sanity.t
- t/plugin/ext-plugin/sanity2.t
> feat: release APISIX 3.5.0

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
> docs: add missing Admin API Plugin endpoints

- docs/en/latest/external-plugin.md
> docs: fix typos in plugin docs

- docs/en/latest/internal/testing-framework.md
Fix documentation mentioning test::nginx `log_level` directive usage.
> docs: fix test directive usage

- docs/en/latest/terminology/consumer.md
- docs/zh/latest/terminology/consumer.md
> docs: add auth plugins that work with consumers to the consumer doc

- docs/en/latest/plugins/proxy-cache.md
Just update the `proxy-cache.md` for unexpected mandarin comment in EN doc
> docs: update proxy-cache.md for incorrect language

- docs/en/latest/plugins/limit-conn.md
> fix(docs): limit-conn plugin typo

- t/core/schema.t
avoid time out in `t/core/schema.t`  TEST 3: collectgarbage
https://github.com/apache/apisix/actions/runs/6232418219/job/16915563503#step:16:344
> ci: fix client socket timed out error

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
- rockspec/apisix-3.6.0-0.rockspec
> feat: release APISIX 3.6.0

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
> docs: fixed typo in 3.6 release log.

- CHANGELOG.md
- docs/zh/latest/CHANGELOG.md
Fix a few things in v3.6.0 release notes.
> docs: update 3.6.0 release notes

- apisix/plugins/cors.lua
This change was missed in #10308.
> fix: update schema description in cors.lua

- docs/en/latest/plugins/response-rewrite.md
- docs/zh/latest/plugins/response-rewrite.md
As titled. It's not a good practice to use underscores in headers.
> docs: update underscore to hyphen in HTTP headers in `response-rewrite` plugin

- README.md
FYI, there're 2 usecase articles publishing for long time, but haven't update on README profile.
- https://apisix.apache.org/blog/2023/06/02/lenovo-uses-apisix/
- https://apisix.apache.org/blog/2023/09/20/wecity-uses-apisix/
> docs: update APISIX usecases in README

- .github/workflows/close-unresponded.yml
This PR will exempt issues labeled `don't close` from being closed by [this](https://github.com/apache/apisix/blob/master/.github/workflows/close-unresponded.yml) github action. Also, the `days-before-issue-stale` has been increased. Ref: https://github.com/actions/stale#exempt-issue-labels
> chore: update rules for unresponded issues

- utils/install-dependencies.sh
Fixes https://github.com/apache/apisix/issues/10401
> feat: install-dependencies switch apisix-base to apisix-runtime

- ci/init-plugin-test-service.sh
> chore: add comment for clarity

- docs/en/latest/deployment-modes.md
Swapped routers with routes in standalone mode. They mean different things for APISIX.
> docs: correct terms in standalone mode doc

- docs/en/latest/terminology/upstream.md
Update documentation to use the right link to the service terminology
> docs: Update link to service terminology

- .github/workflows/fuzzing-ci.yaml
https://github.com/apache/apisix/issues/10431
It is planned to use a replacement event library to fix this problem of linking, but this requires preparation in advance to use APISIX runtime in CI to run tests.
> ci: fuzzing-ci remove openresty

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
- rockspec/apisix-3.7.0-0.rockspec
> feat: release APISIX 3.7.0

- apisix/cli/schema.lua
The CLI tests seem to be [failing repeatedly](https://github.com/apache/apisix/actions/runs/6926888586/job/18839768528#step:7:7489), although when the schema was updated in #10339 the tests were passing.
If the schema change is causing issues, we might need to revert that PR and find the underlying issue.
This PR tries to fix the possible issue with the schema that might be causing the tests to fail.
> fix: don't require etcd under deployment

- docs/en/latest/debug-mode.md
- docs/en/latest/getting-started/load-balancing.md
- docs/en/latest/getting-started/rate-limiting.md
- docs/zh/latest/debug-mode.md
- docs/zh/latest/getting-started/load-balancing.md
- docs/zh/latest/getting-started/rate-limiting.md
Add doc changes #10564 and #10549 to master.
> docs: update xargs command and add `#END` to `debug.yaml` example

- docs/en/latest/plugins/clickhouse-logger.md
- docs/zh/latest/plugins/clickhouse-logger.md
correct the clickhouse-logger's docs
Fixes Issue: https://github.com/apache/apisix/issues/10568
> docs: correct the clickhouse-logger docs

- docs/en/latest/plugins/gzip.md
- docs/zh/latest/plugins/gzip.md
update the gzip plugin documentation
> docs: update the gzip plugin documentation

- CODE_STYLE.md
conflict with code style on the table for table.new to pre-allocate the table
> docs: fix some errors in the pre-allocate table

- docs/en/latest/terminology/consumer.md
> docs: fix spelling in consumer docs

- docs/en/latest/discovery/control-plane-service-discovery.md
- docs/zh/latest/discovery/control-plane-service-discovery.md
> docs: fix wrong links in control plane service discovery doc

- docs/zh/latest/admin-api.md
> docs: remove duplicate sentences in admin-api.md

- docs/zh/latest/CODE_STYLE.md
The English document has been repaired, but the Chinese document is missing
> docs: Fix some errors in Chinese document preallocation table

- docs/en/latest/terminology/plugin-config.md
> docs: update plugin-config.md

- docs/en/latest/deployment-modes.md
- docs/en/latest/profile.md
> docs: add info about env var usage

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
- .github/workflows/gm-cron.yaml
- .github/workflows/redhat-ci.yaml
fix ci error: https://github.com/apache/apisix/actions/runs/7471630641/job/20369004834?pr=10645
> ci: fix start dubbo error

- docs/zh/latest/config.json
- docs/zh/latest/plugins/brotli.md
add Chinese translation for the new brotil plugin
Fixes #10811
> docs: add Chinese translation for the new brotil plugin

- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/config.json
- docs/zh/latest/debug-mode.md
- docs/zh/latest/external-plugin.md
Adjust the directory of Chinese documents
Fixes #10785
> docs: Adjust the directory of Chinese documents

- docs/en/latest/plugins/body-transformer.md
For the body-transformer plugin, add 'template_is_base64'attribute description
> docs:  body-transformer plugin, add 'template_is_base64' attribute description

- docs/en/latest/plugins/jwe-decrypt.md
- docs/zh/latest/plugins/jwe-decrypt.md
Update `jwe-decrypt` plugin info per code.
> docs: update `jwe-decrypt` plugin info

- docs/en/latest/plugins/jwe-decrypt.md
- docs/zh/latest/plugins/jwe-decrypt.md
This PR updates the examples by adding required attributes; or else, with the current example, you error out with:
> docs: add required attributes to the examples of jwe-decrypt

- docs/en/latest/installation-guide.md
- docs/zh/latest/installation-guide.md
> chore: update installation-guide doc (#10820)

- apisix/http/route.lua
- t/discovery/consul_dump.t
fix ci error: https://github.com/apache/apisix/actions/runs/7606590197/job/20712613964#step:19:683
> fix(ci): stability of consul test cases

- docs/en/latest/plugins/multi-auth.md
- docs/zh/latest/plugins/multi-auth.md
Fix IP address in multi-auth doc, remove the mentioning of dashboard, and update a few wordings.
> docs: fix ip address in multi-auth doc

- NOTICE
> chore: hi 2024

- docs/en/latest/config.json
- docs/en/latest/plugins/ocsp-stapling.md
- docs/zh/latest/config.json
- docs/zh/latest/plugins/ocsp-stapling.md
add docs for the new ocsp-stapling plugin
> docs: add docs for the new ocsp-stapling plugin

- docs/en/latest/plugins/grpc-transcode.md
- docs/zh/latest/plugins/grpc-transcode.md
Previously [the python script in this doc was removed and replaced with shell commands](https://github.com/apache/apisix/pull/9414). A few sentences about the Python script seem to have been forgotten. This PR removes them.
> docs: remove outdated content in grpc-transcode plugin doc

- docs/en/latest/plugins/api-breaker.md
Fixes : api-breaker.md example json err format
> docs: fix error in api-breaker.md usage example

- Makefile
- ci/common.sh
This pr want to fix [ci problem](https://github.com/apache/apisix/actions/runs/8015080220/job/21895612978?pr=10887) introduced by https://github.com/apache/apisix/pull/10874
> fix: add apisix/plugin/limit-req to makefile

- docs/zh/latest/tutorials/client-to-apisix-mtls.md
> docs: fix broken code block in client-to-apisix-mtls.md

- t/core/json.t
> test(core.json): add an example for encode empty array

- docs/en/latest/config.json
- docs/zh/latest/config.json
> docs: change the workflow plugin category from General to Traffic Management

- README.md
> docs: remove QQ group

- apisix/ssl/router/radixtree_sni.lua
> perf(ssl): reuse array length variable

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
> feat: release 3.9.0

- docs/en/latest/plugins/consumer-restriction.md
- docs/zh/latest/plugins/consumer-restriction.md
The PR corrected type information in `consumer-restriction` plugin.
> docs: correct `consumer-restriction` type description

- ci/free_disk_space.sh
Fixes # [(bug(ci): ci failing due to incomplete docker image backup)](https://github.com/apache/apisix/issues/11068)
> fix(ci): free disk space

- apisix/plugins/forward-auth.lua
- t/plugin/forward-auth2.t
author: suryaprabhakark
sync https://github.com/apache/apisix/pull/11021
> fix: add post request headers only if auth request method is post

- CHANGELOG.md
add change log for release version 3.8.1
> docs: release version 3.8.1

- CHANGELOG.md
> docs: release version 3.9.1

- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
> docs: release APISIX 3.9.1

- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
> docs: release APISIX 3.8.1

- docs/en/latest/plugins/aws-lambda.md
- docs/zh/latest/plugins/aws-lambda.md
Fixes #11177 (see issue for more details)
> docs: improve `aws-lambda` plugin docs

- .asf.yaml
We need more eyes to improve code quality
> ci: increase PR reviewers to 3 when merge to master.

- README.md
Apache APISIX has a Review page on G2, kindly add a review if you are using Apache APISIX.
> docs: added Write a Review link

- docs/en/latest/deployment-modes.md
Add plugin configs to standalone deployment doc according to the test https://github.com/apache/apisix/blob/master/t/config-center-yaml/plugin-configs.t
Fixes #11255
> docs: add plugin config to standalone deployment doc

- README.md
> docs: add http/3 in README.md and remove outdated content.

- Makefile
> build(undeps): remove all rocks before remove openresty

- conf/debug.yaml
> docs: improve debug mode yaml comments

- docs/en/latest/plugins/opentelemetry.md
- docs/zh/latest/plugins/opentelemetry.md
Simple commit to fix OTel protocol name in the docs.
> docs: fix otel protocol name 

- apisix/admin/resource.lua
- apisix/plugin.lua
- apisix/plugins/sls-logger.lua
- t/admin/plugin-metadata.t
Fixes https://github.com/apache/apisix/issues/11216
fix part 1 of this issue by adding an id field to the plugin metadata with the value of the plugin name
This PR is a partial fork of https://github.com/apache/apisix/pull/11430.
> fix: plugin metadata add id value for etcd checker

- docs/en/latest/FAQ.md
- docs/en/latest/benchmark.md
- docs/en/latest/customize-nginx-configuration.md
- docs/en/latest/install-dependencies.md
- docs/en/latest/installation-guide.md
- docs/en/latest/plugin-develop.md
- docs/en/latest/plugins/aws-lambda.md
- docs/en/latest/plugins/azure-functions.md
- docs/en/latest/plugins/inspect.md
- docs/en/latest/pubsub.md
- docs/en/latest/terminology/plugin.md
- docs/zh/latest/FAQ.md
- docs/zh/latest/benchmark.md
- docs/zh/latest/customize-nginx-configuration.md
- docs/zh/latest/install-dependencies.md
- docs/zh/latest/installation-guide.md
- docs/zh/latest/plugin-develop.md
- docs/zh/latest/terminology/plugin.md
3.10.0 update: https://github.com/apache/apisix/pull/11343
The changes also need to be merged into the 3.10.0 release branch.
> docs: update docs for the removal of `config-default.yaml` (master)

- docs/en/latest/plugins/limit-req.md
- docs/zh/latest/plugins/limit-req.md
Modify the limit-req plugin example
> docs: correct rate in `limit-req` plugin example

- apisix/plugins/multi-auth.lua
> style(multi-auth): code formate

- docs/en/latest/admin-api.md
- docs/en/latest/terminology/credential.md
- docs/zh/latest/admin-api.md
- docs/zh/latest/terminology/credential.md
> docs: fix code blocks in admin-api.md

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
fix ssl_protocols enum values
https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L825
> docs: fix ssl_protocols enum values

- docs/zh/latest/terminology/secret.md
> docs: fix hyperlink in secret.md

- docs/en/latest/plugins/opentelemetry.md
- docs/zh/latest/plugins/opentelemetry.md
Improve `opentelemetry` plugin docs and add Chinese doc.
> docs: improve `opentelemetry` plugin docs

- .asf.yaml
- README.md
> docs: add apisix as AI Gateway.

- docs/en/latest/plugins/proxy-cache.md
- docs/zh/latest/plugins/proxy-cache.md
Improve `proxy-cache` plugin docs.
> docs: improve `proxy-cache` plugin docs

- docs/en/latest/plugins/ai-proxy-multi.md
fix typo in ai-proxy-multi doc
> docs: fix typo in ai-proxy-multi doc

- docs/en/latest/deployment-modes.md
There was a stray comma in plugin_metadata example 😄
> docs: fix typo in deployment-modes.md

- apisix/plugins/ai-drivers/openai-base.lua
- apisix/plugins/ai-proxy/schema.lua
- docs/en/latest/plugins/ai-proxy-multi.md
- docs/en/latest/plugins/ai-proxy.md
- t/plugin/ai-proxy-multi.t
- t/plugin/ai-proxy.t
Support proxying embeddings API in the `ai-proxy` plugin.
> feat(ai-proxy): support embeddings API

- apisix/plugins/ai-aws-content-moderation.lua
> chore: remove unnecessary debug log

- NOTICE
> chore: hi 2025

- docs/en/latest/plugins/workflow.md
- docs/zh/latest/plugins/workflow.md
Improve `workflow` plugin docs.
> docs: improve `workflow` plugin docs

- docs/en/latest/plugins/skywalking-logger.md
- docs/zh/latest/plugins/skywalking-logger.md
Improve `skywalking-logger` plugin docs.
> docs: improve `skywalking-logger` plugin docs

- docs/en/latest/plugins/opentelemetry.md
- docs/zh/latest/plugins/opentelemetry.md
Fix the incorrect attribute structure in `opentelemetry` plugin metadata example from https://github.com/apache/apisix/pull/11940
> docs: fix the incorrect attribute structure in `opentelemetry` plugin metadata example

- docs/en/latest/plugins/request-id.md
- docs/zh/latest/plugins/request-id.md
Improve `request-id` plugin docs.
> docs: improve `request-id` plugin docs

- docs/en/latest/plugins/response-rewrite.md
- docs/zh/latest/plugins/response-rewrite.md
Improve `response-rewrite` plugin docs.
> docs: improve `response-rewrite` plugin docs

- docs/en/latest/plugins/skywalking.md
- docs/zh/latest/plugins/skywalking.md
Improve `skywalking` plugin docs.
> docs: improve `skywalking` plugin docs

- docs/en/latest/tutorials/add-multiple-api-versions.md
> docs: update add-multiple-api-versions.md

- docs/en/latest/stream-proxy.md
- docs/zh/latest/stream-proxy.md
Update stream proxy doc for `proxy_mode` and some sentences/formatting.
Fixes #12087
> docs: update stream proxy doc for `proxy_mode` and some formatting

- docs/en/latest/plugins/loki-logger.md
- docs/zh/latest/plugins/loki-logger.md
Improve `loki-logger` plugin docs.
> docs: improve `loki-logger` plugin docs

- docs/en/latest/plugins/elasticsearch-logger.md
- docs/zh/latest/plugins/elasticsearch-logger.md
Improve `elasticsearch-logger` plugin docs.
> docs: improve `elasticsearch-logger` plugin docs

- docs/en/latest/plugins/ai-rag.md
- docs/en/latest/plugins/ai-rate-limiting.md
Previous `ai-rate-limiting` plugin doc did not show usage with `ai-proxy-multi` before and other common use cases.
Previous `ai-rag` plugin doc did not explain example setup in details.
This PR updated both docs and enriched examples.
> docs: update `ai-rate-limiting` and `ai-rag` docs

- docs/en/latest/plugins/basic-auth.md
- docs/zh/latest/plugins/basic-auth.md
This PR improves `basic-auth` docs and includes the anonymous consumer update from https://github.com/apache/apisix/pull/11792
> docs: improve `basic-auth` docs and update docs for anonymous consumer

- docs/en/latest/plugins/key-auth.md
- docs/zh/latest/plugins/key-auth.md
This PR improves `key-auth` docs and includes the anonymous consumer update from https://github.com/apache/apisix/pull/11792
> docs: improve `key-auth` docs and update docs for anonymous consumer

- docs/en/latest/plugins/hmac-auth.md
- docs/zh/latest/plugins/hmac-auth.md
Improve `hmac-auth` plugin docs and includes the anonymous consumer update from https://github.com/apache/apisix/pull/11792
> docs: improve `hmac-auth` plugin docs and update docs for anonymous consumer 

- docs/en/latest/plugins/request-validation.md
- docs/zh/latest/plugins/request-validation.md
Improve `request-validation` plugin docs.
> docs: improve `request-validation` plugin docs

- README.md
1. Add link to the product page: AI Gateway
2. Add the MCP feature and link
Fixes #
> docs: update readme with APISIX AI Gateway product link and MCP feature

- .asf.yaml
Fix according to the records here: apache/infrastructure-asfyaml@6a03ced
Because I received the following email while developing `apisix-dashboard`(I've also repaired it there https://github.com/apache/apisix-dashboard/pull/3026):
```
An error occurred while processing the github feature in .asf.yaml:
while parsing a mapping
in "apisix-dashboard.git/.asf.yaml::github", line 20, column 1:
^ (line: 20)
unexpected key not in schema 'notifications'
in "apisix-dashboard.git/.asf.yaml::github", line 24, column 1:
pullrequests: notifications@ap ...
^ (line: 24)
---
With regards, ASF Infra.
For further information, please see the .asf.yaml documentation at:
https://github.com/apache/infrastructure-asfyaml/blob/main/README.md
```
Then I found that APISIX also has the same problem.
Fixes #
> fix: `.asf.yaml` format

- apisix/admin/standalone.lua
- t/admin/standalone.spec.ts
standalone credential_etcd_id format: `{username}/credentials/{credential_id}`
username: https://github.com/apache/apisix/blob/bdce47f34fb5fb9a257f00c5a63be83af492c6b8/apisix/schema_def.lua#L713
credential_id: 
https://github.com/apache/apisix/blob/bdce47f34fb5fb9a257f00c5a63be83af492c6b8/apisix/schema_def.lua#L728-L732
https://github.com/apache/apisix/blob/bdce47f34fb5fb9a257f00c5a63be83af492c6b8/apisix/schema_def.lua#L35-L39
Fixes #
> feat(standalone): allow more characters in credential_id for API-driven mode

- .github/workflows/code-lint.yml
- Makefile
- autodocs/generate.sh
- ci/common.sh
- ci/linux_apisix_current_luarocks_runner.sh
Fixes https://github.com/apache/apisix/pull/12277
> revert: temporary fix regarding luarocks

- .github/workflows/push-dev-image-on-commit.yml
- docker/debian-dev/Dockerfile
Build the APISIX dashboard and put it into the dev image.
> feat: add apisix dashboard to dev image

- apisix/plugins/request-validation.lua
- t/plugin/request-validation.t
> fix(request-validation): support Content-Type header with charset for urlencoded data

- docs/en/latest/FAQ.md
- docs/en/latest/getting-started/README.md
- docs/zh/latest/FAQ.md
- docs/zh/latest/getting-started/README.md
In the latest version 3.13.0, we provide a dashboard ui tool out of the box, but it is not mentioned in the documentation. Many users are asking how to use this tool.
- https://github.com/apache/apisix/issues/12311
- https://github.com/apache/apisix/issues/12397
- https://github.com/apache/apisix-dashboard/issues/2981#issuecomment-3050941377
This PR adds some simple tips to the documentation
Fixes #
> docs: add dashboard ui tips

- docs/en/latest/plugins/jwt-auth.md
- docs/zh/latest/plugins/jwt-auth.md
This PR updates JWT relevant docs and addresses the following issues:
* HS256 key not long enough, leading to errors.
* JWT.io front-end has changed. Update instructions.
* Set environment variable for APISIX in Docker.
> docs: update `jwt-auth` docs

- t/package.json
- t/pnpm-lock.yaml
Solve https://github.com/apache/apisix/security/dependabot/160.
Similar to https://github.com/apache/apisix-dashboard/pull/3154.
Fixes #
> chore: upgrade deps to solve vulnerability alerts

- docs/en/latest/plugins/attach-consumer-label.md
- docs/en/latest/plugins/chaitin-waf.md
- docs/en/latest/plugins/jwt-auth.md
- docs/en/latest/plugins/proxy-rewrite.md
- docs/zh/latest/plugins/attach-consumer-label.md
- docs/zh/latest/plugins/chaitin-waf.md
- docs/zh/latest/plugins/jwt-auth.md
- docs/zh/latest/plugins/proxy-rewrite.md
This PR improve `chaitin-waf` plugin docs and remove unintended highlights (that are not rendered) introduced in previous plugin doc improvement PRs.
> docs: Improve `chaitin-waf` plugin docs and remove unintended highlights

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
Add missing documentation for the plugin metadata list API in the admin API docs.
> docs: update admin api documentation for plugin metadata list endpoint
