bin/apisix, conf/nginx.conf, lua/apisix.lua, t/APISix.pm, t/sanity.t
Performance improvement 5%.
old version:
```shell
[rain@instance-2 ~]$ wrk -d 30 http://127.0.0.2:9080/hello
Running 30s test @ http://127.0.0.2:9080/hello
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   578.93us  172.11us  10.87ms   85.12%
Req/Sec     8.52k   639.31     9.99k    74.09%
510290 requests in 30.10s, 637.49MB read
Requests/sec:  16953.25
Transfer/sec:     21.18MB
[rain@instance-2 ~]$ wrk -d 30 http://127.0.0.2:9080/hello
Running 30s test @ http://127.0.0.2:9080/hello
2 threads and 10 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   600.37us  196.83us  19.64ms   87.48%
Req/Sec     8.21k   732.85     9.67k    71.00%
490182 requests in 30.00s, 612.37MB read
Requests/sec:  16338.44
Transfer/sec:     20.41MB
```
new …
=> optimize: merged phase `rewrite` and `access`, make it faster.

bin/apisix, conf/nginx.conf
change: checked the current directory if it's a apisix home folder,
if not then use `/usr/local/openresty`.
change: changed the core file folder to `/tmp/apisix_cores`.
Fix #144.
=> bugfix: maybe missing `with-http_stub_status_module` module in openresty

Makefile, utils/update_nginx_conf_dev.sh
When run `make dev` on a new host without lua 5.x environment,  the output isn't very friendly，the `lua_version` variable is empty but `utils/update_nginx_conf_dev.sh` continue execute the sed substitution，which is meaningless.
fix spelling mistake in `Makefile`: `srouce code` -> `source code`
=> bugfix: failed early when lua isn't installed on `make dev`

bin/apisix
Hi there,
The curl default connect timeout is 120s or more, we should use the timeout in the configuration.
Please review it. thx.
=> Add timeout to init_etcd

COPYRIGHT, conf/config.yaml, doc/plugins/jwt-auth-cn.md, lua/apisix/admin/consumers.lua, lua/apisix/admin/init.lua, lua/apisix/core/id.lua, lua/apisix/plugins/jwt-auth.lua, lua/apisix/plugins/key-auth.lua, rockspec/apisix-dev-0.rockspec, t/admin/plugins.t, t/plugin/jwt-auth.t
=>  feature: supported JWT plugin and added test cases.

conf/config.yaml, doc/architecture-design-cn.md, lua/apisix/core/config_etcd.lua, lua/apisix/core/config_local.lua, lua/apisix/plugin.lua, lua/apisix/plugins/example-plugin.lua, lua/apisix/plugins/heartbeat.lua, t/debug-mode.t, t/node/ssl.t, t/plugin/example.t
print the plugin list which sort by priority.
=> feature: supported debug mode.

conf/config.yaml, lua/apisix.lua, lua/apisix/http/route.lua, t/node/match-host-uri.t
fix https://github.com/iresty/apisix/issues/269
=> feature: supported to match route by host + uri.

lua/apisix/admin/init.lua, lua/apisix/admin/routes.lua, t/admin/routes.t
fix: https://github.com/iresty/apisix/issues/92
todo items:
=> feature: supported `PATCH` method for admin `routes` API.

rockspec/apisix-dev-1.0-0.rockspec
=> bump(deps): update `lua-resty-healthcheck-iresty` to 1.0.1 and removed

doc/plugins/limit-conn-cn.md, doc/plugins/limit-conn.md, doc/plugins/limit-count-cn.md, doc/plugins/limit-count.md, doc/plugins/limit-req-cn.md, doc/plugins/limit-req.md, lua/apisix/plugins/limit-conn.lua, lua/apisix/plugins/limit-count.lua, lua/apisix/plugins/limit-req.lua, t/plugin/limit-conn.t
fix https://github.com/iresty/apisix/issues/228
=> feature: support more key for limit-rate, limit-count, limit-conn

doc/architecture-design-cn.md, lua/apisix.lua, lua/apisix/admin/proto.lua, lua/apisix/admin/routes.lua, lua/apisix/core/ctx.lua, lua/apisix/core/schema.lua, lua/apisix/plugins/grpc-transcode/util.lua, t/core/ctx.t, t/lib/server.lua, t/node/upstream-more-options.t
=> feature: supported to set more upstream options.

lua/apisix/core/yaml.lua
and needs to be compatible at the same time.
=> bugfix: Windows uses `CRLF` by default, but Linux uses `LF` by default

lua/apisix/plugins/example-plugin.lua
change log content as below:
core.log.warn("plugin balancer phase, conf: ", core.json.encode(conf))
=> bugfix:issue #94, typo in plugin

README.md
Code coverage is inaccurate and is temporarily blocked.
=> doc: removed luacov status.

doc/architecture-design-cn.md, doc/plugins/jwt-auth-cn.md, doc/plugins/key-auth-cn.md, doc/plugins/key-auth.md, lua/apisix.lua, lua/apisix/admin/consumers.lua, lua/apisix/consumer.lua, lua/apisix/core.lua, lua/apisix/plugin.lua, lua/apisix/plugins/jwt-auth.lua, lua/apisix/plugins/key-auth.lua, lua/apisix/plugins/limit-count.lua, lua/apisix/schema_def.lua, t/admin/consumers.t, t/node/consumer-plugin.t, t/node/global-rule.t, t/node/merge-route.t, t/plugin/jwt-auth.t, t/plugin/key-auth.t
=> feature: support consumer bind plugins.

lua/apisix/http/router/r3_host_uri.lua, lua/apisix/http/router/r3_uri.lua
Applying/recycling tables in lua is time consuming, so use temporary tables as little as possible. Obtaining the uri parameter operation is relatively low frequency, and the user can conveniently intercept the uri parameter from the plugin. It is not necessary to apply a temporary table every time for this low-frequency operation, and the parameter acquisition is currently closed using a comment. It can be turned on manually if needed, but it will affect performance.
在 lua 中申请/回收 table 是比较耗时的，所以要尽量少的使用临时 table。获取uri参数操作比较低频，且用户可以方便的从插件中截取uri参数。不必要为了这个低频的操作每次申请临时table，当前使用注释的方式关闭参数获取。如果有需要的话可以手动开启，但是会影响性能。
=> change:closing route module get uri parameter variable `api_ctx.matched_params`

bin/apisix, conf/config.yaml, conf/nginx.conf
change(CLI): exported new argument of `error_log.level`.
change(CLI): enabled dashboard when use an independent admin port.
=> change(dashboard): use `/apisix/dashboard` to login dashboard.

conf/config.yaml, doc/plugins/proxy-rewrite-cn.md, doc/plugins/proxy-rewrite.md, lua/apisix/plugins/proxy-rewrite.lua, t/APISIX.pm, t/admin/plugins.t, t/debug-mode.t, t/lib/server.lua, t/plugin/proxy-rewrite.t
This plugin is used to separate `uri`, `host`, `scheme` and `enable_websocket` work in the `upstream` module. Through this plugin, the simplicity and independence of the `upstream` module can be maintained.
此插件用于分离`upstream`模块中的`uri`、`host`、`scheme`和`enable_websocket`功能。让`upstream`模块可以保持简洁和独立性。
Fix #569
=> feature(plugin): rewrite upstream info with plugin `proxy-rewrite`

bin/apisix, conf/config.yaml, conf/nginx.conf, lua/apisix.lua, lua/apisix/http/router/r3_sni.lua, lua/apisix/http/router/radixtree_sni.lua, t/plugin/proxy-rewrite.t, t/router/r3-sni.t, t/router/radixtree-sni.t
fix: https://github.com/iresty/apisix/issues/595
=> feature: enabled HTTP2 and supported to set `ssl_protocols`.

lua/apisix/plugins/zipkin.lua
fixed:[#713 ](https://github.com/iresty/apisix/pull/713)
=> bugfix:zipkin plugin not set tracing data to request header.

lua/apisix/admin/routes.lua
Fix #delete admin routes.lua host and hosts variable duplicate check code
=> delete admin routes.lua host and hosts variable duplicate check code

lua/apisix/plugins/serverless.lua, t/admin/schema.t, t/config-center-yaml/route-upstream.t
Fix https://github.com/apache/incubator-apisix/issues/785
=> bugfix: exported schema for plugin `serverless`.

CHANGELOG_CN.md, FAQ.md, FAQ_CN.md, bin/apisix
a method of luarocks usage to avoid slow or timeout issue
=> update FAQ, add one about slow luarocks

bin/apisix
show more friendly error message to let users know what happened,and where the error come from.
* bin\apisix
Fix https://github.com/apache/incubator-apisix/issues/823
=> fix: show more friendly error log when configuration field missed

lua/apisix/consumer.lua, t/plugin/key-auth.t
fix the logical error in `apisix/consumer.lua` and improve the test case.
* updated apisix/consumer.lua:40-46
* updated the test case [TEST 7: valid consumer] - t/plugin/key-auth.t 
The improved test case run in branch master.
Run in this branch.
=> bugfix: key-auth plugin cannot run accurately in the case of multiple consumers(branch: master)

lua/apisix/core/utils.lua, rockspec/apisix-master-0.rockspec, t/APISIX.pm, t/core/utils.t, t/node/healthcheck-ipv6.t, t/node/upstream-ipv6.t
The OpenResty APIs require the IPv6 literal wrapped inside a square brackets.
Also add tests for IPv6 upstream and update lua-resty-ipmatcher to 0.3.
Fix #816.
=> change: don't strip square brackets from the IPv6

Makefile, lua/apisix/http/router/radixtree_host_uri.lua, lua/apisix/schema_def.lua, t/router/radixtree-host-uri2.t
=> bugfix(radixtree_host_uri): match priority, host > uri.

.travis/linux_openresty_runner.sh, .travis/linux_tengine_runner.sh, Makefile, doc/dev-manual-cn.md, doc/dev-manual.md
=> Split check target into lint & license-check targets in Makefile.

bin/apisix, conf/nginx.conf, utils/install-apisix.sh
Resolve issue #882 and simplify the nginx.conf
Also fix `utils/install-apisix.sh` as on `Debian/Ubuntu` the /bin/sh is a symbolic refer `/bin/dash` rather than `/bin/bash`, which not support `==` equal comparation.
```shell
$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Oct  8 23:49 /bin/sh -> dash
```
* ...
Fix #882 
1. The dashboard resources doesn't need proxy pass to upstream, remove the redundant `proxy_set_header`.
2. The direcctive `index index.html` is [the default setting by nginx](https://nginx.org/en/docs/http/ngx_http_index_module.html#index), …
=> Resolve #882 and simplify conf

bin/apisix, conf/config.yaml
Currently, there is no way to specify the number of worker_process for the dev mode. The PR sets the value of `1` for dev mode and `auto` for prod mode configs.
Fix #918
=> Adding dev mode flag in config yaml to set the nginx worker_process

doc/README.md, doc/getting-started.md
The following PR contains a getting started guide to quickly onboard new users to APISIX
The document contains the following steps:
1. Setting up APISIX
2. General Principles
3. Setup a route & upstream
4. Protect the API with an API key
Fix for: #930
=> Adding getting started guide

t/plugin/key-auth.t
=> Adding unit test for key auth plugin with valid api key

README.md, README_CN.md
Fix error description for installing Dashboard
=> Update README.md about installing Dashboard

bin/apisix, conf/config.yaml, lua/apisix.lua
…ORS.
fix bin/apisix, let the API /apisix/admin support the CORS
=> let the path /apisix/admin support the CORS

lua/apisix/schema_def.lua, rockspec/apisix-master-0.rockspec, t/admin/health-check.t, t/admin/routes.t, t/admin/services.t, t/admin/upstream.t, t/plugin/ip-restriction.t
Fix https://github.com/apache/incubator-apisix/issues/1010 .
Fix https://github.com/apache/incubator-apisix/issues/1009 .
=> optimize: updated the error message after updated new `jsonschema`.

lua/apisix/plugins/jwt-auth.lua, t/plugin/jwt-auth.t
Jwt authentication plugin compatible with Bearer prefix
1.  t/plugin/jwt-auth.t
2.  plugins/jwt-auth.lua 
Fix https://github.com/apache/incubator-apisix/issues/1026
=> Jwt authentication plugin compatible with Bearer prefix

bin/apisix
add tips in the generated nginx.conf
* Edit file : bin/apisix  to declare that the nginx.conf  is a read-only file and do not try to modify it.
=> Comment: add tips in the generated nginx.conf (#1003)

README.md, README_CN.md
fix typo inf Readme.md
change  `Apache Foundation` into `Apache Software Foundation`
I think the `Apache Software Foundation` is the offical name
* README.md
=> doc: fix typo in 'The advantages of Apache APISIX'

conf/config.yaml, lua/apisix/plugins/log-util.lua, lua/apisix/plugins/udp-logger.lua, t/admin/plugins.t, t/debug/debug-mode.t, t/plugin/udp-logger.t
The UDP logger sends the logs to a UDP server. 
Fix for #1069
=> Adding UDP logger plugin

doc/getting-started.md
=> doc: getting-started.md check

Contributing.md
The documents are not consistent in style. I have added some minimal best practices when contributing to the document. Please do have a look.
=> Adding contribution guidelines for the documentation

lua/apisix/core/log.lua
1. implement the debug method with the generic logic, so you don't need
to go into the method if you don't need it.
2. avoid computing the same result among different log levels
=> chore: improve the core.log module

bin/apisix, conf/config.yaml
If we can configure the number of connections, we should also configure the number of files, since n_files need to be larger than n_conns.
=> feature: make the number of file is as configurable as the connections.

README.md, README_CN.md, bin/apisix, conf/config.yaml
1. Support Proxy Protocol
2. Add X-Forwarded-* headers to upstream
- X-Forwarded-For
- X-Forwarded-Proto
- X-Forwarded-Host
- X-Forwarded-Port
Fix #1106
=> Feature: Add support for PROXY Protocol.

bin/apisix, conf/config.yaml, lua/apisix.lua, lua/apisix/core/lrucache.lua, lua/apisix/core/utils.lua, t/core/lrucache.t, t/plugin/fault-injection.t
In the upstream node,  allow using the domain name as the address. 
But in the balancer phase, we can not to use the domain name as the address directly. The domain name must be parsed to an IP address vie DNS query before it can be used, we can do this in the access or rewrite phase.
The original DNS cache was wrong:
1. use DNS's default TTL as cache TTL.
2. After the cache items expire, it must be re-parsed to obtain the latest address.
=> bugfix: updated the dns parse result by TTL.

.gitignore, lua/apisix/debug.lua
* gitignore: ignore hidden file.
=> opt: print warning error message if the yaml route file is invalid.

doc/batch-processor.md, lua/apisix/plugins/batch-processor.lua, t/plugin/batch-processor-refac.t, t/plugin/batch-processor.t
=> Batch processor implementation to aggregate logs in batch 

.travis.yml, lua/apisix/plugins/limit-count.lua, lua/apisix/plugins/limit-count/limit-count-redis.lua, t/plugin/limit-count-redis.t
Support password auth for plugin limit-count-redis.
* replace .travis.yml redis-server service with: docker redis:3.0-alpine
* add redis_password for limit-count schema
Fix #971
=> feature: Support password auth for plugin limit-count-redis

lua/apisix/plugins/grpc-transcode.lua, lua/apisix/plugins/grpc-transcode/request.lua, lua/apisix/plugins/grpc-transcode/response.lua, t/plugin/grpc-transcode.t
plugin `grpc-transcode` supports grpc deadline
=> feat:  plugin `grpc-transcode` supports grpc deadline

doc/plugins/jwt-auth-cn.md, doc/plugins/jwt-auth.md
fix ip addr typo 127.0.0.2
* replace '127.0.0.2' with '127.0.0.1' in jwt plugin doc
Fix #1107
=> doc: fix typo in jwt plugin doc

doc/plugins/limit-count-cn.md, doc/plugins/limit-count.md
add description of redis_password in limit-count doc
Fix #1171
=> doc: add description of redis_password in limit-count doc

bin/apisix
=> change: disables logging of errors about not found files into error_log for admin api.

lua/apisix/admin/global_rules.lua, t/admin/global-rules.t
apisix admin api will return error when access "/apisix/admin/global_rules",
Fix: return all resource when access root.
BTW: i dont see any test case about 'list' action of admin api except 'get', so i did't add external cases.
=> fix: global ruls admin api should list resource without id

doc/getting-started.md, doc/plugin-develop.md
Fixes the question #948
- Update the getting started guide
- Punctuation fixes with additional space.
=> Update doc on how add a prefix to the route and fix punctuation issues in plugin doc

bin/apisix
Duplicate of #1201 and fix for #1196.
Based on the discussion on #1201, the PR only prints the warning message to the user and does not add the root configs to the nginx config
=> Adding warning message when running APISIX in root path

lua/apisix/plugins/basic-auth.lua, rockspec/apisix-master-0.rockspec, t/admin/global-rules.t, t/plugin/basic-auth.t
=> bugfix: the plugin basic-auth needs required field

doc/plugins/limit-count-cn.md, lua/apisix/plugins/heartbeat.lua, lua/apisix/plugins/node-status.lua, t/admin/global-rules.t, t/admin/plugins.t
=> bugfix: plugin node-status and heartbeat don't have schema.

conf/config.yaml, doc/README.md, doc/plugins/tcp-logger.md, lua/apisix/plugins/tcp-logger.lua, t/APISIX.pm, t/admin/plugins.t, t/debug/debug-mode.t, t/plugin/tcp-logger.t
Adding support to tcp logger plugin.
Started working on tcp logger plugin
Referring these 2 repos :- https://github.com/openresty/lua-nginx-module#udpsocksetpeername
https://github.com/fluent/fluent-logger-node
I am more familiar with node.js so I thought it would help me. to understand the flow
Fix #1220
=> Adding tcp logger.

doc/plugins/oauth.md, lua/apisix/plugins/openid-connect.lua
Fix #1242
This PR adds support to verify tokens via a public key. This will reduce additional network calls sent to the Identity Server.
=> Adding support to public key based introspection for OAuth plugin

Makefile
grep doesn't support lazy match by default. To support it, `-P` should
be used instead of `-E`, see:
https://stackoverflow.com/a/5774431
However, we can achieve the same thing without lazy match.
Because OpenResty's not vanilla Nginx, there will be --option after the
executable.
=> bugfix: correct LUAJIT_DIR detection

lua/apisix/http/router/radixtree_host_uri.lua
Fix issue of local variable 'routes' duplicate in create_radixtree_router function.
SUMMARY_HERE
* ...
Fix #XXX
=> bugfix: Fix issue of local variable 'routes' duplicate in create_radixtree_router function.

bin/apisix, conf/config.yaml
Add multiple etcd address support
Fix #1231
=> Add multiple etcd support.

lua/apisix/balancer.lua, t/node/upstream-domain.t
Fix https://github.com/apache/incubator-apisix/issues/1291
=> bugfix: check the count of upstream valid node.

lua/apisix/plugins/limit-count/limit-count-redis.lua
In the old operating mechanism, APISIX may set the `redis` key without the TTL flag. In this case, APISIX will not be able to set any new values.
BTW, it's hard to write a test case for this case :(
we can do this later.
=> bug: set new value if the redis flag is expired.

bin/apisix, lua/apisix/plugins/proxy-cache.lua
1. unit all the default cache time to 10s.
2. remove repeated `if proxy_cache` check.
3. improve `generate_complex_value`'s performance.
4. better indent.
=> chore: improve plugins/proxy-cache

doc/plugins/grpc-transcoding-cn.md
Summary
Full changelog
fix style of grpc-transcoding-cn
Fix #1273
=> fix style of grpc-transcoding-cn

doc/plugins/proxy-rewrite-cn.md, doc/plugins/proxy-rewrite.md, lua/apisix/plugins/proxy-rewrite.lua, t/plugin/proxy-rewrite.t
remove websocket related code in proxy-rewrite plugin
since there is enable controller in the upstream module, there is no need to have websocket enable in this plugin.
And we need to mention this in the next release note
**Notice:**
the user need to transfer their websocket configuration from proxy-rewrite into upstream, if they enabled websocket proxy-rewrite plugin.
*   doc/plugins/proxy-rewrite-cn.md
*   doc/plugins/proxy-rewrite.md
*   lua/apisix/plugins/proxy-rewrite.lua
*   t/plugin/proxy-rewrite.t
Fix https://github.com/apache/incubator-apisix/issues/1331
=> deletion: drop webdocket enable control in proxy-rewrite plugin

.travis/linux_apisix_current_luarocks_runner.sh, .travis/linux_apisix_master_luarocks_runner.sh, Makefile, utils/check-lua-code-style.sh
If we install the latest APISIX by luarocks, we'll get the error log like this:
https://travis-ci.org/github/apache/incubator-apisix/jobs/667148749#L1882
This bug is related to the commit: https://github.com/apache/incubator-apisix/commit/429f0165c202035b18b4437a84c6edc9007fc440#diff-cf73ae5e62361600170ba3c1ffab549e
```
2020/03/26 09:34:48 [error] 10333#10333: *1 [lua] plugin.lua:66: load_plugin(): failed to load plugin [kafka-logger] err: ...share/lua/5.1/apisix/lua/apisix/plugins/kafka-logger.lua:18: module 'apisix.utils.log-util' not found:
no field package.preload['apisix.utils.log-util']
no file '/usr/local/apisix//deps/share/lua/5.1/apisix/utils/log-util.lua'
no file '/usr/share/lua/5.1/apisix/lua/apisix/utils/log-util.lua'
no file …
```
=> bugfix: installed lua file in folder `lua/apisix/utils` .

README.md, README_CN.md, conf/config.yaml, doc/README.md, doc/README_CN.md, doc/plugins/cors-cn.md, doc/plugins/cors.md, lua/apisix/plugins/cors.lua, t/admin/plugins.t, t/debug/debug-mode.t, t/plugin/cors.t
cors plugin
- support base cors header
- support multiple origin
- support forcefully match origin and methods with wildcard
=> features: append cors plugin

t/plugin/openid-connect.t
Resolves #1276 
This PR tests the public key based token introspection for OAuth plugin.
The private key used to sign the token present in the test case:
```
-----BEGIN RSA PRIVATE KEY-----
MIIBOgIBAAJBANW16kX5SMrMa2t7F2R1w6Bk/qpjS4QQhnrbED3Dpsl9JXAx90MY
sIWp51hBxJSE/EPVK8WF/sjHK1xQbEuDfEECAwEAAQJBALyYVE06B5YIPgfU0bjz
ABeM6Pyeseay2qqSpcuL3KVTsZKhFfB49KdhxOGo45SKboVoM1xqOHVUopCFkEeQ
Le0CIQDtrTeGb/388cSM/0YEZvIpE05tecOpAIcI/a6xkluPVwIhAOYvtIF4RDhs
4mGzzPHtvridP5p/PWXkTxiNHfl3esonAiAhb/ET1MWixFCmlXNAQ0tmQ/UQqcTB
DfXxad8d1D1VWQIgAlmIUS4GHEFYSkEInYucv8uzI4Oa/9hFym1eWfaTRU8CIChU
gZnTz8ErlpRAG9TXnsJsvYA7Q3jzaYCmsYxQc2gW
-----END RSA PRIVATE KEY-----
```
The token used in the test case is valid for 10years.
=> Adding test case for public key based introspection

lua/apisix/utils/batch-processor.lua, t/utils/batch-processor.t
- If the batch processor max_retry_count is set to 0, then it will not print the error log when it fails to send the data.
- If the batch processor max_retry_count is set to 1, then it does not reschedule the function execution if sending the logs fails.
=> Batch Processor: Fix for rescheduling execution for max_retry_count is 0 and 1

.travis/linux_tengine_runner.sh
feature: merge upstream tengine (2.3.2 < version < 2.3.3) patches
* modules/mod_dubbo/utils/utils.cc
* modules/ngx_http_upstream_keepalive_module/ngx_http_upstream_keepalive_module.c
* src/http/ngx_http_core_module.c
=> feature: merge upstream tengine (2.3.2 < version < 2.3.3) patches

bin/apisix, conf/config.yaml
Allows you to add custom shared dict through configuration
* config.yaml : lua_shared_dicts
* apisix
=> Allow add custom shared dict

doc/plugins/wolf-rbac-cn.md, doc/plugins/wolf-rbac.md, lua/apisix/plugins/wolf-rbac.lua, t/lib/server.lua, t/plugin/wolf-rbac.t
* Add api `/apisix/plugin/wolf-rbac/change_pwd` used to change password
* Add api `/apisix/plugin/wolf-rbac/user_info` used to get user info
* Add attribute `header_prefix` to customize the prefix of the request/response header added by `wolf-rbac`
=> Wolf-Rbac: Add new api `change_pwd` and `user_info`.

.travis/linux_tengine_runner.sh
remove misc `--add-dynamic-module` for tengine since we do not set `load_module` in nginx.conf
* .travis/linux_tengine_runner.sh
=> bugfix: remove misc `--add-dynamic-module` for tengine branch ci test cases

apisix/init.lua
=> support to run `header_filter` and `body_filter` phase for global rules.

conf/config.yaml
update to use the local DNS resolver by default， update the file conf/conf.yaml.
close https://github.com/apache/incubator-apisix/issues/1378
=> update to use the local DNS resolver by default

kubernetes/README.md, kubernetes/apisix-gw-config-cm.yaml, kubernetes/deployment.yaml, kubernetes/service-aliyun-slb.yaml, kubernetes/service.yaml
➜  kubernetes git:(k8s) tree .
.
├── README.md
├── apisix-gw-config-cm.yaml
├── deployment.yaml
├── service-aliyun-slb.yaml
└── service.yaml
* add example .yaml resource files which support to run `Apache APISIX` on kubernetes
=> feature: add example .yaml resource files which support to run Apache APISIX on kubernetes

apisix/plugins/zipkin.lua, apisix/plugins/zipkin/reporter.lua, doc/plugins/zipkin-cn.md, doc/plugins/zipkin.md, t/lib/server.lua, t/plugin/zipkin.t
allow zipkin to set servie name and local ip sddress so that we can track it in APM system
* apisix/plugins/zipkin.lua
* doc/plugins/zipkin-cn.md
* doc/plugins/zipkin.md
* apisix/plugins/zipkin/reporter.lua
* t/lib/server.lua
* t/plugin/zipkin.t
=> enhance: plugin Zipkin add service name and report local server IP

.travis/linux_apisix_master_luarocks_runner.sh
we need to catch the error case.
=> travis: When the error message is found, set the exit code to 1.

CHANGELOG.md, doc/benchmark.md, doc/how-to-build-cn.md, doc/how-to-build.md
fix doc style of how-to-build-cn.md and how-to-build.md
Full changelog
fix doc style of how-to-build-cn.md and how-to-build.md
related issu: #1273
=> doc style fix:  fix doc style of how-to-build-cn.md and how-to-build.md

.travis.yml, .travis/linux_apisix_current_luarocks_runner.sh, .travis/linux_apisix_master_luarocks_runner.sh, .travis/linux_openresty_runner.sh, .travis/linux_tengine_runner.sh, Makefile, apisix/plugins/proxy-rewrite.lua, rockspec/apisix-master-0.rockspec, t/APISIX.pm, t/plugin/proxy-rewrite.t, utils/install-apisix.sh
If the Luarocks version is lower than "v2.4.3", it does not support the "--only-deps" parameter. Even if we set the "--only-deps" parameter, no error message will be given during runtime.
We only wanted to install the dependencies in the `deps` directory, but the APISIX was also installed so that the test case might load the wrong version of the source code.
=> bugfix(CI): avoid to install APISIX to `deps` folder, that is a bug for older luarocks

.travis/linux_openresty_runner.sh, .travis/linux_tengine_runner.sh
fix travis: https://travis-ci.org/github/apache/incubator-apisix/jobs/677082965#L524
Install the `luacov` when create `deps` folder.
Then we can avoid installing "luacov" after copying "deps" from the "build-cache" folder to the current folder.
=> bugfix(Travis): install the `luacov` when create `deps` folder

apisix/core/lrucache.lua, apisix/core/schema.lua, bin/apisix, t/APISIX.pm, t/core/lrucache.t, t/core/schema.t
one common use case for this library is avoid the so-called "dog-pile effect",     
that is, to limit concurrent backend queries for the same key when a cache miss happens.
=> bugfix(lrucache): when creating cached objects, use resty-lock to avoid repeated creation.

apisix/admin/upstreams.lua, apisix/schema_def.lua, doc/admin-api-cn.md, doc/admin-api.md, doc/architecture-design-cn.md, doc/architecture-design.md, t/admin/routes.t, t/admin/services.t, t/admin/upstream.t, t/node/upstream.t
support saving k8s deployment info to upstream, then controller can watch k8s and update the upstream's nodes info.
=> feat: support saving k8s deployment info to upstream

doc/plugins/serverless-cn.md, doc/plugins/serverless.md
fix some doc styles for serverless-cn.md and serverless.md
related issue: #1273
=> fix the doc style for serverless*.md

apisix/core/config_etcd.lua, t/node/healthcheck.t
=> bugfix: init `clean_handlers` when add new item from etcd.

apisix/core/config_util.lua, apisix/init.lua, t/node/global-rule.t
=> fix: skip tombstone mark when iterating the global values

.luacheckrc, apisix/utils/batch-processor.lua
use a shorter name in `batch-processor.lua`
=> lint(luacheck): limit the maximum length of Lua code to 100.

apisix/plugins/syslog.lua, conf/config.yaml, doc/plugins/syslog-cn.md, doc/plugins/syslog.md, rockspec/apisix-master-0.rockspec, t/admin/plugins.t, t/debug/debug-mode.t, t/plugin/syslog.t
=> Add sys logger.

apisix/plugins/cors.lua, t/plugin/cors.t
1. using rewrite phase to prevent be run after auth plugins. as mentioned #1528 
2. add lru cache for multiple origin case, it helps performance.
=> refactor: using rewrite phase and add lru cache for multiple origin 

apisix/plugins/kafka-logger.lua
=> Adding function to remove stale objects from kafka logger

apisix/plugins/syslog.lua
Add buffer support sys log.
Fix #1500
=> Buffer sys log requests.

apisix/plugins/grpc-transcode/util.lua, t/plugin/grpc-transcode.t
=> plugin grpc-transcode bugfix: got 500 error when using post method

apisix/schema_def.lua, t/admin/schema.t, t/admin/ssl.t, t/lib/test_admin.lua
=> feature: support new field `exptime` for SSL object.

doc/plugins/http-logger-cn.md
=> Add http logger Chinese docs

README_CN.md, doc/how-to-build-cn.md, doc/install-dependencies-cn.md
=> doc:add chinese version for install doc

bin/apisix
=> bugfix: raise error when none of the configured etcd can be connected

.asf.yaml
`asf.yaml` is used to control the description and tags of the project
=> doc: add asf.yaml.

doc/health-check.md, doc/plugins/response-rewrite-cn.md, doc/plugins/response-rewrite.md
fix the doc style for response-rewrite* and health-check.md
related issue: #1273
=> fix some doc style for response-rewrite* and health-check.md

rockspec/apisix-master-0.rockspec
The results are as follows when make deps,
-----
[root@localhost apisix]# make deps
luarocks install --lua-dir=/usr/servers/luajit rockspec/apisix-master-0.rockspec --tree=deps --only-deps --local
Missing dependencies for apisix master-0:
skywalking-nginx-lua-plugin 1.0-0 (not installed)
apisix master-0 depends on skywalking-nginx-lua-plugin 1.0-0 (not installed)
Installing https://luarocks.org/skywalking-nginx-lua-plugin-1.0.rockspec
Error: Failed installing dependency: https://luarocks.org/skywalking-nginx-lua-plugin-1.0.rockspec - /tmp/luarocks_luarocks-rockspec-skywalking-nginx-lua-plugin-1.0-Eo8MgK/skywalking-nginx-lua-plugin-1.0.rockspec: Type mismatch on field version: invalid value '1.0' does not match '[%w.]+-[%d]+' (using rockspec format 1.0)
-------
By changing  the version of …
=> bugfix: change the version of skywalking to 1.0-0 

apisix/plugins/prometheus/exporter.lua
correct the value of overhead in plugins/prometheus/exporter.lua
Fix #1615
=> [bugfix] correct the overhead to fix the bug for #1615

apisix/plugins/prometheus/exporter.lua, t/lib/server.lua, t/plugin/prometheus.t
correct the value of overhead in  plugins/prometheus/exporter.lua
prometheus.t  test 26 to 29
1st  add a mock service /hello4 to sleep 1s， 
=== TEST 26: add a service 3 to distinguish other services
=== TEST 27: add a route 4 to redirect /hello4
=== TEST 28: request from client to /hello4 ( all hit, the hello4 sleep 1s)
=== TEST 29: fetch the prometheus metric data with `overhead`(the overhead < 1s)
With the previous error, the value of overhead was above 1s,  the overhead's value corrected  is less than 1s by fix the error.
Fix #1625
=> [add test case]add testcase for #1625 to test the filed of overhead

benchmark/run.sh, bin/apisix
fix osx compatibility when run `benchmark/run.sh` and `apisix reload`
* change benchmark script sed from set workers `worker_processes \d+` to `worker_processes .* ` to fit `worker_processes auto`
* change sed command to fit OSX in `benchmark/run.sh`
* fix `apisix reload` on OSX.
Fix #1649
=> compatibility of benchmark script and apisix reload command on OSX

bin/apisix
1. buffer=4096 is better for Writes of more than PIPE_BUF bytes may be nonatomic
2. flush=1. Since the log buffer is lowered, the flush time should also be lowered.
Fix https://github.com/apache/incubator-apisix/issues/1567
=> [log] Optimize the buffer size and flush time

doc/admin-api-cn.md, doc/admin-api.md, doc/architecture-design-cn.md, doc/architecture-design.md, doc/plugins/http-logger-cn.md, doc/plugins/http-logger.md, doc/plugins/ip-restriction-cn.md, doc/plugins/ip-restriction.md, doc/plugins/kafka-logger-cn.md, doc/plugins/kafka-logger.md, doc/plugins/proxy-cache-cn.md, doc/plugins/proxy-cache.md, doc/plugins/proxy-mirror-cn.md, doc/plugins/proxy-mirror.md, doc/plugins/skywalking-cn.md, doc/plugins/skywalking.md, doc/plugins/syslog-cn.md, doc/plugins/syslog.md, doc/plugins/tcp-logger-cn.md, doc/plugins/tcp-logger.md, doc/plugins/udp-logger-cn.md, doc/plugins/udp-logger.md, doc/plugins/zipkin-cn.md, doc/plugins/zipkin.md
Supplement the 'X-API-KEY' parameter for each interface that operates admin.
SUMMARY_HERE
* ...
Fix #XXX
=> [doc]Supplement the 'X-API-KEY' parameter for each interface that operates admin.

apisix/balancer.lua, apisix/schema_def.lua, doc/admin-api-cn.md, doc/admin-api.md, t/admin/routes.t, t/admin/services.t, t/admin/upstream.t
add `name` field for route, service, upstream to name each instance, and it is  unique, can't be duplicate.
=> feat: resource name

.travis/apisix_cli_test.sh, bin/apisix
check whether  the user has enabled etcd v2 protocol.
update the apisix_cli_test.sh to provide a friendly error message when  etvd v2 not enabled.
Fix #1523
=> [bugfix(CLI)]: check whether  the user has enabled etcd v2 protocol.

Makefile
重复执行 make run 会启动多个master进程，而 make stop 只能停止一个。
原理：make stop 读取nginx.pid 获取master process id，make stop 后删除 nginx.pid。其他被启动的实例由于缺失nginx.pid文件，读取不到master process id，make stop 失败
* Makefile 中 make run 章节，校验logs/nginx.pid文件是否存在，存在则不再启动nginx实例
Fix #1690
=> fix bug: Execute command 'make run' multiple times, will start multiple processes

apisix/plugins/echo.lua, conf/config.yaml, doc/plugins/echo-cn.md, doc/plugins/echo.md, t/admin/plugins.t, t/debug/debug-mode.t, t/plugin/echo.t
=> Add body filter and header filter plugin drafts.

doc/README_CN.md, doc/health-check-cn.md
add health-check-cn.md
补充中文文档
* 增加健康检查中文文档
Fix #1728
=> Add health-check-cn.md

apisix/admin/global_rules.lua, apisix/admin/routes.lua, apisix/admin/services.lua, apisix/admin/ssl.lua, apisix/admin/stream_routes.lua, apisix/admin/upstreams.lua, apisix/schema_def.lua, t/admin/global-rules.t, t/admin/routes.t, t/admin/services.t, t/admin/ssl.t, t/admin/stream-routes.t, t/admin/upstream.t
Use uniform id rules for `global rules`, `routes`, `service`, `upstream`, `stream_routes`. 
And use `jsonschema` to check it.
=> bugfix: the id can be string object, which contains `^[a-zA-Z0-9-_]+$`.

doc/admin-api.md, doc/zh-cn/admin-api.md
=> doc: update admin-api docs

doc/zh-cn/README.md
=> doc: update README.md

t/core/lrucache.t
t/core/lrucache.t test 6 is fail sometimes.
set a longer ttl time to avoid the cache item expired before to fetch.
=> test: sleep more time for expiring.

doc/README.md, kubernetes/README.md
=> Update k8s doc

apisix/plugins/openid-connect.lua
=> Fix for remote open ID connect introspection

apisix/plugins/heartbeat.lua
fixed https://github.com/apache/incubator-apisix/issues/1656
=> plugin(heartbeat): use `info` log level when failed to report heartbeat.

apisix/balancer.lua, apisix/init.lua, apisix/plugin.lua, benchmark/fake-apisix/conf/nginx.conf, benchmark/fake-apisix/lua/apisix.lua, bin/apisix, conf/config.yaml, t/admin/balancer.t
Cached the global rules to `ctx` .
I got some information from here:
https://gist.github.com/membphis/137db97a4bf64d3653aa42f3e016bd01?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDY4NDQ5Nzk5OTo2ODE0NjA2&notifications_query=reason%3Aparticipating#gistcomment-3353102
=> optimize: Use lru to avoid resolving IP addresses repeatedly .

CHANGELOG.md, CHANGELOG_CN.md, apisix/core/version.lua, doc/how-to-build.md, doc/zh-cn/how-to-build.md, rockspec/apisix-1.4-0.rockspec
@apache/apisix-committers please do have a look.
@moonming would be great if I can get the `CN` translations for the changelog.
=> release: released 1.4-0 version

apisix/plugins/cors.lua
Removes the 'auth' type for the cors plugin
* removed the 'auth' line
Fix #1787
=> remove authentication type for cors plugin

apisix/admin/plugins.lua, t/admin/plugins.t
It's a quiet useful to get the plugin priority information in the `get_plugin_list` API. This helps the plugin manager to know more clearly how  plugins works.
* feature: The 'get_plugin_list' API sorts the return list base on priority
=> The 'get_plugin_list' API sorts the return list base on priority

doc/install-dependencies.md, doc/zh-cn/install-dependencies.md
Signed-off-by: imjoey <majunjiev@gmail.com>
For now, the guide for Fedora users is missing in `Install Dependencies` doc. This PR is going to fix that.
* Add guides for Fedora users in both English and Chinese
* Fix a typo on anchor link.  *I would prefer to add this in this PR instead of a new one.
Thanks.
=> doc: Add guides for installing dependencies on Fedora

bin/apisix
fix: replace `location /robots.txt ` with `location =/robots.txt ` for admin page
=> fix: replace `location /robots.txt ` with `location =/robots.txt `

apisix/core/config_yaml.lua, apisix/init.lua, t/config-center-yaml/route-upstream.t
=> bugfix: failed to set server peer when upstreams.node is address in apisix.yaml

bin/apisix, conf/config.yaml
The default 3s may be too low.
=> feature: allow to congfiure the worker_shutdown_timeout

apisix/balancer.lua, apisix/init.lua, apisix/upstream.lua, t/node/invalid-route.t, t/node/upstream-domain.t, t/node/upstream-node-dns.t
> latest message
While adding test cases, two new bugs were found, and those bugs have existed for several months.
And I fixed them in this PR.
> old message
…S and proxy
the request to the new address.
We have fixed this bug in `master` branch, but we can get if we run this test case in branch `v1.4`. 
Add some test cases to confirm the `master` branch works fine for this case.
```shell
t/node/upstream-node-dns.t .. 7/?
```
Fix https://github.com/apache/incubator-apisix/issues/1834
=> bugfix: fetch wrong the upstream node when there were multiple upstream node with host

CODE_STYLE.md, CODE_STYLE_CN.md, Contributing.md, doc/zh-cn/README.md
We missing the apisix's lua code style guide when writing a plugin, fixing the code bug.
1. Adding `CODE_STYLE.md` base on `https://github.com/apache/incubator-apisix/blob/v1.2/CODE_STYLE.md`, and change it for meeting APISIX project
2. Adding `CODE_STYLE_CN.md` base on `https://juejin.im/post/5d71f9bcf265da03b76b437c`, and change it for readable :))
3. Fixing the `CODE_STYLE_CN.md` invalid path bug within `doc/zh-cn/README.md`
Fix #1846
=> Adding CODE_STYLE.md and CODE_STYLE_CN.md for APISIX

.travis/apisix_cli_test.sh, conf/config.yaml
The recommended value for worker_shutdown_timeout is 240 seconds.
#1853
=> The recommended value for worker_shutdown_timeout is 240 seconds.

doc/zh-cn/benchmark.md
Fix image links in zh-cn/benchmark.md
=> doc: Fix image links in zh-cn benchmark

apisix/schema_def.lua, doc/health-check.md, doc/zh-cn/health-check.md, t/admin/health-check.t
as title. eg: `1.05` means 1005 millisecond.
=> change: the timeout of `healthcheck` should be number type.

apisix/balancer.lua, apisix/schema_def.lua, doc/health-check.md, doc/zh-cn/health-check.md, t/node/healthcheck.t
=> feature: health check supports custom host port.

apisix/core/schema.lua, apisix/plugins/request-validation.lua, t/plugin/request-validation.t
=> change: add request-validation plugin input params schema valid.

.travis/linux_openresty_runner.sh, bin/apisix
Run `apisix start` several times, will start multi nginx processes.when we want to update `conf/config.yaml`, some processes  fail to use the new conf.
#1663 
#1671
=> fix: run `apisix start` several times will start multi nginx processes

apisix/balancer.lua, apisix/schema_def.lua, doc/admin-api.md, doc/zh-cn/admin-api.md, t/admin/upstream.t, t/node/upstream-retries.t
allow setting `retries=0` for an upstream object, this means there is no need to retry.
=> feature: allow to set `retries=0` for upstream object.

Makefile, doc/how-to-build.md, doc/zh-cn/how-to-build.md
=> makefile: add comments for `install` command.

doc/architecture-design.md, doc/zh-cn/architecture-design.md
there is two Nginx typo  in the documents
=> doc: corrected some typo

doc/zh-cn/how-to-build.md
=> doc: update how-to-build.md

apisix/consumer.lua, apisix/core/config_etcd.lua, apisix/http/router/radixtree_sni.lua, apisix/plugins/grpc-transcode/proto.lua, apisix/plugins/prometheus/exporter.lua, apisix/router.lua, apisix/schema_def.lua, t/core/etcd-sync.t, t/plugin/prometheus.t
add more prometheus metrics for better understanding the situation of APISIX nodes.
#1885
=> change: add more prometheus metrics(etcd modify index)

doc/zh-cn/plugins/request-validation.md
=> doc: add `request-validation` plugin chinese document.

README.md, README_CN.md
FIX #1949 
Currently `uri-blocker` does not have a Chinese document. The address of `README_CN.md` will point to the English document. Next, I will use a new PR to submit the Chinese document.
=> doc: fixed `uri-blocker` plugin path error in `README`.

t/node/invalid-upstream.t
as title.
In test 3 of the old use case, both the old and new configurations may trigger errors and generate logs, and they are random. There should be only one error at a time, which makes it easier to ensure stable testing.
unstable output: https://github.com/apache/incubator-apisix/runs/921554160?check_suite_focus=true#step:6:121
=> test: old test case is unstable, running fail sometimes.

bin/apisix
- change: fix wrong info `Warning! Running apisix under /root` when `make init` at non-root path
=> change: fix wrong info `Warning! Running apisix under /root` when `make init` at non-root path

benchmark/fake-apisix/conf/nginx.conf, benchmark/run.sh, benchmark/server/conf/nginx.conf, bin/apisix, conf/config.yaml, t/APISIX.pm, t/debug/debug-mode.t
as title.
Single-core QPS increased from 20118.64 to 22448.23, an increase of about 12%.
And the QPS of this version is 89% of [fake apisix](https://github.com/apache/apisix/tree/master/benchmark/fake-apisix).
disable two plugins by default(proxy-cache, proxy-mirror), if the user wants to enable them, need to modify the `conf/config.yaml` by manual.
=> perf: no longer generate unnecessary nginx conf for better performance.

conf/config.yaml, t/APISIX.pm, t/debug/debug-mode.t
enable proxy-cache and proxy-mirror by default.
resolve  #1987
=> revert: enable proxy-cache and proxy-mirror plugins by default.

apisix/schema_def.lua
Sometimes we might hope the id in the following format: 
- upstream:payment:project_a
- upstream:message_system:project_b
etc.
fix #1955
=> feature: accept ":" in id (#1955)

apisix/plugins/syslog.lua, t/plugin/syslog.t
was called in back timer async.
Fixed #1935.
=> bugfix: passed the copied `api_ctx`, it may be freed if the `api_ctx`

doc/getting-started.md, doc/zh-cn/getting-started.md
The cd command after cloning the repo would fail as it is not yet in the incubator-apisix-docker directory.
The Getting Started steps in the documentation, if ran exactly as shown would not work.  This corrects the `cd` path to that they will work.
=> Correct directory after cloning repo

apisix/init.lua, apisix/script.lua, t/script/script_distribute.t
=> typo: fixed typo about function.

doc/README.md
The current listing of the plugins is cluttered and by refactoring them to functional groups, it will make it easier for the users to find the plugins. The plugins are divided into the following categories.
- General
- Authentication
- Authorization
- Security
- Traffic Control
- Monitoring
- Logging
=> Refactoring plugins into functional categories

apisix/core/response.lua, apisix/init.lua, t/node/remote-addr-ipv6.t, t/plugin/redirect.t, t/router/multi-ssl-certs.t, t/router/radixtree-sni.t
We should pass the APISIX version in the response headers
fixes : https://github.com/apache/incubator-apisix/issues/1877
=> add apisix-version info to headers

apisix/plugins/prometheus/exporter.lua
By looking at name like `apisix_bandwidth` or `apisix_http_latency`,
it is hard to guess their units. Also, it is not so clear for where does
the overhead come from for `apisix_http_overhead` at the first glance.
=> chore: should improve the prometheus metric naming

.travis/linux_openresty_runner.sh, apisix/plugins/authz-keycloak.lua, apisix/plugins/fault-injection.lua, apisix/plugins/redirect.lua, apisix/plugins/request-validation.lua, apisix/plugins/uri-blocker.lua, doc/plugin-develop.md, doc/zh-cn/plugin-develop.md, t/fake-plugin-exit.lua, utils/check-plugins-code.sh
plugins should not exit by itself in access and rewrite phase, it can't be reuse in script, and the plugin engine has already covered:
https://github.com/apache/apisix/blob/master/apisix/init.lua#L134
#2111
=> fix: plugins should not exit by itself

.travis/apisix_cli_test.sh, bin/apisix
Previously, with the default configure, people don't have the chance to
ignore the warning message.
=> change: allow users to see warnings by default

apisix/init.lua, apisix/plugins/log-rotate.lua, conf/config-default.yaml, doc/README.md, doc/plugins/log-rotate.md, doc/zh-cn/README.md, doc/zh-cn/plugins/log-rotate.md, t/core/config-default.t, t/plugin/log-rotate.t
=> feature: implemented plugin `log-rotate`, rotate log by interval time.

t/plugin/tcp-logger.t, t/plugin/udp-logger.t
Wait time is too short it will easy fail in some bad hardware environment.
=> fix: test case wait time is too short

apisix/admin/init.lua
1. /stream_routes needs to be ended with '/'
2. /list only needs GET method
=> chore: restrict the apisix/admin routers

apisix/http/router/radixtree_sni.lua, t/router/radixtree-sni.t
The processes of `ngx_ssl.parse_pem_cert` and `ngx_ssl.parse_pem_priv_key` are relatively expensive, and keypair is inclined to be constant (for a long while), so it's worth to cache the parsed result into LRU cache, which can reduce a part of overheads during `ssl_certificate_by_lua*` phase.
=> improve: cache parsed SSL certs and pkeys

bin/apisix, rockspec/apisix-master-0.rockspec
Signed-off-by: tokers <zchao1995@gmail.com>
=> change: check etcd cluster version when init_etcd

apisix/core/config_etcd.lua, t/node/route-delete.t
If the administrator user creates and deletes the same route multiple times, the new route will not be correctly synchronized to the APISIX gateway node, resulting in some request route matching failures and a 404 response.
bugfix: clear all cached data when get delete action, and removing stale boolean data in table self.values with a safer way
=> bugfix: clear all cached object when got `delete` action, and removing stale boolean data in table `self.values` with a safer way

rockspec/apisix-master-0.rockspec
update lua-resty-etcd version to remove the unnecessary log in etcd v3
=> fix: bump lua-resty-etcd to 1.2

apisix/init.lua, apisix/plugins/consumer-restriction.lua, t/plugin/consumer-restriction.t
The `consumer` provides access to the `service` collection . Put it in the "consumer-restriction" plug-in to achieve, by adding the "schema" field of this plug-in, to control the access of "consumer" and "service".
=> feature: `consumer` provides access to a collection of `service` 

apisix/plugins/http-logger.lua, doc/plugins/http-logger.md, doc/zh-cn/plugins/http-logger.md, t/lib/server.lua, t/plugin/http-logger-new-line.t
as title.
support to report log in this way:
```shell
curl http://****/log -d '
{xxxxxxxxxxxxx}
{yyyyyyyyyyyyy}
'
```
the request logs is concat by '\n' way.
=> feat(http-logger): support to concat multiple log with separator.

doc/router-radixtree.md
Update the `router-radixtree` document.
The former router example in this document use "==" as the default operator, which is not the current behavior.
This PR modifies the example and keeps it consistent with the `admin-api` document.
=> doc: update router variable example (#2298)

apisix/plugins/hmac-auth.lua, doc/plugins/hmac-auth.md, doc/zh-cn/plugins/hmac-auth.md, t/plugin/consumer-restriction.t, t/plugin/custom_hmac_auth.t, t/plugin/hmac-auth.t
fix #2336 .
ref:
https://help.aliyun.com/document_detail/29475.html?spm=a2c4g.11186623.2.15.62c73e789LVg02
https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationConstructingCanonicalizedAmzHeaders
=> change(hmac-auth): update the organization of `signing_string` .

README.md, README_CN.md, apisix/plugins/referer-restriction.lua, conf/config-default.yaml, doc/README.md, doc/_sidebar.md, doc/plugins/referer-restriction.md, doc/zh-cn/README.md, doc/zh-cn/plugins/referer-restriction.md, doc/zh-cn/referer-restriction.md, t/admin/plugins.t, t/debug/debug-mode.t, t/plugin/referer-restriction.t
=> feat: add referer-restriction plugin

apisix/core/config_local.lua
fixed https://github.com/apache/apisix/issues/2361
Use the jit-able API `table.isarray` to replace the artifacts for the better CPU performance.
=> optimize: use table.isarray to check whether table is an array.

apisix/core/id.lua, apisix/init.lua, t/core/random.t, t/stream-node/random.t
related PR: https://github.com/apache/apisix/pull/2306
=> bugfix: set random seed for each worker process at `init_worker` phase, only `init` phase is not enough.

Makefile
wget always leave a file, enven though error happens when download.
So it's maybe not proper to decide wether to download a new file by checking the file's existence.
=> fix: wget -O always leave a file enven though download fail

bin/apisix
IMHO, the operation of "check the etcd cluster version" should check every etcd version in the yaml_conf.etcd.host list.
But the `break` make it only check the first one.
=> bugfix: check every etcd version, rather than only check the first one

apisix/plugin.lua, apisix/plugins/http-logger.lua, bin/apisix, doc/zh-cn/plugins/http-logger.md, t/plugin/http-logger-log-format.t, t/plugin/http-logger-new-line.t
This reverts commit 13b09683400e41529258fe21f013668880a6a5ba.
as title.
For example:
```
curl http://****/apisix/admin/plugin_metadata/http-logger -d '
{
"log_format": {
"host": "$host",
"@timestamp": "$time_iso8601",
"client_ip": "$remote_addr"
}
}'
```
when we enabled plugin `http-logger`, we will get the message body like:
```
{"host":"localhost","@timestamp":"2020-09-23T18:29:07-04:00","client_ip":"127.0.0.1","route_id":"1"}
{"host":"localhost","@timestamp":"2020-09-23T18:29:07-04:00","client_ip":"127.0.0.1","route_id":"1"}
```
related PR: 
https://github.com/apache/apisix/pull/2307
https://github.com/apache/apisix/pull/2294
=> feat(http-logger): support for specified the log formats via admin API

bin/apisix
1. the result below will always be false ,since etcd_version is nil:
```lua
if (etcd_version == "v3" and not res:find("OK", 1, true)) then
is_success = false
if (index == host_count) then
error(cmd .. "\n" .. res)
end
break
end
``` 
and since etcd_version has been checked before, I think maybe there is no need to check it again here.
2. cluster_version has been defined previously, no need to define a new local one.
=> fix: it does'nt make sence to compare etcd_version, since it's nil.

.github/workflows/build.yml, .travis/linux_openresty_runner.sh, apisix/plugins/limit-count.lua, apisix/plugins/limit-count/limit-count-redis-cluster.lua, apisix/plugins/limit-count/limit-count-redis.lua, bin/apisix, doc/plugins/limit-count.md, doc/zh-cn/plugins/limit-count.md, rockspec/apisix-master-0.rockspec, t/APISIX.pm, t/plugin/limit-count-redis-cluster.t
Support for using redis cluster in limit-count plugin.
fix https://github.com/apache/apisix/issues/638
continue PR: https://github.com/apache/apisix/pull/2340
=> feature: plugin `limit-count` support to use `redis` cluster

apisix/core/utils.lua, apisix/init.lua, t/core/utils.t, t/node/upstream-node-dns.t
=> feat: In dns parse, when the parameter `resolvers` is empty, the local dns is used as `resolvers` by default 

apisix/admin/plugin_metadata.lua, apisix/api_router.lua, doc/plugin-interceptors.md, doc/plugins/batch-requests.md, doc/plugins/jwt-auth.md, doc/plugins/prometheus.md, doc/plugins/wolf-rbac.md, doc/zh-cn/plugin-interceptors.md, doc/zh-cn/plugins/batch-requests.md, doc/zh-cn/plugins/jwt-auth.md, doc/zh-cn/plugins/prometheus.md, doc/zh-cn/plugins/wolf-rbac.md, t/admin/plugin-metadata.t
=> feat: use interceptors to protect plugin's route

bin/apisix
Because the old CLI invalid argument prompt is unfriendly. So I modify it, next look like friendly.
No . maybe you can used the CLI
```shell
apisix --help
```
I modified the invalid argument prompt.
=> The old CLI invalid argument prompt is unfriendly.

.travis/linux_openresty_runner.sh
=> CI: remove `luacov`, maybe reopen it later.

apisix/plugins/limit-conn.lua, t/plugin/limit-conn.t
=> fix(limit-conn): conn and default_conn_delay should > 0

apisix/plugins/prometheus/exporter.lua, t/plugin/prometheus.t
Signed-off-by: imjoey <majunjiev@gmail.com>
Fixes #2445 .
This PR is going to add `consumer` label for metric items. Based on this, we could trigger/send notifications to specified consumer when http status is unexpected, as well as get the estimated data about different consumers for several metrics.
=> feat(prometheus): Add consumer metric data support

apisix/core/config_yaml.lua
IMHO, there is no need to loop 10 times for read trailing bytes in stand-alone mode,
or maybe there is some special reason i didn't get.
If so, @membphis  would you please explain it a little? thanks.
=> optimize: read trailing bytes only one time in stand-alone mode.

t/plugin/batch-requests.t, t/plugin/udp-logger.t
Two fixes:
- Delete the test configuration to keep the environment clean, otherwise the next run will fail。
- The wait time of udp-logger test case is too short, it will failed sometime.Increase it to 5 secs keep stable.
=> chore: change test case to keep stable

bin/apisix, conf/config-default.yaml
Support to configure `lua_ssl_trusted_certificate` in configuration, so that one can use the certs signed by their own CA as an external dependency of APISIX, like ETCD.
This PR is necessary for the subsequent TLS for ETCD connection feature.
=> feature: support injecting lua_ssl_trusted_certificate.

doc/getting-started.md, doc/plugins/syslog.md, doc/zh-cn/getting-started.md, doc/zh-cn/plugins/syslog.md
fix #2457 
https://github.com/apache/apisix/blob/master/doc/getting-started.md#add-a-prefix-to-the-route Line 240
should be replaced with
curl -i -X GET "http://127.0.0.1:9080/samplePrefix/get?param1=foo&param2=bar" -H 'apikey: superSecretAPIKey'
the example in  https://github.com/apache/apisix/blob/master/doc/plugins/syslog.md#how-to-enable should be for route not consumers and the value is wrong.
=> [doc]to correct some typo and incorrect examples in getting-started.md and syslog.md

doc/README.md, doc/grpc-proxy.md, doc/zh-cn/README.md
Fix for https://github.com/apache/apisix/issues/2327
=> doc : fixes issue #2327

apisix/core/lrucache.lua, apisix/plugins/basic-auth.lua, apisix/plugins/cors.lua, apisix/plugins/hmac-auth.lua, apisix/plugins/jwt-auth.lua, apisix/plugins/key-auth.lua, apisix/plugins/limit-conn.lua, apisix/plugins/limit-count.lua, apisix/plugins/limit-req.lua, apisix/plugins/serverless.lua, apisix/plugins/syslog.lua, apisix/plugins/wolf-rbac.lua, apisix/plugins/zipkin.lua, t/core/lrucache.t, t/plugin/limit-count-redis-cluster.t, t/plugin/limit-count-redis.t, t/plugin/syslog.t
=> change: make lrucache lock optional

Makefile
The directory is already installed a few lines above.
=> chore: remove redundant installation of limit-count

doc/zh-cn/plugins/node-status.md
This is the description of plugin node-status in Chinese, and I'd love to submit the document in lEnglish later.
This PR is relate with [issue#2379](https://github.com/apache/apisix/issues/2379)
=> docs: node-status.md

apisix/init.lua, conf/config-default.yaml, t/core/utils.t
Sometimes expose version is dangerous, which can be utilized by
malicious crackers when there are some security bugs in that version.
=> feat: hide APISIX version from Server header.

apisix/plugins/key-auth.lua, t/plugin/key-auth.t
Close #2686.
According to the
https://github.com/apache/apisix/pull/2120#discussion_r477153261,
instead of skipping consumer without key, we should make 'key' required
only for consumer configuration.
=> fix(key-auth): 'key' is required in consumer configuration

doc/install-dependencies.md, doc/zh-cn/install-dependencies.md
etcd v3 only supports gRPC as the messaing protocol, only enabling gRPC gateway, APISIX can communicate to it with Restful APIs.
=> docs: mentioned the etcd gRPC gateway

.travis/apisix_cli_test.sh, bin/apisix, conf/config.yaml
=> feat: support ENV variable in configuration

apisix/admin/consumers.lua, apisix/admin/routes.lua, apisix/admin/services.lua, apisix/admin/ssl.lua, apisix/admin/upstreams.lua, apisix/admin/utils.lua, doc/admin-api.md, doc/zh-cn/admin-api.md, t/admin/consumers.t, t/admin/routes.t, t/admin/services.t, t/admin/ssl.t, t/admin/upstream.t
=> feat: generate create/update_time automatically

apisix/core/config_etcd.lua, apisix/core/etcd.lua
=> fix(etcd): handle etcd compaction

apisix/cli/ngx_tpl.lua, apisix/init.lua, t/APISIX.pm, t/core/utils.t, t/node/remote-addr-ipv6.t, t/plugin/redirect.t, t/router/multi-ssl-certs.t, t/router/radixtree-sni.t
I think it's better to just leave `Server: APISIX/2.0` and override the other `server` header field!
demo：
```
$ curl  http://127.0.0.1:9080/test_core -i
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/2.0
Date: Thu, 12 Nov 2020 04:31:03 GMT
tested by python
```
ref:
https://github.com/apache/apisix/issues/2714
=> fix: remove upstream 'Server' header info. fix #2714

doc/how-to-build.md, doc/zh-cn/how-to-build.md
=> docs: modify a typo

bin/apisix
Signed-off-by: liuhong <liuhong_yewu@cmss.chinamobile.com>
Executing apisix init_etcd,it will report min_etcd_version is a nil value when etcd version is less than min_etcd_version
=> fix: min_etcd_version is a nil value when etcd version less than min_etcd_version

apisix/ssl/router/radixtree_sni.lua, t/certs/incorrect.crt, t/certs/incorrect.key, t/router/radixtree-sni.t
Hi, I found that the decrypt function in `aes.lua` will cause lua thread aborted if the key is nil.
fix: #2791
=> fix: check decrypt key to prevent lua thread aborted

apisix/plugins/prometheus/exporter.lua
Since c5dcced1cf90e2ffa5b73583784fc9bd34706aac,
modifiedIndex_org is only accessed in this place without any assignment.
=> chore: remove stale access to modifiedIndex_org

apisix/cli/etcd.lua, apisix/cli/file.lua, apisix/cli/util.lua, bin/apisix
Signed-off-by: Alex Zhang <zchao1995@gmail.com>
Move the etcd initialization into `apisix/cli/etcd.lua`, some auxiliary functions were moved to `apisix/cli/etcd.lua` and the yaml configuration file parsing function was moved to `apisix/cli/file.lua`.
=> refactor: moved etcd initialiation to apisix/cli/etcd.lua

.travis/apisix_cli_test.sh, apisix/cli/ngx_tpl.lua, conf/config-default.yaml, doc/README.md, doc/customize-nginx-configuration.md, doc/zh-cn/README.md, doc/zh-cn/customize-nginx-configuration.md
=> feat: support include other nginx config

bin/apisix
* We don't need to execute `openresty -v 2>&1` twice to get correct version.
* One line code style correction.
=> chore: minor change in bin/apisix

FAQ.md, FAQ_CN.md, apisix/core/id.lua, t/plugin/node-status.t
=> feat: allow user to specify APISIX id in config.yaml

CHANGELOG.md, CHANGELOG_CN.md, README.md, README_CN.md, apisix/core/version.lua, doc/how-to-build.md, doc/zh-cn/how-to-build.md, rockspec/apisix-2.1-0.rockspec
=> release: release 2.1 version.

apisix/plugins/openid-connect.lua
The `openid-connect` plugin is an authentication plugin. As such, it should run in the rewrite phase, not the access phase. The current version runs in the access phase, this PR changes the phase to rewrite.
=> fix: Openid connect plugin should run in rewrite phase.

apisix/admin/consumers.lua, apisix/consumer.lua, apisix/init.lua, doc/admin-api.md, doc/zh-cn/admin-api.md, t/config-center-yaml/stream-route.t, t/node/consumer-plugin.t
=> feat: allow create consumers with multiple auth plugins

apisix/schema_def.lua, t/admin/routes.t
This change imroves the IP schema validation.
=> fix: reject "" for route's remote_addrs

apisix/plugins/http-logger.lua, apisix/plugins/tcp-logger.lua, t/plugin/http-logger.t
Close https://github.com/apache/apisix/issues/2870
=> fix: fixed the non effective config update in http-logger

apisix/plugins/authz-keycloak.lua
The `authz-keycloak` plugin is concerned with authorization against Keycloak, not authentication. As such, it should not be designated as of type `auth`. Also, I suggest to run it in the access phase which seems more appropriate.
=> fix: authz-keycloak plugin should run in access phase and should not be designated as of type auth anymore.

apisix/plugins/authz-keycloak.lua
The `auth-keycloak` plugin expects to find a bearer token in the standard `Authorization` header. However, it tries to obtain a token from a header called `authorization`, i.e. not properly capitalized. This PR fixes the capitalization so the correct header is used; cf. https://en.wikipedia.org/wiki/List_of_HTTP_header_fields.
=> fix: Use correct name when accessing Authorization header in auth-keycloak plugin.

apisix/core/ctx.lua
To avoid accessing memory which is out of bound.
=> fix: we should check the length of input before calling memcmp

conf/config-default.yaml, doc/plugins/node-status.md, doc/zh-cn/plugins/node-status.md, t/admin/plugins.t, t/admin/schema.t, t/debug/debug-mode.t, t/plugin/node-status.t
=> feat: disable node-status by default

apisix/cli/etcd.lua
Signed-off-by: Alex Zhang <zchao1995@gmail.com>
etcd gRPC gateway is required by APISIX, we should detect it when calling `bin/apisix init_etcd`, or errors will occur in the runtime, which harms the service availability.
=> feat: detect whether etcd gRPC gateway is enabled in command line

apisix/core/config_etcd.lua, conf/config-default.yaml, t/core/etcd-sync.t
It improves the behavior under #2899.
=> feat: increase the delay before resync

apisix/core/utils.lua, apisix/plugins/fault-injection.lua, doc/plugins/fault-injection.md, doc/zh-cn/plugins/fault-injection.md, t/core/utils.t, t/plugin/fault-injection.t
=> feat(fault-injection): support Nginx variable in abort.body

apisix/http/router/radixtree_host_uri.lua, apisix/http/router/radixtree_uri.lua, apisix/schema_def.lua, doc/admin-api.md, doc/zh-cn/admin-api.md, t/lib/server.lua, t/node/route-status.t
=> feat: support enable/disable route

t/node/merge-route.t
The time_window field might be the last one, which doesn't have ','
=> test: make node/merge-route.t stable

apisix/plugins/limit-conn.lua, t/plugin/limit-conn.t
=> fix(limit-conn): always save the data of the limit object, and release it in log phase.

apisix/cli/env.lua, apisix/core/ctx.lua, conf/config-default.yaml, doc/router-radixtree.md, rockspec/apisix-master-0.rockspec, t/APISIX.pm, t/lib/test_admin.lua, t/plugin/openid-connect.t, t/router/graphql.t
=> feat: route accroding to the graphql attributes

README.md, README_CN.md
Changed `Github` to `GitHub`
Standardizes the way we spell `GitHub`.  Makes our docs look better.
=> docs: fix case of GitHub

apisix/plugins/server-info.lua, t/plugin/server-info.t
I think there is no need to encode the object that calls `etcd.set`.Because the `lua-resty-etcd` will serialize it.
=> fix: fix on setting server info to etcd

.travis/apisix_cli_test/common.sh, .travis/apisix_cli_test/test_ci_only.sh, .travis/apisix_cli_test/test_control.sh, .travis/apisix_cli_test/test_main.sh, .travis/linux_apisix_current_luarocks_runner.sh, apisix/cli/ngx_tpl.lua, apisix/cli/ops.lua, apisix/control/router.lua, apisix/control/v1.lua, apisix/init.lua, apisix/plugins/example-plugin.lua, conf/config-default.yaml, doc/README.md, doc/control-api.md, t/APISIX.pm, t/control/v1.t
=> feat: add control API

apisix/schema_def.lua, doc/admin-api.md, doc/architecture-design.md, doc/zh-cn/admin-api.md, doc/zh-cn/architecture-design.md, t/node/upstream.t
=> change: remove k8s_deployment_info

apisix/init.lua
A new feature has been added in OpenResty 1.19.3.1:
`Shared ngx.ctx among SSL_* phases and the following phases.`
In the ssl phase, ctx is created but not cleared. 
In the access phase, it is judged that if ctx already exists, it will not be created. 
This causes a same client to access an `https` service and then access another `http` service, it will be reused the previous ctx, resulting in this bug.
fix #3079
we could add test cases later for quick fix. we could track it by #3103  
we don't need to modify docs for this change.
=> fix: ctx being contaminated due to a new feature of openresty 1.19

apisix/control/v1.lua, t/control/schema.t
Expose `upstream_hash_header_schema` and `upstream_hash_vars_schema`.
We need them to verify `hash_on` of upstream:
https://github.com/apache/apisix/blob/8983a8dd278fec89d40b3d9a14eca9ecf9a187fd/apisix/admin/upstreams.lua#L31-L49
https://github.com/apache/apisix/blob/8983a8dd278fec89d40b3d9a14eca9ecf9a187fd/apisix/admin/upstreams.lua#L82-L92
=> chore: expose more schema via control API

.markdownlint.yml, FAQ.md
Remove rules:
MD018 - No space after hash on atx style header
MD020 - No space inside hashes on closed atx style header
MD021 - Multiple spaces inside hashes on closed atx style header
Lint for:
MD019 - Multiple spaces after hash on atx style header
Standardizes our Markdown
=> docs: lint Markdown and remove unneeded rules

apisix/schema_def.lua, t/router/radixtree-uri-vars.t
Previously only the type is applied, and it is too strict.
And now we should allow 4 items in the vars expression.
Fix #3123
=> fix: correct the validation of route.vars

t/plugin/server-info.t
update server-info.t with toolkit.json when write the table value  by sort, and remove some unused lines in case 2.
#3095
=> test: update server-info.t with 'toolkit.json' to print table

apisix/init.lua
And it doesn't free the reference which is actually controlled in C
land.
=> fix: set `ngx.ctx` to nil will corrupt the inner ngx_lua_ctx_tables

apisix/plugins/grpc-transcode/proto.lua, t/plugin/grpc-transcode.t
When watching ETCD, delete a resource item, we will set the corresponding item in `values` to false. ([refer](https://github.com/apache/apisix/blob/master/apisix/core/config_etcd.lua#L412))
When traversing the `values` of the resource, all items are directly used as `table`, which will cause errors.
Use `config_util.iterate_values` to process first to avoid this problem.
close #3166
=> fix: use `config_util.iterate_values` to avoid error by using invalid  data type as table

conf/config-default.yaml, t/admin/plugins.t, t/core/config_etcd.t, t/debug/debug-mode.t
the Dashboard user can fetch the gateway node information by this plugin.
=> chore: enable plugin `server-info` by default.

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/request-help.md, .github/workflows/lint.yml, doc/plugins/openid-connect.md
Due to the ASF's policies changing we cannot use the original GitHub Actions for linting as they are not approved
Lint Markdown for rules:
- MD012/no-multiple-blanks
- MD032/blanks-around-lists
refs #3178 
Fixes the YAML linter so we can continue to have standardized YAML.
Standardizes our Markdown.
=> fix(CI): roll our own linter for YAML

.travis/apisix_cli_test/test_main.sh, apisix/cli/etcd.lua, rockspec/apisix-master-0.rockspec
=> feat: use luasocket instead of curl  in etcd.lua

apisix/admin/global_rules.lua, apisix/schema_def.lua, t/admin/global-rules.t, t/admin/schema.t
Signed-off-by: imjoey <majunjiev@gmail.com>
As https://github.com/apache/apisix-dashboard/issues/1143 comes to a conclusion that `create_time` and `update_time` are needed for `global_rule` entity. This PR is going to  add the two fields and relevant test cases. 
Related to https://github.com/apache/apisix-dashboard/issues/1143  , taking charge of the APISIX part.
=> feat: Add create_time and update_time in global_rule schema

apisix/balancer/chash.lua, t/admin/balancer.t, t/node/healthcheck.t
chash will pick next if last doesn't work to enable set_more_retries().
=> fix: make set_more_retries() work when upstream_type is chash

.travis/apisix_cli_test/test_main.sh, apisix/cli/ngx_tpl.lua, conf/config-default.yaml, doc/customize-nginx-configuration.md, doc/zh-cn/customize-nginx-configuration.md
在使用apisix过程中由于要使用第三方模块，需要用到load_module和include这两个指令，目前关于nginx的自定义配置对这两个指令的支持有问题，因此这个pull request丰富了用户自定义配置的支持
具体见https://github.com/apache/apisix/issues/3203
=> feat: support more customize configure in nginx.conf

apisix/balancer.lua
catch error while new `healthcheck` instance and return the checker with nil.
the function pick_server will treat the nodes as normal  with the 'checker == nil', and get a correct one by rules.
fix #3169
=> chore: catch error while new `healthcheck` instance

apisix/balancer.lua, apisix/init.lua, apisix/upstream.lua, t/discovery/eureka.t
Allow to call yield function in the healthcheck.
Co-authored-by: YuanSheng Wang <membphis@gmail.com>
=> fix: create the health checker in `access` phase

apisix/core/config_etcd.lua
The 401 error is only for v2, so it is safe to remove it now.
=> chore: remove the obsolote etcd v2 protocol error

apisix/plugins/traffic-split.lua, t/plugin/traffic-split.t
I check the schema for plugin traffic-split, it doesn't have additionalProperties = false to limit config, could we add this limit.  so that we could prompt error when config invalid.
fix https://github.com/apache/apisix-dashboard/issues/1294
=> chore(traffic-split): add additionalProperties field to restrict plugin configuration

doc/architecture-design.md
Whilst the original syntax does work, it is better to standardize all anchors to lowercase like most of the codebase
Standardizes the Markdown files.
=> docs: standardize link anchors to be all lowercase

apisix/plugin.lua, t/admin/plugins.t
Injected `$comment` into properties will cause the schema to fail to load, so need to move it.
=> chore: remove injected field of plugin schema from properties

apisix/core/table.lua, apisix/http/service.lua, apisix/plugin.lua, apisix/plugins/example-plugin.lua, apisix/plugins/traffic-split.lua, apisix/router.lua, apisix/stream/plugins/mqtt-proxy.lua, apisix/upstream.lua, t/node/healthcheck.t, t/node/healthcheck2.t
Previously, the parent of up_conf is always a `route` even if it comes from upstream or service.
As the key of the parent will be used as health checker's key, when multiple routes shares the same upstream, the health checker will be bound with one of the route instead of the upstream.
=> refactor: the parent of upstream should point to its original src

apisix/plugins/traffic-split.lua, t/plugin/traffic-split.t
fix #3306
Currently, the vars of the traffic-split plug-in cannot have a horizontal line ("-") when setting the header. This PR is used to allow request parameters and request headers to have a horizontal line ("-").
=> fix(traffic-split): the header set in vars cannot have a horizontal line

apisix/balancer.lua, apisix/balancer/least_conn.lua, apisix/schema_def.lua, doc/admin-api.md, doc/zh-cn/admin-api.md, rockspec/apisix-master-0.rockspec, t/node/least_conn.t
=> feat: load balance by least connections

apisix/balancer.lua, apisix/http/service.lua, apisix/init.lua, apisix/plugin.lua, apisix/router.lua, apisix/upstream.lua, apisix/utils/upstream.lua, t/node/healthcheck-discovery.t, t/node/upstream-discovery.t
=> fix: avoid caching outdated discovery upstream nodes

.travis/apisix_cli_test/test_main.sh, Makefile, apisix/cli/env.lua, apisix/cli/ops.lua, t/cli/cli.t
Cause of the bug: After APISIX is started, the `worker process` has the authority of nobody ordinary user. When APISIX is in the /root directory, ordinary users do not have the authority to access the `/root` directory. Therefore, when APISIX is started, the error log `error.log` will show the following error message:
```
init_worker_by_lua error: /root/apisix-2.1/apisix/init.lua:89: module 'resty.worker.events' not found:
no field package.preload['resty.worker.events']
no file '/root/apisix-2.1//deps/share/lua/5.1/resty/worker/events.lua'
no file '/root/apisix-2.1//deps/share/lua/5.1/resty/worker/events/init.lua'
no file '/root/apisix-2.1/resty/worker/events.lua'
no file '/root/apisix-2.1/resty/worker/events/init.lua'
```
The solution: it is forbidden to execute make run in the /root …
=> fix: APISIX runs in the `/root` directory and reports errors

doc/zh-cn/plugins/skywalking.md
The Chinese document of skywalking is inconsistent with the English document, and the route example in the Chinese document is wrong. This PR is an example of fixing errors in Chinese documents and keeping them consistent with English documents.
Examples of errors in Chinese doc:
```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
"methods": ["GET"],
"uris": [
"/uid/*"
],
"plugins": {
"skywalking": {
"endpoint": "http://10.110.149.175:12800",
"sample_ratio": 1,
"service_name": "APISIX_SERVER"
}
},
"upstream": {
"type": "roundrobin",
"nodes": {
"10.110.149.175:8089": 1
}
}
}'
{"error_msg":"failed to check the configuration of plugin skywalking err: additional properties forbidden, found service_name"}
```
=> docs: fix the example in skywalking doc

apisix/init.lua, t/config-center-yaml/global-rule.t
=> fix: set conf info when global rule is hit without matched rule

doc/examples/plugins-hmac-auth-generate-signature.md, doc/plugins/hmac-auth.md, doc/zh-cn/plugins/hmac-auth.md
Improve the hmac-auth plugin documentation and add detailed usage examples.
close #3334
=> docs: improve the hamc-auth plugin documentation

apisix/control/v1.lua, apisix/upstream.lua, doc/control-api.md, doc/health-check.md, doc/zh-cn/health-check.md, t/control/healthcheck.t
=> feat: allow getting health check status via control API

rockspec/apisix-master-0.rockspec
lua-resty-expr has released the latest version, you need to update lua-resty-expr to v1.1.0
See here:
https://github.com/api7/lua-resty-expr/issues/24
https://github.com/api7/lua-resty-expr/issues/20
=> chore: update lua-resty-expr to v1.1.0

apisix/init.lua, t/node/grpc-proxy.t
=> fix: support upstream_id & consumer with grpc

apisix/consumer.lua, t/config-center-yaml/consumer.t
We already did the same thing with the configuration from etcd.
=> fix(standalone): require consumer's id to be the same as username

doc/json/apisix-grafana-dashboard.json, doc/plugins/prometheus.md, doc/zh-cn/plugins/prometheus.md
Plugin Prometheus have been updated in the last year, but the example grafana dashboard haven't been updated since Feb. 2020. But since I haven't use grafana before, suggestions is highly needed 😿 
**Added**
| metric | panel type |
| ----------- | ----------- |
| HTTP Latency/Overhead | histogram |
| etcd reachable | stat (alert when 0) |
| nginx metric errors | stat |
| etcd modify index | graph |
| batch process entries | graph |
**Fixed**
- Set atomic values to 0 decimals
- Add new variables
- Fix HTTP code labels syntax error
**TODO**
=> fix: update example grafana to lastest prometheus support

.gitignore
Currently when check license (`sudo make license-check`) locally, it would pull openwhisk-utilities. While since it is not ignored, we need to remove it whenever make commits.
=> chore: git ignore openwhisk to smoothly check license locally

conf/config.yaml, kubernetes/deployment.yaml, kubernetes/service.yaml
#3044 imports a format error in kubernetes/service.yaml
https://github.com/apache/apisix/blob/34bcac8bf7a188edbfa9262626c4ec5347e5c495/kubernetes/service.yaml#L25-L43
What this PR does:
- fix the format error
- update default `apiVersion` of deployment
- fix more format with [YAML Language Support by Red Hat](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)
=> chore: fix kubernetes yaml not working

.gitignore, .travis/linux_openresty_common_runner.sh, .travis/linux_tengine_runner.sh, apisix/cli/ngx_tpl.lua, apisix/cli/ops.lua, apisix/init.lua, apisix/plugins/proxy-rewrite.lua, apisix/schema_def.lua, apisix/upstream.lua, doc/admin-api.md, doc/grpc-proxy.md, doc/plugins/grpc-transcode.md, doc/zh-cn/admin-api.md, doc/zh-cn/grpc-proxy.md, doc/zh-cn/plugins/grpc-transcode.md, t/APISIX.pm, t/admin/routes2.t, t/admin/services2.t, t/admin/stream-routes.t, t/admin/upstream2.t, t/grpc-proxy-test.sh, t/node/grpc-proxy.t, t/plugin/grpc-transcode.t
=> feat: support gRPCS

apisix/upstream.lua, t/node/healthcheck-discovery.t
lua-resty-healthcheck remove target according to the `ip, port,
hostname` tuple. If the newly added target has the same tuple, it will
be removed accidently.
=> fix: remove stale checker before adding new one

.travis/apisix_cli_test/test_ci_only.sh, .travis/apisix_cli_test/test_main.sh
This test can't be run if we don't use root privilege.
=> test: move test requires root privilege to ci_only group

apisix/plugins/proxy-rewrite.lua, t/plugin/proxy-rewrite.t
proxy-rewrite plugin support override host with port, rel pr #2079
=> feat: proxy-rewrite host support host with port

apisix/cli/ngx_tpl.lua, benchmark/fake-apisix/conf/nginx.conf, t/APISIX.pm, t/node/http_host.t, t/plugin/hmac-auth.t, t/plugin/openid-connect.t
proxy_set_header Host $host may lose port info, use http_host instead.
=> fix: proxy_set_header Host $host may lose port info

.travis/apisix_cli_test/test_main.sh, apisix/cli/ngx_tpl.lua, apisix/cli/ops.lua, conf/config-default.yaml, doc/plugin-develop.md, example/apisix/plugins/3rd-party.lua, example/apisix/stream/plugins/3rd-party.lua
=> feat: allow customizing lua_package_path & lua_package_cpath

apisix/schema_def.lua, doc/admin-api.md, doc/zh-cn/admin-api.md, t/node/proxy_https.t
=> feat: support specifying https in upstream to talk with https backend

t/APISIX.pm
The buffer size in x86 is 8k while the one in arm64 is 16k.
Fix #3355
=> test: use the same buffer size across different platforms

t/lib/server.lua, t/plugin/proxy-rewrite.t
The output data of the plugin_proxy_rewrite_args method in the `apisix/t/lib/server.lua` file is messy. There should be an orderly output.
close #3403
=> test: sort the output data of the plugin_proxy_rewrite_args method

apisix/init.lua, apisix/upstream.lua, t/admin/upstream-array-nodes.t, t/admin/upstream2.t, t/discovery/eureka.t, t/node/invalid-route.t, t/node/upstream-domain.t
=> fix: upstream dns resolver failed response 503

apisix/balancer/ewma.lua, t/node/ewma.t
Details can be found in #3211 
* [] Have you added corresponding test cases?
* [] Have you modified the corresponding document?
Before
===
apisix: 1 worker + 200 upstream + no plugin
---
```
+ wrk -d 5 -c 16 http://127.0.0.1:9080/hello
Running 5s test @ http://127.0.0.1:9080/hello
2 threads and 16 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     1.65ms    1.53ms  32.40ms   97.65%
Req/Sec     5.26k   663.77     8.41k    79.21%
52974 requests in 5.11s, 211.22MB read
Requests/sec:  10369.65
Transfer/sec:     41.35MB
+ sleep 1
+ wrk -d 5 -c 16 http://127.0.0.1:9080/hello
Running 5s test @ http://127.0.0.1:9080/hello
2 threads and 16 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     1.82ms    1.99ms  30.06ms   96.26%
Req/Sec     5.10k   845.05 …
```
=> feat: ewma use p2c to improve performance

Makefile, apisix/cli/apisix.lua, apisix/cli/ngx_tpl.lua, bin/apisix, doc/install-dependencies.md, doc/zh-cn/install-dependencies.md
Signed-off-by: fukiki <one.fhh@163.com>
When run APISIX, use LuaJIT or Lua 5.1 by default. 
If the local lua version is not 5.1, use openresty-luajit as default.
Fix : #3281
=> fix: Use luajit by default when run APISIX CLI

.github/workflows/centos7-ci.yml, .travis/linux_openresty_common_runner.sh, .travis/linux_tengine_runner.sh, apisix/plugins/kafka-logger.lua, t/plugin/kafka-logger.t
When a topic has multiple partitions, the kafka-logger plugin creates a new producer instance to connect to kafka every time it pushes a message, which causes kafka to reallocate the partition each time, and all messages are placed in the same partition.
This PR reuse producer via lrucache to solve above problem.
fix #3384
=> feat: kafka-logger implemented reuse kafka producer

.github/workflows/chaos.yml
Originally chaos CI use personal repo. Now change it to api7's.
=> chore: use api7/etcd-operator in chaos CI

.github/workflows/build.yml, .travis/apisix_cli_test/test_etcd_tls.sh, .travis/apisix_cli_test/test_main.sh, .travis/linux_apisix_current_luarocks_runner.sh, .travis/linux_tengine_runner.sh, Makefile, apisix/cli/etcd.lua, doc/install-dependencies.md, rockspec/apisix-master-0.rockspec, utils/centos7-ci.sh, utils/install-apisix.sh, utils/linux-install-luarocks.sh, utils/linux-install-openresty.sh
This PR implements the SSL handshaking to etcd cluster in the APISIX command line tool, and it will obey the TLS configuration in `config.yaml`.
=> feat: support to communicate with etcd by TLS in command line

doc/plugins/api-breaker.md, doc/zh-cn/plugins/api-breaker.md
The document is inconsistent with the default parameters in the plugin `schema`. 
This PR mainly solves the problem of keeping the document consistent with the default parameters of the `schema`.
=> docs(api-breaker): the plugin docs is synchronized with the schema

Makefile
The same and more logic has been implemented in apisix cli, but Makefile still use the original one
https://github.com/apache/apisix/blob/6415b295594767e5698b355126ebcdd5e7a37e1b/apisix/cli/ops.lua#L436-L447
=> chore: sync 'ignore stale nginx.pid'(#3416) to Makefile

.travis/linux_openresty_common_runner.sh, apisix/core/utils.lua, rockspec/apisix-master-0.rockspec, t/core/utils.t, t/grpc-proxy-test.sh, t/node/upstream-node-dns.t, t/plugin/limit-count.t, utils/centos7-ci.sh, utils/set-dns.sh
=> feat: switch resolver to lua-resty-dns-client

t/chaos/kill-etcd_test.go
- Reduce waiting time in CI. #3447 only happens in my local environment, in CI it could works well.
- Make background visiting silent, to keep CI log tidy. Thanks for help from apache/apisix-dashboard#1388
=> chore: refine chaos test

.github/workflows/markdown-link-checker.yml
Due to the ASF's policies changing we cannot use the original GitHub Actions for linting as they are not approved.
Change Action to only rull on pull request.
This PR fixes our Markdown link checker.
=> fix(CI): roll our own Markdown link checker

.github/workflows/centos7-ci.yml, utils/centos7-ci.sh
test: modify apisix path for centos7 ci
=> test: make centos7 ci  easier to understand

apisix/plugins/zipkin.lua, apisix/plugins/zipkin/codec.lua, t/lib/server.lua, t/plugin/zipkin.t
According to
https://github.com/openzipkin/b3-propagation#sampling-state:
> sampling applies consistently per-trace: once the sampling decision is
made, the same value should be consistently sent downstream
We should pass the right x-b3-sampled according to our decision.
=> fix(zipkin): always delivery x-b3-sampled header

.travis/linux_openresty_common_runner.sh, apisix/core/utils.lua, t/APISIX.pm, t/core/etcd-auth-fail.t, t/core/etcd-auth.t, t/coredns/Corefile, t/coredns/db.test.local, t/node/upstream-domain-with-special-dns.t, utils/centos7-ci.sh, utils/set-dns.sh
=> feat: support DNS AAAA record

.github/workflows/markdown-link-checker.yml, .github/workflows/spellchecker.yml
~The original markdown-link-check use gaurav-nelson/github-action-markdown-link-check in github actions, which is not allowed for Apache project and aborted for a while. Replace it with install node.js and npm install markdown-link-check~ duplicate of #3197, reverted from this pr
There is no need to `spellcheck` for `push`, when `pull_request` already checked and merging branches won't affect that.
=> chore: remove spellcheck for `push`

apisix/plugins/zipkin.lua, apisix/plugins/zipkin/random_sampler.lua, t/plugin/zipkin.t
=> fix(zipkin): don't cache the per-req sample ratio

doc/plugins/error-log-logger.md, doc/zh-cn/plugins/error-log-logger.md
Fixes an extra '/' typo that was apart of the error-log-logger plugin docs 
Issue [#3473](https://github.com/apache/apisix/issues/3473)
=> docs: update the error-log-logger plugin docs

apisix/schema_def.lua
The default value of health check interval is `0`, while the minimum value is `1`.
=> fix: tweaked the unreasonable default health check interval values

.travis/apisix_cli_test/test_validate_config.sh, apisix/cli/ngx_tpl.lua, apisix/cli/ops.lua, apisix/core/utils.lua, apisix/init.lua, conf/config-default.yaml, t/coredns/db.test.local, t/node/upstream-domain-with-special-dns.t, t/node/upstream-node-dns.t
Since lua-resty-dns-client provides an internal cache, we don't need to
cache it twice.
=> change: default to cache DNS record according to the TTL

README.md, README_CN.md
Since from version 2.3, Apache APISIX needs to be installed OpenSSL develop library first to start.
=> docs: update README

apisix/api_router.lua, apisix/init.lua, apisix/plugin.lua, t/node/global-rule.t
this bug introduced by #3396.
should assign value to `api_ctx.global_rules` before running global rules, otherwise if a plugin exits in the access phase, global rules will not be able to run in the subsequent phases.
=> fix: should assign value to `api_ctx.global_rules` before running global rules

.github/workflows/fuzzing-ci.yaml, Makefile, doc/install-dependencies.md, doc/zh-cn/install-dependencies.md, utils/centos7-ci.sh, utils/linux-install-luarocks.sh, utils/linux-install-openresty.sh
We use luasec since 5399a31b, however, it uses the openssl libs and headers to compile itself, currently, we set two variables `$OPENSSL_LIBDIR` (e.g. `/usr/local/openresty/openssl/lib`) and `$OPENSSL_INCDIR` (e.g. `/usr/local/openresty/openssl/include`).
However, OpenResty 1.17.8 or higher version actually uses `openssl111` as the dir name of openssl. So in this PR, we detect the existence of dir `openssl111` and use it in precedence.
=> fix: use openssl111 in openresty dir in precedence

apisix/plugins/zipkin.lua, apisix/plugins/zipkin/codec.lua, t/plugin/zipkin2.t
=> feat(zipkin): support b3 req header

.github/workflows/chaos.yml, t/chaos/kill-etcd_test.go, t/chaos/utils.go
After #3614 got merged, chaos test is using `httpbin.org` as upstream, which could be unstable. Struggled some time with #3613 and suddenly found apisix inside kubernetes could not directly access localhost openresty...
So changed to deploy httpbin inside kubernetes, to make it stable
=> ci: use httpbin deployed in kubernetes to avoid unstability

t/plugin/key-auth-upstream-domain-node.t
The www.apiseven.com can't be accessed as soon as the Apple's domain.
As limit-count also hit the lrucache.plugin_ctx, we can remove limit-req
with it safely.
=> test: make key-auth-upstream-domain-node stable

apisix/cli/ngx_tpl.lua
close #3662 
Since APISIX and APISIX Dashboard are currently deployed independently of each other, the old /apisix/dashboard API interface is still retained in the ngx_tpl.lua file. We should delete it.
The reasons are as follows:
The /apisix/dashboard API interface is useless;
When users use the rpm package to install APISIX and APISIX Dashboard, there is a directory structure named dashboard in the directory structure of APISIX, which is easy for users to misunderstand that they need to use the `/apisix/dashboard` API interface to perform access.
=> chore: remove the useless configuration in the ngx_tpl.lua file

apisix/balancer.lua, apisix/balancer/chash.lua, t/admin/balancer.t, t/node/chash-balance.t, t/node/healthcheck.t
Previously the default number of retry is equal to the number of node,
but the same node will be tried again according to its weight.
Also ensure the same picker will be used in the whole request,
especially during the retry.
=> fix(chash): ensure retry can try every node

apisix/core/dns/client.lua, apisix/discovery/dns.lua, docs/en/latest/dns.md, t/coredns/db.test.local, t/discovery/dns/sanity.t
=> feat: support SRV record

apisix/control/v1.lua, t/control/schema.t
expose schema of `plugin_config` via control API,
Then, we can use the schema to verify the configuration of `plugin_config` in Dashboard.
=> chore: expose schema of `plugin_config` via control API

apisix/plugin_config.lua, t/node/plugin-configs.t
close #3674
Currently, the `item_schema` is not set for `plugin_config`, 
which causes the plugin configuration to not be validated when incrementally updated from ETCD (see: https://github.com/apache/apisix/blob/master/apisix/core/config_etcd.lua#L347), 
resulting in the default value of the plugin configuration not being set.
=> fix: validate plugins configuration of `plugin_config` via incremental sync

apisix/plugins/log-rotate.lua, apisix/plugins/proxy-cache.lua
You should always use the # operator to get the length of the Lua string instead of the string.len
according to:
https://yousali.me/openresty-best-practices/lua/string_library.html
=> chore: use the # operator to get the length of the Lua string

.github/workflows/chaos.yml, t/chaos/setup_chaos_utils.sh
fix #3625
Currently, chaos test use lastest docker image as apisix, so it's actually always runs on lastest release.
Since we could build docker from local code after https://github.com/apache/apisix-docker/pull/137 got merged, changed to run chaos on current change in PR.
=> ci: run chaos test on HEAD of PR

apisix/plugins/response-rewrite.lua, docs/en/latest/plugins/response-rewrite.md, docs/zh/latest/plugins/response-rewrite.md, t/plugin/response-rewrite.t
Allow user modify http reponse with conditional `vars`.
Eg:
1. we can rewrite response code 502 to 504 with this plugin, rather than write a new plugin
2. add special http header for request witch specific `vars`
3. drop`if` directives when transfer from nginx to APISIX
=> feat: support conditional response rewrite

docs/en/latest/config.json, docs/zh/latest/config.json
There are some missing docs plugins of apisix on the website.
We could find the missing plugins in the doc folder of the apisix repo, but they are not present on the website, because they are not added in the "config.json" file.
So this PR fixes the above issue, as all the missing plugins are added in the "docs/en/latest/config.json" and "docs/zh/latest/config.json" file.
Fix: https://github.com/apache/apisix-website/issues/236
=> docs: Missing plugins doc of apisix shown in website

apisix/plugins/consumer-restriction.lua, docs/en/latest/plugins/consumer-restriction.md, t/plugin/consumer-restriction.t
Fix for #3635 
Add the possibility to add `allowed_methods` for a user when `whitelist` is set.
This will restrict the user to only performed the HTTP action matching the list specified in `allowed_method.methods`
This is the format : 
```
"plugins": {
"key-auth": {},
"consumer-restriction": {
"whitelist": [
"jack1"
],
"allowed_methods":[{
"user": "jack1",
"methods": ["POST"]
}]
}
}
```
I choose to add a dedicated section instead of modifying the existing `whitelist` one because i think it's more readable. 
When nothing is set , then only the whitelist is applied .
And in order to set `allowed_methods` , `whitelist` is required.
Test case updated with 2 basics tests 
1. only allow `post` on resources and try to `get` the resource -> unauthorized
2. Add `get`capability to the user and try …
=> feat: Add filter on HTTP methods for consumer-restriction plugin

apisix/balancer.lua, apisix/balancer/chash.lua, apisix/balancer/ewma.lua, apisix/balancer/least_conn.lua, apisix/balancer/priority.lua, apisix/balancer/roundrobin.lua, apisix/schema_def.lua, apisix/upstream.lua, apisix/utils/upstream.lua, docs/en/latest/admin-api.md, docs/en/latest/control-api.md, docs/zh/latest/admin-api.md, t/admin/balancer.t, t/control/healthcheck.t, t/discovery/consul_kv.t, t/node/priority-balancer/health-checker.t, t/node/priority-balancer/sanity.t, t/node/upstream-discovery.t
=> feat: let balancer support priority

apisix/cli/etcd.lua, apisix/constants.lua, apisix/core/config_etcd.lua, apisix/core/config_yaml.lua, apisix/core/etcd.lua, apisix/init.lua, apisix/patch.lua, t/APISIX.pm, t/admin/plugins-reload.t, t/core/etcd-sync.t, t/core/etcd.t, t/misc/patch.t
=> feat: load etcd configuration when apisix starts

t/node/priority-balancer/sanity.t
=> test: make node/priority-balancer/sanity.t stable

apisix/patch.lua, t/APISIX.pm, t/misc/patch.t
=> fix: correct the luasocket patch

apisix/plugins/traffic-split.lua, t/plugin/traffic-split.t
fix: #3740 
the cause of the bug reference: https://github.com/apache/apisix/issues/3740#issuecomment-789852741
~~this change temporarily stores the route's `upstream_id` in the `matched_route` table. If the current request `match` fails and the temporarily stored `upstream_id` exists in the `matched_route` table, the route's `upstream_id` is restored to the temporarily stored `upstream_id`.~~
when the `route` is configured with an `upstream_id`, the `upstream_id` is passed into the `server_list`.
=> fix: the traffic-split plugin is invalid to bind upstream via upstream_id

t/control/discovery.t
Sometimes Eureka has injected the service when the test runs.
=> test: make control/discovery.t stable

apisix/plugin.lua, t/core/ctx.t
=> chore: the route_name and service_name in ctx should remain different

apisix/init.lua, apisix/plugins/traffic-split.lua, t/plugin/traffic-split.t
fix #3740
Related issues: #3787 
Because the current traffic-split plug-in supports `upstream_id` to refer to the upstream by rewriting the value of `ctx.matched_route.value.upstream_id`. However, when the upstream_id is used by the route and the plugin at the same time, the rewriting of `ctx` will cause the `upstream_id` on the original cached route to be lost.
Therefore, this PR creates a temporary variable of `ctx.upstream_id` to cache the upstream_id configured in the plug-in, avoiding the modification of `ctx.matched_route.value.upstream_id`.
=> fix(traffic-split): binding upstream via upstream_id is invalid

apisix/plugins/cors.lua, docs/en/latest/plugins/cors.md, docs/zh/latest/plugins/cors.md, t/plugin/cors.t
Fix #3763 
* [ x] Did you explain what problem does this PR solve? Or what new features have been added?
* [ x] Have you added corresponding test cases?
* [ x] Have you modified the corresponding document?
=> feat: add allow_origins_by_regex to cors plugin

apisix/control/router.lua, apisix/discovery/consul_kv.lua, docs/en/latest/discovery/consul_kv.md, t/core/utils.t, t/discovery/consul_kv_dump.t, t/node/invalid-route.t, t/node/route-domain.t
1. Add dump support for `consul_kv`, more intro:  https://github.com/yongboy/apisix/blob/consul_dump/docs/en/latest/discovery/consul_kv.md#dump_data
2. Avoid hard code discovery module's private control api fully URI 
Define the module's control api short path, eg `/show_dump_file`
```lua
function _M.control_api()
return {
{
methods = {"GET"},
uris = {"/show_dump_file"},
handler = show_dump_file,
}
}
end
```
And, when you access it,  you need to type it's fully URI:
```shell
GET /v1/discovery/{Module_Name}/show_dump_file
```
eg: 
```shell
GET /v1/discovery/consul_kv/show_dump_file
```
=> feat: add dump for consul_kv

apisix/plugins/error-log-logger.lua, t/plugin/error-log-logger.t
=> fix(error-log-logger): the logger should be run in each process

apisix/plugins/traffic-split.lua, t/plugin/traffic-split2.t
=> feat(traffic-split): the upstream pass_host needs to support IP mode

apisix/admin/proto.lua, apisix/admin/stream_routes.lua, apisix/schema_def.lua, t/admin/schema.t, t/admin/stream-routes.t, t/plugin/grpc-transcode.t
In order to facilitate management and viewing in the dashboard, we need to add response fields (create_time, update_time, desc) in the schema.
This PR is going to  add these fields and relevant test cases.
=> feat: add management fields for `stream_route` and `proto` in schema

docs/en/latest/router-radixtree.md
=> docs: add more example about how to use the router radixtree-uri

apisix/plugins/limit-count/limit-count-redis-cluster.lua, apisix/plugins/limit-count/limit-count-redis.lua
Use redis's eval() to ensure atomic operations of ttl and incrby, and solve the situation where a small number of requests are accidentally killed in high concurrency scenarios
使用redis的eval()确保ttl和incrby的原子性操作，解决高并发场景下少量请求被误杀的情况
=> fix: ensure automic operation in limit-count plugin

apisix/plugins/kafka-logger.lua, docs/en/latest/plugins/kafka-logger.md, docs/zh/latest/plugins/kafka-logger.md, t/plugin/kafka-logger.t
It's recommend to use async [producer_type](https://github.com/doujiang24/lua-resty-kafka#new-1). The performance of sync mode is very poor.
=> change(kafka-logger): send logs in async mode by default

apisix/patch.lua, docs/en/latest/admin-api.md, docs/zh/latest/admin-api.md, t/router/radixtree-uri-vars.t
=> fix: be compatible with the router created before 2.5

apisix/init.lua, t/node/route-domain.t, t/node/upstream-domain.t
=> fix: ensure upstream with domain is cached

docs/en/latest/FAQ.md, docs/en/latest/config.json, docs/es/latest/FAQ.md, docs/zh/latest/FAQ.md, docs/zh/latest/config.json
fix: [#310](https://github.com/apache/apisix-website/issues/310)
update FAQ by fixing broken  links
=> docs: fix broken links in FAQ

docs/en/latest/getting-started.md, docs/zh/latest/getting-started.md
=> docs: the link should be to dashboard instead of APISIX

apisix/plugins/traffic-split.lua, docs/en/latest/plugins/traffic-split.md, docs/zh/latest/plugins/traffic-split.md, t/plugin/traffic-split2.t
When the rules array object in the traffic-split plugin has multiple upstream conditions (weighted_upstreams + match), the request will be confused among multiple upstreams. The following example:
```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
"uri": "/hello",
"plugins": {
"traffic-split": {
"rules": [
{
"match": [
{
"vars": [
["http_id","==","1"]
]
}
],
"weighted_upstreams": [
{
"upstream": {
"name": "upstream_A",
"type": "roundrobin",
"nodes": {
"127.0.0.1:1981":1
}
},
"weight": 3
}
]
},
{
"match": [
{
"vars": [
["http_id","==","2"]
]
}
],
"weighted_upstreams": [
{
"upstream": {
"name": "upstream_B",
"type": "roundrobin",
"nodes": {
"127.0.0.1:1982":1
}
},
"weight": 3
}
]
}
]
}
},
"upstream": {
"type": …
```
=> fix(traffic-split): configure multiple "rules", the request will be confused between upstream

apisix/core/timer.lua, apisix/timers.lua, t/misc/timers.t
Previously we actually run background timer each second.
And the backgroud timer will be blocked if there is not timer registered
To be compatible, now we increase the interval to 1 second.
Fix #3923
=> fix: remove unexpected blocking in background timer

apisix/init.lua
Fix #4103 
* [√] Did you explain what problem does this PR solve? Or what new features have been added?
* [√] Have you modified the corresponding document?
=> fix(healthcheck): only one_loop is needed in the passive health check report

apisix/utils/log-util.lua, docs/en/latest/plugins/kafka-logger.md, docs/zh/latest/plugins/kafka-logger.md
Signed-off-by: libo.huang <huanglibo2010@gmail.com>
1. add server info to kafka log
```json
"server": {
"hostname": "localhost",
"version": "2.5"
}
```
=> feat(kafka-logger): add server info to kafka log

Makefile, apisix/plugins/ext-plugin-post-req.lua, apisix/plugins/ext-plugin-pre-req.lua, apisix/plugins/ext-plugin/helper.lua, apisix/plugins/ext-plugin/init.lua, conf/config-default.yaml, t/APISIX.pm, t/admin/plugins.t, t/debug/debug-mode.t, t/lib/ext-plugin.lua, t/plugin/ext-plugin/sanity.t
=> feat(ext-plugin): step 2, add basic structure

apisix/plugins/response-rewrite.lua, t/plugin/response-rewrite.t
Related to #4150, this PR is going to generate a proper error response when the `body` is a `nil` or an `empty` string. This would prevent APISIX from getting uncaught errors, as the error log mentioned in #4150.
=> fix(response-rewrite): properly base64 process the nil and empty body

apisix/core.lua, apisix/core/resolver.lua, apisix/core/utils.lua, apisix/init.lua, apisix/patch.lua, apisix/plugins/traffic-split.lua, t/misc/patch.t, t/node/route-domain-with-local-dns.t
=> feat: patch tcp.sock.connect to use our DNS resolver

docs/en/latest/how-to-build.md, docs/zh/latest/how-to-build.md
Also prefer to install via package instead of source.
The latter one is not so friendly for beginner.
=> docs: add more way to install APISIX

apisix/core/request.lua, apisix/plugins/ext-plugin/init.lua, rockspec/apisix-master-0.rockspec, t/lib/ext-plugin.lua, t/lib/server.lua, t/plugin/ext-plugin/http-req-call.t
=> feat(ext-plugin): implement the http-req-call protocol

apisix/cli/ngx_tpl.lua, apisix/init.lua, t/APISIX.pm, t/misc/patch.t
Since f914807, the connect of tcpsock was patched by using our own DNS
resolvers. It relies on a dns_resolvers variable which should be
initialized in init_by_lua* phase, however, the initialization step in
stream sub-system is missed so once users enable the stream proxy and
the tcpsock:connect is invoked with a non-IP host, Lua runtime errors
will be thrown.
This PR fixed this issue by initializing the DNS resolvers in the stream
sub-subsystem.
If we use the ETCD FQDN, we may see the following errors continuously.
=> fix: init dns resolvers in stream subsystem

.github/workflows/lint.yml, CONTRIBUTING.md, conf/config-default.yaml, conf/config.yaml, conf/debug.yaml, docs/en/latest/plugin-develop.md, t/APISIX.pm
Also remove helpless yaml lint.
Fix #3962
=> docs: avoid the misleading comment

apisix/plugins/prometheus/exporter.lua, t/plugin/prometheus3.t
=> fix: use original modifiedIndex if possible

apisix/cli/ops.lua, t/cli/test_dns.sh, t/node/upstream-domain-with-special-ipv6-dns.t
=> fix(DNS): support IPv6 resolver

docs/en/latest/getting-started.md, docs/zh/latest/getting-started.md
There are some errors in `docs/en/latest/getting-started.md`  and `docs/zh/latest/getting-started.md`, fix it.
=> docs: update document getting-started.md in en and zh

Makefile
use the environment variable HOMEBREW_PREFIX to determine the location of the brew command installer, to adapt this pr for homebrew https://github.com/Homebrew/install/pull/373/files
fix #4245
=> fix: making APISIX compatible on macOS with ARM chip

apisix/plugins/fault-injection.lua, t/plugin/fault-injection.t
refer to:
https://json-schema.org/understanding-json-schema/reference/array.html
In JSON Schema, it should use `items` to define the array item type, not `item`
=> fix: invalid schema field for plugin `fault-injection`

kubernetes/README.md
In the k8s deployment apisix document, add the deployment link of the helm chart method.
=> docs: add the helm chart link in the k8s deployment apisix doc

apisix/discovery/nacos.lua, apisix/schema_def.lua, ci/install-ext-services-via-docker.sh, docs/en/latest/discovery/nacos.md, t/discovery/nacos.t
=> feat: nacos discovery support namespace

t/chaos/go.mod, t/chaos/kill-etcd_test.go, t/chaos/kube_utils.go
After https://github.com/apache/apisix-docker/pull/176 got merged, chaos test could not directly read logs from `error.log`, but should read from kubernetes logs, since that PR forward `error.log` to docker logs interface.
=> ci: chaos test could not directly read error.log

apisix/cli/ngx_tpl.lua, conf/config-default.yaml, t/cli/test_main.sh
=> chore: support custom charset parameters in config.yaml

apisix/plugins/echo.lua, docs/en/latest/plugins/echo.md, docs/zh/latest/plugins/echo.md, t/plugin/echo.t
It can be done with key-auth plugin.
Fix https://github.com/apache/apisix/issues/3974
=> change(echo): remove odd auth_value

docs/zh/latest/admin-api.md
In the Chinese document, the tls client_key parameter name is now `update_time`, which is wrong. Correct should be `tls.client_key`.
=> docs: fix tls client_key parameter name of upstream request body in Chinese document

apisix/cli/ngx_tpl.lua, conf/config-default.yaml, t/cli/test_main.sh
Enable to set real_ip_recursive to nginx.conf. When apisix is behind multiple layer network, the real client ip may not be recognized. See also [http://nginx.org/en/docs/http/ngx_http_realip_module.html#real_ip_recursive](http://nginx.org/en/docs/http/ngx_http_realip_module.html#real_ip_recursive)
=> feat: add real_ip_recursive to nginx.conf

README.md, docs/en/latest/plugins/skywalking.md, docs/zh/latest/plugins/skywalking.md
Neither Zipkin nor SkyWalking is a part of OpenTracing ecosystem, especially when we speak from Nginx and LUA perspectives. Also, OpenTracing is being abandoned, their APIs are not widely used, and merged into OpenTelemetry, which also doesn't relate to the Nginx ecosystem. So, let's focus on the tech itself.
=> docs: Polish SkyWalking doc and a tiny thing about Zipkin

apisix/cli/ngx_tpl.lua, conf/config-default.yaml, t/cli/test_main.sh
When apisix is ​​in `make run`, it will prompt the following warning message:
```shell
$ make run
./bin/apisix start
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
nginx: [warn] could not build optimal variables_hash, you should increase either variables_hash_max_size: 1024 or variables_hash_bucket_size: 64; ignoring variables_hash_bucket_size
```
Therefore, this PR will add the `variables_hash_max_size` parameter to solve the above warning problem.
Since the value of `variables_hash_max_size: 1024` is not enough, set `variables_hash_max_size: 2048`
=> feat: support custom variables_hash_max_size parameters in config.yaml

apisix/cli/ops.lua, apisix/cli/util.lua, t/cli/test_main.sh
Ref: #4337 
When implementing with #2101, no error handling is implemented so with the invalid config file, apisix would still start without the correct config setup. Here to fix it.
One thing to mention, since I failed to figure out how to get stderr separately when running shell command in Lua, considering normally stdout of `ls` and `mv` would always be empty (on ubuntu), I forward stderr to stdout to get the error msg and fail fast. Not sure if it's working in all OS.
=> fix: add error handling when use customized config 

apisix/cli/ops.lua, ci/linux_apisix_master_luarocks_runner.sh
=> feat(cli): wrap nginx quit cmd

apisix/admin/consumers.lua, apisix/admin/plugin_config.lua, apisix/admin/proto.lua, apisix/admin/routes.lua, apisix/admin/services.lua, apisix/admin/ssl.lua, apisix/admin/stream_routes.lua, apisix/admin/upstreams.lua, apisix/admin/utils.lua, docs/en/latest/getting-started.md, docs/zh/latest/getting-started.md, t/admin/consumers2.t, t/admin/routes3.t, t/admin/ssl3.t, t/admin/upstream3.t
Here I use separate test files for the resources to ensure
the number of resource is 0.
=> fix(admin): correct the resources' count field

apisix/plugin.lua, apisix/stream/plugins/mqtt-proxy.lua, docs/en/latest/plugins/mqtt-proxy.md, docs/zh/latest/plugins/mqtt-proxy.md, t/stream-plugin/mqtt-proxy.t
=> feat(mqtt-proxy): support domain

apisix/cli/ngx_tpl.lua, apisix/cli/ops.lua, apisix/core/os.lua, apisix/init.lua, apisix/plugins/ext-plugin/init.lua, docs/en/latest/external-plugin.md, t/APISIX.pm, t/plugin/ext-plugin/runner_can_not_terminated.sh, t/plugin/ext-plugin/sanity-openresty-1-19.t, t/plugin/ext-plugin/sanity.t
=> feat(ext-plugin): stop the runner with SIGTERM

README.md, apisix/cli/ngx_tpl.lua, apisix/cli/ops.lua, apisix/init.lua, apisix/router.lua, ci/linux_apisix_current_luarocks_runner.sh, conf/config-default.yaml, docs/ar/README.md, docs/en/latest/admin-api.md, docs/en/latest/certificate.md, docs/en/latest/config.json, docs/en/latest/grpc-proxy.md, docs/en/latest/stream-proxy.md, docs/es/latest/README.md, docs/zh/latest/README.md, docs/zh/latest/admin-api.md, docs/zh/latest/certificate.md, docs/zh/latest/config.json, docs/zh/latest/grpc-proxy.md, docs/zh/latest/stream-proxy.md, t/APISIX.pm, t/cli/test_tls_over_tcp.sh, t/stream-node/tls.t, utils/create-ssl.py
=> feat(stream): accept tls over tcp

apisix/cli/ops.lua
I was reading APISIX code, and found some code could be simplified or reformat.
- simplify type check
- reformat indent
- remove unnecessary local var
This PR didn't solve any problems though.
None.
No addition features.
No docs related.
=> chore: using util lib to exectue cmd

apisix/cli/ngx_tpl.lua, apisix/cli/ops.lua, apisix/plugins/client-control.lua, apisix/upstream.lua, conf/config-default.yaml, docs/en/latest/config.json, docs/en/latest/plugins/client-control.md, t/APISIX.pm, t/admin/plugins.t, t/core/config.t, t/debug/debug-mode.t, t/lib/server.lua, t/plugin/client-control.t
=> feat(client-control): set client_max_body_size dynamically

README.md, docs/ar/README.md, docs/es/latest/README.md, docs/zh/latest/README.md
There is a link error in the For Developer section:
https://github.com/apache/apisix/blob/master/docs/en/latest/plugins.md
to
https://github.com/apache/apisix/tree/master/docs/en/latest/plugins
=> docs: fix broken link

docs/zh/latest/architecture-design/upstream.md
Fix error content in zh upstream.md.
The file is in the '/apisix/docs/zh/latest/architecture-design' directory, update '复杂均衡' to '负载均衡'.
=> docs: update error content in zh upstream.md

t/chaos/kill-etcd_test.go, t/chaos/utils.go
fix #4437 
Can not reproduce in the local environment. Try to make it stable by receiving more requests in a certain time period, to make bandwidth-per-second comparison more stable.
Also changed to egress bps comparison as measurement, since egress is what expected to be the same.
=> test: make t/chaos/kill-chaos.t stable

Makefile
I found HOMEBREW_PREFIX variable in Makefile is not assigned correctly, which leads to the error of 'make deps' operation on the Mac.
=> fix: modify the value of HOMEBREW_PREFIX in Makefile

apisix/cli/ops.lua, t/cli/test_control.sh
batch-requests plugin is working based on routing all the the request to 127.0.0.1:9080, if enable-control is on and port is the same with node_listen port, it will add configuration file like this：
```
server {
listen 127.0.0.1:9080;
access_log off;
location / {
content_by_lua_block {
local prometheus = require("apisix.plugins.prometheus")
prometheus.export_metrics()
}
}
}
```
this will cause all the 127.0.0.1:9080/* request route to this control api server, and all the expected  batch-requests  url return 404.
I add some force  check when batch-requests  is enabled.
=> feat(cli): check if control port conflicts with the node port

docs/en/latest/plugins/api-breaker.md, docs/zh/latest/plugins/api-breaker.md
The  minimum of `max_breaker_sec` should be `3` instead of `60`:
https://github.com/apache/apisix/blob/38785557bee818c3d8a3ca1d46f788fc65ab38ab/apisix/plugins/api-breaker.lua#L38-L41
=> docs: fix the valid value interval of `max_breaker_sec`

apisix/cli/ops.lua, t/cli/test_control.sh, t/cli/test_prometheus.sh
check node_listen, control, prometheus port listen conflicts
This pr is a further port conflict check between, node_listen, control, prometheus.
based on my previous pr: #4504
=> feat(cli): check listen port conflicts with each other

apisix/api_router.lua
has_route_not_under_apisix is wrongly assigned, which will  cause router strange  behaviour.
`has_route_not_under_apisix` is initiated to `false`, and fetch_api_router() method is iterating all the route api to find if exists some router api not start with "/apisix".
if the router list appear like this:
```
local api_routes = {
{ uri = "/foo/bar", },
{ uri = "/apisix/aa", },
}
```
has_route_not_under_apisix is first set to `true`, but second loop the value is set to `false`. which is toally wrong.
code is simplifed like this:
```
local api_routes = {
{ uri = "/apisi", },
{ uri = "/apisix/aa", },
}
local has_route_not_under_apisix = false
for _, route in ipairs(api_routes) do
local typ_uri = type(route.uri)
if typ_uri == "string" then
-- bug here, first loop: true, second loop: false …
```
=> fix: has_route_not_under_apisix value is wrongly assigned

apisix/core/ctx.lua, t/core/ctx.t
=> fix: ctx.var.cookie_* cookie not found log

docs/en/latest/getting-started.md, docs/zh/latest/getting-started.md
This change fixes the problems on 'getting-started' page both in Chinese and in English:
- Fix issue https://github.com/apache/apisix/issues/4554
- Added a summary section on the top of this page.
- Listed out 3-step procedure in summary section.
- To avoid calling one thing with multiple names, we decided to replace "Upstream" with "Upstream service", and replace "上游" and "后端服务" with "上游服务" (fixed after review comments), and call 'Route' "路由".
- Removed '$' in front of each code block, because it creates problem when users try to copy the codes or commands down, '$' is not a part of the command, but it gets copied down, it is annoying.
- Fixed some mix uses of punctuations，replaced (,./;'') with （，。、；’）.
- Fixed sections' titles. Titles usually should follow 'verb + noun(s)' pattern.
- …
=> docs: update CN and EN getting-started documents

apisix/cli/ngx_tpl.lua, conf/config-default.yaml, docs/en/latest/stream-proxy.md, docs/zh/latest/stream-proxy.md, t/cli/test_admin.sh, t/cli/test_dns.sh, t/cli/test_snippet.sh, t/cli/test_stream_config.sh
=> change: enable stream proxy only by default

apisix/init.lua, apisix/plugin.lua, apisix/plugins/skywalking.lua, docs/en/latest/plugin-develop.md, docs/zh/latest/plugin-develop.md, t/plugin/skywalking.t
=> fix(skywalking): handle conflict between global rule and route

docs/en/latest/getting-started.md, docs/en/latest/how-to-build.md, docs/zh/latest/getting-started.md, docs/zh/latest/how-to-build.md
This PR provides updates on the 'how-to-build' document in Chinese and English:
1. Changed the order of installation methods listed in ”2. 安装 Apache APISIX“, because the order was not the same as what were listed in the description, it should be in this order: 1. "通过源码包安装" --> 2. "通过RPM 包安装" --> 3. "通过Docker安装"--> 4. "通过Helm Chart安装". **In addition, it seems like the other method "Luarocks" is missing.** 
2. Refactored steps in"通过源码包安装", the steps were blended in two code blocks, they could be split to 5 steps and be clearer.
3. Wrapped up hyperlinks for Docker installation ("通过 Docker 安装") and Helm Chart installation sections(("通过 Helm Chart 安装") for better user experience. 
4.  Refactored "管理（启动、关闭等）APISIX 服务". Described the difference between `make quit` and `make stop`, and suggested …
=> docs: update CN and EN how-to-build document

apisix/ssl/router/radixtree_sni.lua, apisix/stream/router/ip_port.lua, t/APISIX.pm, t/stream-node/sni.t
Reuse TLS session won't run the ssl_certificate phase.
=> fix(stream): sni router is broken when session reuses

docs/en/latest/admin-api.md, docs/en/latest/mtls.md, docs/en/latest/plugin-develop.md, docs/en/latest/plugins/client-control.md, docs/en/latest/plugins/dubbo-proxy.md, docs/en/latest/plugins/gzip.md, docs/zh/latest/admin-api.md, docs/zh/latest/mtls.md, docs/zh/latest/plugins/dubbo-proxy.md
Backport https://github.com/apache/apisix/pull/4669 to release v2.8.
PR https://github.com/apache/apisix/pull/4577 and  https://github.com/apache/apisix/pull/4546 modified sections' titles in 'Getting Started' and 'How to build Apache APISIX' docs in EN and ZH. But the links from other files linked to some titles in these 2 docs were not modified accordingly. Thus, it creates broken links. For example, `how-to-build.md#6-build-openresty-for-apisix` should be `how-to-build.md#step-6-build-openresty-for-apache-apisix` instead. 
After checking, PR https://github.com/apache/apisix/pull/4546 did not introduce broken links, PR https://github.com/apache/apisix/pull/4577 introduced a lot of (10+) broken links. They were not technically 'broken broken', they can redirect to correct pages, but they …
=> docs: fix section titles' links

apisix/core/etcd.lua, t/admin/routes2.t, t/admin/services2.t, t/admin/ssl2.t, t/admin/stream-routes.t, t/admin/upstream2.t
When fetching resource list by the admin-api, some results include the basic id attribute (which created through the manager-api), but some results don't include it (which created through the admin-api). So set the basic id attribute when creating a resource by the admin-api in order to the result consistent.
=> feat: set the basic id attribute when creating a resource via POST

docs/en/latest/admin-api.md, docs/en/latest/mtls.md, docs/en/latest/plugin-develop.md, docs/en/latest/plugins/client-control.md, docs/en/latest/plugins/dubbo-proxy.md, docs/en/latest/plugins/gzip.md, docs/zh/latest/admin-api.md, docs/zh/latest/mtls.md, docs/zh/latest/plugins/dubbo-proxy.md
PR https://github.com/apache/apisix/pull/4577 and  https://github.com/apache/apisix/pull/4546 modified sections' titles in 'Getting Started' and 'How to build Apache APISIX' docs in EN and ZH. But the links from other files linked to some titles in these 2 docs were not modified accordingly. Thus, it creates broken links. For example, `how-to-build.md#6-build-openresty-for-apisix` should be `how-to-build.md#step-6-build-openresty-for-apache-apisix` instead. 
After checking, PR https://github.com/apache/apisix/pull/4546 did not introduce broken links, PR https://github.com/apache/apisix/pull/4577 introduced a lot of (10+) broken links. They were not technically 'broken broken', they can redirect to correct pages, but they cannot redirect to the right spot in these pages.
This PR fixed …
=> docs: fix broken links issues on section titles

CHANGELOG.md, apisix/core/version.lua, docs/ar/README.md, docs/en/latest/admin-api.md, docs/en/latest/config.json, docs/en/latest/how-to-build.md, docs/en/latest/mtls.md, docs/en/latest/plugin-develop.md, docs/en/latest/plugins/client-control.md, docs/en/latest/plugins/dubbo-proxy.md, docs/en/latest/plugins/gzip.md, docs/es/latest/README.md, docs/es/latest/config.json, docs/zh/latest/CHANGELOG.md, docs/zh/latest/admin-api.md, docs/zh/latest/config.json, docs/zh/latest/how-to-build.md, docs/zh/latest/mtls.md, docs/zh/latest/plugins/dubbo-proxy.md, rockspec/apisix-2.8-0.rockspec
=> feat: release 2.8

apisix/balancer.lua, apisix/init.lua, apisix/plugins/serverless/init.lua
It is confusing to have plugin's balancer method and user-defined
balancer.
=> change: rename plugin's balancer method to before_proxy

.github/workflows/code-lint.yml, .github/workflows/fuzzing-ci.yaml, utils/linux-install-luarocks.sh
For now, the package `luarocks` will be installed at `/usr/local` via `make install` command. If simply running the `curl https://raw.githubusercontent.com/apache/apisix/master/utils/linux-install-luarocks.sh -sL | bash -`, we will encounter an error due to privilege errors. For details, please refer to #4703. 
As discussed with @spacewander, we decide to add the `sudo` back via this PR. This would let users install APISIX without any interruptions.
With this patch merged in my environment, I could successfully install luarocks in CentOS 7 as both **non-root** and **root** users.
#4703
=> chore: add sudo privilege for make install command at installing luarocks

apisix/plugins/grpc-transcode.lua, apisix/plugins/grpc-transcode/request.lua, apisix/plugins/grpc-transcode/util.lua, ci/common.sh, t/plugin/grpc-transcode.t
=> fix(grpc-transcode): handle enum type

.github/workflows/build.yml
Currently with `concurrency` support in Github Actions, duplicate workflows would be canceled when commits uploaded. 
But the same situation also happens to master branch that, when two PR merged continuously, the CI of the first commit would be canceled, which looks like CI failed.
So try to fix it. Tested in personal repo: 
Commits in master branch would not be canceled. Only commits in non-master branch and PR would be canceled.
=> ci: should not cancel "duplicated" workflow in master branch

apisix/plugins/error-log-logger.lua, t/plugin/error-log-logger.t
=> fix(error-log-logger): avoid sending stale error log

apisix/plugins/ext-plugin/init.lua, t/lib/ext-plugin.lua, t/plugin/ext-plugin/http-req-call.t
If the plugin-runner sends a stop request but does not set an Http Status Code, APISIX will use 0 as the default status code, causing the current request to run later phases.
see: https://github.com/apache/apisix-java-plugin-runner/issues/55
=> fix(ext-plugin): avoid using 0 as the default http status code

apisix/core/lrucache.lua, apisix/plugins/ext-plugin/init.lua, rockspec/apisix-master-0.rockspec, t/lib/ext-plugin.lua, t/plugin/ext-plugin/sanity.t
=> feat(ext-plugin): send the idempotent key when preparing conf

apisix/admin/consumers.lua, t/admin/consumers2.t
fix https://github.com/apache/apisix/issues/4680
=> fix(admin): check username for updating consumer

apisix/admin/proto.lua, apisix/plugins/grpc-transcode/proto.lua, t/admin/proto.t
=> feat(admin): reject invalid proto

apisix/admin/global_rules.lua, apisix/admin/plugin_config.lua, apisix/admin/routes.lua, apisix/admin/services.lua, apisix/admin/ssl.lua, apisix/admin/upstreams.lua, apisix/admin/utils.lua, t/admin/upstream4.t
=> fix(admin): inject updatetime when the requst is PATCH with sub path

apisix/plugins/real-ip.lua, conf/config-default.yaml, docs/en/latest/config.json, docs/en/latest/plugins/client-control.md, docs/en/latest/plugins/gzip.md, docs/en/latest/plugins/real-ip.md, t/admin/plugins.t, t/core/config.t, t/debug/debug-mode.t, t/plugin/real-ip.t
=> feat(real-ip): implement the first version

apisix/plugins/gzip.lua, docs/en/latest/plugins/gzip.md, t/plugin/gzip.t
right now, type of types attr is array, and we dont't have a method to support the special `gzip_types *` config in Nginx Core. So maybe we can change type of types to support single string, and support * too.
=> feat(gzip): support special * to match any type

.github/workflows/centos7-ci.yml
The package name of apisix in CentOS7 has been added with the OS distribution name `el7`, see https://github.com/api7/apisix-build-tools/pull/67 for details. So this PR is going to change the relevant rpm name to `apisix-${version}-0.el7.x86_64.rpm` from the original `apisix-${version}-0.x86_64.rpm`. This PR will also fix the CI failures due to the stale package name.
=> ci: change centos7 package name with el7

.github/ISSUE_TEMPLATE/config.yml
I add question issue template, so we can jump to the APISIX discussion forum from the Issues.
=> feat: add question issue template

apisix/constants.lua, apisix/plugins/ext-plugin/init.lua, rockspec/apisix-master-0.rockspec, t/lib/ext-plugin.lua, t/plugin/ext-plugin/extra-info.t
=> feat(ext-plugin): support ExtraInfo

ci/centos7-ci.sh
Due to the `build-essentials`, `libncurses5-dev`, `libreadline-dev`, `libssl-dev` packages do not exist in CentOS 7, which leads to CI always complain about the following error. Although this error will not make CI CentOS 7 failed, it may mislead users to do the same action. So this PR will remove the installation of these four packages.
```
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
* base: mirror.dal.nexril.net
* extras: repos.lax.quadranet.com
* updates: mirror.vacares.com
No package build-essential available.
No package libncurses5-dev available.
No package libreadline-dev available.
No package libssl-dev available.
```
=> ci: Remove non-exist dependency packages for CentOS 7

apisix/plugins/authz-keycloak.lua, t/plugin/authz-keycloak.t
=> fix(authz-keycloak): set permissions as empty table when lazy_load_path is false

apisix/plugins/grpc-transcode/util.lua, ci/common.sh, t/plugin/grpc-transcode2.t
=> fix(grpc-transcode): support converting nested message

apisix/core.lua, apisix/init.lua, apisix/plugin.lua, t/node/global-rule.t
fix the issue that plugins in global rule may be cached to route
=> fix: the issue that plugins in global rule may be cached to route

.github/workflows/centos7-ci.yml, utils/linux-install-openresty.sh
The apisix CIs are using the master code of apisix-build-tools for building and packaging. While this would lead to unexpected errors if anything is incompatible. In other words, we should always rely on a stable version. This PR is going to use the `v2.0.0` of apisix-build-tools, which is also heading to the same commit with the latest code of the current master branch.
Related to https://github.com/api7/apisix-build-tools/issues/75.
=> chore: Use build-tools release v2.0.0 instead of the master branch

.github/workflows/centos7-ci.yml
Bump the apisix-build-tools to version v2.1.0, which supports the parameter `local_code_path` for packaging apisix. This PR also uses this new feature to reduce network/time costs in CI.
=> chore(ci): bump build-tools version to v2.1.0

apisix/plugins/referer-restriction.lua, docs/en/latest/plugins/referer-restriction.md, docs/zh/latest/plugins/referer-restriction.md, t/plugin/referer-restriction.t
add blacklist and message for referer-restriction plugin
=> feat(referer-restriction): add blacklist and message

apisix/init.lua, t/node/upstream-node-dns.t
It happened when we are handling upstream with domain inside a route.
Fix #4938
Fix #4941
=> fix: avoid copying unwanted data when the domain's IP changed

apisix/plugins/client-control.lua
to be consistent with with gzip and real-ip plugins' behavior.
=> chore(client-control): return 501 when APISIX-OpenResty missed

apisix/cli/ngx_tpl.lua, apisix/cli/ops.lua, conf/config-default.yaml, t/cli/test_admin.sh
Signed-off-by: wayne-cheng <zhengwei@tiduyun.com>
This is the next PR from https://github.com/apache/apisix/pull/4856#issuecomment-903388170
It's used to support configurating the admin listening address.
The config.yaml example as below：
```yaml
apisix:
admin_listen:            # use a separate port
ip: 127.0.0.2           # Specific IP, if not set, the default value is `0.0.0.0`.
port: 9180
#port_admin: 9180   # Not recommend: This parameter should be set via the `admin_listen`.
```
PTAL @spacewander
=> feat: support configuring admin specific IP

apisix/http/route.lua, apisix/http/router/radixtree_host_uri.lua, apisix/http/router/radixtree_uri.lua, apisix/http/router/radixtree_uri_with_parameter.lua, apisix/plugin.lua, apisix/schema_def.lua, docs/en/latest/admin-api.md, docs/zh/latest/admin-api.md, t/router/radixtree-host-uri2.t, t/router/radixtree-host-uri3.t, t/router/radixtree-uri-host.t, t/router/radixtree-uri-with-parameter.t
=> feat: allow route to inherit hosts from service

apisix/discovery/consul_kv.lua, t/discovery/consul_kv.t
=> fix(consul): retry connecting after a delay

apisix/discovery/dns.lua, t/coredns/db.test.local, t/discovery/dns/mix.t, t/discovery/dns/sanity.t
=> fix(DNS): prefer SRV in service discovery

apisix/ssl.lua, apisix/ssl/router/radixtree_sni.lua, apisix/stream/router/ip_port.lua, conf/config-default.yaml, t/router/radixtree-sni2.t, t/stream-node/sni.t
The fallback SNI works around cases that client doesn't send a SNI
during handshake.
By configuring a fallback SNI we can configure a fallback certificate
with the current SSL APIs.
Fix #3147
=> feat: allow configuring fallback SNI

docs/en/latest/getting-started.md, docs/zh/latest/getting-started.md
Since PR https://github.com/apache/apisix-docker/pull/216 got merged, this PR is going to add some guides for users to run Apache APISIX via docker compose in ARM64 architecture.
=> docs: Add ARM64 support for getting-started guide

apisix/cli/ngx_tpl.lua, apisix/cli/ops.lua, conf/config-default.yaml, t/cli/test_http_config.sh, t/cli/test_main.sh
The previous name is easy to mess up with another "lua_shared_dict"
configuration.
=> change: use a new name to customize lua_shared_dict in nginx.conf

apisix/balancer.lua, apisix/core/config_util.lua, t/core/config_util.t, t/node/upstream-keepalive-pool.t
=> fix(upstream): should not override default keepalive value

apisix/debug.lua, apisix/init.lua, apisix/plugin.lua, conf/config-default.yaml, conf/debug.yaml, docs/en/latest/architecture-design/debug-mode.md, docs/zh/latest/architecture-design/debug-mode.md, t/config-center-yaml/consumer.t, t/config-center-yaml/plugin.t, t/debug/debug-mode.t, t/debug/hook.t
move 'enable_debug' form config.yaml to debug.yaml, make the configuration of debug mode clear and central
=> change(debug): move 'enable_debug' form config.yaml to debug.yaml

apisix/cli/ngx_tpl.lua, apisix/cli/ops.lua, conf/config-default.yaml, docs/en/latest/plugin-develop.md, example/my_hook.lua, t/cli/test_main.sh
See https://github.com/apache/apisix/discussions/5029
=> feat: allow injecting logic to APISIX's method

apisix/ssl.lua, apisix/ssl/router/radixtree_sni.lua, t/router/radixtree-sni2.t
=> fix(ssl): match sni in case-insensitive way

apisix/admin/stream_routes.lua, apisix/stream/router/ip_port.lua, t/stream-node/sanity.t
=> feat(stream_route): support CIDR in ip match

.github/workflows/chaos.yml
A recent change in Chaos Mesh installation script make CI failed, and it's also risky to use the latest version compared to the released version.
=> ci: use chaos mesh released version but not latest

docs/en/latest/how-to-build.md
The descriptions of apisix commands in Step 3: Manage Apache APISIX Server are changed to apisix [action], please check the content, Thanks!
=> docs: update how-to-build step 3 to fix some descriptions of apisix commands

ci/install-ext-services-via-docker.sh
add DISCOVERY_PORT env for nacos service shell, fetch the https://github.com/api7/nacos-test-service/pull/2
=> test: add DISCOVERY_PORT env for nacos docker shell

apisix/http/router/radixtree_host_uri.lua, t/router/radixtree-host-uri3.t
=> fix(radixtree_host_uri): correct matched path

apisix/cli/env.lua, apisix/cli/ops.lua
Signed-off-by: rao yunkun <yunkunrao@gmail.com>
This PR is related with #2467
=> feat: add ulimit too small prompt

.github/workflows/centos7-ci.yml, utils/linux-install-openresty.sh
This PR is going to bump apisix-build-tools to `v2.2.1`, which contains:
- Bugfix: updating APISIX RPM building to fix overwriting the configuration files when updating the APISIX RPM, see https://github.com/api7/apisix-build-tools/pull/95.
- Feature: upgrading apisix_nginx_module_ver to 1.3.0, see https://github.com/api7/apisix-build-tools/pull/81.
=> chore: Bump build-tools version to v2.2.1

apisix/discovery/nacos.lua, t/discovery/nacos2.t
=> fix(nacos): continue to process other services when request failed

docs/zh/latest/admin-api.md, docs/zh/latest/mtls.md, docs/zh/latest/plugins/dubbo-proxy.md
The current Chinese documentation for `步骤6：为 Apache APISIX 构建 OpenResty` jump link looks like this:
The jump link does not jump to the `步骤6：为 Apache APISIX 构建 OpenResty`
After this PR is modified, it will look like this:
=> docs: fix error link of build apisix openresty

.github/workflows/centos7-ci.yml
As docker does not support `COPY` files outside from context. This PR is going to move the apisix for building under apisix-build-tools directory.
The testing has passed by pushing to a new branch `release/trpmfailure`, see https://github.com/apache/apisix/runs/3696433553.
=> ci: fix the rpm build

apisix/plugins/prometheus/exporter.lua
Fix #5146 
prometheus don't work as expected, change latency to zero when it's negative.
Signed-off-by: leslie tsang <leslie.tsang@icloud.com>
=> fix(prometheus): avoid negative latency caused by inconsistent Nginx metrics

docs/en/latest/how-to-build.md, docs/zh/latest/how-to-build.md
add command make install in case of `command not found`
=> docs: update how-to-build.md

apisix/init.lua, t/node/client-mtls.t
change `clent` to `client`
https://github.com/apache/apisix/blob/6096d7f9f72c64b9f290b282be37a51010d1e493/apisix/init.lua#L318
Signed-off-by: leslie tsang <leslie.tsang@icloud.com>
=> chore: fix typo in init.lua

.github/workflows/centos7-ci.yml, utils/linux-install-openresty.sh
This PR is going to bump apisix-build-tools to the latest v2.5.0. This new release fixed a critical bug which would lead to build out the incorrect APISIX rpm package. See the PR https://github.com/api7/apisix-build-tools/pull/125 which fixed the issues: https://github.com/api7/apisix-build-tools/issues/117 and https://github.com/api7/apisix-build-tools/issues/107.
It's noted that the v2.5.0 is backward compatible with v2.2.1 and v2.4.0, so no more changes here.
=> chore: Bump apisix-build-tools to v2.5.0

apisix/plugins/limit-count.lua, docs/en/latest/plugins/limit-count.md, docs/zh/latest/plugins/limit-count.md, t/control/services.t, t/plugin/limit-count-redis-cluster.t, t/plugin/limit-count.t, t/plugin/limit-count2.t
feat(limit-count): support multiple variables as key
=> feat(limit-count): support multiple variables as key

.github/workflows/centos7-ci.yml, apisix/plugins/traffic-split.lua, t/plugin/traffic-split5.t
=> fix(traffix-split): multiple rules with multiple weighted_upstreams under each rule cause upstream_key duplicate

apisix/plugins/ldap-auth.lua, t/plugin/ldap-auth.t
Signed-off-by: leslie <leslie.tsang@icloud.com>
Add handler for invalid basic auth header values.
Ref to #5411
=> fix(auth-ldap): add handler for invalid basic auth header values

apisix/discovery/nacos.lua
bug: if password contains "@" nacos discovery happens error #5373
Fix #5373
=> feat(nacos): be compatible with password contains @

apisix/admin/init.lua, apisix/admin/routes.lua, t/admin/routes3.t
=> fix(admin): modify boolean parameters with PATCH

apisix/core/ctx.lua, apisix/core/request.lua, docs/en/latest/router-radixtree.md, docs/zh/latest/router-radixtree.md, t/core/ctx2.t, t/core/request.t, t/node/vars.t
Support for POST form as matching conditions in advanced matching.
Fix #5399
=> feat: support advanced matching based on post form

apisix/init.lua
api_ctx.uri_parse_param is used when APISIXe still used the r3 router,
this table now no longer exists.
=> chore: remove legacy code

apisix/plugins/datadog.lua, docs/en/latest/plugins/datadog.md, t/plugin/datadog.t
As discussed offline with @spacewander, this PR adds an additional attribute in plugin schema `prefer_name` to provide the flexibility of choosing route/service id over the name (in case of name conflict/user preference).
=> feat: introducing prefer_name attribute in datadog plugin

docs/en/latest/plugins/datadog.md
Suggestion from: https://github.com/apache/apisix/pull/5372#discussion_r746370732
=> docs: custom configuration for datadog plugin

apisix/plugins/skywalking-logger.lua, conf/config-default.yaml, docs/en/latest/config.json, docs/en/latest/plugins/skywalking-logger.md, docs/zh/latest/config.json, docs/zh/latest/plugins/skywalking-logger.md, t/admin/plugins.t, t/plugin/skywalking-logger.t
provide a new logger plugin to support log access log to SkyWalking in SkyWalking Log Format. If skywalking trace plugin is enabled or requests with SkyWalking Trace context header, this plugin will parse the trace context header and print trace context in log. So that the access log can relate to trace.
=> feat: provide skywalking logger plugin

apisix/plugins/datadog.lua, apisix/plugins/prometheus/exporter.lua, apisix/utils/log-util.lua
- Separate utility method for latency calculation.
- Refactor datadog and Prometheus plugin to use the same
=> refactor: Method for latency calculation and related refactoring

apisix/plugins/wolf-rbac.lua, docs/en/latest/plugins/wolf-rbac.md, docs/zh/latest/plugins/wolf-rbac.md, t/plugin/wolf-rbac.t
1. `wolf` changed the port to 12180, because the old port 10080 is blocked by chrome browser. So `wolf-rbac` modified the port in the default address.
2. `wolf` supports ldap authentication, so `wolf-rbac` add the corresponding `authType` parameter description.
=> change(wolf-rbac): change default port number and add `authType` parameter to documentation

apisix/core/response.lua, t/core/response.t
=> fix: response.set_header should remove header like request.set_header

apisix/plugins/kafka-logger.lua, apisix/utils/log-util.lua, docs/en/latest/plugins/kafka-logger.md, docs/zh/latest/plugins/kafka-logger.md, t/plugin/kafka-logger.t
kafka logger supports logging request body 
fix #5343
=> feat(kafka-logger): supports logging request body

apisix/plugin.lua
=> fix: str concat in error call

apisix/plugins/azure-functions.lua, conf/config-default.yaml, docs/en/latest/config.json, docs/en/latest/plugins/azure-functions.md, t/APISIX.pm, t/admin/plugins.t, t/lib/test_admin.lua, t/plugin/azure-functions.t
=> feat(plugin): azure serverless functions

apisix/wasm.lua, docs/en/latest/wasm.md, t/wasm/response-rewrite.t, t/wasm/response-rewrite/main.go
=> feat(wasm): run in http header_filter

apisix/plugin.lua, t/cli/test_admin.sh
changes of /apisix/plugins/ in etcd would make chaos with plugin
loading, only the init_etcd phase actually modifies this key, but this
key should be ignored.
=> fix: ignore changes of /apisix/plugins/

.github/workflows/build.yml, Makefile
The env name is changed by accident during the Makefile refactor
=> ci: fix the broken VERSION env

apisix/plugins/google-cloud-logging.lua, apisix/plugins/google-cloud-logging/oauth.lua, t/lib/server.lua, t/plugin/google-cloud-logging.t
Set the type and token of the write log according to the token type in the Google Oauth response.
https://developers.google.com/identity/protocols/oauth2/openid-connect#exchangecode
=> feat(google-cloud-logging): set token type based on the Oauth response

apisix/plugins/ext-plugin/init.lua, t/lib/ext-plugin.lua, t/plugin/ext-plugin/request-body.t
=> feat(ext-plugin): support to get request body

Makefile, utils/gen-vote-contents.sh
When there is a new version ready to be released and need to vote on the mailing list, the information of the email content sometimes will be wrong, in order to reduce the probability of the wrong content of the email, I wrote a small script to automatically generate the email content, you can go directly to the release directory after the execution of VERSION=x.y.z make release-src and paste the automatically generated content to initiate a mailing list poll
=> feat: add gen-vote-content script

docs/en/latest/plugins/azure-functions.md
Suggestion from: https://github.com/apache/apisix/pull/5594#discussion_r758179470
=> docs: minor update in azure faas http2 documentation

apisix/core/log.lua, t/core/log.t
Currently APISIX `apisix.core.log` test case 6 don't work as expect, this PR fixes it.
Both test case config can pass the prove, which was unexpected.
```
=== TEST 6: print error log with prefix
--- config
location /t {
content_by_lua_block {
local log = require("apisix.core").log.new("test: ")
log.error("error log")
log.warn("warn log")
log.notice("notice log")
log.info("info log")
ngx.say("done")
}
}
--- log_level: error
--- request
GET /t
--- error_log
error log
--- no_error_log
test: warn log
test: notice log
test: info log
```
```
=== TEST 6: print error log with prefix
--- config
location /t {
content_by_lua_block {
local log = require("apisix.core").log
log.error("error log")
log.warn("warn log")
log.notice("notice log")
log.info("info log")
ngx.say("done")
}
}
--- log_level: error …
```
=> test(core.log): fix unit test case

apisix/plugins/log-rotate.lua
`USER1` is not a signal name. The description in the log is misleading. If you need to describe the signal in detail, can should use the description `User-defined signal 1` in the Man Manual instead of `USER1`
=> docs(log-rotate): fix typo

apisix/stream/plugins/mqtt-proxy.lua, docs/en/latest/plugins/mqtt-proxy.md, docs/zh/latest/plugins/mqtt-proxy.md, t/stream-plugin/mqtt-proxy.t
=> feat(mqtt-proxy): support using route's upstream

t/misc/patch.t
Once we can connect it, we know the address is resolved by ourselves.
=> test: we don't need to check the response of http://apisix.apache.org

apisix/plugins/datadog.lua, apisix/plugins/google-cloud-logging.lua, apisix/plugins/http-logger.lua, apisix/plugins/kafka-logger.lua, apisix/plugins/skywalking-logger.lua, apisix/plugins/sls-logger.lua, apisix/plugins/syslog.lua, apisix/plugins/tcp-logger.lua, apisix/plugins/udp-logger.lua
=> fix(batch-processor): we didn't free stale object actually

apisix/cli/file.lua, conf/config.yaml, t/cli/test_main.sh
Thanks for review my first pull request for apisix.
And this is my first time use lua. Give me some advices if possible, thanks.
This is about read default value when ENV not set, I think this may helpful when using k8s in different environment and did not want to set so many ENV variable
result:
etcd.host = http://${{ETCD_HOST}}:2379
etcd.host = http://${{ETCD_HOST:123ss}}:2379
etcd.host = http://${{ETCD_HOST:123ss:123aa}}:2379
=> feat: support resolve default value when environment not set

apisix/plugins/log-rotate.lua, t/plugin/log-rotate.t, t/plugin/log-rotate2.t
FIX #5658 
FIX #5663 
`Before FIX: ` rename log -> compression log -> nginx reopen
`After FIX: ` rename log -> nginx reopen  -> compression log
refer to:
https://nginx.org/en/docs/control.html#logs
=> fix(log-rotate): after enabling compression collect log exceptions

docs/en/latest/architecture-design/global-rule.md, docs/zh/latest/architecture-design/global-rule.md
Global rule doc mistakenly define the scope of plugin.
resolve #4895
=> docs(global_rule): update global rule description

docs/en/latest/plugins/ldap-auth.md
Ldap-auth plugin docs are missing parameters when configuring Consumer.
see https://apisix.apache.org/docs/apisix/plugins/ldap-auth/
And ldap-auth implementation is here https://github.com/apache/apisix/blob/master/apisix/plugins/ldap-auth.lua#L40-L47 
resolve #5668
=> docs(ldap-auth): add consumer parameters for ldap

.github/workflows/cli-master.yml
This test can't be passed outside the master branch.
=> ci: remove linux_apisix_master_luarocks from the CI on release branch

apisix/cli/ngx_tpl.lua, conf/config-default.yaml, t/cli/test_snippet.sh
Fix #5596
Not just custom variables, such as: opentracing_propagate_context
=> feat: add http_server_location_configuration_snippet configuration

rockspec/apisix-master-0.rockspec
the known issue of lua-resty-rocketmq fail to start if worker pid is greater than 65535 is fixed in https://github.com/yuz10/lua-resty-rocketmq/commit/6e0d19ab8b62552a2cdc1bcbf05766b9cfb4694d
=> fix: bump lua-resty-rocketmq to 0.2.1-3

apisix/plugins/consumer-restriction.lua, docs/en/latest/plugins/consumer-restriction.md, docs/zh/latest/plugins/consumer-restriction.md, t/plugin/consumer-restriction.t
consumer-restriction plugin add reject_message parameter support user to custom define return message when request rejected.
=> feat(consumer-restriction):  customize rejected_msg

rockspec/apisix-master-0.rockspec
fix the lua-resty-rocketmq module crash after send more than 65535 messages.
see https://github.com/yuz10/lua-resty-rocketmq/commit/027d4382a836a10bda9200a8c644f45b8c111a38
=> fix: bump lua-resty-rocketmq to 0.3.0-0

apisix/cli/ngx_tpl.lua, conf/config-default.yaml, t/cli/test_access_log.sh
=> feat: enable L4 stream logging

docs/en/latest/admin-api.md, docs/en/latest/stream-proxy.md
=> docs: improve stream proxy filtering with example

docs/en/latest/plugins/mqtt-proxy.md
added "only:false" if http and stream proxy functionality is needed
For clearer documentation purposes and in reference to the general documentation of stream proxy.
=> docs: added only: false to example

apisix/plugins/ext-plugin/init.lua
ext_plugin an expired key in lrucachd that could not find in go runner。
patch for [#5309](https://github.com/apache/apisix/pull/5309)
=> fix(ext-plugin): don't use stale key

apisix/stream/plugins/mqtt-proxy.lua, t/stream-plugin/mqtt-proxy.t
=> fix(mqtt-proxy): client id can be empty

apisix/plugins/slslog/rfc5424.lua, t/plugin/sls-logger.t
log entry unable get millisecond timestamp
=> fix(sls-logger): log entry unable get millisecond timestamp

docs/en/latest/how-to-build.md, docs/zh/latest/how-to-build.md
Signed-off-by: 123liubao <chenly_61@163.com>
add offline installation for how-to-build.md
resolve https://github.com/apache/apisix/issues/5785
=> docs: add offline install to 'how-to-build.md'

utils/install-dependencies.sh
The execution of `install-dependencies.sh` shouldn't be interrupted, add `-y` to fix it.
=> fix(install-dependencies): the execution of the script should not be interrupted

docs/zh/latest/admin-api.md, docs/zh/latest/stream-proxy.md
1. sync stream proxy Chinese version
Ref PR #5783
=> docs: sync stream proxy Chinese version

docs/zh/latest/plugins/request-id.md
Fix typo in Chinese request-id plugin document.
'request-id' plugin attribute named 'include_in_response' default value is true, not false.
lua code:
``` lua
local schema = {
type = "object",
properties = {
header_name = {type = "string", default = "X-Request-Id"},
include_in_response = {type = "boolean", default = true},
algorithm = {type = "string", enum = {"uuid", "snowflake"}, default = "uuid"}
}
}
```
source code: [https://github.com/apache/apisix/blob/master/apisix/plugins/request-id.lua](https://github.com/apache/apisix/blob/master/apisix/plugins/request-id.lua)
English version document:
=> docs(request-id): fix typo in request-id plugin zh document.

apisix/cli/ngx_tpl.lua, docs/en/latest/stream-proxy.md, docs/zh/latest/stream-proxy.md, t/cli/test_core_config.sh, t/cli/test_dns.sh, t/cli/test_stream_config.sh
For development, this change let us don't need to specify `only:
false` additionally.
For DP which is used as L4 proxy, this change won't bring any
difference.
Also it makes the documentation of stream plugin simpler.
=> change: enable HTTP when stream proxy is set and enable_admin is true

apisix/plugins/limit-count.lua, docs/en/latest/plugins/limit-count.md, docs/zh/latest/plugins/limit-count.md, t/plugin/limit-count-redis2.t, t/plugin/limit-count2.t
=> feat(limit-count): allow sharing counter

apisix/stream/plugins/mqtt-proxy.lua, t/stream-plugin/mqtt-proxy.t
=> fix(mqtt): handle properties for MQTT 5

apisix/control/router.lua, docs/en/latest/control-api.md, docs/zh/latest/control-api.md
This PR resolves issue #5882 by adding the following configuration to the `config.yaml` to enable path parameter support for the control api in the plugins
```yaml
apisix:
router:
control: 'radixtree_uri_with_parameter'
```
=> feat: support to use path parameter with plugin's control api

apisix/plugins/jwt-auth.lua, t/plugin/jwt-auth.t
=> chore(jwt-auth): get JWT by ctx.var.cookie_jwt instead of resty.cookie

.github/workflows/chaos.yml, apisix/cli/ngx_tpl.lua, apisix/plugins/proxy-mirror.lua, t/APISIX.pm
Fix #5347
By avoiding creating subrequest, we also speed up the route without
proxy-mirror > 5%.
=> feat: allow setting proxy_request_buffering without disabling proxy-mirror

utils/install-dependencies.sh
Add separately install support for [install-dependencies.sh](https://github.com/apache/apisix/blob/master/utils/install-dependencies.sh)
fix #5795 
> Now we can install via
```bash
./utils/install-dependencies.sh install_etcd
```
=> feat: add separately install support for `install-dependencies.sh`

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
=> chore: only reviewer can mark the review resolved

docs/en/latest/plugins/mqtt-proxy.md
added some explanations for the usage of the mqtt proxy and removed the remote_addr key from the json example configuration
The PR is needed to make the configuration of the mqtt proxy more clearer.
=> docs: added some explanations for the usage of the mqtt proxy

CHANGELOG.md, docs/zh/latest/CHANGELOG.md, rockspec/apisix-2.10.3-0.rockspec
Update `rockspec` and `CHANGELOG` for version 2.10.3. And updates related to version code and documentation will be provided in the PR of `release/2.10` to prevent affecting the master branch.
=> feat: release 2.10.3

apisix/plugins/serverless/init.lua, docs/en/latest/plugins/serverless.md, docs/zh/latest/plugins/serverless.md, t/admin/schema.t, t/plugin/serverless.t
It seems this is miss during the previous rename action.
=> change(serverless): rename "balancer" phase to "before_proxy"

.github/workflows/centos7-ci.yml, apisix/cli/ngx_tpl.lua, apisix/schema_def.lua, apisix/upstream.lua, docs/en/latest/admin-api.md, docs/en/latest/stream-proxy.md, docs/zh/latest/admin-api.md, docs/zh/latest/stream-proxy.md, t/APISIX.pm, t/stream-node/upstream-tls.t, utils/linux-install-openresty.sh
=> feat(L4): support TLS over TCP upstream

apisix/utils/batch-processor.lua, t/plugin/prometheus3.t
fix https://github.com/apache/apisix/issues/6011
=> fix: the prometheus lables are inconsistent when using the same batch-processor instance on multi plugins

apisix/plugins/proxy-control.lua, conf/config-default.yaml, docs/en/latest/config.json, docs/en/latest/plugins/proxy-control.md, t/admin/plugins.t, t/plugin/proxy-control.t
=> feat: set proxy_request_buffering dynamically

docs/en/latest/customize-nginx-configuration.md, docs/zh/latest/customize-nginx-configuration.md
the indent of `nginx_config` and sub indent of the sub entries need to be especially noted because there are many nginx configure variables in various format, which makes easy to mistake when configuring nginx_config.
this PR reduced some None critical info of this [old PR](https://github.com/apache/apisix/pull/6122) and [this issue](https://github.com/apache/apisix/issues/6072)
=> docs: add notice on customize-nginx-configuration docs

apisix/plugins/datadog.lua
Signed-off-by: Bisakh Mondal <bisakhmondal00@gmail.com>
The latency details has already been a part of `log_util.get_full_log` @ #6063
=> chore: remove redundant latency code from datadog plugin

apisix/plugin.lua, t/node/merge-route.t
=> fix: add missing labels after merging route and service

apisix/admin/global_rules.lua, apisix/admin/plugin_metadata.lua, t/admin/global-rules2.t, t/admin/plugin-metadata2.t
Correct the count field of plugin-metadata. please see [comment](https://github.com/apache/apisix/issues/6105#issuecomment-1012855448)
=> fix(admin): correct the count field of plugin-metadata/global-rule

apisix/init.lua, apisix/plugins/public-api.lua, conf/config-default.yaml, t/admin/plugins.t, t/plugin/plugin.t, t/plugin/public-api.t
=> feat: add public api plugin

apisix/plugins/grpc-transcode/proto.lua, apisix/plugins/grpc-transcode/util.lua, t/plugin/grpc-transcode2.t
=> fix(proto): avoid sharing state

apisix/plugins/opentelemetry.lua, conf/config-default.yaml, docs/en/latest/config.json, docs/en/latest/plugins/opentelemetry.md, docs/zh/latest/config.json, docs/zh/latest/plugins/opentelemetry.md, rockspec/apisix-master-0.rockspec, t/plugin/opentelemetry.t
Add opentelemetry plugin.
Fix #3891
=> feat: add opentelemetry plugin

conf/config-default.yaml, t/admin/plugins.t, t/debug/debug-mode.t
Actually it should be disabled in 0aa97c30f7741eeeb341eed0795c3bd0ef1b7556
=> fix(batch-requests): should be disabled by default

ci/linux_apisix_current_luarocks_runner.sh, ci/linux_apisix_master_luarocks_runner.sh
We should compare with the current installation, not the master one.
This bug is introduced in https://github.com/apache/apisix/pull/6192
=> test: fix way to check file installation

apisix/plugins/datadog.lua, apisix/plugins/loggly.lua, apisix/utils/batch-processor.lua, docs/en/latest/batch-processor.md, docs/zh/latest/batch-processor.md, t/utils/batch-processor.t
Signed-off-by: Bisakh Mondal <bisakhmondal00@gmail.com>
Helpful where the batch processor entries can't be processed in one go (transactional) and an error occurs during the middle of the consumption. With this PR, the batch processor takes a hint from the consumer so that the already consumed entries don't get retried in the next run.
Use case: https://github.com/apache/apisix/pull/6113#discussion_r790424879, datadog plugin etc (where entries can't be processed as a bulk)
=> feat(batchprocessor): support partial consumption of batch entries

Makefile, docs/en/latest/how-to-build.md, docs/zh/latest/how-to-build.md
`make undeps` supports to uninstall dependent rocks.
use it in some cases:
- failed rocks after installed partial, clear then reinstall
- modify some rocks source codes, recover them, so purge and reinstall
#6226
=> build: purge all the dependent rocks

.github/workflows/chaos.yml, CHANGELOG.md, apisix/core/version.lua, apisix/plugins/batch-requests.lua, conf/config-default.yaml, docs/en/latest/config.json, docs/en/latest/how-to-build.md, docs/zh/latest/CHANGELOG.md, docs/zh/latest/config.json, docs/zh/latest/how-to-build.md, rockspec/apisix-2.12.1-0.rockspec, t/admin/plugins.t, t/debug/debug-mode.t, t/plugin/batch-requests2.t
=> feat: release 2.12.1

apisix/core/config_etcd.lua, t/core/etcd-sync.t
Discussion in mailing list: https://lists.apache.org/thread/pfkf88h7v515t29xh6csxhhfbhcbt77j
> I have a problem with APISIX and I hope I can discuss it with you.
> APISIX has a configuration item: `etcd.resync_delay`, the effect is to
pause for a while before launching the next watch request when the method
call of watch etcd returns an error.
I understand that this logic is to protect the etcd server from being
overloaded by uninterrupted retries by the client after an unintended
exception.
> I think this protection mechanism is reasonable, but one of the cases of
error is timeout error, which means that no event is generated for the
specified key within the time period of this watch (default 30s timeout),
this kind of error is expected, because usually the configuration of the
gateway …
=> fix(config_etcd): skip resync_delay while etcd watch timeout

.asf.yaml
In https://github.com/apache/apisix/pull/5940#discussion_r802593858,
during solving the merge conflict,
a bug which is fixed in https://github.com/apache/apisix/pull/6204 is
reintroduced.
The test is also changed so it can't catch up the regression.
That PR is approved before merging the master. Luckily, I am cautious
enough to start another turn of review.
We should not rely on the lucky or someone else's caution.
To prevent that from happening again, here we enforce the approval
should be applied with the final state.
=> ci: enforce request review on the final state

docs/en/latest/how-to-build.md, docs/zh/latest/how-to-build.md
Modify the en and en docs. The last PR only modified the EN docs.
Add the cpanm installation command.
Modified etcd startup command to add log output parameters.
Remove the "$" sign before each command.
=> docs: added cpanm installation commands and remove $ sign 

utils/install-dependencies.sh
if had installed `apache-apisix-repo` package on Centos7, no installation. 
then it could continue work on dependent packages' installation.
Fix #4502
=> build(install-deps): noops installed apisix-repo

apisix/plugins/traffic-split.lua, t/plugin/traffic-split5.t
fix https://github.com/apache/apisix/issues/6288
=> fix(traffic-split): failed to match rule when the first rule failed

apisix/plugins/proxy-rewrite.lua, t/plugin/proxy-rewrite3.t
when conf.headers are missing,conf.method can make effect
=> fix(proxy-rewrite): when conf.headers are missing,conf.method can make effect

apisix/core/string.lua, apisix/plugins/limit-count/limit-count-redis-cluster.lua, apisix/plugins/limit-count/limit-count-redis.lua
This PR compresses the `limit-count` plugin's redis lua script.
This will cut the cost of network traffic by about 15%.
=> feat: compresses the redis lua script in limit-count

apisix/plugins/prometheus/exporter.lua, docs/assets/other/json/apisix-grafana-dashboard.json, docs/en/latest/plugins/prometheus.md, docs/zh/latest/plugins/prometheus.md
=> change(prometheus): replace wrong apisix_nginx_http_current_connections{state="total"} label

apisix/cli/etcd.lua, conf/config-default.yaml
related [5158](https://github.com/apache/apisix/pull/5158).   users can configure  the time of retry
=> feat: support for configuring the number of etcd health check retries

apisix/core/ctx.lua, t/router/graphql.t
=> feat(graphql): support http get and post json request

rockspec/apisix-master-0.rockspec
=> fix(opentelemetry): batch_span_processor export zero length spans

apisix/core/request.lua, apisix/plugins/request-validation.lua, t/core/request.t
TODO: convert the remain `ngx.req.get_headers()[XXX]` to core.request.header(...)
=> fix: should not limit the header number

apisix/core/etcd.lua, apisix/core/json.lua, docs/en/latest/getting-started.md, docs/en/latest/internal/testing-framework.md, docs/zh/latest/getting-started.md, t/admin/consumers2.t, t/admin/global-rules2.t, t/admin/plugin-metadata2.t, t/admin/routes3.t, t/admin/ssl3.t, t/admin/upstream3.t
=> change(admin): empty nodes should be encoded as array

docs/en/latest/config.json, docs/en/latest/external-plugin.md, docs/en/latest/internal/plugin-runner.md, docs/zh/latest/external-plugin.md
=> docs(extern-plugin): the implementation of runner

apisix/plugins/request-validation.lua, t/plugin/request-validation.t
This PR allows the [request-validation](https://github.com/apache/apisix/blob/42e84e437f/docs/en/latest/plugins/request-validation.md) to validate more than 100 parameters in a request.
=> fix(request-validation): should not limit the urlencoded post args number

docs/en/latest/plugins/clickhouse-logger.md
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Resolved #6414
=> docs: translate Chinese to English in en clickhouse-logger

docs/en/latest/getting-started.md, docs/en/latest/how-to-build.md
Fixes #6380 
This PR fixes issues in the "Getting Started" and "Building Apache APISIX" pages.
- Adds internal hyperlinks
- Fixes typos
- Enhances readability and usability
=> docs: update "getting started" and "how to build" guides
