apache/apisix

- utils/install-dependencies.sh
In `ubuntu:18.04` docker image, I executed  `install-dependencies.sh` and then executed `linux-install-luarocks.sh` , but got an error saying unable to find unzip.
```
Configuring LuaRocks version 3.8.0...
Lua version detected: 5.1
Lua interpreter found: /usr/local/openresty/luajit/bin/luajit
lua.h found: /usr/local/openresty/luajit/include/luajit-2.1/lua.h
Could not find 'unzip'.
Make sure it is installed and available in your PATH.
configure failed.
```
So I want to add `unzip` into `install-dependencies.sh` script.
> fix: add unzip into ubuntu dependency install script

- rockspec/apisix-master-0.rockspec
Bugfix in `opentelemetry-lua`: spans exporter may panic when traceID is invalid.
> fix(opentelemetry): exporter may panic when trace id  is invalid.

- apisix/plugins/error-log-logger.lua
- docs/en/latest/plugins/error-log-logger.md
- docs/zh/latest/plugins/error-log-logger.md
- t/plugin/error-log-logger-clickhouse.t
Add error-log-logger supports clickhouse.
> feat(error-log-logger): add clickhouse for error-log-logger

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
1、The tag of the json code block in markdown should be 'json' instead of 'shell'
2、Adjusting file alignment to make the document more formal
> docs(style): fix json code block syntax

- docs/en/latest/plugins/forward-auth.md
- docs/zh/latest/plugins/forward-auth.md
> docs: fix forward-auth plugin doc

- t/lib/server.lua
- t/plugin/http-logger2.t
FIX https://the-asf.slack.com/archives/CUC5MN17A/p1646136677114399
> test(http-logger): fetch request and response body test case

- docs/en/latest/router-radixtree.md
- docs/zh/latest/router-radixtree.md
APISIX recently updated support for json and GET. This PR corresponds to this increase.
#6343
> docs: add latest content about GraphQL in APISIX

- apisix/plugins/ext-plugin/init.lua
- rockspec/apisix-master-0.rockspec
- t/lib/ext-plugin.lua
- t/lib/server.lua
- t/plugin/ext-plugin/http-req-call.t
This PR add the ability to call upstream server when change the response header. 
When we implement SSO, we can set and modify cookie in APISIX plugin layer and also call upstream at the same time.
This is refer to https://github.com/apache/apisix-go-plugin-runner/issues/67
ext-plugin-proto : https://github.com/api7/ext-plugin-proto/pull/26
apisix-go-plugin-runner : https://github.com/apache/apisix-go-plugin-runner/pull/68
> feat: add `rewrite:RespHeaders` and modify the upstream response headers via `request` implementation

- README.md
- docs/en/latest/wasm.md
- docs/zh/latest/README.md
Like iOS, WebAssembly is often called as Wasm but not WASM.
> docs(Wasm): use official name

- apisix/core/etcd.lua
- apisix/plugins/server-info.lua
- conf/config-default.yaml
- docs/en/latest/plugins/server-info.md
- docs/zh/latest/plugins/server-info.md
- t/plugin/server-info.t
Currently, server-info is refactored, so we should backport to 2.10 release. Because 2.10 is a LTS version.
> change: backport server-info to 2.10

- apisix/cli/file.lua
- apisix/core/config_yaml.lua
- t/cli/test_standalone.sh
- t/cli/test_yaml_config_variables.sh
Support for reading environment variables from yaml configuration files.
resolve https://github.com/apache/apisix/issues/5244
> feat: support for reading environment variables from yaml configuration files #5244

- conf/config-default.yaml
…e internal API (now exposed to the public using the public-api plugin)
> chore: remove unused option "global_rule_skip_internal_api"

- .github/workflows/centos7-ci.yml
The same option is already applied in build.yml
> ci: don't cancel other tests when a test fails

- apisix/plugins/prometheus.lua
- apisix/plugins/prometheus/exporter.lua
- t/plugin/prometheus2.t
- t/plugin/prometheus3.t
> fix(prometheus): conflict between global rule and route configure

- apisix/init.lua
- apisix/plugin.lua
- apisix/plugins/example-plugin.lua
- docs/en/latest/plugin-develop.md
- docs/zh/latest/plugin-develop.md
- t/plugin/example.t
Fix https://github.com/apache/apisix/issues/6601
> feat: add delayed_body_filter phase

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> ci: issue should be labeled only after triage

- apisix/plugins/request-validation.lua
- t/plugin/request-validation2.t
> fix(request-validate): handle duplicate key in JSON

- apisix/core/table.lua
- t/core/table.t
> fix: deepcopy doesn't copy the metatable

- apisix/plugins/log-rotate.lua
- t/plugin/log-rotate2.t
Bugfix in log-rotate: log-rotate can not rotate logs strictly hourly(or minutely)
FIX #6517
> fix(log-rotate): should rotate logs strictly hourly(or minutely)

- utils/linux-install-luarocks.sh
luarocks 3.4.0 is out of date, it will cause the follow error:
```
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
```
ref https://github.com/api7/lua-resty-radixtree/issues/107
So we need to update luarocks version to 3.8.0
> backport: update luarocks version to 3.8.0

- utils/install-dependencies.sh
Method `install_etcd` removed in #6588,  need to clean it up in `utils/install-dependencies.sh`
> chore: remove unused code in utils script

- apisix/api_router.lua
As the issue described in https://github.com/apache/apisix/issues/6620 , if I there is one plugin with wrong api routes info, the function fetch_api_router in api_router.lua would always report exception, and lead to internal error for the normal http request. This PR is to avoid such embarrassing situation.
Fixes #6620 (issue)
> fix: improve function fetch_api_router in api_router.lua

- apisix/plugins/authz-keycloak.lua
- docs/en/latest/plugins/authz-keycloak.md
- t/plugin/authz-keycloak.t
Support of password grant type for token generation (#6574)
Committing changes after adding new feature for generating token based on `user id/password` and also taking support of grant type `password`
feat: #6574
> feat: add support for password grant in keycloak plugin

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
> docs: modify the make install in how to build Apache APISIX doc

- apisix/plugins/forward-auth.lua
- docs/en/latest/plugins/forward-auth.md
- docs/zh/latest/plugins/forward-auth.md
- t/plugin/forward-auth.t
Add optional request method for forward-auth plugin, when it is `POST`, the request body will be send to the `authorization` service.
Fixes #6344
> feat: add optional request method for forward-auth plugin

- docs/en/latest/plugins/opentelemetry.md
Context: https://github.com/open-telemetry/opentelemetry.io/pull/1185
/cc @austinlparker
> docs: fix links to OpenTelemetry specification

- docs/zh/latest/plugins/opentelemetry.md
- Context: https://github.com/open-telemetry/opentelemetry.io/pull/1185
- This is the zh counterpart to #6711.
/cc @austinlparker
> docs(zh): fix links to OpenTelemetry specification

- apisix/plugins/basic-auth.lua
- apisix/plugins/ldap-auth.lua
- docs/en/latest/plugins/basic-auth.md
- docs/en/latest/plugins/ldap-auth.md
- docs/zh/latest/plugins/basic-auth.md
- t/plugin/basic-auth.t
- t/plugin/ldap-auth.t
about auth-plugin when have password and username hidding real message when password or username is not match
Fixes https://github.com/apache/apisix/issues/6703
> fix: hidding real message when password or username is error

- docs/en/latest/plugins/opentelemetry.md
- This PR is in support of https://github.com/open-telemetry/opentelemetry.io/pull/1185.
- It is a followup to https://github.com/apache/apisix/pull/6711#discussion_r834869409.
- Note that I did my best to figure out the intent of the original paragraph was based on a translation of the zh version of the page. Hopefully you see this as a correct improvement.
/cc @leslie-tsang @austinlparker @SergeyKanzhelev
> docs: opentelemetry plugin update to prose

- .github/workflows/code-lint.yml
- .github/workflows/doc-lint.yml
Target: Improving script `git ls-files` functionality and redundancy.
Changes: filter files with `git ls-files`, remove `grep`.
> chore(lint): filter files by git-ls-files and remove subcommand grep

- apisix/cli/env.lua
The current `env.lua` uses CMD `openresty` to launch the service, which causes the master process unable to handle the `USR2` signal properly.
This PR use __absolute__ path CMD to handle it.
> fix: `env.lua` should use absolute path

- ci/centos7-ci.sh
- ci/pod/docker-compose.common.yml
- docs/en/latest/FAQ.md
- docs/en/latest/how-to-build.md
- docs/zh/latest/FAQ.md
- docs/zh/latest/how-to-build.md
- utils/linux-install-etcd-client.sh
Upgrading etcd version to 3.5.2 for ci. This way we can test the compatibility of apisix with the latest version of etcd
> chore: upgrade etcd version to 3.4.18 for ci

- Makefile
- bin/apisix
- ci/centos7-ci.sh
- utils/install-dependencies.sh
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
`command -v` is the builtin shell cmd, the `which` can be replaced so that we don't need an extra dependency.
Fixes #6776
> feat: use `command -v` instead of `which` to find the installed path.

- .licenserc.yaml
Sets the license location threshold. This _should_ avoid errors thrown in PRs like these https://github.com/apache/apisix/runs/5973924648?check_suite_focus=true
See https://github.com/apache/apisix/pull/6775#discussion_r845818022 for context.
> chore: set the license location threshold

- apisix/plugins/ext-plugin/init.lua
- t/lib/ext-plugin.lua
- t/plugin/ext-plugin/http-req-call.t
add support for multi-header with same key like `set-cookie`
https://github.com/apache/apisix-go-plugin-runner/issues/74
> fix: add support for multi-header with same key

- apisix/plugins/jwt-auth.lua
- t/plugin/jwt-auth.t
The jwt-auth plugin's response body may leak secrets in error message
> fix: jwt-auth error may leak secret

- apisix/plugins/grpc-web.lua
- t/plugin/grpc-web.t
> fix(grpc-web): don't override Access-Control-Allow-Origin header in response

- apisix/plugins/jwt-auth.lua
- t/plugin/jwt-auth.t
Adjust the error log level in the `jwt-auth` plugin to warn
> chore(jwt-auth): adjust error log level to warn

- apisix/plugins/authz-keycloak.lua
- t/plugin/authz-keycloak.t
> fix(authz-keycloak): do not expose internal errors to the client

- apisix/cli/ops.lua
- t/cli/test_kubernetes.sh
Fix #6830 
Inject the env variable when k8s service discovery is enabled -> apisix/opt.lua
- [Y] I have explained the need for this PR and the problem it solves
- [Y] I have explained the changes or the new features added to this PR
- [Y] I have added tests corresponding to this change
> feat: inject kubernetes discovery environment variable

- apisix/plugins/basic-auth.lua
- apisix/plugins/ldap-auth.lua
- apisix/plugins/wolf-rbac.lua
- t/plugin/basic-auth.t
- t/plugin/ldap-auth.t
- t/plugin/wolf-rbac.t
> fix: do not expose internal errors to the client

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
Apache APISIX now support CentOS 8 repo, update the docs for it.
> docs(how-to-build): update centos repo support

- apisix/stream/xrpc/protocols/redis/init.lua
- apisix/stream/xrpc/runner.lua
- apisix/stream/xrpc/sdk.lua
- t/xrpc/apisix/stream/xrpc/protocols/pingpong/init.lua
- t/xrpc/pingpong.t
> feat(xRPC): basic stream support

- apisix/schema_def.lua
- apisix/stream/router/ip_port.lua
- apisix/stream/xrpc/protocols/redis/init.lua
- apisix/stream/xrpc/runner.lua
- apisix/stream/xrpc/sdk.lua
- t/xrpc/apisix/stream/xrpc/protocols/pingpong/init.lua
- t/xrpc/apisix/stream/xrpc/protocols/pingpong/schema.lua
- t/xrpc/pingpong.t
> feat(xRPC): support dynamic upstream

- apisix/init.lua
- apisix/ssl/router/radixtree_sni.lua
A more suitable way is to reject client TLS handshake directly, just
like what Go has done.
Fixes #6896
> fix: the client verify flag might not be set

- apisix/schema_def.lua
- t/APISIX.pm
- t/admin/upstream-array-nodes.t
- t/plugin/referer-restriction.t
Make a simple modification to make the upstream nodes host support ipv6
Fixes #6905
> fix: upstream nodes cant't include ipv6 addr

- apisix/init.lua
- apisix/stream/xrpc/sdk.lua
- apisix/upstream.lua
- apisix/utils/upstream.lua
- t/xrpc/apisix/stream/xrpc/protocols/pingpong/init.lua
- t/xrpc/pingpong.t
> feat(xRPC): support dynamic upstream with upstream_id

- apisix/plugins/wolf-rbac.lua
- t/plugin/wolf-rbac.t
Replace ngx.req.get_post_args to core.request.get_post_args, so that we can support more than 100 post args.
> chore: replace ngx.req.get_post_args to core.request.get_post_args

- apisix/plugins/ext-plugin/init.lua
- t/lib/ext-plugin.lua
- t/plugin/ext-plugin/http-req-call.t
The same fix to other headers.
I only found one place to fix and I think request headers not to fix. What else?
@spacewander 
https://github.com/apache/apisix/pull/6811#issuecomment-1096463034
> fix(ext-plugin): append resp header when multiple headers with the same name is given

- apisix/timers.lua
> chore: the second returned value of ngx.thread.wait is execution result but not err

- apisix/core/string.lua
- apisix/plugins/authz-keycloak.lua
Replace replace ngx.decode_args to core.string.decode_args, so that we can support more than 100 raw args.
> chore: replace ngx.decode_args to core.string.decode_args

- apisix/cli/env.lua
- apisix/cli/ops.lua
Allow apisix start when open file descriptors unlimited
> fix: allow apisix start when open file descriptors unlimited

- docs/zh/latest/plugins/jwt-auth.md
If '<>' is used in the document, the code block format is required. Otherwise, the official website will fail to build.
As follows:
> docs: fix code block format in jwt-auth doc

- apisix/cli/ops.lua
Using Lua library(penlight, luafilesystem) to do file system related operations.
* If shell command mkdir not exist, command `mkdir -p path` will failed.
* Avoid `mkdir` dependency, use penlight path library, it's a dependent library of APISIX.
> refactor(ops): penlight path instead of shell command mkdir

- apisix/stream/xrpc/sdk.lua
- t/xrpc/apisix/stream/xrpc/protocols/pingpong/init.lua
- t/xrpc/pingpong.t
- t/xrpc/pingpong2.t
> feat(xRPC): support timeout

- docs/en/latest/plugins/request-validation.md
- docs/zh/latest/plugins/request-validation.md
Signed-off-by: smile-luobin <luobin_smile@163.com>
fix bugs in doc of request-validation plugin
> docs: fix bugs in doc of request-validation plugin

- apisix/init.lua
> perf: avoid rematching SSL when our customized Nginx is used

- apisix/plugins/key-auth.lua
- docs/en/latest/plugins/key-auth.md
- docs/zh/latest/plugins/key-auth.md
- t/plugin/key-auth.t
As a user, I want to only change uri args or headers when hiding credentials in the `key-auth` plugin
When `hide_credentials` is set to `false` passes the request header or query string containing authentication information to the Upstream. If `true`, the corresponding header or query string will be deleted, depending on whether the key is obtained from the header or the query string.
Fixes #6940
> feat: just change uri args or headers when hiding credentials

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
- .github/workflows/chaos.yml
- .github/workflows/cli-master.yml
- .github/workflows/cli.yml
- .github/workflows/code-lint.yml
- .github/workflows/doc-lint.yml
- .github/workflows/fuzzing-ci.yaml
- .github/workflows/kubernetes-ci.yml
- .github/workflows/lint.yml
- .github/workflows/performance.yml
- .github/workflows/stale.yml
- .github/workflows/tars-ci.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> ci: Set permissions for GitHub actions

- apisix/init.lua
- conf/config-default.yaml
- t/router/radixtree-uri-sanity.t
> feat: add option to normalize uri like servlet

- .asf.yaml
Branch like https://github.com/apache/apisix/tree/release/2.3 is not
protected.
> ci: revert wildcard rule as it doesn't work

- docs/en/latest/how-to-build.md
- docs/zh/latest/how-to-build.md
Updated Chinese installation documentation.
This PR is only responsible for the internationalization and synchronization of English changes from https://github.com/apache/apisix/pull/6964.
> docs: upadate Chinese installation docs

- apisix/cli/ip.lua
- apisix/cli/ops.lua
- rockspec/apisix-master-0.rockspec
- t/cli/test_validate_config.sh
Handle `real_ip_from` CIDR format on plugin batch-requests when APISIX init.
* Add `cli.ip` module with lua-resty-mediador/ip.lua to verify
* Support loopback and unspecified(zeros) ip address
* Support IPv4 and IPv6
https://github.com/apache/apisix/blob/cc88a8db0ba64e1cb351e389ca5ec64c516073d6/apisix/cli/ops.lua#L279-L281
> feat(ops): handle real_ip_from CIDR format

- .ignore_words
- apisix/stream/xrpc/protocols/redis/commands.lua
- apisix/stream/xrpc/protocols/redis/init.lua
- apisix/stream/xrpc/protocols/redis/schema.lua
- apisix/stream/xrpc/runner.lua
- apisix/stream/xrpc/sdk.lua
- t/xrpc/redis.t
> feat(redis): delay according to the cmd & key

- apisix/plugins/api-breaker.lua
- docs/en/latest/plugins/api-breaker.md
- docs/zh/latest/plugins/api-breaker.md
- t/plugin/api-breaker.t
When upstream is in the unhealthy state, the api-breaker returns unhealthy.http_statuses only, without a response body.
In order to be more compatible to the client, return a default response body is useful.
Fixes #6923
> api-breaker plugin returns default response body

- apisix/plugins/opentelemetry.lua
- conf/config-default.yaml
- docs/en/latest/plugins/opentelemetry.md
- docs/zh/latest/plugins/opentelemetry.md
opentelemetry's default network port for OTLP/HTTP is 4318 not 4317.
The default network port for OTLP/gRPC is 4317.
> change(opentelemetry): the default network port for OTLP/HTTP is changed to 4318

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
- apisix/core/pubsub.lua
- t/pubsub/pubsub.t
According to the closed #6995 PR, there are some review comments on the pubsub module, fix it throughout the PR.
> chore: improve the implementation of pubsub module

- docs/en/latest/plugins/api-breaker.md
- docs/en/latest/plugins/proxy-cache.md
- docs/en/latest/plugins/proxy-mirror.md
- docs/en/latest/plugins/request-validation.md
Updates the documentation of the "proxy-cache", "request-validatoin", "proxy-mirror", and "api-breaker" Plugins.
> docs: update "Traffic" Plugin docs 2

- t/plugin/traffic-split.t
Improve ci(traffic-split) stability. HTTP status code check 200 instead of 502
> ci(traffic-split): improve ci stability

- apisix/stream/xrpc/runner.lua
> fix(xRPC): release ctx.var when ctx is done

- apisix/core/ctx.lua
- apisix/stream/xrpc/runner.lua
- docs/en/latest/apisix-variable.md
- docs/en/latest/xrpc.md
- t/xrpc/apisix/stream/xrpc/protocols/pingpong/init.lua
- t/xrpc/pingpong2.t
- t/xrpc/pingpong3.t
> feat(xrpc): register variable rpc_time

- apisix/balancer.lua
- t/node/upstream-keepalive-pool.t
> fix(upstream): keepalive should consider TLS param

- docs/en/latest/benchmark.md
- docs/zh/latest/benchmark.md
1. As described in the issue: https://github.com/apache/apisix/issues/5966#issuecomment-1006105454, I added @membphis's comment to the Benchmark page;
2. It seems currently we have both English version and Chinese version doc about benchmark:
- https://github.com/apache/apisix/blob/master/docs/en/latest/benchmark.md
- https://github.com/apache/apisix/blob/master/docs/zh/latest/benchmark.md
but the Chinese doc is missing some parts, so I translated them from the English version;
Fixes #5966
> docs: sync Chinese benchmark doc and add notes on running the benchmark

- apisix/stream/xrpc/protocols/redis/init.lua
- docs/en/latest/apisix-variable.md
- t/xrpc/redis2.t
> feat(xrpc): register variable redis_cmd_line

- apisix/core/pubsub.lua
- apisix/include/apisix/model/pubsub.proto
Add the default ping handler, which will be overridden when the user re-calls the on function to set the `cmd_ping` handler. There are already test cases for `cmd_ping` in the original tests.
> feat: add default handler for pubsub ping command

- bin/apisix
- utils/linux-install-luarocks.sh
> fix: make ci pass under OpenResty 1.21

- .asf.yaml
As discussed, now we decide to allow using rebase only when backport
multiple commits to the `release/xx` branch. Therefore we can preserve
the commit message.
> ci: enable rebase in some situation

- docs/en/latest/pubsub.md
Add pubsub develop documentation example for Apache Kafka.
> docs: add pubsub develop example for kafka

- .github/workflows/build.yml
- .github/workflows/cli-master.yml
- .github/workflows/cli.yml
- .github/workflows/kubernetes-ci.yml
- .github/workflows/tars-ci.yml
- ci/common.sh
- ci/linux_apisix_current_luarocks_runner.sh
- ci/linux_apisix_master_luarocks_runner.sh
- ci/linux_openresty_common_runner.sh
> chore(ci): apt update before install

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- apisix/plugins/redirect.lua
- bin/apisix
- ci/centos7-ci.sh
- conf/config-default.yaml
- docs/en/latest/config.json
- docs/en/latest/plugins/redirect.md
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/config.json
- docs/zh/latest/plugins/redirect.md
- rockspec/apisix-2.14.0-0.rockspec
- t/plugin/redirect.t
- utils/linux-install-luarocks.sh
> feat: release 2.14.0

- ci/common.sh
- t/plugin/file-logger-reopen.t
- t/plugin/prometheus2.t
- t/xrpc/redis.t
This commit addresses the problem with these actions:
1. increase the rerun limit
2. make sure the last reopen file is expired
3. increase redis delay to reduce the effect of the request latency
4. increase report time so the tcp-logger in prometheus test doesn't
report to TCP receiver as we don't have such a TCP receiver.
Fixes #7037
> test: reduce CI failure caused by flaky tests

- utils/install-dependencies.sh
- utils/linux-install-luarocks.sh
This commit addresses the problem with these issuse:
1. Missing wget on centos and fedora system.
2. luarocks was installed in /usr/local/bin，make sure /usr/local/bin is included in the system default PATH variable.
> fix: install dependencies issues

- apisix/cli/ops.lua
- t/cli/test_validate_config.sh
> fix(batch-requests): ignore "unix:" in the configuration

- apisix/plugins/proxy-cache/disk_handler.lua
- t/plugin/proxy-cache/disk.t
When request method mismatch `cache_method`, it will also bypass instread of reading cached data.
Fixes #7096
> fix(proxy-cache): bypass when method mismatch cache_method under disk strategy

- apisix/balancer/chash.lua
- apisix/core.lua
- apisix/core/dns/client.lua
- apisix/core/math.lua
- t/node/chash-balance.t
Unlike the planned, I choose to do the gcd in APISIX because in this way
we don't need to take care of dynamically resizing.
Fixes #7042
> fix: reduce memory usage when abnormal weights are given in chash

- t/cli/test_main.sh
This should avoid "logs/nginx.pid: No such file or directory" error
which causes ci failures in:
https://github.com/apache/apisix/runs/6585253041?check_suite_focus=true
https://github.com/apache/apisix/runs/6565320107?check_suite_focus=true
> test: make sure the nginx.pid is written

- ci/common.sh
> ci: ignore releases.hashicorp.com's new certificate which can't be verified in CentOS7

- apisix/plugin.lua
- apisix/schema_def.lua
- docs/en/latest/terminology/plugin.md
- docs/zh/latest/terminology/plugin.md
- t/admin/plugins.t
- t/plugin/plugin.t
> feat: allow customizing response in the plugin

- docs/en/latest/plugin-develop.md
- docs/zh/latest/plugin-develop.md
When developing plug-ins, I didn't pay attention to the user-defined path of plug-ins, resulting in no plug-ins found during testing. The original document didn't clearly remind this directory structure.
The modified content is to add a path prompt description to the document file
Fixes #6743
- [✅] I have explained the need for this PR and the problem it solves
- [✅] I have explained the changes or the new features added to this PR
- [✅ ] I have added tests corresponding to this change
- [✅ ] I have updated the documentation to reflect this change
- [✅] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)
> docs:update "plugin-develop"(#6743)

- apisix/plugins/prometheus/exporter.lua
- apisix/stream/xrpc.lua
- apisix/stream/xrpc/metrics.lua
- apisix/stream/xrpc/protocols/redis/init.lua
- apisix/stream/xrpc/protocols/redis/metrics.lua
- apisix/stream/xrpc/sdk.lua
- docs/en/latest/xrpc.md
- docs/en/latest/xrpc/redis.md
- t/xrpc/prometheus.t
> feat(redis): add metrics

- apisix/cli/ngx_tpl.lua
- apisix/cli/ops.lua
The http_stub_status_module is required in fact, as:
1. missing this module will generate "failed to fetch Nginx status" error:
https://github.com/apache/apisix/blob/a99eb64f23737a8796606f48b851e27be52a3e6e/apisix/plugins/prometheus/exporter.lua#L245
2. both OpenResty and APISIX-Base already contains this module
Therefore I decide to remove the additional check to make code simpler.
> chore: require http_stub_status_module exists

- apisix/plugins/response-rewrite.lua
- t/plugin/response-rewrite2.t
Fixes Bug of #6750, schema format incorrect. And more sanity test cases. 
When APISIX Dashboard was adapted for compatibility, we found that its schema formatting error made the dashboard crash.
> fix(response-rewrite): schema format error

- docs/en/latest/plugins/response-rewrite.md
- docs/zh/latest/plugins/response-rewrite.md
Fixes # (issue) https://github.com/apache/apisix/issues/7130
> docs: add re case on response-rewrite plugin

- apisix/debug.lua
- t/debug/dynamic-hook.t
- t/debug/hook.t
Fixes # (issue) https://github.com/apache/apisix/issues/7159
> fix: add debug yaml validation

- apisix/upstream.lua
- t/node/upstream.t
Thanks for the report from @redynasc
Fixes #7175
> fix: distinguish different upstreams even they have the same addr

- apisix/plugins/openid-connect.lua
- docs/en/latest/plugins/openid-connect.md
- t/plugin/openid-connect.t
Add support for capturing OIDC refresh tokens in RP scenario. This is an important feature for people implementing BFF designs, especially considering refreshing the access token using previous techniques (such as hidden iframe) will, soon, not be available (Safari already blocks it).
This addition has been discussed in Slack and was implemented according to Zexuan Luo's recommendations:
https://the-asf.slack.com/archives/CUC5MN17A/p1654178597713989
The relevant English documentation is also updated.
> feat: Add support for capturing OIDC refresh tokens

- benchmark/run.sh
1. Write worker_processes into config.yaml instead of nginx.conf
2. Improve script compatibility
3. Disable  `proxy-cache` and `proxy-mirror` plugins
Fixes #7205
> fix(benchmark): write worker_processes into config.yaml

- docs/en/latest/plugins/opentelemetry.md
- docs/zh/latest/plugins/opentelemetry.md
update Chinese opentelemetry docs. https://github.com/apache/apisix/pull/7086
> docs: update Chinese opentelemetry docs

- apisix/plugins/kafka-logger.lua
- docs/en/latest/plugins/kafka-logger.md
- docs/zh/latest/plugins/kafka-logger.md
export 4 importent params about kafka-producter for kafka-logger plugins
if no problem on this commit, i will edit docs later
> feat: export some importent params for kafka-client

- docs/en/latest/plugins/error-log-logger.md
- docs/en/latest/plugins/google-cloud-logging.md
- docs/en/latest/plugins/sls-logger.md
Updates the documentation of the "Observability/Loggers" Plugins (4/n).
> docs: update "Loggers" Plugin 4/n

- apisix/init.lua
- conf/config-default.yaml
1、`core.request.header` will get all request headers and cache these, we don't need to do this on critical code paths.
2、We can use `api_ctx.var.http_x_forwarded_proto` to get only one header we need
Fixes #7258
> perf: don't cache all request headers on critical code path

- apisix/cli/etcd.lua
- conf/config-default.yaml
As it only affects the startup.
> change(etcd): the health_check_retry should be named as startup_retry

- apisix/init.lua
- apisix/plugin.lua
- apisix/schema_def.lua
- docs/en/latest/terminology/plugin.md
- docs/zh/latest/terminology/plugin.md
- t/admin/plugins.t
- t/plugin/custom_sort_plugins.t
> feat: allows users to specify plugin execution priority

- apisix/init.lua
- t/plugin/proxy-rewrite2.t
Co-authored-by: soulbird <zhaothree@gmail.com>### Description
backport PRs to fix https://github.com/apache/apisix/issues/7215 in branch 2.10
Original PR: 
https://github.com/apache/apisix/pull/7229
https://github.com/apache/apisix/pull/7287
> backport: multi request header X-Forwarded-Proto will be sent to upstream as string

- Makefile
- t/cli/test_makefile.sh
> fix(make): make reload doesn't call apisix reload

- apisix/plugins/limit-count.lua
- t/plugin/limit-count2.t
> fix(limit-count): conf with group and disable can't be configured

- apisix/admin/v3_adapter.lua
- t/admin/filter.t
> feat: filter fields supported by all objects

- apisix/cli/file.lua
- apisix/cli/schema.lua
- apisix/core/etcd.lua
- t/cli/test_deployment_data_plane.sh
- t/cli/test_deployment_mtls.sh
> feat(deployment): data plane connects to control plane

- .gitignore
add grpc_server_example, grpc-web-server and node_modules to .gitignore
> chore: add grpc_server_example, grpc-web-server and node_modules to .gitignore

- apisix/balancer.lua
- t/node/upstream-keepalive-pool.t
This bug is introduced in https://github.com/apache/apisix/commit/3dddf41382e8916ce92d7e29c1e8e6d86b821304
> fix(upstream): http connection was put into https connection pool

- apisix/core/etcd.lua
- t/core/etcd-auth-fail.t
Avoid error:
runtime error: /home/runner/work/apisix/apisix/apisix/core/etcd.lua:322: attempt to index field 'header' (a nil value)" (req 0)
stack traceback:
coroutine 0:
/home/runner/work/apisix/apisix/apisix/core/etcd.lua: in function 'set'
...runner/work/apisix/apisix/apisix/plugins/server-info.lua:128: in function 'set'
> fix(etcd): check error code in the body

- apisix/plugins/redirect.lua
- there're test cases at `t/plugin/redirect.t`
so we can remove this stale TODO, and avoid developers working on repeated.
> chore: remove stale todo at plugin redirect

- apisix/plugin.lua
- apisix/plugins/prometheus/exporter.lua
- docs/en/latest/plugins/prometheus.md
- docs/zh/latest/plugins/prometheus.md
- t/plugin/prometheus.t
Fixes #5837 
Use the request header to carry the name of ngx.shared.DICT that needs to be fetched, use `ngx.shared.DICT.capacity` and `ngx.shared.DICT.free_space` to get the current status of `ngx.shared.DICT`, and use `gauge` to store the status
> feat(promethues): add ngx.shared.DICT status

- t/deployment/conf_server.t
In tests 6&7 of `t/deployment/conf_server.t`, two separate instances of etcd are actually used: 127.0.0.1:12379 and 127.0.0.1:2379. 
The `balancer` phase in `conf_server` will choose one of them based on the load balancing policy.
If select one of the instances through the `balancer` of `conf_server` when granting lease, and select another instance through the `balancer` of `conf_server` when writing data with lease, the `requested lease not found` error will occur. Because the lease is not issued by the etcd instance that selected to  write the data.
Fixes #7476
> chore: tweak conf_server unstable test cases

- t/plugin/openwhisk.t
Avoid test failures:
Failed test 't/plugin/openwhisk.t TEST 12: hit route (with wrong api_host) -
pattern "failed to process openwhisk action, err:" should match a line
in error.log
happened in CentOS 7 test.
Look like 127.0.0.0 is connectable in some environment.
> test(openwhisk): ensure the request sent to a wrong host

- apisix/discovery/kubernetes/informer_factory.lua
Fixs #7489
- [] I have explained the need for this PR and the problem it solves
> fix: cleanup variable before re list and watch

- apisix/plugins/jwt-auth.lua
- docs/en/latest/plugins/jwt-auth.md
- docs/zh/latest/plugins/jwt-auth.md
- t/plugin/jwt-auth.t
- t/plugin/jwt-auth2.t
> feat(jwt-auth): support setting clock skew for verifying

- docs/en/latest/discovery/kubernetes.md
- docs/zh/latest/discovery/kubernetes.md
docs: add missing default_weight config for kubernetes discover doc
#7501
> docs: add missing default_weight config

- apisix/plugin.lua
- apisix/plugins/key-auth.lua
- t/node/consumer-plugin2.t
> fix:  auth plugin repeats the rewrite phase

- docs/en/latest/config.json
- docs/en/latest/terminology/plugin-config.md
- docs/en/latest/terminology/plugin.md
Moves the "Plugin Config" page to the "Terminology" section and fixes small issues in the page and the "Plugin" page.
> docs: move "Plugin Config" to "Terminology" sec

- apisix/plugins/clickhouse-logger.lua
- docs/en/latest/plugins/clickhouse-logger.md
- docs/zh/latest/plugins/clickhouse-logger.md
- t/plugin/clickhouse-logger.t
When the apisix load is heavy, there are many access logs, and the endpoint load of a single clickhouse is too heavy. The clickhouse-alogger plugin supports multiple endpoints to share the load.
> feat(clickhouse-logger): support multi clickhouse endpoints

- apisix/plugins/wolf-rbac.lua
- t/lib/server.lua
- t/plugin/wolf-rbac.t
Sorry, there were some issue with the last PR. This PR will fix the problem of error code return.
When wolf-rbac checks the permissions, if the wolf server returns an error, it will return the original error code to the client as is.
> fix(wolf-rbac):  Return the error code returned by the wolf server

- apisix/schema_def.lua
- t/admin/plugins.t
- t/plugin/plugin.t
Plugin filter expr expressions may contain logical operators, so schema cannot be limited to array.
> fix: plugin filter expr schema error

- apisix/plugins/prometheus/exporter.lua
- conf/config-default.yaml
- docs/en/latest/plugins/prometheus.md
- t/plugin/prometheus4.t
close #4273
Add extra labels from nginx variables for http request metrics.
Fixes #4273
> feat(prometheus): extra labels from nginx var for http request metrics

- docs/assets/other/json/apisix-grafana-dashboard.json
update grafana json for nginx shared dict in prometheus
update grafana json to add nginx shared dict, which default config is `internal-status|upstream-healthcheck|worker-events|lrucache-lock|balancer-ewma|balancer-ewma-locks|balancer-ewma-last-touched-at|etcd-cluster-health-check`.
> feat(grafana json): update grafana json for nginx shared dict in prometheus

- apisix/plugins/redirect.lua
- t/plugin/redirect.t
- t/plugin/redirect2.t
> fix(redirect):  compatible with old version data

- apisix/admin/init.lua
- t/admin/api.t
We designed a new Admin API data format for APISIX v3 that is not compatible with what was once v2. We now lack the means to distinguish which version of the Admin API is currently in use, so I will add a default response header for Admin APIia that contains its version number information.
No issue was created.
> feat: add version header for Admin API

- docs/en/latest/plugins/batch-requests.md
- docs/zh/latest/plugins/batch-requests.md
Fix pipeline type of batch requests plugin,  maybe it should be an array.
> docs: update pipeline  type  of  batch  requests plugin

- apisix/core/config_etcd.lua
- apisix/core/config_util.lua
- apisix/core/config_xds.lua
- apisix/core/config_yaml.lua
- t/core/config_util.t
> fix: use a new way to manage clean_handler

- apisix/cli/schema.lua
- t/cli/test_validate_config.sh
The validation is introduced in https://github.com/apache/apisix/commit/fc0dc15fcc430fe255cceab007e33ee03ce7025b
Several people complain this change breaks their code.
> fix: remove the restriction of etcd prefix

- apisix/core/pubsub.lua
remove useless judge in pubsub init, the `loaded`  table is empty after `new`
https://github.com/starwing/lua-protobuf/blob/master/protoc.lua#L301
> chore: remove useless judge in pubsub init

- apisix/plugins/syslog.lua
- docs/en/latest/plugins/syslog.md
- docs/zh/latest/plugins/syslog.md
- t/plugin/prometheus2.t
> change(syslog): remove deprecated max_retry_times and retry_interval

- apisix/init.lua
- t/APISIX.pm
- t/error_page/error_page.t
> fix: the phases after proxy should run when 500 happens before proxy

- apisix/core/pubsub.lua
recovery old pb state after pubsub.new, so that it won't affect other module who use pb state.
> fix: recovery old pb state after pubsub.new

- apisix/cli/file.lua
- apisix/cli/ngx_tpl.lua
- apisix/cli/ops.lua
- apisix/cli/schema.lua
- apisix/plugins/redirect.lua
- conf/config-default.yaml
- docs/en/latest/FAQ.md
- docs/en/latest/plugins/redirect.md
- docs/zh/latest/FAQ.md
- docs/zh/latest/plugins/redirect.md
- t/cli/test_main.sh
- t/plugin/redirect.t
> change: drop support for enable_http2 and listen_port in apisix.ssl

- ci/pod/nacos/service/Dockerfile
OpenJDK images is being deprecated.
ref:
[1]: https://github.com/docker-library/openjdk/issues/505
[2]: https://hub.docker.com/_/openjdk
CI failed by this: https://github.com/apache/apisix/runs/7964485433?check_suite_focus=true#step:9:90
the repo of this images: https://github.com/adoptium/containers (LICENSE is Apache 2.0)
> ci: change base JDK images to eclipse-temurin as openjdk is being deprecated

- apisix/plugins/workflow.lua
- conf/config-default.yaml
- t/admin/plugins.t
- t/plugin/workflow.t
I want to combine the existing DSL to support more complex limiting scenarios, this PR is just the first step in providing workflow plugins to implement basic orchestration capabilities.
> feat: add workflow plugin(mvp)

- docs/en/latest/FAQ.md
- docs/zh/latest/FAQ.md
Users can implement APISIX's own health detection through the fault-injection plugin.
> docs(FAQ): add APISIX health probe solution

- docs/en/latest/config.json
- docs/en/latest/plugins/workflow.md
- docs/zh/latest/config.json
- docs/zh/latest/plugins/workflow.md
> docs: add docs of workflow plugin

- apisix/plugins/opentelemetry.lua
- t/plugin/opentelemetry.t
According to [opentelemetry's spec](https://github.com/open-telemetry/opentelemetry-specification/blob/ea61daeeaf8a3770a5189528abc09f25b87c7531/specification/trace/api.md#spankind), span kind coming from apisix would make more sense to be `server`, this also allows tools like newrelic or datadog to feed dashboards that are split per transaction (request uri in apisix's case as it is the name of the span) and thei response times and statuses.
> fix: Change opentelemetry's span kind to server

- docs/en/latest/plugins/proxy-cache.md
- docs/zh/latest/plugins/proxy-cache.md
update documents under `docs/zh/latest/plugins/` along with `docs/en/latest/plugins/`
> docs(plugin): refactor proxy-cache.md

- apisix/init.lua
- apisix/plugin.lua
- docs/en/latest/plugin-develop.md
- docs/zh/latest/plugin-develop.md
- t/node/plugin.t
So we can do some clean up job in the plugin.
> feat: call `destroy` method when Nginx exits

- apisix/admin/plugin_metadata.lua
- t/admin/plugin-metadata.t
- t/admin/plugin-metadata2.t
The plugin metadata does not implement the filter in v3 adapter, add it in this PR and modify the test cases.
> fix: plugin metadata missing v3 adapter call

- apisix/core/table.lua
- apisix/plugins/log-rotate.lua
- t/plugin/log-rotate2.t
1.  Waiting for nginx reopen files to avoid losing logs during compression
2.  Refactor code to ensure that the signal is sent once at a time
> fix: reload once when log rotate

- docs/en/latest/FAQ.md
- docs/zh/latest/FAQ.md
Signed-off-by: hansedong <admin@yinxiaoluo.com>
Add an FAQ item for apisix high latency due to Etcd
> docs: add an FAQ item for apisix high latency due to etcd

- README.md
- docs/zh/latest/README.md
In the documentation's [get-started](https://github.com/apache/apisix#get-started) part, links of [install documentation](https://github.com/apache/apisix/blob/master/docs/en/latest/installation-guide.md) and [Getting Started](https://github.com/apache/apisix/blob/master/docs/en/latest/getting-started.md) are hard to read(guess due to the JSX part in MD file is not properly rendered)
Fixes #7831
> docs: update install and get started link in readme.md

- apisix/cli/ngx_tpl.lua
- apisix/core/grpc.lua
- apisix/init.lua
- rockspec/apisix-master-0.rockspec
- t/APISIX.pm
- t/core/grpc.t
> feat: integrate grpc-client-nginx-module in APISIX

- apisix/cli/ngx_tpl.lua
- t/APISIX.pm
- t/node/grpc-proxy.t
> fix(gRPC): set :authority header to the upstream host

- apisix/consumer.lua
- apisix/plugin.lua
- t/node/consumer-plugin2.t
- t/node/plugin-configs.t
> fix: use modifiedIndex as lru key when merge plugins from route and consumer

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
- apisix/cli/ngx_tpl.lua
- apisix/plugins/cas-auth.lua
- ci/init-plugin-test-service.sh
- ci/kcadm_configure_cas.sh
- ci/pod/docker-compose.plugin.yml
- conf/config-default.yaml
- docs/en/latest/config.json
- docs/en/latest/plugins/cas-auth.md
- t/APISIX.pm
- t/admin/plugins.t
- t/lib/keycloak_cas.lua
- t/plugin/cas-auth.t
> feat: add cas-auth plugin

- apisix/cli/ops.lua
- t/cli/test_cmd.sh
> fix: prevent failing to start because of the conf server sock

- rockspec/apisix-master-0.rockspec
As we use the latest APISIX-Base in the CI,
we need to ensure the latest Lua code is used.
Now we ship the Lua module of grpc-client-nginx-module in APISIX-Base
so we don't need to install it via luarocks.
> chore: now we ship the Lua module of grpc-client-nginx-module in APISIX-Base

- apisix/admin/consumer_group.lua
- apisix/admin/consumers.lua
- apisix/admin/init.lua
- apisix/consumer.lua
- apisix/consumer_group.lua
- apisix/core/ctx.lua
- apisix/init.lua
- apisix/plugin.lua
- apisix/schema_def.lua
- docs/en/latest/admin-api.md
- docs/en/latest/apisix-variable.md
- docs/en/latest/config.json
- docs/en/latest/terminology/consumer-group.md
- docs/en/latest/terminology/plugin.md
- docs/zh/latest/admin-api.md
- docs/zh/latest/apisix-variable.md
- t/admin/consumer-group.t
- t/config-center-yaml/consumer-group.t
- t/node/consumer-group.t
> feat: add consumer group

- apisix/debug.lua
fix the misspelling function name of apply_new_func
Fixes #8109
> fix: change the misspelling of function name

- conf/config-default.yaml
- t/cli/test_main.sh
Nowadays, more and more users deploy APISIX via container. As Nginx's worker_cpu_affinity doesn't count with cgroup, enabling worker_cpu_affinity by default will affect the behavior of APISIX, for instance, multiple instances will be bound to one CPU. To avoid this problem, it would be better to disable CPU affinity option by default in the conf/config-default.yaml.
Fixes  https://github.com/apache/apisix/issues/8042
> change: update the default value about enable_cpu_affinity

- apisix/core/ai.lua
- t/core/ai.t
> feat(ai): add dynamic route cache key

- apisix/plugins/ai.lua
- t/plugin/ai.t
> fix(ai): use # to concat route cache key parts

- CODE_STYLE.md
> docs: specify function return value

- apisix/http/route.lua
- apisix/init.lua
- apisix/plugins/ai.lua
- conf/config-default.yaml
- t/admin/plugins.t
- t/core/config.t
- t/debug/dynamic-hook.t
- t/plugin/ai.t
> perf: simple setup upstream

- apisix/plugins/ai.lua
- t/debug/dynamic-hook.t
- t/plugin/ai2.t
> perf: allow skip body filter

- docs/en/latest/terminology/plugin-config.md
- docs/en/latest/terminology/upstream.md
- docs/en/latest/tutorials/protect-api.md
- docs/zh/latest/terminology/plugin-config.md
- docs/zh/latest/terminology/upstream.md
- docs/zh/latest/tutorials/protect-api.md
> docs: protect-api.md typo, remove redundant braces.

- apisix/plugin.lua
- t/plugin/plugin.t
> fix: meta.filter in plugin doesn't work in response-rewrite plugin

- docs/en/latest/building-apisix.md
- docs/zh/latest/building-apisix.md
Use git clone instead of the source package for development environments. Because of source package is missing test case. Old documents will mislead the user. So I fix that.
Fixes #8168
> docs: fix building apisix misled

- docs/en/latest/plugins/hmac-auth.md
- docs/zh/latest/config.json
- docs/zh/latest/plugins/hmac-auth.md
> docs: update hmac-auth doc

- apisix/plugins/zipkin.lua
- apisix/plugins/zipkin/codec.lua
- apisix/plugins/zipkin/reporter.lua
- t/plugin/zipkin2.t
https://github.com/apache/apisix/issues/7795
> fix(zipkin): send trace IDs with a reject sampling decision

- apisix/schema_def.lua
- t/admin/upstream.t
Fixes  https://github.com/apache/apisix/issues/8114
the docs pr https://github.com/apache/apisix/pull/8191
> feat: add dafault value roundrobin for upstream_schema

- t/plugin/ai3.t
> test: add cases of ai module

- apisix/ssl/router/radixtree_sni.lua
> chore: export the set cert/key process so we can hook it

- apisix/cli/ngx_tpl.lua
- apisix/core/ctx.lua
- apisix/init.lua
- t/APISIX.pm
- t/plugin/proxy-rewrite.t
- t/plugin/proxy-rewrite2.t
- t/plugin/proxy-rewrite3.t
fix can not modify x-forwarded-host in proxy rewrite
> fix: can not modify x-forwarded-host in proxy rewrite

- docs/en/latest/stand-alone.md
- docs/zh/latest/stand-alone.md
I've recently updated from 2.15.0 to 3.0.0 and experienced an issue with the SSL configuration that I've narrowed down to the parameter `ssl` changed to `ssls` in the `apisix.yml` file when using standalone mode.
> docs: Update standalone docs for change in SSL parameter

- apisix/plugin.lua
- t/plugin/plugin.t
> fix: APISIX extended variables cannot be used in `_meta.filter`

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
> fix(ci): the `set-output` command is deprecated

- utils/check-category.py
Fix a confusing comment about Python 2 vs. 3.  The path labeled py2 is actually Python 3 and vice versa.
> style: fix a confusing comment about Python 2 vs. 3

- apisix/plugins/log-rotate.lua
- t/plugin/log-rotate2.t
> fix(log-rotate): max_kept works on compression files

- docs/zh/latest/upgrade-guide-from-2.15.x-to-3.0.0.md
The upgrade guide for APISIX was released last week. The content is very detailed, but I think some description details can be improved.
> docs: update Upgrade Guide CN version details and conclusion

- apisix/consumer.lua
- apisix/core.lua
- apisix/core/env.lua
- apisix/core/utils.lua
- apisix/init.lua
- apisix/plugin.lua
- t/core/env.t
- t/core/utils.t
- t/plugin/key-auth.t
As part of https://github.com/apache/apisix/issues/8319:
Step 1: Support the use of environment variables to manage keys. Information in the consumer configuration is more private, so we first used environment variables in the consumer to manage sensitive information.
Currently only test cases have been added for the key-auth plugin, the test cases for other plugins will be completed in a separate PR.
> feat: support store secret in env for auth plugin

- docs/en/latest/config.json
- docs/en/latest/terminology/kms.md
- docs/zh/latest/config.json
- docs/zh/latest/terminology/kms.md
As part of https://github.com/apache/apisix/issues/8319:
Add documentation for managing secrets via environment variables.
> docs: add kms env doc

- .github/workflows/gm-cron.yaml
- .github/workflows/gm.yml
- ci/linux_openresty_tongsuo_runner.sh
- utils/linux-install-openresty.sh
> ci: add cron job for GM

- apisix/admin/init.lua
- apisix/admin/kms.lua
- apisix/constants.lua
- apisix/core/etcd.lua
- apisix/schema_def.lua
- docs/en/latest/admin-api.md
- t/admin/kms.t
As part of https://github.com/apache/apisix/issues/8319:
Support adding KMS resources through Admin API.
> feat(admin): add kms admin api

- apisix/core/config_etcd.lua
- t/core/config_etcd.t
> fix: last_err can be nil when the reconnection is successful

- .github/workflows/centos7-ci.yml
ref: https://github.com/actions/runner-images/issues/6399
> ci: use fixed os version of ubuntu

- apisix/plugin.lua
- t/node/consumer-plugin.t
> fix: the plugins bound on the service use the latest configuration

- rockspec/apisix-master-0.rockspec
- t/cli/test_dns.sh
> feat: support resolve upstream host in stream subsystem

- apisix/core/config_etcd.lua
- t/core/config_etcd.t
There is no need to use table to hold it.
> chore(etcd): only one watching stream at most in each `core.config` object

- apisix/plugins/request-id.lua
- t/plugin/request-id-reload-bugfix.t
> fix: unregister timer when snowflake etcd keepalive failed

- apisix/plugins/grpc-transcode.lua
- apisix/plugins/grpc-transcode/proto.lua
- t/plugin/grpc-transcode-reload-bugfix.t
> fix: define destroy() to close protos

- docs/en/latest/installation-guide.md
Fixes #8530
Slack discussion: https://the-asf.slack.com/archives/CUC5MN17A/p1671152569546829
> docs: add missing `kubectl exec` step in the installation guide.

- apisix/core/pubsub.lua
- t/pubsub/kafka.t
- t/pubsub/pubsub.t
Currently, `pubsub` module uses relative path for pb file loading, once apisix's [`cwd`](https://en.wikipedia.org/wiki/Working_directory) is not `/usr/local/apisix`, it will cause pb file loading failure.
> step to change apisix's `cwd`
```bash
cd ~/
apisix start
```
> fix: use absolute path as pubsub search path

- apisix/plugins/ext-plugin/init.lua
- t/lib/ext-plugin.lua
- t/plugin/ext-plugin/response.t
> fix(ext-plugin-post-resp): can't set content-type response header

- apisix/inspect/dbg.lua
- apisix/inspect/init.lua
- t/plugin/inspect.t
fix: correct inspect plugin default hooks file path and add hook remove logs
> fix: correct inspect plugin default hooks file path and add hook remove logs

- apisix/admin/init.lua
- apisix/admin/resource.lua
- apisix/admin/routes.lua
> refactor(admin): refactor resource routes

- docs/en/latest/admin-api.md
In some places, `kms` was not renamed to `Secret`. This has been fixed.
Ref: #8448
> docs: rename kms to secret

- docs/en/latest/terminology/plugin-config.md
The documentation for plugin config looks like this currently (inappropriate code block formatting):
This has been fixed:
> docs: fix code block

- docs/en/latest/terminology/plugin-config.md
- docs/en/latest/terminology/plugin.md
> docs: fix plugin config naming

- apisix/core/json.lua
- t/admin/api.t
- t/core/json.t
- t/gm/gm.t
- t/plugin/ext-plugin/sanity.t
- t/plugin/real-ip.t
- t/stream-node/sanity.t
Remove backslash before slash when encoding.
issue: #7785 
Fixes #7785
> fix: remove backslash before slash when encoding

- apisix/admin/consumer_group.lua
- apisix/admin/global_rules.lua
- apisix/admin/init.lua
- apisix/admin/plugin_config.lua
- apisix/admin/proto.lua
- apisix/admin/resource.lua
- apisix/admin/routes.lua
- apisix/admin/services.lua
- apisix/admin/stream_routes.lua
- apisix/admin/upstreams.lua
> refactor(admin): stream_routes/upstreams/protos/services/global_rules/consumer_groups/plugin_configs

- apisix/plugins/elasticsearch-logger.lua
- docs/en/latest/plugins/elasticsearch-logger.md
- docs/zh/latest/plugins/elasticsearch-logger.md
- t/plugin/elasticsearch-logger.t
When the apisix load is heavy, there are many logs, and the endpoint load of a single elasticsearch is too heavy. The elasticsearch-logger plugin supports multiple endpoints to share the load.
Fixes  (#8431)
> feat(elasticsearch-logger): support multi elasticsearch endpoints

- apisix/core/config_etcd.lua
- t/core/config_etcd.t
> fix(etcd): reloaded data may be in res.body.node

- docs/en/latest/getting-started.md
- docs/zh/latest/getting-started.md
> docs(getting-started): rewrite the install section

- apisix/plugins/mocking.lua
- docs/en/latest/plugins/mocking.md
- docs/zh/latest/plugins/mocking.md
- t/plugin/mocking.t
> fix: mocking plugin panic when response_example contain $ (#8810)

- apisix/plugins/body-transformer.lua
- conf/config-default.yaml
- docs/en/latest/config.json
- docs/en/latest/plugins/body-transformer.md
- t/admin/plugins.t
- t/plugin/body-transformer.t
This plugin is used to transform the request or response body from one
format to another format, e.g. JSON to XML.
It depends on xml2lua and lua-resty-template.
Use cases:
* simple SOAP proxy
* generic template-based transform
> feat: Body transformer plugin

- apisix/cli/schema.lua
- t/cli/test_deployment_control_plane.sh
Fixes https://github.com/apache/apisix/issues/8804
Maybe just add the schema of admin to conrol_plane config definition is enough?
> fix: add admin schema to control_plane config

- apisix/cli/ngx_tpl.lua
- apisix/discovery/tars/init.lua
- conf/config-default.yaml
- t/APISIX.pm
- t/tars/discovery/stream/tars.t
Signed-off-by: ashing <axingfly@gmail.com>
Fixes #7779 
add tars service discovery, and it is the last PR for service discovery in the stream subsystem 
for test case, i add `stream_extra_init_by_lua_start` to file `APISIX.pm`.
some code inspired by PR: https://github.com/apache/apisix/pull/8640
> feat: stream subsystem support tars service discovery

- apisix/core/etcd.lua
- t/admin/ssl.t
The default http code of patch method to admin.resources is `201`. It should be corrected to `200`.
> fix(admin): fix wrong http code for patch method

- docs/en/latest/getting-started.md
- docs/zh/latest/getting-started.md
change nginx var link from http to https, avoid browser unsafe tips
> docs: Update getting-started.md

- apisix/plugins/request-id.lua
- docs/en/latest/plugins/request-id.md
- docs/zh/latest/plugins/request-id.md
- t/plugin/request-id2.t
Fixes # ([issue](https://github.com/apache/apisix/issues/8720))
> feat: add 'range_id' algorithm for 'request-id' plugin

- apisix/plugins/limit-count/limit-count-local.lua
At the limit-count-local.lua code, there accept a parameter conf, but there doesn't pass it from init.lua. And this code doesn't need this conf parameter. I forget to remove this parameter when I develop this logic so I need to fix that.
Fixes #8893
> fix: limit count plugin conf parameter undefined error

- .github/workflows/build.yml
- .github/workflows/centos7-ci.yml
- .github/workflows/fips.yml
- .github/workflows/gm-cron.yaml
Docker image caching to reduce ci build time was just implemented in the CI build pipeline. Upon seeing it's success we are now implementing this in other CI pipelines as well.
> feat(ci): implement image caching in remaining ci pipelines

- apisix/core/utils.lua
- apisix/plugins/proxy-rewrite.lua
- t/plugin/proxy-rewrite3.t
> fix(proxy-rewrite): escape args part if it's not from user conf

- apisix/plugins/gzip.lua
In the gzip plugin, content_type needs to be determined only when types is table, so it would be more appropriate to put it in the table logic，which can improve code performance.
> perf: optimized gzip code logic

- .github/workflows/build.yml
Removing `matrix.os_name` from the image cache key will create a single docker image regardless of the difference in operating systems. In the current implementation, multiple caches are created for the same type of test run on different OS. Due to this the cache storage limit is exceeded and GitHub evicts the least recently used cache, resulting in cache miss which leads to longer CI runtime.
> fix(ci): remove matrix.os_name from image cache key

- docs/en/latest/FAQ.md
- docs/zh/latest/FAQ.md
This section of the document "How to configure ETCD auth for APISIX" is indeed missing. 
Fixes #8833
> docs: update doc for guide user to config auth etcd

- docs/en/latest/config.json
- docs/zh/latest/config.json
Currently, the [**_workflow_**](https://github.com/apache/apisix/blob/d3ac217cb26ab731d51f1ef8275932df8bf72c7b/docs/en/latest/config.json#L187) plugin is in the "[**_serverless_**](https://github.com/apache/apisix/blob/d3ac217cb26ab731d51f1ef8275932df8bf72c7b/docs/en/latest/config.json#LL180-L181C33)" category (for both [`EN`](https://github.com/apache/apisix/blob/d3ac217cb26ab731d51f1ef8275932df8bf72c7b/docs/en/latest/config.json#LL180-L187C32) & [`ZH`](https://github.com/apache/apisix/blob/7926408305c36af1003f76c860a9dd027ab32026/docs/zh/latest/config.json#L173&L180)). However, the workflow plugin doesn't run user-defined code, and it doesn't integrate with serverless platforms like AWS-lambda either. Hence, it's recommended to put the workflow plugin in the …
> docs: shift workflow plugin to general category

- apisix/plugins/degraphql.lua
- ci/pod/docker-compose.plugin.yml
- ci/pod/openfunction/function-example/test-uri/go.mod
- ci/pod/openfunction/function-example/test-uri/go.sum
- conf/config-default.yaml
- docs/en/latest/config.json
- docs/en/latest/plugins/degraphql.md
- t/admin/plugins.t
- t/plugin/degraphql.t
Thanks for @tzssangglass to provide the initial implementation.
Fixes #8787
> feat: add degraphql plugin

- docs/en/latest/discovery/kubernetes.md
- docs/zh/latest/discovery/kubernetes.md
In k8s discovery, clearly state the restriction on the use of port number.
> docs: k8s discovery: state the restriction on the use of port number

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
- rockspec/apisix-3.2.0-0.rockspec
> feat: release APISIX 3.2.0

- .github/workflows/centos7-ci.yml
- .github/workflows/fuzzing-ci.yaml
Without this change, CI in https://github.com/spacewander/incubator-apisix/pull/39 can't run because it hardcodes the repo name.
> ci: ensure the test can run with different repo name

- docs/zh/latest/installation-guide.md
- docs/zh/latest/plugins/error-log-logger.md
- docs/zh/latest/plugins/log-rotate.md
- docs/zh/latest/plugins/mqtt-proxy.md
- docs/zh/latest/terminology/consumer-group.md
Some code blocks currently look like this：
The reason is because Chinese quotes are used to mark the beginning and end of the title.
Now, Chinese quotes are replaced with half-width quotation mark.
> docs: replace full-width quotation mark with half-width quotation mark

- apisix/plugins/ldap-auth.lua
- ci/centos7-ci.sh
- ci/common.sh
- ci/linux_apisix_current_luarocks_runner.sh
- ci/linux_apisix_master_luarocks_runner.sh
- ci/linux_openresty_common_runner.sh
- rockspec/apisix-master-0.rockspec
- t/chaos/utils/Dockerfile
A new `lua-resty-ldap` has been released that provides a completely different API and more new features, we need to upgrade it to exclude API incompatibilities and prepare for another advanced LDAP plugin.
This upgrade is completely non-destructive to the user, and theoretically any test cases do not need to be modified to prove compatibility.
Head of #9022
> feat: bump lua-resty-ldap version for ldap-auth

- apisix/plugins/cors.lua
- t/plugin/cors3.t
When CORS requirements are more complicated than setting `Access-Control-Allow-Origin` to `*` then we set the `Vary` to `Origin`. This avoids caching the wrong response.
Last week I was debugging an issue where requests where failing with CORS errors. 
After some digging it became clear that when the first request to the endpoint did not match the allowed origins the request was cached and this cached resolve was then used later on for Origins that should be allowed. This turned out to be because the `Vary` header did not contain `Origin`. 
Secondly I also resolved an issue where I was unable to use only `allow_origins_by_regex` in standalone mode by allowing `allow_origins` to be an empty string. 
*I'm not sure what `metadata_schema` is used for so this maybe wrong.*
> fix: Non wildcard origin in CORS should sent Vary header

- ci/linux_apisix_master_luarocks_runner.sh
Some tests were inadvertently broken rings, and this PR tries to fix them. 
https://github.com/apache/apisix/actions/runs/4432527919/jobs/7776660356
https://github.com/apache/apisix/actions/runs/4425114852/jobs/7767316567
They are due to the introduction of the Rust toolchain, but the strange thing is that this CI works fine in the test before the PR merge, but keeps failing after the merge.
> test: fix cli test on master

- .github/workflows/build.yml
Ref: https://github.com/apache/apisix/pull/8735#discussion_r1102232577
Freeing up disk space when saving docker images helps, but sometimes, disk space may become full even while loading docker images. Take this [job](https://github.com/apache/apisix/actions/runs/4420311721/jobs/7776553142) for example.
Creating a new github action step that would free disk space will prevent disk space from becoming full in both cases:
- When there is a cache miss and we need to save the docker images
- When there is a cache hit and we need to load the saved docker images from the cache.
> ci: fix low disk space error when loading saved docker images

- apisix/init.lua
- t/node/healthcheck-leak-bugfix.t
Fixes #8932
Only `route.value.upstream.parent` has table reference to `route`, so skip it in `deepcopy` to fix this bug and also avoid a recursive copy (https://github.com/apache/apisix/commit/27c37b191f35da983d40dd42e5ea517105107567).
```
dns_value = {
create_time = 1678955679,
id = "1",
plugins = {
["serverless-pre-function"] = {
functions = {...},
phase = "before_proxy"
}
},
priority = 0,
status = 1,
update_time = 1678955679,
upstream = <1>{
checks = {
active = {...}
},
hash_on = "vars",
nodes = <2>{ {...}, {...} },
nodes_ref = <table 2>,
original_nodes = <table 2>,
parent = <3>{
checker = {...},
checker_idx = 1,
checker_upstream = <table 1>,
clean_handlers = {...},
createdIndex = 2688845,
has_domain = true,
key = "/apisix/routes/1",
modifiedIndex = 2688845,
orig_modifiedIndex = …
```
> fix: checker leak for domain nodes

- apisix/core/config_util.lua
- t/core/config_util.t
Fixes https://github.com/apache/apisix/issues/8492
Fix #8648
> fix: etcd data sync exception

- docs/en/latest/mtls.md
> docs: fix 404 link on mTLS

- apisix/cli/ops.lua
- t/cli/test_admin.sh
> fix(cli): fix allow_admin allows non-`127.0.0.0/24` to access admin api with empty admin_key

- docs/en/latest/mtls.md
Signed-off-by: Navendu Pottekkat <navendu@apache.org>
Remove instruction to use APISIX base and add front matter to mTLS docs.
> docs: remove APISIX base instruction

- apisix/upstream.lua
Fixes https://github.com/api7/lua-resty-healthcheck/pull/15#discussion_r1144565155
> fix: host_hdr should not be false

- CONTRIBUTING.md
fix incorrect semantic.yml link
> docs: fix incorrect semantic.yml link

- docs/en/latest/plugins/prometheus.md
add missing closing quotes in example block
Improve readability of documentation
There is a code block not ended and documentation doesn't render fine.
> docs: close example config block

- apisix/admin/upstreams.lua
- apisix/consumer_group.lua
- apisix/plugin_config.lua
- t/admin/upstream5.t
Fixes https://github.com/apache/apisix/issues/5339
> fix: check upstream reference in traffic-split plugin when delete upstream

- CODE_OF_CONDUCT.md
- CODE_STYLE.md
- THREAT_MODEL.md
- docs/en/latest/discovery/consul.md
- docs/en/latest/discovery/control-plane-service-discovery.md
- docs/en/latest/discovery/kubernetes.md
- docs/en/latest/discovery/nacos.md
- docs/en/latest/internal/testing-framework.md
- docs/en/latest/plugins/aws-lambda.md
- docs/en/latest/plugins/fault-injection.md
- docs/en/latest/plugins/forward-auth.md
- docs/en/latest/plugins/gm.md
- docs/en/latest/plugins/grpc-web.md
- powered-by.md
A few typos and grammatical errors were discovered and have been corrected.
cc: @navendu-pottekkat, @juzhiyuan, @SylviaBABY
> docs: Corrected typos and grammatical errors

- docs/en/latest/tutorials/client-to-apisix-mtls.md
- docs/zh/latest/tutorials/client-to-apisix-mtls.md
Correct the description of `client.ca` and `cert`.
> docs: client.ca in client-to-apisix-mtls.md

- docs/zh/latest/installation-guide.md
The documentation says the default is 8000,But it seems out of date to me.
null
- [yes] I have updated the documentation to reflect this change
> docs: update default port to 9080

- docs/en/latest/getting-started/README.md
- docs/zh/latest/getting-started.md
> docs: add-api7-information

- rockspec/apisix-master-0.rockspec
- t/xds-library/main.go
Fixes: #9253 
I try to upgrade the lua-resty-ldap to 0.2.2 . and to re-try run `make deps`. it's success. 
the output as the follow
```shell
$ make deps
Wrote
variables.OPENSSL_LIBDIR = "/opt/homebrew/opt/openresty-openssl111/lib"
to
/Users/guohao/.luarocks/config-5.1.lua
Wrote
variables.OPENSSL_INCDIR = "/opt/homebrew/opt/openresty-openssl111/include"
to
/Users/guohao/.luarocks/config-5.1.lua
Missing dependencies for apisix master-0:
lua-resty-ldap 0.2.2-0 (not installed)
apisix master-0 depends on lua-resty-ctxdump 0.1-0 (0.1-0 installed)
apisix master-0 depends on api7-lua-resty-dns-client 7.0.1 (7.0.1-0 installed)
apisix master-0 depends on lua-resty-template 2.0 (2.0-1 installed)
apisix master-0 depends on lua-resty-etcd 1.10.4 (1.10.4-0 installed)
apisix master-0 …
```
> fix: upgrade lua-resty-ldap to 0.2.2

- docs/en/latest/plugins/consumer-restriction.md
Same as [this PR](https://github.com/apache/apisix/pull/9251), previous PR merged into the wrong branch. 
Test: https://gist.github.com/kayx23/4c29d608991f5b9216c71d6c45c68d01
Relevant PR: https://github.com/api7/docs/pull/130
> docs: updated consumer-restriction plugin use with Global Rule

- apisix/core/response.lua
- apisix/plugin.lua
- t/core/response.t
- t/plugin/grpc-transcode2.t
Fixes #9228 
and fix: 
Fixed a problem with a unit test left before.
This unit test proves that there is a collaboration problem between http-logger and some plugins, which will cause http-logger to repeatedly print the content of the body.
> fix: hold_body_chunk should use seperate buffer for each plugin in case of pollution

- docs/en/latest/terminology/secret.md
https://apisix.apache.org/docs/apisix/terminology/secret/
See changed file.
> docs: fix admonition in Terminology, Secret

- docs/en/latest/plugins/prometheus.md
add missing closing quotes in example block
Improve readability of documentation
There is a code block not ended and documentation doesn't render fine.
> docs: fix typo in prometheus doc

- apisix/plugins/batch-requests.lua
- t/plugin/batch-requests-grpc.t
batch-requests: read trailer headers if exist, especially for grpc response.
> fix: batch-requests: read trailer headers if exist

- docs/en/latest/tutorials/expose-api.md
- docs/zh/latest/getting-started.md
- docs/zh/latest/tutorials/expose-api.md
For [this](https://apisix.apache.org/docs/apisix/tutorials/expose-api/#expose-your-service), after `step1` and `step2`, when we execute step3 test, 
`curl -i -X GET "http://127.0.0.1:9080/get?foo1=bar1&foo2=bar2" -H "Host: example.com"`
throws {"error_msg":"404 Route Not Found"}. So, the endpoint has been updated to  `http://127.0.0.1:9080/anything/get` from `http://127.0.0.1:9080/get`.
Fixes #8729, (Review https://github.com/apache/apisix/pull/7952#discussion_r1150118134)
P.S. > @navendu-pottekkat I've made the changes, but I'm uncertain whether I need to update [this](https://github.com/apache/apisix/blob/master/docs/en/latest/terminology/plugin.md#:~:text=curl%20%2Dv%20/dev/null%20http%3A//127.0.0.1%3A9080/get%3Fversion%3Dv2%20%2DH%22host%3Ahttpbin.org%22) & …
> docs: (fix) tutorial expose your service

- apisix/plugins/proxy-rewrite.lua
- t/plugin/proxy-rewrite.t
Besides custom `upstream_uri` var, it should set `ngx.var.uri` to keep compatible.
> fix: proxy-rewrite should set ngx.var.uri

- apisix/cli/ngx_tpl.lua
- t/APISIX.pm
apisix grpc-transcode dont support  grpc server written by Python, c++ or nodejs. This is because apisix nginx config file miss set  “grpc_set_header   Te trailers”.  
This is error response:
```
HTTP/1.1 500 Internal Server Error
Date: Tue, 11 Apr 2023 14:22:51 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
grpc-status: 2
grpc-message: Missing :te header
Server: APISIX/3.1.0
```
https://github.com/apache/apisix/issues/8186
https://github.com/apache/apisix/issues/9079
> fix: grpc_set_header   Te trailers

- apisix/plugins/response-rewrite.lua
- t/plugin/response-rewrite.t
fix response-rewrite plugin can't add only one character
Fixes https://github.com/apache/apisix/issues/9223
> fix: response-rewrite plugin can't add only one character

- docs/en/latest/stream-proxy.md
Improved the part of doc before the MySQL example in Stream Proxy doc
> docs: updated Stream Proxy doc

- docs/en/latest/config.json
- docs/en/latest/tutorials/websocket-authentication.md
This PR adds a new tutorial for using authenticated websocket connections.
Opening a new PR because the original PR (https://github.com/apache/apisix/pull/8462) is stale and the original author is busy to address suggestions.
> docs: add guide to authenticate websocket connections

- apisix/plugins/wolf-rbac.lua
- t/plugin/wolf-rbac.t
https://github.com/apache/apisix/issues/9287
- [ x ] I have explained the need for this PR and the problem it solves
- [ x ] I have explained the changes or the new features added to this PR
- [ x ] I have added tests corresponding to this change
- [ x ] I have verified that this change is backward compatible (If not, please discuss on the [APISIX mailing list](https://github.com/apache/apisix/tree/master#community) first)
> fix(wolf-rbac): other plugin in consumer not effective when consumer used wolf-rbac plugin (#9287)

- t/APISIX.pm
- t/lib/server.lua
- t/plugin/ext-plugin/http-req-call.t
1. Record the logs of apisix and test server separately for better observation
2. Use the defined log format
> chore(test): split the access log of apisix and test server

- .github/workflows/fips.yml
- t/node/client-mtls.t
always set `openssl3_prefix`, so that apisix is compiled with openssl3 even if the build cache is not hit.
> fix(ci): fips: ensure apisix compiles with openssl3

- apisix/plugins/body-transformer.lua
- t/plugin/body-transformer.t
> fix: body-transformer plugin return raw body anytime

- ci/linux_openresty_common_runner.sh
The following error always occurs in ci tests because the ETCD is not initialised
Fixes #9417
> fix: 404 error in ci test

- Makefile
Following instruction in [Building APISIX from source](https://apisix.apache.org/docs/apisix/next/building-apisix/) to build APISIX and encountered the following issue related to Rust not installed in the environment:
Issue was introduced by this PR about LDAP: https://github.com/apache/apisix/pull/9037
Updated Makefile to check if Rust is installed in the environment before installing other deps. 
[See here](https://github.com/apache/apisix/pull/9444/commits/f82e9c3de351aa713f05dd69ea6b9cc8f73af19a)
> fix: add `rust-check` target to the makefile for deps pre-checking

- .github/workflows/stale.yml
- apisix/schema_def.lua
- t/admin/upstream3.t
- t/stream-plugin/mqtt-proxy2.t
> fix: upstream `key` config add `mqtt_client_id` support

- docs/en/latest/getting-started/configure-routes.md
- docs/en/latest/getting-started/key-authentication.md
- docs/en/latest/getting-started/load-balancing.md
- docs/en/latest/getting-started/rate-limiting.md
The links in the Prerequisites section of rate limiting were broken.
This PR takes `Get APISIX` link to the correct readme page
and takes `Configure Routes` to the correct configure-routes page
Fixes #9473
> docs: fix broken links in documentation

- docs/en/latest/getting-started/README.md
- docs/zh/latest/getting-started.md
Fixes #9496 
In document https://apisix.apache.org/zh/docs/apisix/getting-started/README/ , use curl to interact with apisix3.3
get the following response is
```shell
curl "http://127.0.0.1:9080" --head | grep Server
Server: APISIX/3.1.0
```
The correct one is
```shell
curl "http://127.0.0.1:9080" --head | grep Server
Server: APISIX/3.3.0
```
> docs: fix the apisix version of getting-started document

- apisix/cli/snippet.lua
- apisix/core/etcd.lua
- t/core/config_etcd.t
- t/core/etcd.t
1. The JWT auth token is stored in the etcd cli table, so reuse the table between calls to avoid repeat auth calls.
2. The path between conf server and etcd should enable keepalive so that we could reuse the same connection to do etcd calls. Besides avoiding connection overhead, the etcd v3 uses [connection based auth](https://etcd.io/docs/v3.5/learning/design-auth-v3/).
> fix(etcd): reuse cli and enable keepalive

- apisix/core/config_etcd.lua
- ci/linux_openresty_runner.sh
- t/core/etcd-sync.t
- t/fuzzing/public.py
- t/plugin/error-log-logger-skywalking.t
1. only one http connection to watch the prefix for all resources
2. use chunked streaming to receive events in the connection, timeout=50 second
Sequence Diagram:
```
/routes watcher->/routes watcher: first sync_data()
/routes watcher->main watcher: start
/routes watcher->/routes watcher: wait main watcher
/upstreams watcher->/upstreams watcher: first sync_data(), wait main watcher
main watcher->etcd: get current etcd revision and start watch there
main watcher-->/routes watcher: started
main watcher-->/upstreams watcher: started
/routes watcher->etcd: readdir() if need_reloaded
/routes watcher->main watcher: iterate history watch events, found
/upstreams watcher->main watcher: no history event, wait...
etcd-->main watcher: watch event
main watcher->main watcher: save event
main …
```
> feat(config_etcd): use a single long http connection to watch all resources

- docs/zh/latest/tutorials/observe-your-api.md
The word 'Zinpin' in 'docs/zh/latest/tutorials/observe-your-api.md' is wrong.'Zipkin' is right.so fixed it.
> docs: fix typo error in observe your api docs

- apisix/admin/resource.lua
- t/admin/secrets.t
Permit updating the selected attributes of the specified, existing secrets by PATCH.
Fixes #9503
> fix(admin): fix secrets do not support to update attributes by PATCH

- apisix/plugins/error-log-logger.lua
- apisix/plugins/skywalking-logger.lua
- t/plugin/error-log-logger-skywalking.t
- t/plugin/skywalking-logger.t
> fix(skywalking-logger, error-log-logger): support $hostname in skywalking service_instance_name

- ci/pod/openfunction/build-function-image.sh
The tests are failing intermittently due to failed response from goproxy.cn like here - https://github.com/apache/apisix/actions/runs/5117952022/jobs/9201757096?pr=9526#step:13:217
This PR replaces the env variable which sets GOPROXY to point to goproxy.cn for builds and replaces it with https://proxy.golang.org
> ci: failing CI due to go build fail

- apisix/admin/init.lua
- t/admin/plugins-reload.t
Inform user when request /plugins/reload/ using wrong HTTP methods. More details in https://github.com/apache/apisix/issues/9481
- **confirmation required.**
> feat: Inform user when request /plugins/reload/ using wrong HTTP methods

- docs/zh/latest/plugins/serverless.md
The word 'severless' in 'serverless.md' is wrong.It is shoud be 'server' not 'sever'.So changed it to 'serverless'.
> docs: fix typo in serverless

- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
Updated the wording to be more accurate as those plugins are not just for HTTP.
Side note: i have noticed that the default parameter is currently `subsystem=http`. Not too accurate either imho but this will require some changes to the codebase (open for discussion).
> docs: updated Admin API wording for `HTTP Plugins`

- apisix/core/pubsub.lua
- apisix/plugins/grpc-transcode/proto.lua
- apisix/plugins/grpc-transcode/request.lua
- apisix/plugins/grpc-transcode/response.lua
- apisix/plugins/grpc-transcode/util.lua
- t/plugin/opentelemetry-bugfix-pb-state.t
> fix: save and restore pb state

- docs/assets/other/json/apisix-grafana-dashboard.json
Change Prometehus queries of the latency graphs to consider selected `$route` and to use dynamic rate interval (`$__rate_interval`).
These changes lead to a better user experience with the provided Grafana dashboard. The main focus is to allow users to see latency metrics for a particular route.
The changes don't affect existing users in any way, the default view stays the same. The required version of Grafana stays the same.
These are the altered panels:
> docs: adjust queries in Grafana dashboard

- apisix/admin/init.lua
- t/admin/resources.t
When user tries to create an invalid resource using the admin API, the error response is not clear.
Fixes #9569
ref: https://github.com/apache/apisix/issues/9569#issuecomment-1567654262
> refactor: return concise error when invalid resource is used

- docs/en/latest/plugins/loki-logger.md
Fixes #9399, fix some documentation errors introduced in that PR.
> docs(loki-logger): fix content and format error

- docs/en/latest/installation-guide.md
- docs/zh/latest/installation-guide.md
The GPG public key of openresty need to be imported
Fixes #9681
> docs: update how to install apisix on debian

- docs/en/latest/installation-guide.md
- docs/zh/latest/installation-guide.md
Changes included in this PR to the Debian installation guide.
* Corrects where to sudo (for installation and apisix cli)
* Fixes https://github.com/apache/apisix/issues/9675, moved debian instruction out of RPM
Build info:
```
$ lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
```
$ dpkg --print-architecture
amd64
```
> docs: update Debian Installation Guide

- apisix/plugins/prometheus/exporter.lua
- conf/config-default.yaml
- docs/en/latest/plugins/prometheus.md
- docs/zh/latest/plugins/prometheus.md
- t/plugin/prometheus4.t
Close https://github.com/apache/apisix/issues/9653
> feat(prometheus): allow user configure DEFAULT_BUCKETS

- apisix/plugins/body-transformer.lua
- t/plugin/body-transformer.t
> fix(body-transformer): xml2lua: replace empty table with empty string

- apisix/core/config_etcd.lua
Fixes using incorrect revision when loading full data without ```loaded_configuration```
> fix: get the correct revision

- apisix/plugins/jwt-auth.lua
remove unused parameter of function `get_secret` and `get_rsa_or_ecdsa_keypair`
> refactor(jwt-auth): remove unused parameter

- conf/config-default.yaml
`report_interval` was [documented in docs](https://apisix.apache.org/docs/apisix/next/plugins/skywalking/#configuring-the-endpoint) but not documented as a configuration option in `config-default.yaml`. 
This PR adds it.
https://github.com/apache/apisix/blob/7ec3c0f583510ebcdf9c414f83792e1ac247a5b9/t/admin/plugins-reload.t#L294-L299
> chore: add missing `report_interval` option for `skywalking` plugin in `config-default.yaml`

- conf/config-default.yaml
Update comments/documentations in `config-default.yaml` as the file is referenced in new docs.
Will make the updates in a series of PRs (by `apisix`, `nginx_config`, and so on) for easier review. 
This PR is for the `apisix` section.
**No functional changes in these PRs.**
> docs: update `apisix` section in `config-default.yaml`

- apisix/plugins/log-rotate.lua
- t/plugin/log-rotate3.t
Fix the bug that the `max_kept` configuration of the log-rotate plugin doesn't work when use custom name
Fixes #9061
> fix(log-rotate): the max_kept configuration doesn't work when using custom name

- docs/zh/latest/config.json
- docs/zh/latest/plugins/loki-logger.md
Fixes https://github.com/apache/apisix/issues/9676 (issue)
> docs: Chinese documentation for loki-logger

- docs/en/latest/pubsub.md
Fix typo in pubsub.md.The word 'Aapche' is wrong.Fixed it to 'Apache'.
> docs: fix typo in pubsub.md

- docs/en/latest/terminology/plugin.md
- docs/zh/latest/terminology/plugin.md
Porting part of the doc from [API7 doc](https://docs.api7.ai/apisix/key-concepts/plugins) about plugins execution priorities and precedences to here to better explain the concept.
> docs: add information to better explain plugin execution priorities and precedences

- apisix/plugins/limit-conn/init.lua
- t/stream-plugin/limit-conn2.t
> fix(limit_conn): do not use the http variable in stream mode

- apisix/plugins/mocking.lua
- docs/en/latest/plugins/mocking.md
- docs/zh/latest/plugins/mocking.md
- t/plugin/mocking.t
> feat: mock plugin support adding headers

- apisix/plugin_config.lua
- apisix/router.lua
- docs/en/latest/control-api.md
- t/config-center-yaml/plugin-configs.t
- t/node/plugin-configs.t
update_count is reset once updated, which will cause lru cache key conflict, in turn reusing the old route conf.
> fix: update_count is reset once updated, cause cache key conflict 

- apisix/plugins/proxy-rewrite.lua
- t/plugin/proxy-rewrite3.t
Fixes #9638 
Tests to be added
> fix: support regex_uri with unsafe_uri in proxy-rewrite

- apisix/admin/init.lua
- apisix/admin/proto.lua
- apisix/admin/resource.lua
- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
- t/admin/consumer-group-force-delete.t
- t/admin/plugin-configs-force-delete.t
- t/admin/protos-force-delete.t
- t/admin/services-force-delete.t
- t/admin/upstream-force-delete.t
Support to force delete resources with header `X-Force-Delete: true`.
Fixes #9795
example:
```bash
❯ curl http://127.0.0.1:9180/apisix/admin/upstreams/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '{
"nodes": {
"127.0.0.1:8080": 1
},
"type": "roundrobin"
}'
❯ curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '{
"uri": "/*",
"upstream_id": 1
}'
{"value":{"priority":0,"upstream_id":1,"uri":"/*","create_time":1689038794,"id":"1","status":1,"update_time":1689038916},"key":"/apisix/routes/1"}
❯ curl http://127.0.0.1:9180/apisix/admin/upstreams/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X DELETE
{"error_msg":"can not delete this upstream, route [1] is still using it now"}
❯ curl …
```
> feat: support force delete resource

- apisix/plugins/google-cloud-logging.lua
- docs/en/latest/plugins/google-cloud-logging.md
- docs/zh/latest/plugins/google-cloud-logging.md
- t/plugin/google-cloud-logging.t
- t/plugin/google-cloud-logging2.t
Add missing config field for google cloud logging plugin
* docs: add client_email field for google-cloud-logging plugin
* docs: add client_email field and log_format default value for google-cloud-logging plugin in zh
> fix(google-cloud-logging): add missing config

- docs/en/latest/getting-started.md
Get this: 
```
curl -s "http://127.0.0.1:9080" --head | grep Server
Server: APISIX/2.15.0
```
Instead of: 
```
curl "http://127.0.0.1:9080" --head | grep Server
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Server: APISIX/2.15.0
```
> docs: using curl silent mod when fetching version

- apisix/plugins/opa.lua
- ci/pod/opa/example.rego
- t/plugin/opa.t
Fixes #9704 
Documentation to be updated
> feat: allow sending headers upstream returned by OPA server

- apisix/plugins/loki-logger.lua
- t/plugin/loki-logger.t
Fixes #9848 
The nginx variable evaluation currently takes place inside callback function which is executed by batch processor and `ngx.var` is not available outside of request phases. This change makes sure that the variables are evaluated in the hot path. 
> fix: loki-logger nil context in batch processor

- apisix/plugins/ua-restriction.lua
- docs/en/latest/plugins/ua-restriction.md
- docs/zh/latest/plugins/ua-restriction.md
- t/plugin/ua-restriction.t
Fixes https://github.com/apache/apisix/issues/7467
> change(ua-restriction): allowlist and denylist can't be enabled at the same time

- conf/config-default.yaml
- docs/en/latest/deployment-modes.md
* Update certificate names in decoupled mode
* Add configuration blocks of `role_data_plane` and `role_control_plane` in `config-default.yaml` to better document for different modes of APISIX deployment.
Fixes #9883
> docs: update certificate names in decoupled mode and add configurations for different deployment modes to `config-default.yaml`

- docs/en/latest/certificate.md
- docs/zh/latest/certificate.md
use shell instead of python to configure ssls resources
> docs: use shell instead of python to configure ssls resources

- docs/en/latest/config.json
- docs/en/latest/tutorials/monitor-api-health-check.md
Added a tutorial for Monitor API Health Check with Prometheus
> docs: Add tutorial on monitoring API health check

- docs/en/latest/deployment-modes.md
Ref: https://the-asf.slack.com/archives/CUC5MN17A/p1690309561460119?thread_ts=1690230991.755169&cid=CUC5MN17A
> docs: add example for protos

- apisix/ssl/router/radixtree_sni.lua
Fixes https://github.com/apache/apisix/issues/9901
> perf(ssl): break out right after sni matched.

- ci/centos7-ci.sh
- ci/redhat-ci.sh
https://github.com/apache/apisix/actions/runs/5677818659/job/15386805689
CI failure caused by using incompatible latest version (openresty:1.21.4.2)
> fix(ci): OpenResty 1.21.4.1 should be specified

- ci/init-plugin-test-service.sh
The CI uses the nightly version of Openwhisk which might result in inconsistent behavior or build failure altogether.
cc: @kingluo 
> fix: avoid using nightly version of openwhisk

- apisix/cli/file.lua
- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
- t/cli/test_standalone.sh
> feat: support pulling env vars from yaml keys

- apisix/discovery/kubernetes/init.lua
- apisix/discovery/tars/init.lua
- docs/en/latest/discovery/kubernetes.md
- docs/zh/latest/discovery/kubernetes.md
due to this PR https://github.com/apache/apisix/pull/9913 merge, we don't need to check OpenResty support ngx.process in the stream subsystem or not because we use OpenResty version >= 1.21.4.
> chore: remove check of OpenResty in code because APISIX can not start when using an old version of OpenResty

- rockspec/apisix-master-0.rockspec
Update lua-rest-t1k plugin to 1.1.0 for better performance. Compared to 1.0.3, ~50% performance improvement in the case of GET requests.
> feat: update lua-resty-t1k to 1.1.0

- docs/en/latest/plugins/proxy-cache.md
- docs/zh/latest/plugins/proxy-cache.md
Added docs as per https://github.com/apache/apisix/issues/9957
```bash
$ curl http://127.0.0.1:9180/apisix/admin/routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
"uri": "/ip",
"plugins": {
"proxy-cache": {
"cache_strategy": "memory",
"cache_zone": "memory_cache",
"cache_ttl": 10
}
},
"upstream": {
"nodes": {
"httpbin.org": 1
},
"type": "roundrobin"
}
}'
{"key":"/apisix/routes/1","value":{"id":"1","update_time":1691137580,"strip_path_prefix":false,"status":1,"upstream":{"nodes":{"httpbin.org":1},"type":"roundrobin","hash_on":"vars","pass_host":"pass","scheme":"http"},"priority":0,"create_time":1690796578,"uri":"/ip","plugins":{"proxy-cache":{"cache_ttl":10,"cache_strategy":"memory","cache_zone":"memory_cache","cache_control":false,"hide_cache_headers":false,"cache_k …
```
> docs: add in-memory caching example for `proxy-cache`

- utils/install-dependencies.sh
EndeavourOS is a Linux distribution based on Arch Linux but the output of `cat /etc/issue` doesn't contain `Arch` which is the current check for installing dependencies from AUR in install-dependencies.sh. This PR makes consideration for EndeavourOS
> fix: add support for dependency installation on endeavouros

- apisix/plugins/log-rotate.lua
replace `string.sub` with `string.byte`
> perf(log-rotate): replace string.sub with string.byte

- apisix/plugins/tencent-cloud-cls/cls-sdk.lua
- t/plugin/tencent-cloud-cls.t
Fixes https://github.com/apache/apisix/issues/9842
> fix(tencent-cloud-cls): DNS parsing failure

- .github/workflows/cli.yml
There are some failed "CLI Test" workflow runs due to a timeout, such as: https://github.com/apache/apisix/actions/runs/5851037609 .
The successful jobs take nearly 15 minutes to complete, such as https://github.com/apache/apisix/actions/runs/5864979479 .
I think 15 minutes for the timeout value is not sufficient.
> ci: update the timeout value in cli.yml

- docs/en/latest/plugins/grpc-transcode.md
- docs/zh/latest/plugins/grpc-transcode.md
Fixes https://github.com/apache/apisix/issues/10006
> docs: fix grpc-transcode.md error

- ci/linux_apisix_master_luarocks_runner.sh
There are some failed "CLI Test (master)" workflow runs, such as https://github.com/apache/apisix/actions/runs/5886312117/job/15963999013 .  
We can get the following error message in the "Linux Script" job:
```
Error: 2023/08/17 03:14:30 [error] 32685#32685: open() "/usr/local/apisix/logs/nginx.pid" failed (2: No such file or directory)
Error: Process completed with exit code 1.
```
The problem code is in `ci/linux_apisix_master_luarocks_runner.sh`
```
sudo PATH=$PATH apisix init
sudo PATH=$PATH apisix start          # step 1
sudo PATH=$PATH apisix quit           # step 2
sudo PATH=$PATH apisix start          # step 3
sudo PATH=$PATH apisix stop
```
After run `apisix quit`, if the process does not exit totaly before `apisix start` (step 3), the `apisix start` will not create a new …
> ci: fix a bug that open nginx.pid failed

- apisix/admin/init.lua
- docs/en/latest/admin-api.md
- t/admin/schema-validate.t
https://lists.apache.org/thread/6lsbhh4c9ytjmrkr0jt66j5s4vyh482k
> feat: add schema validate admin API

- apisix/inspect/dbg.lua
- t/plugin/inspect.t
if all hooks are done and debug mode are disabled, it would be better turn on jit on immediately.
https://api7.ai/blog/apisix-lua-dynamic-debugging-plugin
`Once debugging ends and all breakpoints have been revoked, the system will return to normal JIT mode, and the cleared JIT cache will be regenerated once it re-enters the hot spot.`
> fix(inspect): jit should be recovered after all hooks are done

- docs/en/latest/profile.md
Signed-off-by: Navendu Pottekkat <navendu@apache.org>
Adds instructions on how to use environment variables with configuration files in addition to using an environment variable to switch between multiple configuration files.
So now we are suggesting two ways to manage configuration while deploying APISIX in multiple environments.
> docs: mention how to use environment variables in configuration file

- conf/config-default.yaml
- docs/en/latest/discovery/nacos.md
User confused this `weight` field as the weight attached to each nacos node
Reference #10081
> docs: clarify meaning of "weight" in nacos

- t/secret/vault.t
unescaped left brace in test file
https://github.com/apache/apisix/actions/runs/6009132173/job/16297969790
> fix: unescaped left brace in test file

- Makefile
- ci/centos7-ci.sh
- ci/common.sh
- ci/linux_apisix_current_luarocks_runner.sh
- ci/linux_apisix_master_luarocks_runner.sh
- ci/linux_openresty_common_runner.sh
- ci/redhat-ci.sh
- docs/en/latest/building-apisix.md
- t/chaos/utils/Dockerfile
- utils/install-dependencies.sh
This is a follow up PR to https://github.com/apache/apisix/pull/9936 and removes mentions of RUST from docs as well as remove the scripts that install and check for rust.
> fix: remove Rust related scripts and doc update

- apisix/plugins/chaitin-waf.lua
- t/plugin/chaitin-waf.t
support UNIX sock URL like `unix:/path/to/safeline/resources/detector/snserver.sock`
> fix: update chaitin-waf.lua to support unix sock in host pattern

- apisix/http/route.lua
- apisix/http/router/radixtree_host_uri.lua
- apisix/http/router/radixtree_uri.lua
- apisix/http/router/radixtree_uri_with_parameter.lua
- apisix/init.lua
- t/cli/test_route_match_with_graphql.sh
Reuse of `match_opts` causes the value of the next request to overwrite the value of the current request. GraphQL requests call the `ngx.req.read_body` API, which is a non-blocking call. If the request body has not been fully read (for example, if the body size exceeds the nginx buffer), the coroutine will yield. If there are other requests during this time period, `match_opts` will be contaminated by other requests, resulting in matching the wrong route.
Fixes: #10197
> fix: graphql post request route matching exception

- conf/config-default.yaml
> chore:  modify the description of ssl.key_encrypt_salt in config-default.yaml

- apisix/cli/ngx_tpl.lua
- conf/config-default.yaml
access log's buffer size can be configed.
Access log buffering can significantly reduce disk I/O and improve server performance. Enabling access log buffering is relatively simple in NGINX. To do this, use the following directive in your NGINX configuration:
access_log /var/log/nginx/access.log main buffer=32k;
This directive tells NGINX to store the access log entries in a buffer of size 32k before writing them to the log file. Increasing the buffer size can minimize the number of write operations to the disk, resulting in improved performance.
Fixes #10219
> feat: support configuring the buffer size of the access log

- apisix/schema_def.lua
- t/admin/upstream-array-nodes.t
- t/admin/upstream.t
- t/wasm/global-rule.t
> feat: strictly validate the input of core resources

- docs/en/latest/plugins/ua-restriction.md
_**Blacklist**_ and _**whitelist**_ are profane terms. Hence, the usage of appropriate terms like allowlist and denylist is suggested instead in [ua-restriction.md](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/ua-restriction.md#description).
Fixes #9042 
cc: @shreemaan-abhishek, @navendu-pottekkat, @nfrankel
> docs: replace non-inclusive terms in ua-restriction plugin doc

- docs/en/latest/terminology/global-rule.md
- docs/en/latest/terminology/plugin-config.md
- docs/en/latest/tutorials/protect-api.md
With the current situation of documentation, it's very likely that users might end up not having any context about `Global rules` when considering the plugin execution precedence.
> docs: update info about plugin execution order and phases

- apisix/discovery/consul/init.lua
- apisix/discovery/consul/schema.lua
- apisix/discovery/consul_kv/init.lua
- apisix/discovery/consul_kv/schema.lua
- ci/pod/docker-compose.first.yml
- docs/en/latest/discovery/consul.md
- docs/en/latest/discovery/consul_kv.md
- t/control/discovery.t
- t/discovery/consul.t
- t/discovery/consul_kv.t
This PR adds support for ACL tokens when using _consul_ or _consul_kv_ service discovery as described in #9532.
> feat: add token support for consul discovery (#9532)

- apisix/balancer.lua
https://github.com/apache/apisix/blob/35349ef508351364216c0c2f1c0fd8798905b9e2/apisix/balancer.lua#L82-L83
The above error log reports an error in some cases even if the request is valid and successful. In the initial requests, `get_target_status()` will always fail as the target status is not yet finalized. It does not make sense to report an error for positive outcomes.
Note that the `get_target_status()` failure just signifies that the system failed to get the health status only. We do not know if the target is actually unhealthy. And even if the node is unavailable/unhealthy `get_target_status()` does not report the error, but some warn logs like this:
```
2023/09/04 22:13:09 [warn] 14709#16724107: *2442 [lua] healthcheck.lua:650: [healthcheck] (upstream#/apisix/upstreams/1) unhealthy …
```
> fix: use warn log for get healthcheck target status failure

- apisix/schema_def.lua
Fixes https://github.com/apache/apisix-ingress-controller/issues/2003
All core resources like service, upstream , route, plugin have name field but plugin_config doesn't and after this PR where additional fields were [prohibited](https://github.com/apache/apisix/pull/10233), passing name in plugin_config gives an error. Ingress controller currently doesn't differentiate and adds name to plugin_config as well so currently there is this issue between apisix and ingress controller.
So this PR adds the name field to plugin_config to solve the compatibility issue and also for consistency
> fix: add name field in plugin_config schema for consistency

- t/cli/test_cmd.sh
correct the customized-config-path name in test_cmd.sh
> test: correct the customized-config-path name in test_cmd.sh

- apisix/core/config_util.lua
- apisix/upstream.lua
- conf/config-default.yaml
- t/node/healthcheck-leak-bugfix.t
When we modify the upstream (adding or deleting nodes), APISIX first deletes the health check object and then recreates the health check object. The process of deletion and recreation may affect other parallel requests searching for healthy nodes, leading to the following error:
So we will replace `checker:clear()` with function `checker:delayed_clear()`. This function marks all targets to be removed, but do not actually remove them. If before the delay parameter any of them is re-added, it is unmarked for removal.
This function makes it possible to keep target state during config changes, where the targets might be removed and then re-added.
It's very hard to add test cases. I tried but failed.
Follow these steps to reproduce:
1. create a router
```
curl …
```
> fix: keep healthcheck target state when upstream changes

- conf/config-default.yaml
Remove the configuration item `apisix.stream_proxy.only`, the L4/L7 proxy needs to be enabled through the configuration item `apisix.proxy_mode`: [#9607](https://github.com/apache/apisix/pull/9607)
> chore: remove stream_proxy.only in config-default.yaml

- t/plugin/limit-req3.t
In this PR, I use curl send http2 request to test the limit-req plugin.
> test: use http2 to test limit-req plugin

- apisix/discovery/consul/init.lua
**1.configure**
config.yaml
discovery:
consul:
servers:
- "http://localhost:8500"
keepalive: true
Version: 3.6.0
**2.situation**
Using the consul service, I found that there is a process leak. When reloading or quitting, there will be a nginx process shutting down and never exit.
When nginx reloads, the consul worker with keepalive turned on will not exit normally, will be in shutting down state, and will always access consul's health api.
You only need to make a judgment before creating a new timer to solve the process leak.
This problem does not exist when keepalive is false, but there will be an obvious memory leak.
htop -p $(pgrep -d',' -f "nginx")
process will not exit!
To process exit when testing, please change consul node state.
**3.testing**
start consul discovery, and try to …
> fix: fix consul plugin worker will not exit while reload or quit

- apisix/core/ctx.lua
- t/core/ctx2.t
- t/plugin/traffic-split5.t
> fix: post_arg match fails because content-type contains charset

- apisix/plugins/openid-connect.lua
- docs/en/latest/plugins/openid-connect.md
- docs/zh/latest/plugins/openid-connect.md
- t/plugin/openid-connect4.t
Add the ability to configure additional authorization params included in the openid-connect plugin.
Fixes #10057 
If tests are required, I may need assistance in writing those.
> feat: Add authorization params to openid-connect plugin

- docs/en/latest/plugins/degraphql.md
- docs/en/latest/plugins/grpc-transcode.md
- docs/en/latest/tutorials/add-multiple-api-versions.md
- docs/zh/latest/plugins/grpc-transcode.md
9080 is used as the admin port which is not the default and raises misconception/confusion among users:
[Example](https://the-asf.slack.com/archives/CUC5MN17A/p1698205230477449):
> docs: fix usage of incorrect admin api port

- Makefile
Since mac use M1/M2(arm64) chip, apisix will be always installed failure when execute `make install`, it's not about the permission, it's new system constraint and it doesn't work even mac user unlock it.
The change is adjust
* `ENV_INST_BINDIR` path from `/usr/bin` to `/usr/local/bin` for Mac arm64 only
* `ENV_INST_LUADIR` path from `/usr/share/lua/5.1` to `/opt/homebrew/Cellar/lua/{version}` for Mac arm64 only
Ideally for those non-distributed managed package, we better put in `/usr/local/bin` rather than `/usr/bin` regardless Linux/MacOS, `/usr/local/` is more for those self install packages. Anyway, this change only affect mac arm64 developer, please review. thank you
intend to fix https://github.com/apache/apisix/issues/6225 issue permanently
> fix: make install failed on mac

- apisix/plugins/opentelemetry.lua
- t/plugin/opentelemetry4-bugfix-pb-state.t
- t/plugin/opentelemetry5.t
The previous implementation did not [follow the spec][1]. I'll list the reasoning below.
Span name:
> HTTP server span names SHOULD be {http.method} {http.route} if there
is a (low-cardinality) http.route available. HTTP server span names SHOULD be {http.method} if there is no (low-cardinality) http.route available. HTTP client spans have no http.route attribute since client-side instrumentation is not generally aware of the "route", and therefore HTTP client spans SHOULD use {http.method}. Instrumentation MUST NOT default to using URI path as span name, but MAY provide hooks to allow custom logic to override the default span name.
It's clearly mentioned that the span name MUST NOT use URI path, but the previous implementation did exactly that. Now it uses `http.method http.route` where …
> change(opentelemetry): make span name and attributes follow the standard spec

- docs/en/latest/stream-proxy.md
- docs/zh/latest/stream-proxy.md
Try with the current command in the doc and use `mysql` client to connect with the MySQL server, you will see an error: `Authentication plugin 'caching_sha2_password' cannot be loaded. The specific module can not be found`.
This is because MySQL 8.0 uses `caching_sha2_password` as the default authentication rather than `mysql_native_password`, which has been the default authentication in earlier versions.
For this docker example, an easy way to resort back to using `mysql_native_password` is to add `mysqld --default-authentication-plugin=mysql_native_password`:
> docs: update the mysql docker example in stream proxy to use mysql_native_password

- ci/pod/openfunction/function-example/test-body/hello.go
- t/grpc_server_example/main.go
"io/ioutil" has been deprecated since Go 1.16
> chore: deprecate the pacakge `io/ioutil`

- apisix/plugins/kafka-logger.lua
- t/plugin/kafka-logger2.t
While the doc was updated in #10126, the code was not. As a user, it could be confusing to see the doc mentions `required_acks` doesn't support 0, yet the schema and test say otherwise.
> fix: remove 0 from required_acks allowed values for kafka-logger

- apisix/discovery/nacos/init.lua
- apisix/discovery/nacos/schema.lua
- conf/config-default.yaml
- t/discovery/nacos3.t
feat: support Nacos ak/sk authentication
> feat: support Nacos ak/sk authentication

- apisix/plugins/multi-auth.lua
- conf/config-default.yaml
- docs/en/latest/config.json
- docs/en/latest/getting-started/key-authentication.md
- docs/en/latest/plugins/multi-auth.md
- docs/zh/latest/getting-started/key-authentication.md
- t/admin/plugins.t
- t/debug/debug-mode.t
- t/plugin/multi-auth.t
Add multiple authentication for routes. This is the implementation of multi-auth plugin
```json
{
"plugins":{
"multi-auth":{
"auth_plugins":[
{
"basic-auth":{ }
},
{
"key-auth":{
"query":"apikey",
"hide_credentials":true,
"header":"apikey"
}
},
{
"jwt-auth":{
"cookie":"jwt",
"query":"jwt",
"hide_credentials":true,
"header":"authorization"
}
}
]
}
}
}
```
Fixes #10196
> feat: add multi-auth plugin

- apisix/cli/schema.lua
_clean copy of #10534 by @pottekkat_
Reverts the schema.lua file to before I introduced the changes that might be causing errors in the CI.
Reverts the file back to this point: https://github.com/apache/apisix/blob/c757bafeb94315e03d3cc1ba4c88a0a94c081fd1/apisix/cli/schema.lua
> fix: revert schema because of errors in CI

- apisix/core/utils.lua
- t/plugin/fault-injection2.t
Current regex for evaluating variables like: `$var`, `${var}`, etc. would also match `$var}` including the closing brace. This has been fixed.
Fixes #10478
> fix: closing brace should not be a part of variable

- apisix/plugin.lua
- apisix/plugins/limit-count/init.lua
- t/plugin/limit-count3.t
> fix(limit-count): all consumers should share the same counter

- docs/en/latest/debug-mode.md
- docs/zh/latest/debug-mode.md
The debug.yaml needs a trailing #END (just like the routes.yaml)
The first sample misses it. This PR fixes it.
> docs: Add #END to the `debug.yaml` basic snippet

- docs/en/latest/upgrade-guide-from-2.15.x-to-3.0.0.md
Signed-off-by: Navendu Pottekkat <navendu@apache.org>
Improve the upgrade guide documentation to make it easy to follow and improve discoverability.
Future upgrade guides can be nested under an upgrade guide section and this page will be moved under the section without changing its link.
> docs: improve upgrade guide

- docs/en/latest/getting-started/load-balancing.md
- docs/en/latest/getting-started/rate-limiting.md
- docs/zh/latest/getting-started/load-balancing.md
- docs/zh/latest/getting-started/rate-limiting.md
In the current version of the APISIX documentation, there is a shell command intended for testing purposes:
`hc=$(seq 100 | xargs -i curl "http://127.0.0.1:9080/headers" -sL | grep "httpbin" | wc -l); echo httpbin.org: $hc, mock.api7.ai: $((100 - $hc))`
This command utilizes the -i option with xargs, which is deprecated in GNU xargs, particularly on newer GNU/Linux distributions. 
The updated command is as follows:
`hc=$(seq 100 | xargs -I {} curl "http://127.0.0.1:9080/headers" -sL | grep "httpbin" | wc -l); echo httpbin.org: $hc, mock.api7.ai: $((100 - $hc))`
> docs: update xargs command in documentation

- apisix/core/etcd.lua
- t/admin/routes.t
- t/core/config_etcd.t
- t/core/etcd.t
> fix: missing etcd init_dir and unable to list resource

- t/node/healthcheck-https.t
https://github.com/apache/apisix/issues/9993
> ci: new test case for https health check

- apisix/core/config_yaml.lua
Fixes #10402
Please review. Not sure why is the log message printed multiple times and how to avoid it.
> refactor: add log after apisix.yml config reload in standalone mode

- apisix/core/config_etcd.lua
The [etcd related pr](https://github.com/apache/apisix/pull/9456) imported a timer that never quits.
According to [the official recommendation](recommendations), the timer will cause memory leak.
It will affect all versions between 3.4.0 and 3.7.0, including 3.2.2
Fixes #10392 #10349
Frequent configuration changes can cause memory to keep going up.
The memory goes from 0.2% to 1.7% in few hours
And the memory keeps stable after fixed
> fix: memory leak caused by timer that never quit

- apisix/plugins/proxy-rewrite.lua
If header_value is resolved to nil or empty table, `add_header` will throw an error https://github.com/openresty/lua-resty-core/blob/master/lib/resty/core/request.lua#L364
It's better to do nothing.
ref: https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/req.md#add_header
> fix: do not invoke add_header if value resolved as nil

- apisix/core/config_etcd.lua
- conf/config-default.yaml
- t/core/config_etcd.t
- t/core/etcd-sync.t
Due to the [fix](https://github.com/apache/apisix/pull/10614), the saved etcd revision will be discarded when re-watch etcd, APISIX need to re-traverse all keys in etcd every time, that leads to high cpu usage
> fix: not saving etcd revision

- apisix/control/v1.lua
- apisix/plugins/prometheus/exporter.lua
fix: #10664
build a `mostly_healthy` test case based on test-nginx is too difficult for me.  so this PR not include test case
I will add the test case form this metric at the next PR
> fix: mostly_healthy is healthy

- apisix/plugins/zipkin.lua
- t/plugin/zipkin.t
An error(attempt to index local 'opentracing' (a nil value))  occurs in the following situations:
- failed to parse b3 header and return 400.
- plugins with higher priority return or throw exceptions.
All of the above result in a not being assigned value to ctx.opentracing. so got a error in log phase. this pr will fix it.
Fixes #10590
> fix(zipkin): avoid getting a nil value in log phase(#10590)

- apisix/plugins/authz-keycloak.lua
> fix: authz-keycloak add return detail err (#10682)

- docs/en/latest/profile.md
Mention env var support in `apisix.yaml` and add a caution note for exporting vars.
See the below issues for more background info:
Closes #10509 
Closes #10530
The info is also mentioned in the [Admin API doc](https://apisix.apache.org/docs/apisix/admin-api/#using-environment-variables) but not easy to locate. Personally I only found out after looking for the PR that adds the feature.
From a user perspective, when I search for apisix config env var, this is the doc that comes up first.
_Though it seems from the doc title that this doc wasn't originally for this content._
There has been other user that recently mentioned the info could not be located:
https://the-asf.slack.com/archives/CUC5MN17A/p1703518877003939
> docs: mention env var support in `apisix.yaml`

- docs/en/latest/plugins/openid-connect.md
- docs/zh/latest/plugins/openid-connect.md
The PR primarily updates reasons why one could run into 500 internal server error with `no session state found` in the error log when working with `openid-connect` plugin. The causes were gathered from current docs, github issues, slack threads, internal discussions, and through my own experience working with this plugin.
The `no session state found` is a commonly seen error but it could be resulted from a number of reasons. APISIX currently does not return more specific errors to help users troubleshoot. Hopefully this doc update can help some users and if the community finds out more scenarios that could cause the error, this section could be enriched further down the road.
> docs: update troubleshooting list for `openid-connect` plugin

- apisix/upstream.lua
- t/node/upstream-discovery-dynamic.t
upstream original_nodes is not updated when fill_node_info structure after cloning the nodes table. This PR stores the cloned nodes in the original nodes before fill_node_info
#9805
> fix: cache original_nodes with nodes

- apisix/plugins/response-rewrite.lua
- t/plugin/response-rewrite3.t
> feat(response-rewrite): support brotli when use filters.regex option

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/CHANGELOG.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
> feat: release APISIX 3.8.0

- apisix/plugins/authz-keycloak.lua
- t/plugin/authz-keycloak2.t
In the authz_keycloack plugin, when we set `lazy_load_paths` as true and do not provide `resource_registration_endpoint` either in the plugin config or in the discovery doc we get a 500 error code. 
This error code comes from here https://github.com/apache/apisix/blob/ab67b095bf7200274b37af5c589fc093858d98e8/apisix/plugins/authz-keycloak.lua#L580 when we try to get the length of `permission` because an integer value, 503, is passed to it from here https://github.com/apache/apisix/blob/ab67b095bf7200274b37af5c589fc093858d98e8/apisix/plugins/authz-keycloak.lua#L506
This PR changes the return value of `permission` to `nil`.  This will now return error 503 when this check runs:
https://github.com/apache/apisix/blob/ab67b095bf7200274b37af5c589fc093858d98e8/apisix/plugins/authz-keycloak.lua#L569 …
> fix: authz_keycloak plugin giving 500 error 

- apisix/plugins/openid-connect.lua
- t/plugin/openid-connect.t
When using the openid-connect plugin with `bearer_only` as false, the plugin will normally authenticate both requests with the session cookie and requests with an explicit `Authorization: Bearer` header. This is very useful to allow both browser based and programmatic access to some resource.
However, if you set `use_jwks` instead of explicitly setting the public key, requests with a proper `Authorization: Bearer` header still get the `302 Found` response.
Fix by adding `conf.use_jwks` to the check.
Fixes #10669
> fix(openid-connect): use_jwks breaking authentication header

- docs/en/latest/certificate.md
The [certificate doc page](https://apisix.apache.org/docs/apisix/certificate/) has a test request
curl --resolve 'test.com:9443:127.0.0.1' https://test.com:9443/hello -k -vvv
The request url has an error because the path should be `/get`, not `/hello`
> docs: fix request url error in certificate doc

- docs/zh/latest/plugins/limit-count.md
Fixes #10798 
add Chinese translation of using variables for secrets in limit-count plugin
> docs: allow to use environment variables for limit-count plugin settings

- apisix/plugins/brotli.lua
- docs/en/latest/plugins/brotli.md
- t/lib/server.lua
- t/plugin/brotli.t
- Fixes #10739 (issue)
---
Skipping the `brotli` compression if the upstream response is already compressed.
The problem occurs when the upstream service sends compressed data/response either in `gzip` or `deflate`. Apisix tries to compress data in `brotli` which is already compressed and, in turn, returns encoded data that can not be used by the browser or application.
There are two options to solve the problem first to skip the further compression and return with the upstream compressed response. The second is to decompress the upstream response and then compress using `brotli`, which is not viable on apisix gateway, it increases the overhead of the gateway and results in increasing latency and computation requirements.
This PR solves the Issue by skipping the `brotli` compression if …
> fix(brotli-plugin): Skip brotli compression for upstream compressed response

- docs/en/latest/installation-guide.md
- docs/zh/latest/installation-guide.md
The 3.8.0 deb package no longer relies on the openresty software source.
> chore: update installation-guide doc

- docs/en/latest/plugins/dubbo-proxy.md
Fixes #10648 
The PR update the docs for dubbo-proxy with the following information :
- Only Map<String, Object> is supported
- Only hessian2 is supported for serialization, so the user must set this in dubbo config of their applications
- The data to the user program can be passed as header
- [] I have explained the changes or the new features added to this PR
- [] I have added tests corresponding to this change
> docs: update dubbo-proxy doc

- apisix/plugins/jwe-decrypt.lua
- t/plugin/jwe-decrypt.t
> fix: plugin jwe-decrypt decryption failure

- Makefile
- apisix-master-0.rockspec
- benchmark/run.sh
- docs/en/latest/building-apisix.md
- docs/en/latest/install-dependencies.md
- docs/zh/latest/building-apisix.md
- docs/zh/latest/install-dependencies.md
- utils/install-dependencies.sh
Remove the sh and docs for build/install `APISIX` on MacOS, it will be not supported
Fixes #
Part of: https://github.com/apache/apisix/issues/10784
> chore: Remove the shell and docs for build/install APISIX on MacOS

- apisix/cli/file.lua
- apisix/cli/schema.lua
- apisix/plugin.lua
- apisix/ssl.lua
- conf/config-default.yaml
- t/admin/ssl2.t
- t/admin/ssl4.t
- t/node/data_encrypt.t
- t/node/data_encrypt2.t
- t/node/upstream-mtls.t
- t/plugin/authz-casdoor.t
- t/plugin/authz-keycloak3.t
- t/plugin/csrf.t
- t/plugin/elasticsearch-logger.t
- t/plugin/error-log-logger-clickhouse.t
- t/plugin/google-cloud-logging2.t
- t/plugin/hmac-auth3.t
- t/plugin/jwt-auth3.t
- t/plugin/kafka-proxy.t
- t/plugin/openid-connect2.t
- t/plugin/rocketmq-logger2.t
- t/plugin/sls-logger.t
- t/plugin/tencent-cloud-cls.t
This is a fix for issue 10484, the field ssl:key_encrypt_salt has been removed, all the encrypt and decrypt operations are using data_encryption:keyring field now.
key_encrypt_salt and keyring are all used for data encrypt and decrypt, but in fact the are doing the same thing, this change remove key_encrypt_salt only field keyring need to be reserved.
Fixes #10484
> change: unify the keyring and key_encrypt_salt fields, remove ssl:key_encrypt_salt

- docs/en/latest/plugins/openid-connect.md
- docs/zh/latest/plugins/openid-connect.md
Fixes #10876 
- Fix wrong link in openid-connect documentation. Due to the lack of Chinese documents, English documents are temporarily used instead.
> docs: fix wrong link in openid-connect docs

- apisix/plugins/mocking.lua
- t/plugin/mocking.t
support built-in variables in response_headers in mocking plugin
Fixes #10868
> feat: support built-in variables in response_headers in mocking plugin

- apisix/plugins/elasticsearch-logger.lua
- ci/pod/docker-compose.plugin.yml
- t/plugin/elasticsearch-logger.t
1. Add compatibility headers to ensure smooth transition from version `7.x` to `8.x` 
2. update the elasticsearch in test env
Fixes #8647
> fix(elasticsearch-logger): add compatibility headers

- apisix/plugins/jwe-decrypt.lua
- docs/en/latest/plugins/jwe-decrypt.md
- docs/zh/latest/plugins/jwe-decrypt.md
- t/plugin/jwe-decrypt.t
add restriction for `jwe-decrypt` plugin
the secret length should be 32 chars only, it will be checked on the `check_scheme`
Fixes #
https://github.com/apache/apisix/pull/10883#issuecomment-1931380021
> fix: jwe-decrypt secret length restriction

- apisix/secret.lua
- t/secret/secret_lru.t
> fix: when delete the secret cause 500 error 

- apisix/discovery/kubernetes/informer_factory.lua
This PR fix url path splicing bug.
endpoints api url: /api/v1/`namespaces`/{namespace}/endpoints/{name}
ref: https://docs.openshift.com/container-platform/4.8/rest_api/network_apis/endpoints-core-v1.html#apiv1namespacesnamespaceendpointsname
> fix: wrong namespace related endpoint in k8s

- apisix/discovery/kubernetes/informer_factory.lua
- apisix/discovery/kubernetes/init.lua
- apisix/discovery/kubernetes/schema.lua
- docs/en/latest/discovery/kubernetes.md
- docs/zh/latest/discovery/kubernetes.md
- t/kubernetes/discovery/kubernetes.t
- t/kubernetes/discovery/kubernetes3.t
This PR add support endpointslices in kubernetes discovery
> feat(discovery): support endpointslices in kubernetes discovery

- docs/en/latest/plugins/workflow.md
- docs/zh/latest/plugins/workflow.md
The doc of workflow plugin should use `9080` instead of `0080`.
> docs(workflow): fix apisix http port

- docs/en/latest/plugins/ext-plugin-post-resp.md
The current state:
> After enabling this plugin, APISIX will use the lua-resty-http library to make requests to the upstream...
Leads to a confusion that APISIX would now use `lua-resty-http` to send requests to the upstream. The above statement can lead to some more misleading conclusions. Like this:
https://the-asf.slack.com/archives/CUC5MN17A/p1708676667225869
> docs: improve clarity for `ext-plugin-post-resp` plugin

- apisix/core/config_etcd.lua
The error_log level should be  when etcd compacts since we should avoid etcd compact
> chore: the log level should be "error" when etcd compacts

- apisix-master-0.rockspec
Full changelog: https://github.com/chaitin/lua-resty-t1k/compare/v1.1.0...v1.1.1
The primary modification involves correcting a bug that triggers a warning-level log when executing `sock:setkeepalive` in `request.lua` .
> feat(chaitin-waf): update lua-resty-t1k to 1.1.1

- docs/en/latest/plugin-develop.md
The current state:
> In APISIX, only the authentication logic can be run in the rewrite phase. Other logic needs to run before proxy should be in access phase.
is misleading (#10965 for example).  This has been removed along with a little addition about the `body_filter` and `header_filter` phases.
> docs: remove misleading information

- docs/en/latest/plugins/ua-restriction.md
- docs/zh/latest/plugins/ua-restriction.md
In ua-restriction plugin, the allowlist and denylist cannot be configured at the same time. Yet the example given configured both:
This PR updates the example and improves writing.
> docs: update example in ua-restriction plugin doc

- apisix/plugins/jwt-auth.lua
- t/plugin/jwt-auth4.t
> fix(jwt-auth): real_payload was overridden by malicious payload

- .github/workflows/http3.yml
- t/APISIX.pm
In https://github.com/apache/apisix/pull/10989 and https://github.com/apache/apisix/pull/11010, APISIX already supports configuring HTTP/3 and supports HTTP/3 CI. This PR want to refactor the CI to make sure that all test cases of APISIX work correctly with `enable_http3` and `disable_http3`.
> Test framework of APISIX depends on apisix-runtime which is build with nginx [ngx_http_v3_module](https://nginx.org/en/docs/http/ngx_http_v3_module.html). And the `http3` directive of `nginx` is `on` by default.
For `build.yml`, it will use `APISIX.pm` with `http3 off` for test cases. All test cases will run without http3.
```perl
listen 1994 quic reuseport;
listen 1994 ssl;
http2 on;
http3 off;
ssl_certificate             cert/apisix.crt;
ssl_certificate_key         cert/apisix.key; …
```
> refactor(http3): enable http3 directive only in http3 CI

- apisix-master-0.rockspec
Full changelog: https://github.com/chaitin/lua-resty-t1k/compare/v1.1.1...v1.1.3
The primary modification involves correcting a bug that failed to set the timeout for the `cosocket`, as well as optimizing the use of the array table to improve performance.
> feat(chaitin-waf): update lua-resty-t1k to 1.1.3

- CHANGELOG.md
- apisix/cli/ops.lua
- apisix/cli/schema.lua
- conf/config-default.yaml
- docs/en/latest/grpc-proxy.md
- docs/zh/latest/grpc-proxy.md
- t/cli/test_main.sh
- t/core/config-default.t
**This PR is a Breaking Change.**
in https://github.com/apache/apisix/pull/10887, I upgrade openresty-1.25.3.1 for APISIX. There is a deprecation in nginx. The `http2` parameter in `listen` directive is deprecated.
> The parameter is deprecated, the [http2](https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2) directive should be used instead.
In https://github.com/apache/apisix/pull/10887, in order to maintain backward compatibility, I did not modify the method of `enable http2` in APISIX. But this will bring a breaking change to users.
for example.
`config.yaml`
```yaml
apisix:
node_listen:
- ip: 127.0.0.1
port: 9081
enable_http2: true  # enable HTTP/2 for 127.0.0.1:9081
- ip: 127.0.0.2
port: 9082
enable_http2: false # disable HTTP/2 for 127.0.0.1:9082
```
generated `nginx.conf` …
> change: use apisix.enable_http2 to enable HTTP/2 in APISIX

- apisix/schema_def.lua
- apisix/upstream.lua
- t/node/invalid-port.t
> fix(schema): the port value greater than 65535 should not be allowed

- apisix/ssl.lua
> perf(ssl): replace 'string.len' with '#'

- apisix/plugin.lua
- conf/config-default.yaml
- t/admin/consumers.t
- t/node/chash-hashon.t
- t/plugin/error-log-logger-clickhouse.t
- t/plugin/key-auth.t
Fixes https://lists.apache.org/thread/30wf080qvrzokronrx283sy8x8kondqf
> feat: enable sensitive fields encryption by default

- apisix/plugins/brotli.lua
When there is a chunk in the `eof`, brotli plugin overwrite the response `arg[1]`. Which results into partial response.
- Fixes #11079
> fix(brotli): brotli partial response fix

- apisix/admin/init.lua
- apisix/cli/ops.lua
> fix: rectify the warning printed when `admin_key_required` == `false`

- apisix/core/request.lua
- apisix/plugins/real-ip.lua
- apisix/plugins/ua-restriction.lua
- t/core/request.t
- t/plugin/hmac-auth.t
Signed-off-by: ashing <axingfly@gmail.com>
Fixes #11126
In order to prevent the caller from judging the data type by itself.
notice: After `core.request.header` function changed, we need to get original header value by using `core.request.headers` in file `real-ip.lua` and `ua-restriction.lua`
> fix(request.header): core.request.header return string instead of table

- apisix/plugins/forward-auth.lua
- t/plugin/forward-auth.t
- t/plugin/forward-auth2.t
forward-auth plugin doesn't work if the request is POST and authservice api is GET. Its happening due to forwading the POST method request headers like content-type and expect. Moved these headers only if authserver api is also POST.
Fixes the issue with forward-auth plugin with POST headers. 
https://github.com/apache/apisix/issues/10927
https://github.com/apache/apisix/issues/11020
> fix: add post request headers only if auth request method is post

- apisix/plugin.lua
- apisix/plugins/prometheus/exporter.lua
- t/cli/test_prometheus_reload.sh
- t/plugin/prometheus4.t
This PR allows disabling the export server when prometheus is removed from plugins list in config.yaml and then the plugin reload api is called.
Fixes #11046
> fix(prometheus): disable features when prometheus plugin is turned off

- apisix/core/request.lua
- t/core/request.t
> fix(request.headers): no longer returns all http headers, but limited to the default 100. 

- apisix/plugins/openid-connect.lua
- t/plugin/openid-connect5.t
…session on locking session storage (example unauth_action=deny)
This PR is fixing a bug where sessions are blocked until ttl is expired in case of an authentication error. For example unauthenticated session and `unauth_action='deny'` and locking session storage is configured.
Basically the same problem as in https://github.com/apache/apisix/pull/10788 but in case of error.
> fix: close session in case of error to avoid blocked session

- .asf.yaml
release/3.9 branch is invalid and the protection should be removed. 
I will rebuild the correct release/3.9 branch ASAP, and then we can restore the release/3.9 branch protection.
After this PR was merge, we will do:
1. delete `release/3.9` branch
2. rename branch `release/3.9.0` to `release/3.9` 
3. submit new PR to protect branch `release/3.9`
> chore: release/3.9 branch is invalid and the protection should be removed

- .asf.yaml
This reverts commit 005281c13278db16e2a2070854428481b585f0c6.
> chore: restore release/3.9 branch protection 

- apisix/secret.lua
Instead of caching the secrets resource and iterating over all of them in a loop to find the correct secret resource, it's better to directly use the `get` function. This also maintains consistency with other parts of the apisix code.
> fix(secret): rectify the way to fetch secret resource by id

- apisix/stream/router/ip_port.lua
- t/stream-node/sanity-repeat.t
Fix https://github.com/apache/apisix/issues/11259
this bug introduced in https://github.com/apache/apisix/pull/10298/files#diff-0234dd467ed66c3dffbef844397e9e7e018c287aab324ba8dd0b5a9e03b89360, I have no idea why made those changes,
set `route.value.xxx_matcher`  to nil is insane, the stream route only working in first matched request now, after first match, all requests to same stream route will be panic with nil matcher:
> fix: stream route matcher is nil after first match

- .github/workflows/cli.yml
- Makefile
- apisix/core/config_etcd.lua
- t/cli/test_etcd_sync_event_handle.sh
Fixes #11267
Ensure that all etcd events are handled, rather than jumping out of the execution flow when a checking error is encountered.
Current wrong behavior will cause changes in etcd to no longer take effect on the started data plane.
The issue has existed since at least APISIX 2.0, which was long, 4-5 years ago.
> fix: validation fails causing etcd events not to be handled correctly

- apisix/secret/vault.lua
- docs/en/latest/admin-api.md
- docs/en/latest/terminology/secret.md
- docs/zh/latest/admin-api.md
- docs/zh/latest/terminology/secret.md
- t/secret/vault.t
HashiCorp Cloud and Enterprise editions support multi-tenancy based on the namespace concept. By using a specific HTTP Header, we can get the key from a specific namespace.
This makes sense, for HashiCorp Cloud it looks like namespaces are turned on by default and its default namespace is admin, which will not work when the client (APISIX) does not specify a namespace.
This PR adds namespace support on HCV (HashiCorp Vault).
**In addition to this, I would suggest to rename the `vault` module in APISIX to `hcv`, based on the fact that `vault` itself is a neutral term that stands for some kind of component used to store keys. `HashiCorp Vault` is the name of that software, so it should be written `hcv` and not `vault`.**
**I would suggest renaming it, and in the meantime, we could add some …
> feat: support hcv namespace

- apisix/ssl.lua
- t/admin/ssl4.t
Due to the failure to handle the OpenSSL error generated during the AES decryption process, this error was caught by Nginx during the TLS handshake request, resulting in the request failure.
In the scenario of key rotation, due to the attempt to traverse all keys and attempt decryption, the error messages generated earlier should be ignored when decryption is successful.
reference：
* https://github.com/openresty/lua-resty-string/pull/65#issuecomment-1185765216
* https://segmentfault.com/a/1190000015326570
Fixes #11148
> fix(ssl): SSL key rotation caused request failure

- utils/install-dependencies.sh
was not installed during make deps on the ubuntu dev container for vscode. since this is definitely required for luarocks to work there shouldnt be any negative consequences on any system that already has it installed
Add a explicit dependency on `libyaml-dev` in the apt base systems, since it does not get installed on at least
some distributions (ubuntu 22 dev container in this case). Without this luarocks will not install any dependencies and fails saying it can't find the lib.
No changes to the performance_test.sh (the only test file that is relevant) need to be made
#11290 
- [x ] I have explained the need for this PR and the problem it solves
- [x ] I have explained the changes or the new features added to this PR
> fix: add libyaml-dev dependency for apt

- apisix/core/request.lua
- t/core/request.t
> fix: after updating the header, get the old value from the ctx.var

- apisix/plugins/datadog.lua
- t/plugin/datadog.t
When datadog tries to upload metrics containing the consumer username tag, it fails.
Basically the code there tries to splice a string with a table (without __tostring), which is completely wrong, and it has had this problem since the original version of the plugin, which went undetected because the original authors didn't write test cases related.
The previous author of PR #10934 was closed by bot for not adding test cases and no longer responding. Thanks to the issue reporter and the author of the previous PR.
Fixes #9269
> fix(datadog): report consumer username tag

- apisix/plugins/key-auth.lua
- docs/en/latest/plugins/key-auth.md
- docs/zh/latest/plugins/key-auth.md
- t/plugin/cors.t
- t/plugin/key-auth.t
When the key is missing while accessing a route with the key-auth plugin enabled, we get the message, "Missing API key found in request," which isn't correct. How is something missing in the request, found in the request?
Instead, it should be phrased as "Missing API key in request," which is clearer.
While users may be able to make sense of the older message, it is an easy enough change.
This PR updates the message in the code, tests, and docs.
> fix: make the message clearer when API key is missing

- apisix-master-0.rockspec
Lua Casbin version [1.41.9](https://github.com/casbin/lua-casbin/releases/tag/v1.41.9) fixes bug [157](https://github.com/casbin/lua-casbin/issues/157) with PR [158](https://github.com/casbin/lua-casbin/pull/158).
This allows to escape commas in policy rules and is especially useful for `{N,M}` **pattern quantifier**, which would otherwise throw an error ("invalid policy size"), since it considers the comma as a CSV field separator.
The affected plugin is [**authz-casbin**](https://apisix.apache.org/docs/apisix/plugins/authz-casbin/) which depends on Casbin.
<details>
<summary>show/hide</summary>
Model file:
```conf
[request_definition]
r = sub, obj, act
[policy_definition]
p = sub, obj, act
[policy_effect]
e = some(where (p.eft == allow))
[matchers]
m = regexMatch(r.sub, p.sub) && …
```
> chore(deps): Update dep casbin to 1.41.9

- docs/en/latest/plugins/body-transformer.md
The base64 example was missing `template_is_base64`
> docs: fix broken example in body-transformer

- apisix/core/config_etcd.lua
- t/plugin/error-log-logger-clickhouse.t
- t/plugin/sls-logger.t
Signed-off-by: ashing <axingfly@gmail.com>
Fixes https://github.com/apache/apisix/issues/11216
fix part 2 of this issue
the `load_full_data` function in the file `config_etcd.lua`(load all exist data from etcd when apisix start), `checker` does not depend on `item_schema` to have a value
https://github.com/apache/apisix/blob/507df1262de88c4ed3ee8a637de46c4f4d2412f8/apisix/core/config_etcd.lua#L540-L546
But in the `sync_data` function (watch new events from etcd when apisix running), `checker` relies on `item_schema` should have value.
https://github.com/apache/apisix/blob/507df1262de88c4ed3ee8a637de46c4f4d2412f8/apisix/core/config_etcd.lua#L668
As a result, the plugin metadata resource cannot reach the checker logic when etcd watch. …
> fix: etcd sync data checker should work

- docs/en/latest/FAQ.md
- docs/en/latest/benchmark.md
- docs/en/latest/customize-nginx-configuration.md
- docs/en/latest/install-dependencies.md
- docs/en/latest/installation-guide.md
- docs/en/latest/plugin-develop.md
- docs/en/latest/plugins/aws-lambda.md
- docs/en/latest/plugins/azure-functions.md
- docs/en/latest/plugins/inspect.md
- docs/en/latest/pubsub.md
- docs/en/latest/terminology/plugin.md
- docs/zh/latest/FAQ.md
- docs/zh/latest/benchmark.md
- docs/zh/latest/customize-nginx-configuration.md
- docs/zh/latest/install-dependencies.md
- docs/zh/latest/installation-guide.md
- docs/zh/latest/plugin-develop.md
- docs/zh/latest/terminology/plugin.md
Same as https://github.com/apache/apisix/pull/11503 (cherry picked) but for the 3.10.0 release branch.
> docs: update docs for the removal of `config-default.yaml` (3.10.0)

- docs/en/latest/tutorials/monitor-api-health-check.md
docs: fix word spell error in monitor-api-health-check.md.Change APISX  to APISIX .
> docs: fix word spell error in monitor-api-health-check.md

- docs/en/latest/plugins/gzip.md
- docs/zh/latest/plugins/gzip.md
Clarify that the gzip buffers size is in bytes.
> docs: clarify `gzip_buffers` unit size

- conf/config.yaml.example
Add `http.lua_shared_dict.prometheus-metrics` annotation in `config.yaml.example` file
> chore: add `http.lua_shared_dict.prometheus-metrics` annotation in `config.yaml.example` file

- t/plugin/traffic-split3.t
foo.com used in traffic split test is a valid domain now and sending plain http request will yield `302` status code instead of `502`.
https://github.com/apache/apisix/actions/runs/10823712557/job/30029684940?pr=11499#step:21:380
> fix(ci): foo.com is no longer a bad gateway

- apisix/cli/ops.lua
- t/cli/cli_envsubst_confusion.t
- t/cli/test_main.sh
- t/cli/test_standalone.sh
Fixes #11121
Fixes #11239
1. Import environment variables with the same prefix to Nginx using assignment style
2. In the `init_by_lua` phase
3. There will be confusion issues
```
use Test::Nginx::Socket 'no_plan';
master_on();
repeat_each(1);
our $prefix = "prefix";
our $longer = "longer";
$ENV{TEST_ENV_SAME_PREFIX} = $prefix;
$ENV{TEST_ENV_SAME_PREFIX_LONGER} = $longer;
add_block_preprocessor(sub {
my ($block) = @_;
if (!$block->request) {
$block->set_value("request", "GET /t");
}
my $config = $block->config // "";
$config .= <<_EOC_;
location = /t {
content_by_lua_block {
local prefix = os.getenv("TEST_ENV_SAME_PREFIX")                 
local longer = os.getenv("TEST_ENV_SAME_PREFIX_LONGER")
assert(prefix == "$::prefix" and longer == "$::longer")
}
}
_EOC_
$block->set_value("config", …
```
> fix: confusion when substituting ENV in config file

- apisix/plugin.lua
- t/node/consumer-plugin3.t
The data plane did not properly handle encryption and decryption when configuring a non authentication plugin on a consumer. This bug resulted in error logs and lack of encryption of sensitive information about the configuration of such plugins in etcd.
error log like:
```
[lua] plugin.lua:1027: decrypt_conf(): failed to get schema for plugin: csrf, context: ngx.timer"
```
> fix: encryption/decryption for non-auth plugins in consumer

- apisix/admin/consumers.lua
- apisix/admin/credentials.lua
- apisix/admin/init.lua
- apisix/admin/resource.lua
- apisix/consumer.lua
- apisix/core/config_etcd.lua
- apisix/core/etcd.lua
- apisix/schema_def.lua
- docs/en/latest/admin-api.md
- docs/en/latest/config.json
- docs/en/latest/terminology/credential.md
- docs/zh/latest/admin-api.md
- docs/zh/latest/config.json
- docs/zh/latest/terminology/credential.md
- t/admin/credentials.t
- t/node/consumer-plugin.t
- t/node/consumer-plugin2.t
- t/node/credential-plugin-basic-auth.t
- t/node/credential-plugin-incremental-effective.t
- t/node/credential-plugin-jwt-auth.t
- t/node/credential-plugin-key-auth.t
- t/node/credential-plugin-multi-credentials.t
- t/node/credential-plugin-set-request-header.t
- t/node/credential-plugin-work-with-other-plugin.t
This PR add a resource named `credential` and implement Admin APIs for it.
Credential is used to hold the authentication credentials for the Consumer.
Credentials are used when multiple credentials need to be configured for a Consumer.
> feat: implement credential

- apisix/plugins/splunk-hec-logging.lua
- docs/en/latest/plugins/splunk-hec-logging.md
- t/plugin/splunk-hec-logging.t
The default keepalive timeout is too long and will lead to lot of sockets left open in high scale.
> feat(splunk-logger): allow configuring keepalive_timeout

- .asf.yaml
- CHANGELOG.md
- Makefile
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
https://lists.apache.org/thread/p2klbhp2onm3shb3nsc70gjvmmdjnzo0
> chore: release 3.11.0

- apisix/consumer.lua
- t/plugin/consumer-bug-fix.t
Due to wrong modified index being assigned to consumer, it doesn't get the updated data. This PR fixes that.
> fix: use right modifiedIndex for consumer when use credential

- docs/assets/other/json/apisix-grafana-dashboard.json
Current the grafana dashboard has panels for RPS per status code and RPS per service/route. 
This change adds a total RPS panel as well.
> feat: add Total request per second panel in grafana dashboard

- docs/en/latest/plugins/ai-proxy.md
The `override.endpoint` configuration in the `ai-proxy` plugin is not under the `model` configuration.
Documentation update only - to be in sync with the following code from
`plugins/ai-proxy/drivers/openai.lua`:
```
local endpoint = core.table.try_read_attr(conf, "override", "endpoint")
```
> docs: fix the ai-proxy override.endpoint

- ci/linux_openresty_tongsuo_runner.sh
- ci/pod/otelcol-contrib/config.yaml
Fix an environment error in CI where the OTel Collector was working abnormally, causing tests that relied on it to always fail.
For example: https://github.com/apache/apisix/actions/runs/11949539768/job/33309196303?pr=11765
> fix: otel ci test error

- apisix/core/config_util.lua
- apisix/upstream.lua
When a client requests, if the currently hit route or the corresponding upstream changes again, APISIX will try to re-create the health check checker for the upstream of the currently hit route and release the original health check checker.
During the process of re-creating the health check checker, when each upstream node is added as the target of the health check, the locking operation may take a long time to execute.
If the process of creating a health check checker is relatively long, and the route or the corresponding upstream changes at the same time, the parent of the upstream has been released, and in the previous step, the re-created healthcheck checker will be added to an empty object (the original intention is to Added to the new upstream parent), the checker can't be released, …
> fix: the health checker can't be released due to the health parent being released early

- apisix/plugins/jwt-auth.lua
- ci/common.sh
- docs/en/latest/plugins/jwt-auth.md
- t/plugin/jwt-auth4.t
Support configuring key_claim_name like kong: https://docs.konghq.com/hub/kong-inc/jwt/configuration/#config-key_claim_name
> feat(jwt-auth): support configuring `key_claim_name`

- apisix/plugins/basic-auth.lua
- apisix/plugins/hmac-auth.lua
- apisix/plugins/jwt-auth.lua
- apisix/plugins/multi-auth.lua
- apisix/utils/auth.lua
- t/plugin/multi-auth2.t
When using auth plugins with the multi auth plugin, if one of the authentication fails but other auth plugins succeed, the basic auth plugin will record a warning log, causing inconvenience to the user.
[apisix/apisix/plugins/multi-auth.lua at master · apache/apisix](https://github.com/apache/apisix/blob/master/apisix/plugins/multi-auth.lua#L75) The muti auth plugin does not record the error message returned by the plugin.
When there are multiple plugins in muti auth, if the final verification is passed (that is, any plugin is verified), even if other plugins return errors, no error log needs to be recorded
If all plugins fail to verify, summarize the error messages of multiple plugins into a log for recording.
> feat: plugins in multi-auth returns error instead of logging it

- apisix/plugins/workflow.lua
- docs/en/latest/plugins/workflow.md
- t/plugin/workflow-without-case.t
This change makes `case` a non required field and an absence of `case` will be considered default match.### Checklist
> feat: allow workflow config without case

- docs/en/latest/plugins/traffic-split.md
- docs/zh/latest/plugins/traffic-split.md
After https://github.com/apache/apisix/pull/9115/, the traffic-split plugin already supports configuring `scheme` in `weighted_upstreams`, but the documentation has not been updated.
> docs: weighted_upstreams of traffic-split support configuring scheme

- docs/en/latest/plugins/openid-connect.md
Fixed typos in openid-connect documentation
No code change
> docs: fix openid-connect documentation typos

- conf/config.yaml.example
- docs/en/latest/plugins/prometheus.md
- docs/zh/latest/plugins/prometheus.md
Previous feat PR didn't update the doc https://github.com/apache/apisix/pull/10869
> docs: update for prometheus metrics expiration

- .github/workflows/build.yml
- apisix/plugins/ai-proxy/drivers/openai.lua
- t/APISIX.pm
- t/plugin/ai-proxy2.t
The ai-proxy plugin code had missing nil check for `parsed_url`. This bug remained undetected by the test cases as all test cases use valid override.endpoint. While developing the plugin, this bug remained undeteced by me too because I was using self hosted openai server.
> fix(ai-proxy): missing parsed_url nil check

- apisix-master-0.rockspec
- ci/common.sh
- ci/linux-install-openresty.sh
- utils/install-dependencies.sh
fix: https://github.com/apache/apisix/actions/runs/12293837387/job/34451936593?pr=11824#step:5:22314
**The current version of `lualdap` has been archived: https://luarocks.org/modules/fperrad/lualdap**
I noticed that the implementation of ldap-auth has been replaced, and the lualdap dependency has not been used. So I think it needs to be removed.
* This PR is introduced: https://github.com/apache/apisix/pull/3894
* Replaced by resty-ldap: https://github.com/apache/apisix/pull/7590
> fix(ci): remove lualdap deps

- apisix/plugin.lua
- apisix/plugins/limit-count.lua
- apisix/plugins/workflow.lua
Current logic requires the table `supported_actions` defined in workflow.lua to be changed when any new plugin is added to the workflow plugin. With this change, the registration in the table is offloaded to the newly added plugin by implementing the function workflow_handler()
> refactor: workflow plugin registration

- apisix/core/config_etcd.lua
```
[error] 56#56: *223892756 lua user thread aborted: runtime error: /usr/local/apisix/apisix/core/config_etcd.lua:260: attempt to compare number with nil
stack traceback:
coroutine 0:
/usr/local/apisix/apisix/core/config_etcd.lua: in function </usr/local/apisix/apisix/core/config_etcd.lua:130>
coroutine 1:
[C]: in function 'ngx_thread_wait'
/usr/local/apisix/apisix/core/config_etcd.lua:285: in function </usr/local/apisix/apisix/core/config_etcd.lua:268>, context: ngx.timer
[error] 56#56: *223892756 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/core/config_etcd.lua:287: attempt to concatenate local 'err' (a boolean value)
stack traceback:
coroutine 0:
/usr/local/apisix/apisix/core/config_etcd.lua: in function </usr/local/apisix/apisix/core/config_etcd.lua:268>, …
```
> fix: etcd watch restart when receive invalid revision

- apisix/plugins/jwt-auth.lua
- t/plugin/jwt-auth4.t
`key` and `secret` attributes should not be allowed to be configured empty.
> fix(jwt-auth): disallow empty key configuration attributes

- apisix/core/table.lua
- apisix/init.lua
- apisix/plugin.lua
- apisix/plugins/ai.lua
- t/core/table.t
The current deepcopy, when it finds that the original table has already been copied, will directly use the original table. This causes the copied table and the original table to share one table, which does not conform to the semantics of deepcopy. After fixing, the same table will be copied only once by default, we also allow specifying special fields to use shallow copy because, for the health checker module, we need to mount the checker corresponding to the upstream into the original route table so that old checker objects can be released when routes are updated or deleted.
> fix: deepcopy should copy same table exactly only once

- apisix/plugins/ai-proxy/drivers/openai.lua
- t/plugin/ai-proxy2.t
Although the `ai-proxy` plugin officially supports only `openai` as an LLM provider, the plugin can be used to proxy requests to azure-openai service as mentioned in this blog: https://docs.api7.ai/apisix/how-to-guide/ai-gateway/proxy-azure-openai-requests, by entering the correct URL in `override.endpoint` attribute of `ai-proxy`.
However, the `azure-openai` deployment URL contains some query params that wasn't being carried into the request (HTTP request made by `ai-proxy` plugin) to the LLM endpoint. This PR ensures that query params in `override.endpoint` are appropriately used.
> fix(ai-proxy): query params in override.endpoint not being sent to LLMs

- .gitignore
- .licenserc.yaml
- utils/lj-releng
lua global `load` is not covered by default by the lj-relang which is used for lint tests. This PR makes sure overrides the code with the one which takes that into account
needed for this: https://github.com/apache/apisix/pull/11793
> fix: add support for ignoring "load" global variable

- docs/en/latest/control-api.md
> docs: add discovery endpoints to control api doc

- t/plugin/traffic-split.t
Example of failing test in master: https://github.com/apache/apisix/actions/runs/12578912814.
This is because this upstream returns 302 redirect now instead of 200. Replacing this with httpbin.org.
> fix: failing CI due to wrong status from upstream in traffic split

- docs/en/latest/plugins/opentelemetry.md
This PR fixes build failures caused by unclosed HTML `<br>` tags in the `opentelemetry.md` documentation file.
The changes:
- update unclosed `<br>` tags to `<br />`
> fix: the docs website build failed due to incorrect unclosed tag `<br>`

- docs/zh/latest/plugins/opentelemetry.md
This PR fixes build failures caused by unclosed HTML `<br>` tags in the `opentelemetry.md` documentation file.
The changes:
- update unclosed `<br>` tags to `<br />`
> fix: the zh docs website build failed due to incorrect unclosed tag <br>

- apisix/plugins/traffic-split.lua
- t/plugin/traffic-split5.t
During creation of roundrobin object for upstream in traffic-split. `upstream_obj.upstream`: [1] is assigned a string if the upstream configuration only has the weight value.
In this case, if we reload the plugin via the plugin reload API. The roundrobin object gets recreated but since `upstream_obj.upstream` has a string value. `upstream_obj.upstream.vid = i`: [2] causes panic because it expects `upstream_obj` to be a table.
[1]: https://github.com/apache/apisix/blob/6a845761c3fbb18bd4bdc5efb278a6c351ae7434/apisix/plugins/traffic-split.lua#L220
[2]: https://github.com/apache/apisix/blob/6a845761c3fbb18bd4bdc5efb278a6c351ae7434/apisix/plugins/traffic-split.lua#L208
> fix(traffic-split): `upstream_obj.upstream` should not be a string

- apisix/plugins/opentelemetry.lua
- conf/config.yaml.example
- docs/en/latest/plugins/opentelemetry.md
- docs/zh/latest/plugins/opentelemetry.md
- t/plugin/opentelemetry.t
- t/plugin/opentelemetry2.t
- t/plugin/opentelemetry3.t
- t/plugin/opentelemetry4-bugfix-pb-state.t
- t/plugin/opentelemetry5.t
- t/plugin/security-warning2.t
This PR replaces plugin attribute with plugin metadata in Opentelemetry plugin. Now the same configuration will have to be passed with plugin metadata and not attribute.
> refactor(opentelemetry): replace plugin attribute with plugin metadata

- apisix/upstream.lua
For a route configured with an upstream using service discovery, when a request hits the route, it will fetch the latest nodes of the current upstream through `discovery.nodes` and compare it using the `compare_upstream_node` function. Only if there is a change in the node list, `new_nodes` will be set to `upstream.nodes`. Then we copy `upstream` using `table.clone`, creating a new table to replace the previous upstream. 
Another function worth mentioning is `fill_node_info`, which fills some necessary fields in `upstream.nodes`.
Now let me describe a race condition scenario:
Request A gets `[{"port":80,"weight":50,"host":"10.244.1.33"}]` from  `discovery.nodes`. After executing  `fill_node_info`, it becomes  `{"port":80,"weight":50,"host":"10.244.1.33", "priority": 0}`.
then due to some …
> fix: race condition problem while update upstream.nodes

- docs/en/latest/installation-guide.md
- docs/zh/latest/installation-guide.md
There is a grammatical error in the provided config.yaml configuration in the "Updating Admin API key" section of the APISIX installation guide, missing a colon.
> docs: Correcting grammatical errors in the installation guide document.

- docs/en/latest/plugins/real-ip.md
- docs/zh/latest/plugins/real-ip.md
This PR fixes build failures caused by unclosed HTML `<br>` tags in the `opentelemetry.md` documentation file.
The changes:
- update unclosed `<br>` tags to `<br />`
> fix: the docs website build failed due to incorrect unclosed tag <br>

- apisix/plugins/chaitin-waf.lua
Fixes lua entry thread aborted when event_id is nil
> fix(chaitin-waf): fix event_id is nil

- apisix/plugins/ai-proxy-multi.lua
- apisix/plugins/ai-proxy.lua
- apisix/plugins/ai-proxy/base.lua
- t/plugin/ai-proxy-multi2.t
In the previous `ai-proxy-multi` feat PR: #11986, the `ai-proxy-multi` module would overwrite the `ai-proxy` module functions.
Due to this, the `ai-proxy` plugin would execute `ai-proxy-multi` plugin's logic. This issue was found during some manual tests. The CI could not detect because it could not run properly as test::nginx could not initialise an nginx process as it could not find a certificate specified in the following test:
https://github.com/apache/apisix/blob/cc7441fb1e89a234994489bbd5ead8440b94ccb3/t/plugin/ai-proxy-multi2.t#L291-L296
The CI failure log: https://github.com/apache/apisix/actions/runs/13489934366/job/37686455127#step:19:190
> fix(ai-proxy): abstract a base for ai-proxy

- apisix/plugins/grpc-web.lua
> fix(grpc-web): useless code and code format

- apisix/plugins/ai-content-moderation.lua
- t/plugin/ai-content-moderation2.t
```bash
2025/02/25 04:00:33 [error] 115#115: *8048 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/ai-content-moderation.lua:151: bad argument #2 to 'error' (expected table to have __tostring metamethod)
stack traceback:
coroutine 0:
[C]: in function 'error'
/usr/local/apisix/apisix/plugins/ai-content-moderation.lua:151: in function 'phase_func'
/usr/local/apisix/apisix/plugin.lua:1205: in function 'run_plugin'
/usr/local/apisix/apisix/init.lua:681: in function 'http_access_phase'
access_by_lua(nginx.conf:319):2: in main chunk, client: 172.20.0.1, server: _, request: "POST /post HTTP/1.1", host: "127.0.0.1:9080"
```
This bug is encountered because a table is passed directly to log function. This PR fixes it.
> fix: error while trying to log table in ai-content-moderation plugin

- apisix/plugins/ai-proxy/schema.lua
- docs/en/latest/plugins/ai-proxy-multi.md
- docs/en/latest/plugins/ai-proxy.md
Passing stream option in request body has no effect as it is overridden by default value in the schema. If I want to support stream mode, I need specify stream option in plugin configuration explicitly, which is a bad UX.
> fix(ai-proxy): remove model options' `stream` default value

- apisix/plugins/ai-proxy-multi.lua
- t/plugin/ai-proxy-multi2.t
The number of retries is counted on `ctx.ai_balancer_try_count`, the variable name mismatch will lead to infinite retry loop. This has been fixed.
> fix(ai-proxy-multi): dead loop when retrying

- apisix/plugins/ai-proxy-multi.lua
- apisix/plugins/ai-proxy/schema.lua
- apisix/plugins/ai-rate-limiting.lua
- docs/en/latest/plugins/ai-proxy-multi.md
- docs/en/latest/plugins/ai-proxy.md
- t/plugin/ai-rate-limiting.t
In a previous refactor PR the fallback strategy was removed  in order to accomodate the ai-rate-limiting-plugin. This PR introduces a fallback strategy that fits well with the rate-limiting construct in ai-proxy-multi.
> feat(ai-proxy-multi): implement rate limiting based fallback strategy

- apisix/init.lua
- apisix/plugins/ai-drivers/openai-base.lua
- apisix/plugins/ai-proxy-multi.lua
- apisix/plugins/ai-proxy.lua
- apisix/plugins/ai-proxy/base.lua
- apisix/plugins/ai-proxy/schema.lua
- t/plugin/ai-proxy-multi.balancer.t
- t/plugin/ai-proxy-multi.openai-compatible.t
- t/plugin/ai-proxy-multi.t
- t/plugin/ai-proxy-multi2.t
- t/plugin/ai-proxy.openai-compatible.t
- t/plugin/ai-proxy.t
- t/plugin/ai-proxy2.t
This PR does the following fixes:
checks if the response content-type header is not nil before doing string.find
return 504 if timeout error occurs
weight is required when configuring upstream nodes in ai-proxy-multi
bypass nginx upstream in ai-proxy-multi
add debug logs for ai usage
remove max timeout limit in schema
return http code when read chunk causes error
> chore: rectify business logic/code in ai-proxy

- apisix/plugins/ai-aws-content-moderation.lua
- apisix/secret/aws.lua
- t/plugin/ai-aws-content-moderation-secrets.t
- t/plugin/ai-aws-content-moderation.t
- t/plugin/ai-aws-content-moderation2.t
When initializing the lua-resty-aws module, it may send requests to IDMS endpoint which may timeout in non-aws environment or just introduce delays in some cases. Thus it is good to remove the initialisation from the module level.
Also, it is unnecessary to initialise the module for each request. This problem has also been fixed which ensures that if any there are any delays in initialising the module, such delay would occur only once.
> fix: timeout risk in usages of `lua-resty-aws`

- apisix/plugins/ip-restriction/init.lua
- docs/en/latest/plugins/ip-restriction.md
- t/plugin/ip-restriction.t
Support 404 response code to hide the route from blacklisted/not whitelisted sources
Fixes https://github.com/apache/apisix/issues/12056
> feat(ip-restriction): support 404 response code

- .asf.yaml
- CHANGELOG.md
- apisix/core/version.lua
- docs/en/latest/building-apisix.md
- docs/en/latest/config.json
- docs/zh/latest/building-apisix.md
- docs/zh/latest/config.json
https://lists.apache.org/thread/2l719v58v24sk83rjrfw30fm773j115w
> chore: release 3.12

- docs/en/latest/terminology/credential.md
- docs/zh/latest/terminology/credential.md
When I consulted the terminology/credential document, I found that the API address in the example was different from the API address for creating credentials in the admin-api. I verified that the API address in the terminology/credential example was wrong, and I tried to change it according to the admin-api document.
> docs: change the API address in the terminology credential documentation example

- apisix/plugin.lua
- t/node/plugin1.t
plugins repeats the rewrite phase when consumer configs with a plugin.  
#10945 #10873
> fix: plugins repeats the rewrite phase when consumer configs with a plugin

- apisix/discovery/kubernetes/schema.lua
- t/kubernetes/discovery/kubernetes.t
Fixes https://github.com/apache/apisix/issues/11857
Currently due to schema validation limitation, setting higher shared_size results in following error
``` bash
nginx: [error] init_by_lua error: /home/ashish/dev/apisix/apisix/core.lua:21: failed to parse yaml config: invalid discovery kubernetes configuration: object matches none of the required
stack traceback:
```
> fix: allow for large shared_size in kubernetes discovery

- docs/en/latest/config.json
- docs/en/latest/plugins/ai-rate-limiting.md
Move AI plugins into the AI category and correct `ai-rate-limiting` plugin doc display name
Close #12088.
> docs: move AI plugins into the AI category and correct `ai-rate-limiting` plugin doc display name

- docs/en/latest/plugins/ua-restriction.md
- docs/zh/latest/plugins/ua-restriction.md
Improve `ua-restriction` plugin docs
> docs: improve `ua-restriction` plugin docs

- docs/en/latest/plugins/file-logger.md
- docs/zh/latest/plugins/file-logger.md
Fix wrong data structure in `file-logger` plugin example.
Close #12115
> docs: fix wrong data structure in `file-logger` plugin example

- docs/en/latest/plugins/body-transformer.md
- docs/zh/latest/config.json
- docs/zh/latest/plugins/body-transformer.md
Improve `body-transformer` plugin docs and add Chinese doc.
> docs: improve `body-transformer` plugin docs

- apisix/upstream.lua
- t/discovery/reset-healthchecker.t
Follow up to this fix: https://github.com/apache/apisix/pull/12118
The healthchecker should also be released when new node count is 0.
> fix: release healthchecker on 0 nodes

- apisix/admin/init.lua
- apisix/admin/standalone.lua
- apisix/cli/config.lua
- apisix/cli/file.lua
- apisix/cli/ngx_tpl.lua
- apisix/cli/ops.lua
- apisix/cli/schema.lua
- apisix/core/config_yaml.lua
- ci/linux_openresty_common_runner.sh
- conf/config.yaml.example
- docs/en/latest/deployment-modes.md
- t/APISIX.pm
- t/admin/standalone.spec.ts
- t/admin/standalone.t
- t/discovery/consul_dump.t
- t/jest.config.ts
- t/package.json
- t/pnpm-lock.yaml
- t/tsconfig.json
This PR aims to add an Admin API specialized for Standalone mode to allow users to flush in-memory configurations through them.
The user can pass in the configuration as JSON or YAML via HTTP PUT and it will:
1. Decode input
2. Check each item in the input against the resource's JSON schema
3. Broadcast them to every worker
4. Load them, and APISIX takes effect.
This would make the stateless mode even more stateless, and it would no longer even depend on the file system. This will help our Ingress Controller use case.
In addition to the UPDATE API, there is also a GET API for dumping configurations, which will return the current configuration version and configuration contents.
However, the configuration content will be a deep copy replica of the input content, because APISIX will add …
> feat: add standalone admin api

- .github/workflows/lint.yml
- .licenserc.yaml
- t/package.json
- t/pnpm-lock.yaml
- t/ts/admin_api.ts
- t/ts/utils.ts
- t/tsconfig.esm.json
- t/tsconfig.json
Split from #12196, modifications in functionality and testing frameworks were introduced there, making those PR not pure.
First we can merge this PR, after that rebase that PR, we can make that PR to focus on the function, also easy to backport.
> test: improve typescript-based test framework

- apisix/cli/config.lua
- apisix/plugins/server-info.lua
- conf/config.yaml.example
- docs/en/latest/config.json
- docs/en/latest/plugins/server-info.md
- docs/zh/latest/config.json
- docs/zh/latest/plugins/server-info.md
- t/admin/plugins.t
- t/control/schema.t
- t/debug/debug-mode.t
- t/plugin/server-info.t
Reverts apache/apisix#12218
Stop this undiscussed (and unjustifiably hastily merged) BREAK CHANGE.
> revert: "change: delete the `server-info` plugin"

- apisix/admin/standalone.lua
- apisix/core/config_yaml.lua
- docs/en/latest/deployment-modes.md
- t/admin/standalone.spec.ts
- t/admin/standalone.t
In standalone mode, APISIX’s Admin API currently requires clients to retrieve the entire configuration on every sync. As configurations grow in size or change more often, this full-sync approach can lead to unnecessary network traffic and increased latency in applying updates. Moreover, frequent resource changes force a full rebuild of the internal radixtree, which significantly degrades lookup performance under heavy churn.
In the scenario of service discovery, the upstream will always update frequently, and we hope to only update the upstream without affecting the usage of other resources.
**Control the changes of each resource by adding `<resource-type>_conf_version`**:
```json
{
"consumer_groups_conf_version": 1000,
"consumers_conf_version": 1000,
"global_rules_conf_version": 1000, …
```
> feat(standalone): support revision in API-driven standalone mode like etcd

- apisix/cli/file.lua
The purpose of the `read_yaml_conf` function is to read `config.yaml`, but it also parses and validates `apisix.yaml`. This validation only needs to be performed when the CLI module starts, and there is no need to repeatedly parse and validate apisix.yaml during runtime when try to get `config.yaml`:
https://github.com/apache/apisix/blob/958312fb016f5a63eac22f0955087e1fdc390c54/apisix/core/config_local.lua#L61
Fixes #
> fix: only parse and validate apisix.yaml in cli when startup

- apisix/upstream.lua
- apisix/utils/upstream.lua
When the number of nodes discovered by the service is large, the comparison based on node content in the `compare_upstream_node` function will be very CPU-intensive. Since every request goes through `compare_upstream_node`, this results in much higher CPU consumption for upstreams based on service discovery compared to regular upstreams. 
The current PR optimization approach is to first compare the memory addresses of `nodes` tables in `compare_upstream_node`. If the addresses are identical, it can quickly determine that two `nodes` are identical. 
For this optimization to work, the following conditions must be met:
* All existing and future service discoveries should not modify data on the same table. When a change occurs in a `service_name` corresponding to its `nodes`, a new table …
> perf: compare service discovery nodes by addresss

- apisix/schema_def.lua
- docs/en/latest/admin-api.md
- docs/zh/latest/admin-api.md
- t/admin/metadata.spec.ts
- t/admin/metadata.t
- t/ts/admin_api.ts
This PR organizes the resource schema and ensures that resources that are primarily manipulated by users contain a metadata section consisting of `name`, `desc`, `labels`. 
This will address some issues in downstream projects such as the [new embedded dashboard](https://github.com/apache/apisix-dashboard/issues/2981) or the [API declarative configuration tool for APISIX (ADC)](https://github.com/api7/adc).
| Resource | Status |
|--------|--------|
| Route | name✅ <br> desc✅ <br> labels✅ |
| Service | name✅ <br> desc✅ <br> labels✅ |
| Upstream | name✅ <br> desc✅ <br> labels✅ |
| Consumer | name❌ Replaces `name` and `id` with `username`, which will always have the same value. <br> desc➕ <br> labels✅ | 
| ConsumerCredential | name➕ <br> desc✅ <br> labels✅ | 
| SSL | name❌ SSL does not appear …
> feat: fill in the metadata of resource schema

- apisix/admin/standalone.lua
- apisix/consumer.lua
- apisix/core/config_etcd.lua
- apisix/core/config_yaml.lua
- apisix/schema_def.lua
- apisix/stream/router/ip_port.lua
- t/admin/standalone.spec.ts
- t/cli/test_status_api.sh
> fix(standalone): API-driven mode does not properly handle consumer schema

- .github/workflows/code-lint.yml
- Makefile
- autodocs/generate.sh
- ci/common.sh
- ci/linux_apisix_current_luarocks_runner.sh
CI on master is failing as luarocks install is no longer working due to following reported error: https://github.com/luarocks/luarocks/issues/1797
This PR adds a temporary fix which needs to be reverted after the above issue is fixed.
> fix: temporary fix for broken luarocks server

- apisix/cli/config.lua
- apisix/plugins/server-info.lua
- conf/config.yaml.example
- docs/en/latest/plugins/server-info.md
- docs/zh/latest/plugins/server-info.md
- t/admin/plugins.t
- t/debug/debug-mode.t
mark `server-info` plugin as deprecated and update docs
mailing list: https://lists.apache.org/thread/nrwqo1gbc0z4z48fkb8dd4rn0trnfnz9
> change: mark `server-info` plugin as deprecated

- apisix/core/ctx.lua
- t/core/ctx3.t
Fixes #
While  calculating the value of the key, the current logic overrides the original key and stores the wrong key in the cache causing cache miss. This PR makes sure that original key is not modified.
> fix: original key being modified causing cache inconsistency

- utils/linux-install-luarocks.sh
Fixes #
Recently a bug was found in luarocks which is fixed in luarocks 3.12.0.
This will also help revert: https://github.com/apache/apisix/pull/12277
> chore: upgrade luarocks version

- CHANGELOG.md
This PR reviews the changelog entries for versions after APISIX 3.8.0 to identify any missing entries.
**Note**: PRs related to documentation, chores, tests, and CI changes should not be included in the changelog.
The following table lists PRs that need to be added to the changelog (marked as "Yes" in the "Missing" column).
| PR Title | PR Link | Missing | Notes |
| --- | --- | --- | --- |
| feat: support uri_arg_ when use radixtree_uri_with_parameter | https://github.com/apache/apisix/pull/10645 | Yes | - |
| Revert "fix: the leak of prometheus metrics (#10655)" (#11025) | https://github.com/apache/apisix/pull/10655 | No | Revert PR |
| fix: linux-install-luarocks are not compatible with the openresty environment (#10813) | https://github.com/apache/apisix/pull/10813 | Yes | - |
| …
> docs: update CHANGELOG with recent changes

- apisix/admin/standalone.lua
- t/admin/standalone.t
add duplicate resource check in API-driven standalone mode
Fixes #12259
> fix: check if `config` contains duplicate resources in API-driven standalone mode

- apisix/discovery/consul/init.lua
- docs/en/latest/discovery/consul.md
- t/discovery/consul2.t
When using consul as a service registry, if a user registers a service without filling in the port number, the default value is not set in apisix, resulting in `svc_port` possibly being `nil`, which in turn results in `local service_id = svc_address ... “:” ... svc_port` cannot be spliced.
Fixes https://github.com/apache/apisix/issues/11134
> fix: handle consul nil port cases by defaulting to port 80

- .github/workflows/check-changelog.yml
- CHANGELOG.md
- ci/check_changelog_prs.ts
This PR provides a script to check the changelog for completeness. If a PR is not of type docs, chore, test, or ci, and is not listed in the IGNORE_PRS variable, but is missing from the changelog, the script will raise an error.
Note: This script currently only checks changelog entries for versions after 3.8.0.
1. Manually removed a changelog entry for version 3.12.0, and the script correctly reported an error.
2. Tested an upcoming version (e.g., 3.13.0) that hasn’t been tagged yet to verify if the script works correctly. In this case, it compares the current latest code from the main branch with the previous version (3.12.0).
> ci: add GitHub Action to check CHANGELOG consistency with PRs

- t/admin/filter.t
failed jobs:
https://github.com/apache/apisix/actions/runs/15817495697/job/44579024603
https://github.com/apache/apisix/actions/runs/15821515715/job/44591668640
the result of 
```
ngx.encode_args({ service_id = "1", upstream_id = "1" })
```
is `service_id=1&upstream_id=1` or `upstream_id=1&service_id=1`, the order of `service_id` and `upstream_id` is random.
so the final uri is `/apisix/admin/routes?filter=service_id=1&upstream_id=1` or  `/apisix/admin/routes?filter=upstream_id=1&service_id=1`, because second one meaning only filter by `upstream_id=1`, and the result is same as `service_id=1 && upstream_id=1`, so this test case working sometimes.
Fixes #
> fix: flaky t/admin/filter.t due to url encoding for query params

- apisix/core/ctx.lua
- t/core/ctx3.t
Fixes #
For each request, the following log is printed multiple times and the logs get flooded with it. The primary purpose for this log was for testing so it should be set to debug.
> refactor: change log level to debug to avoid unnecessary logs

- apisix/cli/ngx_tpl.lua
- apisix/discovery/nacos/init.lua
- apisix/discovery/nacos/schema.lua
- t/APISIX.pm
- t/discovery/nacos.t
- t/discovery/nacos2.t
Breakout from: https://github.com/apache/apisix/pull/12263
Fixes #
Currently nacos discovery uses event library and during testing it was found out that when using lua-resty-events, sometimes not all workers get the events. And inconsistencies emerge. Moreover the idiomatic way to share data between workers is through a shared dict. Therefore this PR migrates nacos from older events mechanism to newer shared dict way. Now only priviliged agent will fetch data from nacos and write to shdict while all workers will read from it.
> feat: replace events library with shdict

- .github/workflows/build.yml
Fixes #
- https://github.com/apache/apisix/pull/3521 This PR had added a release check to package and upload release artifact.
- https://github.com/apache/apisix/pull/5567 This PR removed the release artifact step but the rest of the steps were left which are of no use now.
Those steps also are failing CI on release PR: https://github.com/apache/apisix/pull/12378 and can be removed
> ci: remove redundant package steps

- apisix/cli/etcd.lua
- t/cli/test_deployment_data_plane_with_readonly-etcd.sh
- t/cli/test_deployment_data_plane_with_readonly_etcd.sh
**What**
This PR implements skipping write operations to etcd when the `deployment.role` is `data_plane`.
**How**
Make a judgment in `etcd.init()`.
**Why**
Since `init_etcd` is called directly in https://github.com/apache/apisix-docker/blob/release/apisix-3.2.2/debian-dev/docker-entrypoint.sh#L39-L40, it does not make judgments like in https://github.com/apache/apisix/blob/3.2.2/apisix/cli/ops.lua#L821-L823. Causes apisix running as a container, there will be a problem when `deployment.role` is `data_plane`.
From a maintenance perspective, I also want to avoid adding things in places like `docker-entrypoint.sh`, as this would obviously duplicate more code. As for testing, there's currently no direct testing of the APISIX container, and it's difficult for me to do this in a short amount of …
> fix:  deployment data plane with read-only etcd

- .github/workflows/build.yml
- apisix/plugins/elasticsearch-logger.lua
- ci/pod/docker-compose.plugin.yml
- docs/en/latest/plugins/elasticsearch-logger.md
- docs/zh/latest/plugins/elasticsearch-logger.md
- t/plugin/elasticsearch-logger.t
Fixes 
Error comes when using elasticsearch version 9+
We want to remove the compat header and have a general support for all major versions.
For elasticsearch logger plugin comptability check. Following are the observations and conclusion based on reading docs and self testing.
The `type` field issue:
Before version 7, the `type` field was required in json schema https://github.com/elastic/elasticsearch/blob/8453f7701de25c467ce08088ddddac185cb8028c/rest-api-spec/src/main/resources/rest-api-spec/api/create.json#L21.
The current tests without `type` fail on version 6(here it's 6.7) with the following error
Batch Processor[elasticsearch-logger] failed to process entries: elasticsearch server returned status: 400, body: {"error":{"root_cause":[{"type":"action_request_validation_exception","re …
> fix: support multiple versions of Elasticsearch logger

- apisix/consumer.lua
- t/admin/consumer-credentials.t
Fixes https://github.com/apache/apisix/issues/12393
This PR introduced a critical bug https://github.com/apache/apisix/pull/11840 due to which consumers are not updated  until a subsequent update in credentials due to credential version being used even for checking consumer update.
More context on this comment: https://github.com/apache/apisix/pull/11840/files#r2193898420
> fix(consumer): missed consumer update due to wrong version in cache

- apisix/plugins/zipkin.lua
- t/plugin/mcp-bridge.t
- t/plugin/zipkin3.t
According to Zipkin's documentation, the TraceID passed via HTTP headers uses lowercase hexadecimal encoding, not binary data. For example, the B3 specification states that the value of the X-B3-TraceId header is 16 or 32 lowercase hexadecimal characters (corresponding to 64 or 128 bits, respectively)
- https://zipkin.io/pages/instrumenting.html#:~:text=Ids%20are%20encoded%20as%20hex,strings
- https://github.com/openzipkin/b3-propagation?tab=readme-ov-file#traceid-1
We need to convert the trace_id and span_id formats stored in the variables.
Fixes #12271
> fix: zipkin trace_id and span_id format in ngx_var

- apisix/cli/ngx_tpl.lua
- apisix/cli/ops.lua
- docs/en/latest/plugins/opentelemetry.md
- docs/zh/latest/plugins/opentelemetry.md
We changed the attribute of the Opentelemetry plugin to metadata in PR https://github.com/apache/apisix/pull/11940. After that, users can set the `set_ngx_var` property in metadata. However, the generated template file still relies on the `set_ngx_var` property from the plugin attribute to predefine variables https://github.com/apache/apisix/blob/master/apisix/cli/ops.lua#L553-L556, which will confuse users. This PR removes this judgment and allows this property to be controlled in metadata only.
Fixes #12402
> fix(opentelemetry): remove plugin attr set_ngx_var

- apisix/plugins/ai-drivers/openai-base.lua
- apisix/plugins/ai-request-rewrite.lua
- apisix/plugins/chaitin-waf.lua
- ci/common.sh
- ci/linux_openresty_common_runner.sh
- ci/redhat-ci.sh
- t/plugin/ai-proxy.openai-compatible.t
- t/plugin/ai-rate-limiting.t
- t/plugin/ai-request-rewrite2.t
- t/plugin/ai3.t
- t/plugin/chaitin-waf-reject.t
The test here https://github.com/apache/apisix/actions/runs/16511586539/job/46694453675
failed due to invalid configuration but in case of Bailout, the tests is considered successful. This change asserts and finds for the bailed out test and fails CI if any test was bailed out.
The following tests fail after the changes in script in this pr https://github.com/apache/apisix/actions/runs/16519080359/job/46716551717
https://github.com/apache/apisix/actions/runs/16519816286/job/46718888226?pr=12462#step:16:236
I have modified the above tests to finally pass.
The doc says
"By default the test scaffold treats NGINX server startup failures as fatal errors in running the tests. The must_die section, however, turns such a failure into a normal test checkup."
If you have just one test then it holds …
> fix: skipped failing bailedout tests in CI

- docs/en/latest/installation-guide.md
- docs/zh/latest/installation-guide.md
> docs: update rpm installation guide

- apisix/core/utils.lua
- apisix/plugins/forward-auth.lua
- docs/en/latest/plugins/forward-auth.md
- docs/zh/latest/plugins/forward-auth.md
- t/plugin/forward-auth.t
The existing regex in util.resolve_var doesn't handle all the variable cases properly. For eg: when passed with $post_arg.xyz, it fails to resolve the variable. So regex is being modified to support the aforementioned key.
This was not caught previously because the test cases didn't assert the values properly.
> fix(forward-auth): extra_headers not resolving variable on $post_arg.

- apisix/utils/batch-processor-manager.lua
- apisix/utils/batch-processor.lua
- t/plugin/kafka-logger.t
When merging the configurations of service and route, APISIX will first perform a deepcopy on the configuration of the service. 
https://github.com/apache/apisix/blob/e3e5a99d0fab06d920707a8731401b72341aabfa/apisix/plugin.lua#L585-L586
This results in each route associated with this service getting an independent plugin configuration table, causing the cache in `batch-processor-manager.lua` that is based on table memory addresses as keys to not work properly.
After this fix, every logger plugin that integrated with `batch-processor-manager.lua` can share the same batch processor object as long as the plugin configuration is identical. For example, with kafka-logger, even if the exact same kafka-logger plugin is configured on different services, the batch processor object and kafka …
> fix: batch processor cache not working when configure plugin in service

- apisix/cli/ngx_tpl.lua
- apisix/core/ctx.lua
- apisix/plugins/ai-drivers/openai-base.lua
- apisix/plugins/ai-proxy-multi.lua
- apisix/plugins/ai-proxy.lua
- apisix/plugins/ai-proxy/base.lua
- apisix/plugins/ai-request-rewrite.lua
- apisix/plugins/prometheus/exporter.lua
- conf/config.yaml.example
- docs/en/latest/plugins/ai-proxy-multi.md
- docs/en/latest/plugins/ai-proxy.md
- docs/en/latest/plugins/prometheus.md
- docs/zh/latest/plugins/prometheus.md
- t/APISIX.pm
- t/plugin/ai-proxy-multi.balancer.t
- t/plugin/ai-proxy-multi.openai-compatible.t
- t/plugin/ai-proxy-multi.t
- t/plugin/ai-proxy-multi2.t
- t/plugin/ai-proxy3.t
- t/plugin/ai-rate-limiting.t
- t/plugin/prometheus-ai-proxy.t
- t/plugin/prometheus.t
- t/plugin/prometheus2.t
- t/plugin/prometheus3.t
- t/plugin/prometheus4.t
This PR adds two things:
1. It adds latency and token info for ai-proxy plugin in the access log for easy debugging.
2. It adds prometheus metrics for ai related requests and adds two more labels `request_type` to distinguish between normal requests and ai related requests & `llm_model`
Fixes #
> feat(ai-proxy): add latency and usage in access log and prometheus metrics

- apisix/cli/config.lua
- apisix/core/config_etcd.lua
- conf/config.yaml.example
- t/cli/test_load_full_data_init_worker.sh
When using etcd as the config server, the apisix master process performs a full data load during the init phase and saves the result in `loaded_configuration`. After the master forks other worker processes, these worker processes will directly initialize configurations based on `loaded_configuration`:
https://github.com/apache/apisix/blob/1b0bb84ccf343bd1aedc4bfff1afa9fcefb7c4d5/apisix/core/config_etcd.lua#L1023-L1031
Since `loaded_configuration` in the master process is not continuously updated, after running for some time, `loaded_configuration` may become outdated. If a worker restarts at this point, it will use an outdated configuration for initialization. If any requests are sent to this worker at that time, these requests may be processed by incorrect confiurations.
Because the …
> fix(etcd): load full data from etcd while worker restart

- apisix/plugins/ai-drivers/openai-base.lua
- t/plugin/ai-proxy3.t
In the user's environment, the content field returned by the LLM service may be null. Our code needs to handle this case to avoid panic:
```
apisix/plugins/ai-drivers/openai-base.lua:160: invalid value (userdata) at index 1 in table for 'concat'
```
> fix(ai-proxy): check type of choices/usage/content fields before use it

- apisix/plugins/ai-drivers/openai-base.lua
In the previously merged PR, `ctx.llm_raw_usage` was being set in the stream mode but missed in non stream mode. 
https://github.com/apache/apisix/pull/12530/files
> fix: missing ctx.llm_raw_usage in non-stream mode

- apisix/plugins/ai-proxy-multi.lua
- t/plugin/ai-proxy-multi.t
I noticed that when invalid url is passed in override endpoint like "http//localhost:8080" (here : is missing). The ai configuration is still accepted.
But later error comes in user request path and user gets 500
This PR adds endpoint validation during schema check.
> fix(ai-proxy): catch malformed override endpoint in schema validation

- apisix/plugins/ai-proxy-multi.lua
- t/plugin/ai-proxy-multi3.t
```
local endpoint = core.table.try_read_attr(instance_conf, "override", "endpoint")
```
endpoint will be nil when user use official ai service as instance.
> fix(ai-proxy-multi): panic when instance dont have custom endpoint

- apisix-master-0.rockspec
- apisix/plugins/request-id.lua
- docs/en/latest/plugins/request-id.md
- docs/zh/latest/plugins/request-id.md
- t/plugin/request-id3.t
Feat # https://github.com/apache/apisix/issues/12559
This pr introduces the ksuid algorithm for request-id which generates a sequential ID always 27 characters encoded in alphanumeric base62 that will lexicographically sort by timestamp. retain their time-ordered property through a string and it enough 128-bit of randomness  to provide strong protection against collisions (duplicates)，more than uuid
e.g.
``` text
ksuid：325ghCANEKjw6Jsfejg5p6QrLYB
REPRESENTATION:
String: 325ghCANEKjw6Jsfejg5p6QrLYB
Raw: 15430DBBD7F68AD7CA0AE277772AB36DDB1A3C13
COMPONENTS:
Time: 2025-09-01 16:39:23 +0800 CST
Timestamp: 356715963
Payload: D7F68AD7CA0AE277772AB36DDB1A3C13
```
- [√] I have explained the need for this PR and the problem it solves
- [√] I have explained the changes or the new features added to …
> feat: add ksuid algorithm on request-id plugin

- apisix/events.lua
- apisix/healthcheck_manager.lua
This PR fixes a spelling error in the function name `get_healthcheck_events_modele` to `get_healthcheck_events_module`. The typo in the function name ("modele" instead of "module") could cause confusion and potential issues when calling this function.
Fixes #
> fix: correct spelling error in get_healthcheck_events_module function name

- docs/en/latest/deployment-modes.md
Update notes for API-drive standalone mode. Remove the experimental label for the next release (3.14.0).
> docs: update notes for API-drive standalone mode

- apisix/cli/config.lua
- apisix/core/lrucache.lua
- apisix/init.lua
- apisix/secret.lua
- conf/config.yaml.example
- t/core/lrucache.t
- t/router/radixtree-sni2.t
Our secret feature includes an LRU cache to store values obtained from the secret provider (vault, AWS, GCP) to reduce the number of requests to the secret provider. However, due to without `invalid_stale` parameter, this cache never expires. https://github.com/apache/apisix/blob/9ae24032b6177daa6dfd31de04bfedc435a842d5/apisix/ssl/router/radixtree_sni.lua#L241-L242 https://github.com/apache/apisix/blob/9ae24032b6177daa6dfd31de04bfedc435a842d5/apisix/secret.lua#L188-L190 https://github.com/apache/apisix/blob/9ae24032b6177daa6dfd31de04bfedc435a842d5/apisix/core/lrucache.lua#L54-L62
However, if only the `invalid_stale` parameter is specified, when the cache entry expires, it will be necessary to query the secret provider to obtain the secret while receiving downstream requests. This can …
> fix(secret): refresh stale lru cache item in background

- apisix/cli/ngx_tpl.lua
- t/cli/test_admin_ui.sh
add absolute_redirect off; in /ui location to fix redirect port err
Fixes #12511
> fix: embedded UI redirect error when behind proxy

- apisix/plugins/redirect.lua
- t/plugin/redirect.t
In the original logic, using values like `X-Forwarded-Proto: any_value` could bypass the redirect.
Obviously, this logic is incorrect, so in this PR it's adjusted to redirect when `X-Forwarded-Proto` is not `https`.
part of #12500 
Fixes #
> fix(plugin/redirect): ensure redirect when scheme is not `https`

- apisix/init.lua
- t/admin/standalone.t
In order for the admin API  standalone mode to work properly in the stream subsystem, we need to execute the `apisix.admin` module initialization function like in the HTTP subsystem: https://github.com/apache/apisix/blob/5e804cf26e4d283a417c40698219ff99ddeda4c4/apisix/admin/standalone.lua#L415-L455. The previous test cases called `/apisix/admin/configs` API in a prior test case and then test-nginx performed a reload, which led to executing the following code and failed to detect that the backend timer was not started correctly. https://github.com/apache/apisix/blob/5e804cf26e4d283a417c40698219ff99ddeda4c4/apisix/core/config_yaml.lua#L395-L429
Fixes #
> fix: run init_worker of apisix.admin module in stream subsystem
