doc/architecture-design-cn.md
lua/apisix/balancer.lua
t/APISix.pm
t/balancer.t

fixed https://github.com/iresty/apisix/issues/65

feature: supported consistent hash for dynamic load balancing.

---

lua/apisix/admin/init.lua
lua/apisix/admin/routes.lua
lua/apisix/admin/services.lua
lua/apisix/core/config_etcd.lua
lua/apisix/core/schema.lua
t/admin/services.t
t/node/not-exist-service.t

feature: use schema check for service configuration.

---

lua/apisix/admin/init.lua
lua/apisix/admin/upstreams.lua
lua/apisix/core/schema.lua
t/admin/upstream.t

feature: used schema to check the upstream configuration.

---

README.md
README_CN.md

moved the "plugins" section to the beginning of the document.

doc: added section `Install APISIX Development Environment`.

---

.travis.yml

travis: skipped the test case when install `test::nginx` library.

---

lua/apisix/core/config_etcd.lua

bugfix: avoid generating huge duplicate error logs when synchronizing data from etcd.

---

lua/apisix/consumer.lua
lua/apisix/core/config_local.lua

bugfix: modify the tips and add a error tips when read config file.

---

doc/https-cn.md

doc: need Chinese version, support to load certificate for HTTPS request

---

lua/apisix/plugins/limit-conn.lua
lua/apisix/plugins/limit-count.lua
lua/apisix/plugins/limit-req.lua
t/plugin/limit-conn.t
t/plugin/limit-count.t
t/plugin/limit-req.t

Fix https://github.com/iresty/apisix/issues/187

bugfix plugin: used config's version as a part of `key`.

---

bin/apisix
conf/config.yaml

Hi there, this is a very simple change, please review it, thx.

Support configure node_ssl_listen

---

Makefile
README.md
README_CN.md
bin/apisix
lua/apisix/plugins/node-status.lua

feature: added `init` action in makefile to initialize the runtime

---

.travis.yml
Makefile
README.md
README_CN.md
bin/apisix

bugfix: compiled module 'rapidjson' with the luajit of openresty.

---

Makefile

Hi, there
Please review it, thx.

Add copy http/*.lua in Makefile

---

doc/https-cn.md

Update the doc of Chinese version https according the  already updated English version. #237

update the doc of https for Chinese version.

---

README.md
README_CN.md
bin/apisix
doc/benchmark-cn.md
doc/benchmark.md
doc/https-cn.md
doc/https.md
doc/plugins-cn.md
doc/plugins.md
doc/plugins/key-auth-cn.md
doc/plugins/key-auth.md
doc/plugins/limit-conn-cn.md
doc/plugins/limit-conn.md
doc/plugins/limit-count-cn.md
doc/plugins/limit-count.md
doc/plugins/limit-req-cn.md
doc/plugins/limit-req.md
doc/plugins/prometheus-cn.md
doc/plugins/prometheus.md

add the openresty version check

---

doc/architecture-design-cn.md
doc/libr3.md

fixed https://github.com/iresty/apisix/issues/253

doc: added doc for how to use libr3.

---

bin/apisix

use 4 space instead of `tab`.
simple code style.
short length of source code.

change(CLI): code style.

---

lua/apisix/http/balancer.lua

fix: https://github.com/iresty/apisix/issues/262

bugfix: do nothing for current checker when worker is exiting.

---

.travis/linux_runner.sh
Makefile
rockspec/apisix-0.5-0.rockspec
rockspec/apisix-dev-0.rockspec

use local path when install development ENV.

luarocks: code style.

---

bin/apisix

check the openresty version in Lua land.

---

bin/apisix

change(CLI): simple code style and check the openresty version at `init`

---

doc/architecture-design-cn.md

close https://github.com/iresty/apisix/issues/282

fix document error

---

lua/apisix/core/schema.lua
t/admin/consumers.t
t/admin/routes.t
t/admin/services.t
t/admin/upstream.t
t/plugin/limit-req.t

fixed https://github.com/iresty/apisix/issues/284

feature: added desc for upstream and service in schema. 

---

doc/architecture-design-cn.md
doc/health-check.md
doc/plugins/limit-count-cn.md
doc/plugins/limit-count.md

fixed some small wrong in doc.

 doc: added new doc about health check.

---

lua/apisix/core/schema.lua
t/admin/health-check.t

Add json schema default value and some constraint such as `minimum`, `maximum`  for `healthcheck` schema. Some test cases are also added in t/admin/health-check.t
Fixes #266

add health check json schema constraint and test cases. 

---

bin/apisix

Fix node_ssl_listen conf not working

---

bin/apisix
conf/nginx.conf

only has the allow is useless, which is must works with deny. it's security problem.

bugfix: fixed wrong of allow and deny in nginx.conf.

---

rockspec/apisix-dev-1.0-0.rockspec

luarocks do not support to use latest dependencies.

luarocks: use dependencies with specified version.

---

bin/apisix
conf/config.yaml

fixed https://github.com/iresty/apisix/issues/339

feature: support multiple ips of `allow`.

---

bin/apisix

Hi, this is a missing modify in commit 6e457bfc078b20a64a0fafb5f3371bd138941eef

bugfix: fixed wrong allow in /apisix/dashboard

---

lua/apisix/admin/services.lua
lua/apisix/admin/upstreams.lua
lua/apisix/http/balancer.lua
t/node/upstream.t

bugfix: failed to fetch upstream id in `balancer` phase.

---

.travis.yml
rockspec/apisix-dev-1.0-0.rockspec
t/node/healthcheck.t
t/node/host.t
t/node/match-host-uri.t
t/node/merge-route.t
t/node/sanity.t
t/node/timeout-upstream.t
t/node/upstream.t

fix: https://github.com/iresty/apisix/issues/358

luarocks: update `lua-resty-libr3` to version 1.0.

---

rockspec/apisix-0.6-0.rockspec

release version 0.6.

---

Makefile

fixed https://github.com/iresty/apisix/issues/375

bugfix: created dir for zipkin.

---

lua/apisix/core/json.lua
lua/apisix/core/lrucache.lua
lua/apisix/http/balancer.lua
t/core/lrucache.t

feature: add new option `release`, will release it automatically

---

doc/install-dependencies.md

Up install luarocks in Debian 9

---

lua/apisix/plugins/limit-conn.lua
lua/apisix/plugins/limit-count.lua
lua/apisix/plugins/limit-req.lua
t/plugin/limit-count.t

bugfix: allowed to use more limit key.

---

lua/apisix/core/config_etcd.lua
lua/apisix/http/balancer.lua
lua/apisix/plugin.lua
t/APISix.pm
t/lib/test_admin.lua
t/node/healthcheck-stop-checker.t

bugfix: stop the checker if the config source is changed.

---

conf/config.yaml
lua/apisix/http/router/radixtree_sni.lua
t/APISix.pm
t/router/r3-host-uri.t
t/router/radixtree-sni.t

default router to `radixtree_uri` and `radixtree_sni`.

feature(router): implemented new SNI router `radixtree_sni`, and change

---

.travis/linux_runner.sh
.travis/osx_runner.sh
Makefile
doc/architecture-design-cn.md
doc/libradixtree.md
lua/apisix.lua
lua/apisix/admin/init.lua
lua/apisix/admin/schema.lua
rockspec/apisix-dev-1.0-0.rockspec
t/APISix.pm
t/admin/schema.t
t/node/sanity-r3.t
t/node/sanity-radixtree.t
t/node/wildcard-host.t
t/router/r3-sni.t
t/router/radixtree-sni.t

change(router): use `radixtree_sni` as default SSL router.

---

bin/apisix
lua/apisix/core.lua
lua/apisix/core/version.lua

fixed https://github.com/iresty/apisix/issues/420

feature: added `version` option for CLI.

---

FAQ.md
FAQ_CN.md
README.md
README_CN.md

Fix https://github.com/iresty/apisix/issues/400

doc(Q/A): why etcd.

---

doc/plugins/jwt-auth-cn.md
t/plugin/jwt-auth.t

fixed https://github.com/iresty/apisix/issues/454

change(plugin): name style.

---

doc/architecture-design-cn.md
lua/apisix/schema_def.lua
t/admin/routes.t
t/lib/test_admin.lua

Support HTTP Method 'CONNECT' & 'TRACE'

support http method 'connect' & 'trace'

---

FAQ.md
FAQ_CN.md

删除FAQ和FAQ_CN中的多余符号

---

.travis/linux_runner.sh
doc/doc-index.md

Fix https://github.com/iresty/apisix/issues/550

doc: doc index.

---

doc/plugins/ip-restriction-cn.md
doc/plugins/ip-restriction.md
doc/plugins/jwt-auth-cn.md

something about: https://github.com/iresty/apisix/pull/546

doc(ip-restriction): style.

---

.travis/linux_runner.sh
lua/apisix/plugins/ip-restriction.lua
rockspec/apisix-dev-1.0-0.rockspec
t/plugin/ip-restriction.t

Fix https://github.com/iresty/apisix/issues/557

change: used `resty-matcher` to match ip address, which support IPv6.

---

COPYRIGHT
README.md
doc/plugins/jwt-auth.md

Apisix #567

---

README_CN.md
doc/stream-proxy-cn.md
doc/stream-proxy.md
utils/install-apisix.sh

Apisix #596 #598

---

Makefile
utils/install-apisix.sh

fix: https://github.com/iresty/apisix/issues/597

bugfix: avoided using temporary files to get the LuaJIT main path.

---

doc/admin-api-cn.md
lua/apisix/admin/init.lua
lua/apisix/admin/node_status.lua
lua/apisix/core/etcd.lua
t/plugin/node-status.t

feature: added new admin api `/admin/node_status`.

---

README.md
README_CN.md
doc/doc-index.md

doc: added doc for `proxy-rewrite` plugin.

---

CHANGELOG.md
CHANGELOG_CN.md
README.md
README_CN.md

https://github.com/iresty/apisix/blob/master/Contributing.md#how-to-add-a-new-feature-or-change-an-existing-one
SUMMARY_HERE
* ...
Fix #XXX

changelog: added changelog for 0.8.

---

README.md

In README: Deleted the table with supported systems and replaced it with a simple unordered list.
Resolves #565

change doc: deleted table and changed it to list 

---

lua/apisix/schema_def.lua

bugfix: removed uesless schema of upstream.

---

README.md
README_CN.md
doc/plugins/proxy-rewrite-cn.md
doc/plugins/proxy-rewrite.md
lua/apisix/core/request.lua
lua/apisix/plugins/proxy-rewrite.lua
t/plugin/proxy-rewrite.t

change: proxy-rewrite plugin add request headers rewriting

---

lua/apisix/core/version.lua

* [bugfix]: change apisix/core/version to 0.8.
* [bugfix]: change apisix/core/version to 0.8.

bugfix(version.lua): change version to 0.8.

---

README_CN.md

close https://github.com/iresty/apisix/issues/655

doc: Update README_CN

---

doc/architecture-design.md

close https://github.com/iresty/apisix/issues/645
we can preview the doc here:
https://github.com/juzhiyuan/apisix/blob/master/doc/architecture-design.md

doc: translate architecture-design.md to English

---

conf/config.yaml
lua/apisix/http/router/radixtree_host_uri.lua
t/router/radixtree-host-uri.t

base on https://github.com/iresty/apisix/pull/670
TODO：support wildcard host name. (fixed)

feature: support for `host + uri` as an index (radixtree)

---

README.md
README_CN.md
doc/plugins/proxy-rewrite-cn.md
doc/plugins/proxy-rewrite.md
t/plugin/proxy-rewrite.t

fixed https://github.com/iresty/apisix/issues/658

feature: support remove header in rewrite plugin.

---

bin/apisix
conf/config.yaml

Apisix #533

---

lua/apisix/core/config_etcd.lua

fix https://github.com/iresty/apisix/issues/709

bugfix: updated the etcd index id.

---

bin/apisix
conf/config.yaml

fixed https://github.com/iresty/apisix/issues/697

bugfix: removed epoll in nginx.conf.

---

doc/plugins/limit-count-cn.md
doc/plugins/limit-count.md
lua/apisix/plugins/limit-count.lua
lua/apisix/plugins/limit-count/limit-count-redis.lua
t/plugin/limit-count-redis.t

plugin(limit-count): put the redis configuration to root directory.

---

.travis.yml
COPYRIGHT
doc/install-dependencies.md
lua/apisix/core/schema.lua
lua/apisix/plugins/example-plugin.lua
lua/apisix/plugins/prometheus.lua
lua/apisix/plugins/zipkin.lua
rockspec/apisix-master-0.rockspec
t/admin/global-rules.t
t/admin/health-check.t
t/admin/routes.t
t/admin/services.t
t/admin/ssl.t
t/admin/upstream.t
t/node/invalid-upstream.t
t/plugin/example.t
t/plugin/ip-restriction.t
t/plugin/jwt-auth.t
t/plugin/key-auth.t
t/plugin/limit-conn.t
t/plugin/limit-count.t
t/plugin/limit-req.t
t/plugin/openid-connect.t
t/plugin/prometheus.t
t/plugin/proxy-rewrite.t
t/plugin/serverless.t
t/plugin/zipkin.t

lua-resty-jsonschema is faster and easy to compile.
todo items:

change: used `lua-resty-jsonschema` instead of `lua-rapidjson`.

---

README.md

Added [Authing](https://authing.cn) into Idp
@juzhiyuan

Added Authing into IdP

---

doc/plugins/jwt-auth.md

Fixed some markdown syntax in jwt-auth.md.

doc: Update jwt-auth.md

---

README.md

https://github.com/iresty/apisix/blob/master/Contributing.md#how-to-add-a-new-feature-or-change-an-existing-one
- Add a section for deployment on public cloud 
- Add link to tutorials about the recommended APISIX deployment in AWS
* [doc] Add a section for deployment on public cloud 
* [doc] Add link to tutorials about the recommended APISIX deployment in AWS

Update README.md - Add AWS deployment tutorial link

---

lua/apisix/plugin.lua
t/plugin/jwt-auth.t
t/plugin/node-status.t
t/plugin/prometheus.t

fix the wrong "method" restriction in plugin's inner api
Fix #750

bugfix: fix issue #750

---

doc/dev-manual-cn.md
doc/dev-manual.md

Add `TEST_NGINX_BINARY`  environment variables description for dev-manual doc

Doc update

---

Makefile

fix: https://github.com/apache/incubator-apisix/issues/763
Bugfix: change dir  apisix into incubator-apisix
Makefile

Bugfix: change dir  apisix into incubator-apisix

---

bin/apisix
doc/dev-manual-cn.md
doc/dev-manual.md

add restart apisix server command
* ...
Fix #XXX

add restart apisix server command

---

doc/plugins/redirect-cn.md

resolve https://github.com/iresty/apisix/issues/735
related PR https://github.com/iresty/apisix/pull/732

doc: redirect-cn.md

---

.travis/ASF-Release.cfg
doc/plugins/redirect-cn.md
doc/plugins/redirect.md
lua/apisix/plugins/redirect.lua
t/plugin/redirect.t

`grpc_server_example` is only for run test cases in Travis CI.

license: ingore grpc_server_example dir for check license.

---

doc/powered-by.md

Doc: add HelloTalk into powered-by

---

doc/grpc-proxy-cn.md
doc/grpc-proxy.md
t/grpc-proxy-test.sh

Fix https://github.com/apache/incubator-apisix/issues/780

ASF: added license header.

---

doc/https-cn.md

Fix typo
fix https://github.com/apache/incubator-apisix/issues/759

docs: fix typo

---

.travis.yml
.travis/ASF-Release.cfg

travis: only start the redis server for linux os.

---

README.md

Changed wording for clarity in README.md

---

doc/grpc-proxy-cn.md
doc/grpc-proxy.md
doc/plugins/grpc-transcoding-cn.md
doc/plugins/grpc-transcoding.md
lua/apisix/plugins/grpc-transcode.lua
lua/apisix/plugins/redirect.lua
t/node/route-filter-func.t
t/router/radixtree-uri-host.t

To make `t/plugin/ip-restriction.t` pass, need to make a new release of https://github.com/iresty/jsonschema.

chore: fixed typo detected by misspell

---

CHANGELOG.md
CHANGELOG_CN.md

Update v0.9.0-rc1 CHANGELOG.md and CHANGELOG_CN.md.

change: update v0.9.0-rc1 changelog.

---

doc/powered-by.md

add tangdou into powereby page

---

doc/plugins/proxy-rewrite-cn.md

bugfix: `proxy-rewrite-cn.md` enable plugin example error.

---

doc/grpc-proxy-cn.md
doc/grpc-proxy.md
doc/plugins/grpc-transcoding-cn.md
doc/plugins/grpc-transcoding.md

fix grpc server example link.
* fix grpc server example link.

fix: grpc server example link

---

t/admin/services.t

fix: typo in test cases #508

---

doc/install-dependencies.md

openresty -> OpenResty
resolve https://github.com/apache/incubator-apisix/issues/848

fix writing rule

---

lua/apisix/plugins/proxy-rewrite.lua

optimization code performance 
* lua\apisix\plugins\proxy-rewrite.lua

optimization: performance upgrade for proxy-rewrite by avoid luajit NYI

---

README.md
README_CN.md

SUMMARY_HERE
* ...
Fix # Centos7中使用 systemctl命令

doc: fix typo in README_CN.md

---

doc/plugins/limit-conn.md

fix error in limit-conn.md

---

lua/apisix/core/log.lua
t/core/log.t

If we cache level in the require file, it might be wrong.

bugfix: fetch the current log level when needs.

---

lua/apisix/balancer.lua
t/node/chash-balance.t

Fix https://github.com/apache/incubator-apisix/issues/892

bug: maybe no valid upstream node.

---

.travis/linux_openresty_runner.sh
.travis/linux_tengine_runner.sh
.travis/osx_openresty_runner.sh
Makefile
README.md
README_CN.md
lua/apisix/core/version.lua

fixed https://github.com/apache/incubator-apisix/issues/902 and https://github.com/apache/incubator-apisix/issues/901

bugfix: fixed install deps in makefile.

---

.travis.yml
.travis/osx_openresty_runner.sh

fixed https://github.com/apache/incubator-apisix/issues/901

travis: removed luacheck for macos.

---

doc/plugins/grpc-transcoding-cn.md
lua/apisix/plugins/grpc-transcode.lua
lua/apisix/plugins/grpc-transcode/request.lua
lua/apisix/plugins/grpc-transcode/response.lua
lua/apisix/plugins/grpc-transcode/util.lua
lua/apisix/schema_def.lua

主要是处理了int64类型数据精度损失的问题
Fix #821

plugin(grpc-transcode): support new options for `protocol buffer` encoding.

---

lua/apisix/core/config_etcd.lua

is outdated and cleared.
Fix #869.

bugfix: reloaded the etcd configuation data if the index

---

doc/admin-api-cn.md
lua/apisix/admin/init.lua
lua/apisix/admin/routes.lua
lua/apisix/core/etcd.lua
t/admin/routes.t

feature: support to specify TTL for route。

---

README.md
README_CN.md

Adding twitter social icons

---

.gitignore

Added `conf/nginx.conf` to `.gitignore`
Resolves #968

Added the conf/nginx.conf to .gitignore

---

lua/apisix/core/config_etcd.lua
lua/apisix/core/etcd.lua
rockspec/apisix-master-0.rockspec

bugfix: upgrade etcd to version 0.8 and modify the connection keys.

---

lua/apisix/balancer.lua

If the retries option in the upstream object is not configured. It will be set according to the number of nodes.
Fix #977

improve: set a default value if retries option in the upstream object is not configured

---

README.md
README_CN.md

add one instruction
* add yarn install instructions
Fix #XXX

add yarn install instructions

---

README.md
README_CN.md
doc/README.md
doc/README_CN.md
doc/plugins/fault-injection-cn.md
doc/plugins/fault-injection.md

doc: Add doc for fault-injection plugin.

---

bin/apisix

fix path error when install with luarocks
* bin/apisix

fix path error when install with luarocks

---

README.md

doc: READEME.md optimaztion

---

doc/plugins/response-rewrite.md

doc: response-rewrite.md  optimiazition

---

.travis.yml
.travis/linux_apisix_luarocks_runner.sh
utils/install-apisix.sh

Fix https://github.com/apache/incubator-apisix/issues/1059

travis: run a apisix instance which intalled by luarocks.

---

Contributing.md

Fix https://github.com/apache/incubator-apisix/issues/1094

doc: check code style and test case style.

---

bin/apisix

feature: increase the default size of the core file

---

.travis/check-nginxconf.sh
bin/apisix

fix https://github.com/apache/incubator-apisix/pull/1085#issuecomment-583718295

CLI: added missing Lua path.

---

doc/plugins/prometheus-cn.md
doc/plugins/prometheus.md

Fix https://github.com/apache/incubator-apisix/issues/1103

doc: add link to download grafana meta data.

---

README.md
README_CN.md
doc/README.md
doc/README_CN.md
doc/plugins/wolf-rbac.md

Add wolf-rbac plugin to README

doc: add wolf-rbac plugin

---

CHANGELOG.md
CHANGELOG_CN.md

doc: added changelog for 1.1 release.

doc: added changelog for 1.1 release.

---

rockspec/apisix-master-0.rockspec

* ddd76d7 - (6 minutes ago) feature: supported table value as default value.

change: updated jsonschema to v0.6 .

---

FAQ.md

I am facing this issue as the first step installing the apisix, I am not sure why this is not listed in the FAQ, but I think we should.
This solution is originally posted in the openresty issue comments, hard to find. https://github.com/openresty/homebrew-brew/issues/10#issuecomment-550650867

Add an installation issue on the FAQ page

---

.travis/linux_tengine_runner.sh

Added and patch tengine with privileged_agent_process.patch
Fix #912

feature: Added and patch tengine with privileged_agent_process.patch

---

lua/apisix/stream/router/ip_port.lua
t/stream-node/sanity.t
t/stream-plugin/mqtt-proxy.t

Fix https://github.com/apache/incubator-apisix/issues/1104

bugfix: compare server_port with number data type.

---

rockspec/apisix-1.1-0.rockspec
utils/check-version.sh

update check-version tool for releasing. and add 1.1 rockspec

update check-version tool for releasing. and add 1.1 rockspec

---

CHANGELOG.md
CHANGELOG_CN.md
doc/how-to-build-cn.md
doc/how-to-build.md
lua/apisix/core/version.lua

release new version 1.1

---

t/APISIX.pm
t/lib/test_admin.lua

to define the working path by himself.

test: exported ENV{APISIX_HOME}, allow user to define the working path by himself.

---

bin/apisix
doc/plugins/oauth.md
doc/profile-cn.md
lua/apisix/core/config_local.lua
lua/apisix/core/config_yaml.lua
lua/apisix/core/profile.lua
lua/apisix/debug.lua
t/APISIX.pm
t/core/profile.t

add profile

---

bin/apisix

* Fix bad code style in apisix file.
Fix  #1180

Fix bad code style.

---

doc/profile.md

Add English translation.
Fix #1170

doc: add English doc `doc/profile-cn.md`

---

bin/apisix

Add profile in the core module.
Fix #1184

add profile to core lua configs.

---

.travis.yml
.travis/linux_apisix_current_luarocks_runner.sh
.travis/linux_apisix_master_luarocks_runner.sh

travis: supports installing APISIX using the current branch and running

---

README.md
README_CN.md
doc/architecture-design-cn.md
doc/architecture-design.md

doc: add usage about global ruls

---

doc/plugins/ip-restriction.md

Change ip restriction doc 
Fix #984

modify ip restrictions plugin doc.

---

t/utils/batch-processor.t

Adding test case for extending buffer timer and removing unused configs

---

Makefile
utils/install-apisix.sh

change: use the correct parameters based on the version of luarocks 

---

rockspec/apisix-master-0.rockspec

update lua resty ipmatcher.
Fix #1234

update lua resty ipmatcher.

---

doc/how-to-build-cn.md
doc/how-to-build.md

* add export `PERL5LIB` env for running test cases

doc: add export `PERL5LIB` env for running test cases

---

lua/apisix/admin/ssl.lua
t/admin/ssl.t
t/lib/test_admin.lua

fixed https://github.com/apache/incubator-apisix/issues/994

bugfix: hide ssl private key in admin API.

---

t/admin/schema.t

test: added test cases.

---

doc/plugin-develop-cn.md
doc/plugin-develop.md

Add priority related information for plugin development guide doc / plugin-develop-cn.md
SUMMARY_HERE
* [doc/plugin-develop-cn.md]
Fix #XXX

Add priority related information for plugin development doc

---

lua/apisix/plugins/proxy-rewrite.lua
t/plugin/proxy-rewrite.t

bugfix(proxy-rewrite): Invalid pattern.

---

doc/how-to-build-cn.md
doc/how-to-build.md

Modify Unit test local run setup document.
Fix #1239

Add unit test troubleshoot doc.

---

.travis.yml
.travis/linux_openresty_runner.sh
.travis/linux_tengine_runner.sh
.travis/osx_openresty_runner.sh

travis(osx): install the redis by brew.

---

README.md
README_CN.md

doc: add correct link address for "etcd Clustering Guide" of incubator-apisix/README_CN.md

---

doc/plugin-develop.md

just update the doc of english version ,the chinese version is ok.
just update doc
none

doc: change Lua/apifix to lua/apisix

---

doc/plugins/tcp-logger-cn.md

add tcp-logger-cn.md

---

rockspec/apisix-master-0.rockspec

Updating the json schema version

---

doc/plugins/limit-req-cn.md
doc/plugins/limit-req.md

* fix style for limit-req & limit-req-cn
Fix #1273

fix style of limit-req & limit-req-cn

---

README_CN.md
doc/getting-started-cn.md
doc/getting-started.md

add chinese version

---

doc/plugins/basic-auth.md

Summary
Full changelog
fix style of basic-auth
Fix #1273

Doc basic auth

---

doc/plugins/fault-injection.md

Summary
Full changelog
fix style of fault-injection
Fix #1273

fix style of fault-injection

---

doc/plugins/basic-auth-cn.md

Summary
Full changelog
fix style of basic-auth-cn
Fix #1273

fix style of basic-auth-cn

---

doc/plugins/grpc-transcoding.md

Summary
Full changelog
fix style of grpc-transcoding
Fix #1273

fix style of grpc-transcoding

---

.travis.yml
.travis/osx_openresty_runner.sh

Fix https://github.com/apache/incubator-apisix/issues/1313

CI(OSX): do not ignore run, run part test cases every time.

---

doc/README.md
doc/README_CN.md
doc/plugins/udp-logger-cn.md
doc/plugins/udp-logger.md

Addibgn udp logger docs.
Fix #1274

add udp logger docs.

---

lua/apisix/core/config_yaml.lua
t/config-center-yaml/route-upstream.t

bugfix: added `key` field when parse route from local yaml.

---

lua/apisix.lua
t/plugin/prometheus.t

feature: run log plugins in the global rule

---

.travis/apisix_cli_test.sh
bin/apisix
conf/config.yaml
lua/apisix.lua
t/APISIX.pm
t/node/route-domain-with-local-dns.t

enable local DNS resolver
Fix #1164

enable local DNS

---

CODE_STYLE.md
Contributing.md

#1273
https://github.com/apache/incubator-apisix/pull/1356#discussion_r399891409

Adding code style and doc linting tool for contribution guidelines

---

.travis/linux_tengine_runner.sh

update lua resty.

---

doc/health-check.md

Fix https://github.com/apache/incubator-apisix/issues/1374
Health check doc json format error
* Fix `doc/health-check.md ` json format error

Fix doc json format error.

---

apisix/plugins/proxy-cache.lua
t/plugin/proxy-cache.t

change: blacklist $request_method in proxy-cache's cache key.

---

apisix/plugins/response-rewrite.lua
doc/plugins/response-rewrite-cn.md
doc/plugins/response-rewrite.md
t/plugin/response-rewrite.t

response-rewrite plugin support rewrite binary data to client
* doc/plugins/response-rewrite-cn.md
* doc/plugins/response-rewrite.md
* apisix/plugins/response-rewrite.lua
* apisix/t/plugin/response-rewrite.t

feature: response-rewrite plugin rewrite binary data to client by base64

---

apisix/init.lua
apisix/plugins/cors.lua
t/plugin/cors.t

bugfix: plugin in header_filter/body_filter should be run like log phase

---

apisix/init.lua

Refactor the way to run global rule in log/header filter/body filter 

---

apisix/init.lua
t/node/invalid-route.t

bugfix: should not drop the error msg of `dns_parse`.

---

apisix/plugins/tcp-logger.lua
apisix/plugins/udp-logger.lua

fix small error log in loggers.

---

README.md
README_CN.md

fixed https://github.com/apache/incubator-apisix/issues/1424

doc: updated link of user wall.

---

apisix/balancer.lua
apisix/http/service.lua
apisix/plugin.lua
t/lib/test_admin.lua
t/node/merge-route.t

bugfix: check if the upstream node is host.

---

CHANGELOG.md
doc/benchmark.md
doc/how-to-build-cn.md
doc/how-to-build.md

fix the style for CHANGELOG.md.
* fix style for CHANGELOG.md.
Related issue  #1273

fix style for CHANGELOG.md.

---

doc/batch-processor.md
doc/benchmark-cn.md
doc/benchmark.md
doc/getting-started-cn.md
doc/getting-started.md
doc/grpc-proxy-cn.md
doc/stand-alone-cn.md

fix some doc styles by markdownlint
related issue: #1273

fix some doc styles by markdownlint

---

apisix/plugins/kafka-logger.lua
apisix/plugins/syslog.lua
apisix/plugins/tcp-logger.lua
apisix/plugins/udp-logger.lua

Remove stale object in sys log.

---

apisix/plugins/prometheus/exporter.lua
t/plugin/prometheus.t

feature(prometheus): support to collect metric `overhead`

---

FAQ.md
FAQ_CN.md

Add FAQ about how to reload your own plugin
SUMMARY_HERE
* ...
Fix #XXX

[doc]Add FAQ about how to reload your own plugin

---

bin/apisix

SUMMARY_HERE
* ...
Fix [https://github.com/apache/incubator-apisix/issues/1564](https://github.com/apache/incubator-apisix/issues/1564)

Fix incorrect variable name `hostCount`

---

t/admin/routes-array-nodes.t
t/admin/services-array-nodes.t
t/node/upstream-array-nodes.t

test: updated style.

---

Makefile

for #1463 
1. hide install command 
2. add default check for install

fix: add default checkw for default and hide install command

---

CODE_OF_CONDUCT.md

doc: add coc file

---

apisix/plugins/skywalking/tracer.lua

`if service_id and service_id then`
to 
`if service_id and instance_id then`

check `instance_id`

---

doc/plugins/batch-requests-cn.md
doc/plugins/batch-requests.md

typo of markdown doc style
update doc style in batch-requests-cn.md and batch-requests.md HttpResponse section

doc style for batch-requests.HttpResponse section

---

doc/README.md
doc/README_CN.md
doc/plugins/grpc-transcode-cn.md
doc/plugins/grpc-transcode.md

Update and rename grpc-transcoding-cn.md to grpc-transcode-cn.md

---

doc/plugins/echo-cn.md

doc: update echo-cn.md

---

doc/README.md
doc/README_CN.md
doc/plugins/authz-keycloak-cn.md
doc/plugins/authz-keycloak.md

Chinese translation of authz-keycloak plugin doc
Fix #1711

Chinese translation of authz-keycloak plugin doc

---

apisix/plugins/echo.lua
t/plugin/echo.t

feature(echo): support header filter and access phases.

---

t/admin/services-string-id.t

Add test cases in #1659

---

apisix/core/config_etcd.lua

just like the title said
SUMMARY_HERE
* ...
Fix #XXX

sync_times need to reset

---

apisix/core/config_yaml.lua

just like the title said
SUMMARY_HERE
* ...
Fix #XXX

missing premature parameter

---

doc/architecture-design.md
doc/zh-cn/architecture-design.md

When reading the doc, i find  there are some puncuation error in the document smaple shell code.

Fix some punctuation error in the document sample shell code

---

doc/zh-cn/architecture-design.md

Fix `doc/zh-cn/architecture-design.md` some images path error.
Fix #1812

fix doc/zh-cn/architecture-design.md images path error

---

.github/workflows/build.yml
.travis.yml
.travis/linux_openresty_runner.sh
.travis/linux_tengine_runner.sh
t/node/remote-addr-ipv6.t

using GitHub action for CI
feature: using GitHub action for CI
update:  .travis/linux_openresty_runner.sh
update: .travis/linux_tengine_runner.sh
update:  t/node/remote-addr-ipv6.t
Fix #1789

feature: using GitHub action for CI

---

.github/PULL_REQUEST_TEMPLATE.md

*Please answer each of these after submitting your pull request:*
we need add more questions when create PR, so others will understand why and what.

doc: add more info for pr template.

---

README.md

Found some link errors when start reading the docs.

fix hyper links in readme

---

README.md
README_CN.md

doc: update README.md for proxy-mirror

---

README.md

Fix a markdown link syntax error.

doc: Fix link syntax in README.md

---

FAQ.md
FAQ_CN.md
doc/admin-api.md
doc/architecture-design.md
doc/discovery.md
doc/plugins/prometheus.md
doc/plugins/proxy-rewrite.md
doc/plugins/redirect.md
doc/zh-cn/admin-api.md
doc/zh-cn/architecture-design.md
doc/zh-cn/discovery.md
doc/zh-cn/plugins/http-logger.md

doc: fix typos.

---

conf/config.yaml

fixes https://github.com/apache/incubator-apisix/issues/1870

update comment to 30 seconds

---

doc/how-to-build.md
doc/plugins/request-validation.md

- Added OSx unit test troubleshooting steps
- fixed formatting of JSON content in request validation doc

doc improvements for OSx unit tests and request validation plugin

---

apisix/plugins/limit-count/limit-count-redis.lua

bugfix: fix limit-count plugin redis.ttl error.

---

README.md
README_CN.md

fixes https://github.com/apache/incubator-apisix/issues/1944

1944 fix grpc transcode readme

---

apisix/plugins/openid-connect.lua
apisix/plugins/redirect.lua
apisix/plugins/uri-blocker.lua
apisix/plugins/zipkin.lua
t/plugin/uri-blocker.t

relate issue: https://github.com/apache/incubator-apisix/issues/1934 , #1956

bugfix: avoid to modify the original plugin conf.

---

apisix/core.lua
apisix/init.lua
apisix/plugin.lua

as title, for better performance.

perf: used empty table if the user is not enabled any plugin.

---

apisix/http/router/radixtree_sni.lua
apisix/init.lua
t/grpc-proxy-test.sh
t/router/radixtree-sni.t

bugfix: fail to handshake if there is no certificate matched by host.

---

README_CN.md
doc/zh-cn/plugins/uri-blocker.md

add uri-blocker plugin Chinese docs.

doc: add uri-blocker plugin Chinese docs

---

doc/plugins/uri-blocker.md

doc: update uri-blocker plugin docs

---

CHANGELOG.md
CHANGELOG_CN.md
README.md
README_CN.md
apisix/core/version.lua
doc/how-to-build.md
doc/zh-cn/how-to-build.md
rockspec/apisix-1.5-0.rockspec

released 1.5.0 version.
@apache/apisix-committers please do have a check.
@membphis After PR merge, please upload `apisix-1.5-0.rockspec` to https://luarocks.org/modules/apisix/apisix

release: released 1.5.0 version.

---

rockspec/apisix-0.9-0.rockspec
rockspec/apisix-1.0-0.rockspec
rockspec/apisix-1.1-0.rockspec
rockspec/apisix-1.2-0.rockspec
rockspec/apisix-1.3-0.rockspec
rockspec/apisix-1.4-0.rockspec
rockspec/apisix-1.4.1-0.rockspec
rockspec/apisix-1.5-0.rockspec

fix https://github.com/apache/apisix/pull/1872/, which not using the right way to install from luarocks.

rocks: use tag instead of branch.

---

apisix/plugins/cors.lua
doc/plugins/cors.md
doc/zh-cn/plugins/cors.md
t/plugin/cors.t

feat: add '**' for alllow_headers and complete docs

---

doc/zh-cn/plugins/authz-keycloak.md

doc: update authz-keycloak plugin docs

---

Contributing.md
FAQ.md
FAQ_CN.md
README.md
README_CN.md
apisix/plugins/redirect.lua
doc/how-to-build.md
doc/index.html
doc/powered-by.md
doc/zh-cn/how-to-build.md
kubernetes/README.md
kubernetes/config.sh
rockspec/apisix-master-0.rockspec
utils/install-apisix.sh

doc: remove all ‘incubator’

---

apisix/plugins/limit-conn.lua
t/plugin/limit-conn.t

be called multiple times.
fix #1986
* do not need to update doc

bugfix: used a table array to store the `status`, allow the plugin can

---

.travis/apisix_cli_test.sh
bin/apisix
conf/config.yaml

feat: allow customizing worker_processes

---

README.md
README_CN.md

doc: update uri-blocker name for README.

---

doc/plugins/request-validation.md
doc/zh-cn/plugins/request-validation.md

FIX #2033
1/ update example syntax error for request-validation plugin.
2/ add example to request-validation plugin english document.

doc: update example syntax error for request-validation plugin.

---

README_CN.md

doc: fixed health-ckeck document path for README_CN.md

---

apisix/plugins/prometheus/exporter.lua

fix: prometheus metric api bug

---

apisix/init.lua
apisix/plugin.lua
apisix/plugins/basic-auth.lua
apisix/plugins/jwt-auth.lua
apisix/plugins/key-auth.lua
t/node/consumer-plugin.t

updated, the cache needs to be updated.
fix #2019

bugfix: when the plug-in configuration that is bound to the consumer is

---

.travis/apisix_cli_test.sh
bin/apisix

bugfix: avoid setting Server header twice

---

apisix/plugins/prometheus/exporter.lua
t/plugin/prometheus.t

add hostname label for metric `etcd_reachable`

change: add prometheus metrics `node_info`(hostname) 

---

README.md

doc: add dashboard link in README to sync

---

apisix/plugins/limit-count.lua
t/plugin/limit-count-redis.t

change: use draft7 for JSON Schema

---

apisix/plugins/ip-restriction.lua
apisix/schema_def.lua
t/plugin/ip-restriction.t

change: update plugin's schema ip-restriction with `draft7` way

---

doc/plugins/authz-keycloak.md
doc/plugins/request-id.md
doc/plugins/request-validation.md
doc/zh-cn/plugins/authz-keycloak.md
doc/zh-cn/plugins/request-id.md
doc/zh-cn/plugins/request-validation.md

doc: fix doc use 4 spaces instead of tab

---

.travis/apisix_cli_test.sh
bin/apisix
conf/config-default.yaml

support custom access log format
#2009

feat: support custom access log format

---

doc/powered-by.md

Update since #1317. Need to update image @moonming. 
Also, do we need to sync the image here and [README](https://github.com/apache/apisix#who-uses-apisix)?

doc: add more companies to power-by page 

---

apisix/plugins/fault-injection.lua
doc/plugins/fault-injection.md
doc/zh-cn/plugins/fault-injection.md

plugin(fault-injection): use draft7 way to rewrite the JSON Schema.

---

.travis/ASF-Release.cfg
LICENSE
apisix/balancer/ewma.lua

fixed https://github.com/apache/apisix/issues/2131

license: fixed license issue for ewma.lua.

---

doc/architecture-design.md
doc/plugins/log-rotate.md

A few links in the documents are invalid

fix link in documents

---

CODE_STYLE.md

fix: remove useless `)` in CODE_STYLE.md

fix:  remove useless `)` in CODE_STYLE.md

---

t/plugin/log-rotate.t

fix:https://github.com/apache/apisix/issues/2138

fix:log-rotate.t is unstable

---

.travis/linux_openresty_runner.sh
utils/check-plugins-code.sh

optimize output of check-plugins-code

---

apisix/plugins/serverless.lua
t/admin/schema.t

fix spelling error of header_filter, which couse serverless not work in header_filter phase

fix: serverless plugin not work in header_filter phase

---

apisix/admin/ssl.lua
apisix/core.lua
apisix/core/string.lua
apisix/http/router/radixtree_sni.lua
t/core/string.t

chore: add string utility for simplicity and correctness

---

.travis/linux_openresty_runner.sh
.travis/linux_tengine_runner.sh
.travis/osx_openresty_runner.sh
apisix/plugins/grpc-transcode/util.lua
t/plugin/grpc-transcode.t

fix bug: grpc-transcode plugin converts http/json parameters abnormally
#1991

bugfix: grpc-transcode plugin converts http/json parameters abnormally

---

doc/health-check.md

fix typo Update health-check.md

---

doc/architecture-design.md
doc/zh-cn/architecture-design.md

doc: fix format

---

apisix/core/config_yaml.lua
t/config-center-yaml/route.t

bugfix: load yaml config in privileged agent

---

.travis/apisix_cli_test.sh
bin/apisix
conf/config-default.yaml

I need to get env variables in the plugin so I need to set nginx conf environment variables

optimize set nginx conf env

---

README.md
README_CN.md

doc: added channel at slack and added new qq group.

---

t/node/healthcheck.t
t/node/route-delete.t

the test case is unstable, it runs fail sometimes.
current way: before creating and deleting routes in batches, clear all routes first.

test: before creating and deleting routes in batches, clear all routes first

---

apisix/plugins/hmac-auth.lua
doc/plugins/hmac-auth.md
doc/zh-cn/plugins/hmac-auth.md
t/APISIX.pm
t/plugin/custom_hmac_auth.t
t/plugin/hmac-auth.t

`hmac-auth` add signed headers to  calculate signature

feat: `hmac-auth` add signed headers to  calculate signature

---

apisix/admin/ssl.lua
apisix/http/router/radixtree_sni.lua
t/router/radixtree-sni.t

Previously I added the support for setting multiple certs and pkeys for a single domain, but the encryption for private keys  was forgotten, so here i fixed it.

bugfix: supported the encryption/decryption for multi priv keys

---

t/plugin/tcp-logger.t

fix: increase wait time to avoid fail

fix: increase wait to avoid fail

---

.travis/linux_apisix_master_luarocks_runner.sh
apisix/core/config_etcd.lua

bugfix: use correct version of etcd in linux_apisix_master_luarocks

---

t/node/ewma.t
t/node/invalid-route.t
t/node/invalid-service.t
t/node/invalid-upstream.t
t/node/service-empty.t
t/plugin/consumer-restriction.t

as title.
format the test case by tool `reindex` .

test: wait for more time and then check the error log.

---

apisix/core/ctx.lua
t/core/ctx.t

feat: support to fetch `consumer_name` or `consumer_id` via `ctx.var`

---

.travis/linux_tengine_runner.sh

The CI of tengine often reports errors due to timeouts. Since tengine is no longer maintained, so I skip unit tests

CI: skip run tengine test cases.

---

apisix/schema_def.lua
doc/admin-api.md
doc/zh-cn/admin-api.md
t/admin/consumers.t
t/admin/routes.t
t/admin/services.t
t/admin/ssl.t
t/admin/upstream.t

Signed-off-by: imjoey <majunjiev@gmail.com>
Following with #2279 , this PR is going to add `labels` property support for `Route`/`Consumer`/`Service`/`SSL` objects, as well as fix some typos introduced by #2279 .

feat: Add lables for route/consumer/service/ssl objects

---

apisix/plugins/kafka-logger.lua
apisix/utils/log-util.lua
doc/plugins/kafka-logger.md
doc/zh-cn/plugins/kafka-logger.md
t/plugin/kafka-logger.t

feat: add new filed `meta_style`, collect the request information with `original` style.
eg:
```
send data to kafka: POST /hello?ab=cd HTTP/1.1
host: localhost
content-length: 6
connection: close
abcdef
```

feat: add new filed `meta_style`, collect the request information with `original` style.

---

README.md
README_CN.md

doc: add user story about eFactory.

---

.travis/linux_apisix_master_luarocks_runner.sh
Makefile

bugfix: install the Lua files in `apisix/ssl/router` .

---

.travis/linux_apisix_current_luarocks_runner.sh
.travis/linux_apisix_master_luarocks_runner.sh

CI: run the APISIX instance in an empty folder.

---

apisix/plugins/kafka-logger.lua

style: tweak error log in kafka-logger

---

apisix/plugins/hmac-auth.lua
t/plugin/hmac-auth.t

change(hmac-auth): split schema to adapt different occasions

---

Makefile
bin/apisix
t/node/route-domain-with-local-dns.t
t/node/route-domain.t

fix #2370 to remove the logs dir.
fix #2334 to replace baidu.com with github.com in test cases

chore: remove the folder 'logs'  in root and replace baidu.com with github.com in test cases

---

README.md
README_CN.md

add milestone info in README.md and README_CN.md
resolve #2400

add milestone info in README.md and README_CN.md

---

CONTRIBUTING.md
FAQ_CN.md
doc/plugins/basic-auth.md
doc/zh-cn/plugins/basic-auth.md
doc/zh-cn/plugins/skywalking.md

fix broken link with https://github.com/tcort/markdown-link-check. 
This tool supports **GitHub actions**, do we need to deploy one in apisix?

chore: fix broken link

---

apisix/core.lua
apisix/plugins/prometheus/exporter.lua
t/plugin/prometheus.t

fix(prometheus): don't provide etcd metrics when you don't use it

---

doc/plugins/ip-restriction.md
doc/zh-cn/plugins/ip-restriction.md

doc: correct the doc of plugin ip-restriction

---

apisix/admin/consumers.lua
apisix/admin/plugin_metadata.lua
t/admin/consumers.t

change: use 405 as the error code for unsupported HTTP method

---

.travis/linux_openresty_runner.sh
t/stream-node/random.t

We don't enable Lua code override now, its output is unstable and this is unacceptable.
Disabling the Lua code override first will make CI run faster.

CI: turn off the Lua code coverage check in CI.

---

apisix/admin/init.lua
apisix/admin/plugins.lua
apisix/debug.lua

Since we localized require, I think it's more reasonable to put it in front of the sentences which calling it.

style: move localized require in front of directives which calling it.

---

apisix/plugins/jwt-auth.lua

Fixed some code style typos, keep the code base clean.

style: fixed some code style problems

---

apisix/http/router/radixtree_host_uri.lua
t/router/radixtree-host-uri-priority.t

Fix: [#2423](https://github.com/apache/apisix/issues/2423).

bugfix(radixtree_host_uri): set route priority.

---

apisix/plugins/consumer-restriction.lua
t/plugin/consumer-restriction.t

plugin(consumer-restriction): use draft7 way to rewrite the JSON Schema.

---

apisix/core/utils.lua
t/core/utils.t

Solve https://github.com/apache/apisix/issues/2436.

change: read 8bytes from /dev/urandom as the random seed for better randomness

---

apisix/api_router.lua
t/admin/plugin-metadata.t

This bug is introduced in 6a543a9.

fix: we didn't traverse the plugin interceptors correctly

---

doc/plugins/echo.md
doc/zh-cn/plugins/echo.md

doc(echo): mark it as production-unready

---

apisix/plugins/request-validation.lua

Plugin(request-validation): use draft7 way to rewrite the JSON Schema

---

FAQ.md
FAQ_CN.md

doc: we can also use reload after configuration changed

---

doc/architecture-design.md

doc: fixed minor format issue in architecture-design.md.

---

.travis/apisix_cli_test.sh
bin/apisix

fix: previously we could not merge configuration without middle layer

---

Makefile

Using this script we can generate the release package more quickly

makefile: add release-src in makefile.

---

apisix/plugins/hmac-auth.lua
doc/plugins/hmac-auth.md
doc/zh-cn/plugins/hmac-auth.md
t/plugin/hmac-auth.t

…ader related to the plugin.
fix #2490

feat: remove auth headers for hmac-auth plugin.

---

apisix/init.lua

Fix for https://github.com/apache/apisix/issues/2449

bugfux : fixes issue #2449

---

apisix/core/response.lua
apisix/plugins/response-rewrite.lua
t/lib/server.lua
t/plugin/response-rewrite.t

feat(response-rewrite): clear cache headers to avoid polluting the cache

---

apisix/plugins/jwt-auth.lua
t/plugin/jwt-auth.t

change(jwt-auth): split schema to adapt different occasions

---

CHANGELOG.md
CHANGELOG_CN.md
README.md
README_CN.md
apisix/core/version.lua
doc/how-to-build.md
doc/zh-cn/how-to-build.md
rockspec/apisix-2.0-0.rockspec

https://github.com/apache/apisix/milestone/7
2.0 milestone almost finished, it’s time to start release

release: release 2.0-rc version.

---

apisix/plugins/limit-count.lua
doc/plugins/limit-count.md
doc/zh-cn/plugins/limit-count.md
t/plugin/limit-count.t

feat: The limit-count plugin supports service_id field.

---

README.md
README_CN.md

doc: fixed download links.

---

apisix/plugins/fault-injection.lua
doc/plugins/fault-injection.md
doc/zh-cn/plugins/fault-injection.md
t/plugin/fault-injection.t

Support percentage for the finer granularity fault injection.

feature: support percentage for fault injection

---

README.md
README_CN.md

doc: add videos of ApacheCon.

---

apisix/plugins/hmac-auth.lua
doc/plugins/hmac-auth.md
doc/zh-cn/plugins/hmac-auth.md
t/plugin/consumer-restriction.t
t/plugin/custom_hmac_auth.t
t/plugin/hmac-auth.t

fix: the plugin hmac-auth missed a `\n`

---

doc/zh-cn/install-dependencies.md

update install-dependencies.md

doc：update install-dependencies.md

---

apisix/plugins/jwt-auth.lua
t/plugin/jwt-auth.t

Signed-off-by: Jaycean <jinchen_jacean@163.com>
fix: #2553 
- jwt-auth add consumer_schema to the _M

fix: jwt-auth add consumer_schema to the _M

---

apisix/plugins/echo.lua
t/lib/server.lua
t/node/remote-addr-ipv6.t
t/plugin/echo.t
t/plugin/redirect.t
t/router/multi-ssl-certs.t
t/router/radixtree-sni.t

fix(echo): modify response body correctly

---

.travis/apisix_cli_test.sh
bin/apisix
conf/config-default.yaml

change: rename APIX_WORKER_PROCESSES to APISIX_WORKER_PROCESSES

---

.github/workflows/build.yml

Fix for https://github.com/apache/apisix/issues/2505

CI : yaml style

---

CHANGELOG_CN.md

doc: Update CHANGELOG_CN.md

---

CODE_STYLE.md

Currently we already have the line length style check in lj-releng. The
length we chose is 100.
Close #2569.

chore: update CODE_STYLE to catch up with the reality

---

.travis/apisix_cli_test.sh
bin/apisix
conf/config-default.yaml

feat: support `json` encoding escape for access logs

---

apisix/balancer.lua
apisix/discovery/eureka.lua
apisix/discovery/init.lua
apisix/schema_def.lua
conf/config-default.yaml
doc/discovery.md
doc/zh-cn/discovery.md
t/discovery/eureka.t

support multi service discovery

feature: support multi service discovery

---

apisix/core/table.lua
apisix/plugins/api-breaker.lua

feat: implement `array_find` in `apisix.core.table`

---

apisix/plugins/redirect.lua

bugfix: fix typo name of redirect plugin.

---

doc/README.md
doc/zh-cn/README.md

Fix for the issue https://github.com/apache/apisix/issues/2529

doc : fixes issue #2529

---

apisix/core/table.lua
apisix/plugins/hmac-auth.lua
apisix/plugins/log-rotate.lua
apisix/plugins/skywalking.lua
t/core/table.t

fix https://github.com/apache/apisix/issues/2557

chore: move try_read_attr function into table.lua (#2257)

---

doc/plugins/api-breaker.md
doc/zh-cn/plugins/api-breaker.md

Fix for the issue https://github.com/apache/apisix/issues/2584
close #2584

fix(doc): update api-breaker’s language switcher link

---

.travis/linux_apisix_master_luarocks_runner.sh
README.md
bin/apisix

bug(CLI): CI failed, failed to load `apisix.cli.ngx_tpl`

---

.travis/linux_apisix_master_luarocks_runner.sh

related https://github.com/apache/apisix/pull/2588

CI: remove temporary steps.

---

t/admin/plugins.t
t/plugin/basic-auth.t
t/plugin/limit-conn.t
t/plugin/limit-count.t

test: format by `reindex`.

---

doc/examples/plugins-hmac-auth-generate-signature.md
doc/plugins/hmac-auth.md
doc/zh-cn/plugins/hmac-auth.md

Plugins(Doc): Optimize the document for hmac-auth

---

apisix/core/config_yaml.lua
apisix/init.lua
t/config-center-yaml/route.t

feat: support stream configuration in standalone mode

---

.travis/linux_apisix_master_luarocks_runner.sh
apisix/cli/env.lua
bin/apisix

test: make CI pass again

---

.travis/linux_apisix_master_luarocks_runner.sh
bin/apisix

test: remove temporary hack

---

utils/check-lua-code-style.sh

chore: exclude ngx_tpl.lua from the style check

---

apisix/plugins/jwt-auth.lua
t/plugin/jwt-auth.t

fix(jwt-auth): validate if the claimed secret is base64 encoded.

---

.travis/linux_apisix_current_luarocks_runner.sh
.travis/linux_apisix_master_luarocks_runner.sh
.travis/linux_openresty_mtls_runner.sh
.travis/linux_openresty_runner.sh

will support `1.19.3.1` later.
fix https://github.com/apache/apisix/issues/2645

CI: specified to use openresty `1.17.8.2`.

---

.github/semantic.yml

According to https://github.com/zeke/semantic-pull-requests , we use this configuration to allow this bot to only to check PR's title.

chore(semantic-pr): added policy for semantic-pr

---

doc/README.md
doc/zh-cn/README.md

and sync the Chinese version from English version.

docs: put the chapter "admin api" to the front, and sync the Chinese version from English version

---

conf/config-default.yaml
doc/plugins/skywalking.md
doc/zh-cn/plugins/skywalking.md
t/APISIX.pm
t/admin/plugins.t
t/debug/debug-mode.t
t/plugin/skywalking.t

change: disable skywalking by default.

---

apisix/init.lua
apisix/plugin.lua
apisix/plugins/example-plugin.lua
apisix/plugins/log-rotate.lua
apisix/timers.lua
t/plugin/log-rotate.t

fix(log-rotate): avoid creating multiple timers

---

.travis/apisix_cli_test.sh
apisix/cli/ngx_tpl.lua
conf/config-default.yaml

fix: disable ssl_session_tickets by default

---

conf/config-default.yaml
doc/architecture-design.md
doc/zh-cn/architecture-design.md
t/APISIX.pm

Close #2659.
close https://github.com/apache/apisix/issues/2672

feat: disable example-plugin by default

---

.github/workflows/markdown-link-checker.yml

We could use this CI to check if links in markdown files are alive.
related issue #2681

feat(CI): create markdown-link-checker.yml

---

apisix/init.lua
apisix/schema_def.lua
doc/admin-api.md
doc/architecture-design.md
doc/zh-cn/admin-api.md
doc/zh-cn/architecture-design.md
t/node/merge-route.t
t/node/upstream-websocket.t

change: enabled websocket in route
resolve #1791
Pre-submission checklist:
enable websocket
update the test cases
update the user's guide
this is a non-backward compatible PR

 chore(core): enabled websocket in route and service

---

.gitignore
apisix/core/profile.lua
t/core/profile.t

fix: use same config-default.yaml for different environments

---

apisix/schema_def.lua
t/admin/services.t

feat: increase the length of rule name to 100

---

rockspec/apisix-master-0.rockspec

fix: upgrade lua-resty-etcd to 1.4.2

---

t/lib/server.lua
t/node/merge-route.t
t/plugin/hmac-auth.t
t/plugin/proxy-mirror.t

chore: sort the request headers output by the _M.uri and _M.old_uri  function in t/lib/server.lua

---

apisix/core/table.lua
apisix/plugin.lua
apisix/plugins/example-plugin.lua
t/admin/plugins-reload.t
t/core/table.t

fix: reload plugin when plugin attribute is changed

---

doc/admin-api.md
doc/zh-cn/admin-api.md

docs: add create/update_time fields

---

doc/plugins/batch-requests.md
doc/zh-cn/plugins/batch-requests.md

docs: modify batch-requests.md

---

doc/stand-alone.md
doc/zh-cn/stand-alone.md

fixed https://github.com/apache/apisix/issues/2616

docs: modify the stand-alone.md to add instructions for enable SSL

---

doc/plugins.md
doc/zh-cn/plugins.md

docs: clarify how we handle disabled plugin which is matched

---

doc/zh-cn/plugins/kafka-logger.md

fix https://github.com/apache/apisix/issues/2719

fix(docs): kafka-logger in Chinese

---

t/lib/server.lua

chore: code format optimization of `t/lib/server.lua` file

---

apisix/plugins/http-logger.lua
apisix/schema_def.lua
doc/plugins/http-logger.md
doc/zh-cn/plugins/http-logger.md
t/plugin/http-logger.t

fix(http-logger): validate uri

---

t/config-center-yaml/ssl.t

test: check SSL configuration for stand alone mode

---

apisix/init.lua
t/plugin/plugin.t

fix: user's route was prior to the plugin's one

---

t/lib/test_admin.lua

test: write the config.yaml according to the profile

---

.travis/common.sh
.travis/linux_apisix_current_luarocks_runner.sh
.travis/linux_apisix_master_luarocks_runner.sh
.travis/linux_openresty_mtls_runner.sh
.travis/linux_openresty_runner.sh
.travis/linux_tengine_runner.sh
.travis/osx_openresty_runner.sh
utils/linux-install-luarocks.sh
utils/linux-install-openresty.sh

ci: refactor runners

---

apisix/init.lua

chore: add a deprecate log for enable_websocket in upstream

---

apisix/plugins/http-logger.lua
t/plugin/http-logger-log-format.t

fix: the log report of the custom log format is incorrect.

---

apisix/balancer.lua

fixed https://github.com/apache/apisix/issues/2745

fix: call the checker:clear() before call the checker:stop() .

---

doc/zh-cn/plugins/node-status.md

Since there is node-status.md in English, so I add a link to that.

docs: add a English link of node-status.md

---

doc/plugins/node-status.md

There is no node-status.md in English, so I add it.

docs: add node-status.md in English to the doc

---

.travis/apisix_cli_test.sh
t/admin/plugins-reload.t

Avoid modifying config-default,yaml directly.

test: improve bin/apisix test cases.

---

apisix/admin/utils.lua
t/admin/consumers.t

fix: we didn't keep the create_time correctly

---

apisix/admin/consumers.lua
apisix/admin/global_rules.lua
apisix/admin/plugin_metadata.lua
apisix/admin/proto.lua
apisix/admin/routes.lua
apisix/admin/services.lua
apisix/admin/ssl.lua
apisix/admin/stream_routes.lua
apisix/admin/upstreams.lua
apisix/core/config_etcd.lua
apisix/core/etcd.lua
t/core/etcd.t

fix(etcd): avoid getting with prefix

---

doc/plugins/response-rewrite.md
doc/zh-cn/plugins/response-rewrite.md

1. add Summary for 'zh-cn/plugins/response-rewrite.md'
2. add Attention message for 'response-rewrite' doc.
ref:
https://github.com/apache/apisix/issues/2721

docs: add Attention message for 'response-rewrite' doc.

---

apisix/admin/consumers.lua
apisix/balancer/chash.lua
apisix/consumer.lua
apisix/core/ctx.lua
apisix/plugin.lua
apisix/plugins/basic-auth.lua
apisix/plugins/consumer-restriction.lua
apisix/plugins/hmac-auth.lua
apisix/plugins/jwt-auth.lua
apisix/plugins/key-auth.lua
apisix/plugins/limit-req.lua
apisix/plugins/prometheus/exporter.lua
apisix/plugins/wolf-rbac.lua
apisix/schema_def.lua
doc/admin-api.md
doc/architecture-design.md
doc/plugins/consumer-restriction.md
doc/zh-cn/admin-api.md
doc/zh-cn/architecture-design.md
doc/zh-cn/plugins/consumer-restriction.md
t/admin/consumers.t
t/core/ctx.t
t/plugin/key-auth.t
t/plugin/prometheus.t

refactor(consumer): remove id and use username only

---

apisix/plugins/http-logger.lua
t/lib/server.lua

fix(http-logger): correct the Content-Type of newline format log report

---

apisix/core/string.lua
apisix/discovery/eureka.lua
apisix/plugins/batch-requests.lua
apisix/plugins/cors.lua
apisix/plugins/ip-restriction.lua
apisix/plugins/log-rotate.lua
apisix/plugins/proxy-rewrite.lua
apisix/ssl/router/radixtree_sni.lua
t/lib/test_admin.lua

string_find -> str_find
find_str -> str_find
global string.find -> local str_find

fix: format the string.find

---

apisix/plugins/zipkin.lua
apisix/plugins/zipkin/reporter.lua
t/plugin/zipkin.t

fix: https://github.com/apache/apisix/issues/2726

feat: Improve zipkin span reporter performance

---

.travis/apisix_cli_test.sh
bin/apisix

close https://github.com/apache/apisix/issues/2670

fix(CLI): add Authorization header while enable etcd auth

---

doc/zh-cn/plugins/prometheus.md

fixed typo from zh-cn/plugins/prometheus.md

docs: fixed typo from zh-cn/plugins/prometheus.md

---

doc/aws.md

The image doesn't exist, cc @pahud 
And this file is in English only, no Chinese copy.

docs: remove non existing image

---

doc/stream-proxy.md
doc/zh-cn/stream-proxy.md

docs: fix stream proxy example

---

apisix/schema_def.lua
t/admin/services.t

feat: support '.' in id definition

---

apisix/schema_def.lua

fix(consumer): keep the id field for compatibility

---

apisix/plugins/kafka-logger.lua
doc/plugins/kafka-logger.md
doc/zh-cn/plugins/kafka-logger.md
t/plugin/kafka-logger.t

feat(kafka-logger): the key field should be optional.

---

.travis/apisix_cli_test.sh
bin/apisix

feat: allow whitespace-wrapped variables in config.yaml

---

.github/workflows/build.yml
.gitignore
.travis/apisix_cli_test_in_ci.sh
.travis/linux_apisix_current_luarocks_runner.sh

test: check the behavior when connecting to old etcd

---

doc/zh-cn/plugins/cors.md

add a space so that the example link is displayed correctly

docs: add a space so that the example link is displayed correctly

---

conf/config-default.yaml

This helps us to locate the problem.

feat: add rewritten proxy url in access log

---

apisix/schema_def.lua

fix: we should keep 'enable_websocket' for compatibility

---

apisix/plugins/hmac-auth.lua
t/plugin/hmac-auth.t

feat: the request parameter participating in the signature can be the parameter name

---

apisix/admin/plugins.lua
conf/config-default.yaml
t/APISIX.pm
t/admin/plugins.t
t/core/config.t

chore: sort default plugin list for easier search

---

apisix/plugin.lua
t/config-center-yaml/route-service.t
t/config-center-yaml/route-upstream.t
t/config-center-yaml/route.t

Fix #2828.
The bug is introduced in #2121.
Can't be reproduced in over 1 millions requests after applying this
patch.

fix: distinguish different routes which has the same service

---

FAQ_CN.md

docs:  uses etcd to implement millisecond configuration sync

---

doc/plugins/kafka-logger.md
doc/zh-cn/plugins/kafka-logger.md

close #2861
Optimize the attribute description of the `kafka-logger` document.

docs(kafka-logger): optimize the description of the attribute.

---

t/admin/plugins-reload.t

test: increase waiting time to make plugins reload test stable

---

apisix/plugins/kafka-logger.lua

solve #2860 
just lint the code

chore: lint kafka-logger

---

.travis/apisix_cli_test.sh
apisix/cli/ngx_tpl.lua
t/APISIX.pm

fix: we didn't initialize custom variable for admin access log

---

.travis/apisix_cli_test.sh

test: update apisix_cli_test.sh to fix CI

---

doc/plugin-develop.md
doc/zh-cn/plugin-develop.md

doc fix, Synchronize  doc/plugin-develop.md with doc/zh-cn/plugin-develop.md

fix: Synchronize with english doc

---

apisix/api_router.lua
apisix/init.lua
apisix/plugins/prometheus.lua
conf/config-default.yaml
doc/plugins/prometheus.md
doc/zh-cn/plugins/prometheus.md
t/admin/plugins-reload.t
t/plugin/prometheus.t

feat(prometheus): allow customizing Prometheus export uri

---

doc/plugins/http-logger.md
doc/zh-cn/plugins/http-logger.md

docs(http-logger): Improve the attribute description of the document.

---

doc/architecture-design.md
doc/zh-cn/architecture-design.md

fix https://github.com/apache/apisix/issues/2843

docs: corrected link in architecture-design

---

t/node/chash-balance.t

test: improve chash-balance cases

---

apisix/admin/routes.lua
apisix/http/route.lua
apisix/http/router/radixtree_host_uri.lua
apisix/http/router/radixtree_uri.lua
rockspec/apisix-master-0.rockspec
t/admin/routes.t
t/config-center-yaml/route.t

feat: validate the operator in vars

---

doc/admin-api.md

docs: add missing consumer username in English version

---

Makefile

add `git submodule update --init --recursive` for CI

test: add git submodule update --init --recursive

---

FAQ.md
FAQ_CN.md

docs: etcd faq

---

apisix/consumer.lua
apisix/plugins/basic-auth.lua
apisix/plugins/hmac-auth.lua
apisix/plugins/jwt-auth.lua
apisix/plugins/key-auth.lua

chore: simpify the consumer attach in auth plugin

---

apisix/plugins/sls-logger.lua
t/plugin/sls-logger.t

fix:https://github.com/apache/apisix/issues/2930

fix: change  string concat

---

apisix/plugins/http-logger.lua
apisix/plugins/kafka-logger.lua
apisix/plugins/syslog.lua
apisix/plugins/tcp-logger.lua
apisix/plugins/udp-logger.lua
t/plugin/syslog.t
t/plugin/tcp-logger.t
t/plugin/udp-logger.t

Closing https://github.com/apache/apisix/issues/2922.

fix: fixed the non-effective plugin configuration update in tcp/udp-logger plugin

---

.travis/apisix_cli_test.sh
apisix/cli/etcd.lua

chore: handle error when connecting with passwd to etcd without auth

---

t/node/merge-route.t

test: make node/merge-route.t stable

---

apisix/core/request.lua
apisix/plugins/hmac-auth.lua
apisix/plugins/request-id.lua
apisix/plugins/wolf-rbac.lua
apisix/plugins/zipkin.lua
t/core/request.t

fix: refresh cached header when we set request header

---

rockspec/apisix-master-0.rockspec

feat: install lua-resty-hmac-ffi

---

CHANGELOG.md
CHANGELOG_CN.md

as title.
related PR: https://github.com/apache/apisix/pull/2244

docs: update CVE information in the CHANGELOG of `2.0`

---

apisix/plugins/skywalking.lua
t/plugin/skywalking.t

chore(skywalking): the range of sample rate should be `[0, ratio)`

---

apisix/plugins/fault-injection.lua

Previously, we got n+1/101 as the percentage.

fix: we should use [1, 100] for percentage instead of [0, 100]

---

t/admin/routes2.t

test: solve conflict between #2993 and #2943

---

doc/plugins/server-info.md

docs: update server-info.md

---

apisix/core/etcd.lua

fix: avoid duplicate auto-generated id

---

.travis/apisix_cli_test.sh
apisix/cli/file.lua
apisix/cli/ops.lua
apisix/core/config_local.lua
conf/config.yaml
doc/how-to-build.md
t/core/config.t

Also merge bundle of repeated code.

fix: avoid unnecessary type check and support var in local_conf

---

.github/workflows/spellchecker.yml
apisix/core/ctx.lua
apisix/core/etcd.lua
apisix/plugins/response-rewrite.lua
doc/aws.md
doc/plugins/kafka-logger.md
doc/plugins/response-rewrite.md
doc/plugins/sls-logger.md
doc/plugins/tcp-logger.md
doc/plugins/udp-logger.md
t/core/response.t
t/node/upstream-node-dns.t
t/plugin/prometheus.t
t/router/graphql.t

style: check misspell

---

CHANGELOG.md
CHANGELOG_CN.md
README.md
doc/architecture-design.md
doc/plugins/wolf-rbac.md
doc/zh-cn/discovery.md

Removes unneeded whitespace from Markdown and it will standardize our documentation.

docs: remove unneeded whitespace from Markdown

---

apisix/core/config_etcd.lua
apisix/core/config_yaml.lua
apisix/plugins/zipkin.lua
apisix/plugins/zipkin/reporter.lua
t/node/invalid-route.t
t/node/invalid-service.t
t/node/invalid-upstream.t

chore: spelling

---

.travis/apisix_cli_test.sh
apisix/cli/ops.lua
doc/stand-alone.md
doc/zh-cn/stand-alone.md

feat: check if Admin API is used with etcd config_center

---

.github/ISSUE_TEMPLATE/improve-docs.md

feature: added improve docs issue template to reduce set labels manually.

feat: added improve docs issue template

---

doc/plugins/http-logger.md
doc/plugins/request-validation.md

docs: corrected typo in doc

---

.github/workflows/build.yml
t/admin/schema.t
t/admin/services.t
t/admin/ssl.t
t/core/config.t
t/core/ctx.t
t/core/etcd-sync.t
t/core/string.t
t/node/route-domain.t
t/plugin/consumer-restriction.t
t/plugin/error-log-logger.t
t/plugin/hmac-auth.t
t/plugin/http-logger.t
t/plugin/limit-count.t
t/plugin/limit-req.t
t/plugin/proxy-cache.t
t/router/multi-ssl-certs.t

Removes unneeded whitespace and standardizes our code

refactor: remove trailing whitespace

---

.github/workflows/lint.yml
.gitignore
.markdownlint.yml
doc/zh-cn/getting-started.md
doc/zh-cn/plugins/mqtt-proxy.md

- add a Markdownlint config file
- lint Markdownlint for MD039 - Spaces inside link text
https://www.npmjs.com/package/markdownlint-cli
Adds basic testing for our Markdown.  This will standardize our Markdown.

feat: add a GitHub Action to lint the Markdown

---

apisix/init.lua
t/node/upstream.t

feat: return 502 for upstream not found in the DP

---

kubernetes/deployment.yaml

fix: remove hardcoded TZ env

---

apisix/ssl/router/radixtree_sni.lua
t/router/radixtree-sni.t

feat: improve the error msg when client doesn't send SNI

---

Makefile

fix: copy the files in conf/cert when installing

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/macOS.yml
.github/workflows/spellchecker.yml
.gitignore
.yamllint
conf/apisix.yaml
conf/config-default.yaml
conf/config.yaml
conf/debug.yaml
kubernetes/deployment.yaml
kubernetes/service-monitor-for-prometheus.yaml
kubernetes/service.yaml
t/APISIX.pm

Lint some YAML
Add a `.yamllint` config file
Standardizes our YAML files

feat(CI): add a GitHub Action to lint the YAML files

---

t/lib/server.lua

Now we connect to real skywalking for test.

test: remove useless skywalking mock

---

CHANGELOG.md

docs: fix spelling

---

doc/zh-cn/plugins/server-info.md

Because the `report_interval` minimum is 60. So it's a bad example.

fix: bad server_info example

---

.travis/linux_apisix_master_luarocks_runner.sh
Makefile

fix: add control directory in installation

---

apisix/plugin.lua
doc/architecture-design.md
doc/zh-cn/architecture-design.md
t/debug/debug-mode.t

fix: make debug-mode work with global rule

---

doc/admin-api.md
doc/zh-cn/admin-api.md

docs: catch up with the current status of route

---

.travis/linux_apisix_master_luarocks_runner.sh

chore: remove temporary hack

---

.github/semantic.yml
CONTRIBUTING.md

docs: update contributing guide

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/request-help.md

docs: when opening issue, also mention the Nginx version

---

apisix/control/v1.lua
apisix/core/table.lua
apisix/plugin.lua
doc/control-api.md
t/control/schema.t
t/core/table.t
t/lib/test_admin.lua

feat: expose schema via control API

---

apisix/schema_def.lua
t/config-center-yaml/route.t

Used as a reference to script metadata.

feat: add script_id field used by dashboard

---

CODE_STYLE.md
CODE_STYLE_CN.md
doc/zh-cn/install-dependencies.md

Optimized several places in the document that may cause confusion to developers

docs: fix documentation about ETCD

---

apisix/plugins/example-plugin.lua
doc/plugin-develop.md
doc/zh-cn/plugin-develop.md

docs: improve the plugin-develop doc

---

.github/workflows/build.yml

ci: pass again

---

t/plugin/traffic-split.t

test: fix unstable test in traffic-split.t

---

doc/how-to-build.md
doc/zh-cn/how-to-build.md

docs: mention iresty/test-nginx should be used

---

t/plugin/limit-count.t

close #3108
`limit-count` plugin add more test cases to cover the case where the upstream is a domain name.

test: limit-count add more test cases to cover the case where the upstream is a domain name

---

README.md
README_CN.md

docs: use new badges

---

doc/admin-api.md
doc/zh-cn/admin-api.md
t/admin/plugins.t

/apisix/admin/plugins/?all=true to /apisix/admin/plugins?all=true
fix https://github.com/apache/apisix/pull/2886#discussion_r549553878

chore: tweak the uri to view plug-in types

---

apisix/schema_def.lua
t/admin/routes.t
t/config-center-yaml/route.t

feat: allow host with underscore

---

apisix/consumer.lua
apisix/plugin.lua
t/config-center-yaml/consumer.t

feat: add consumer plugin validation at DP side

---

apisix/cli/ops.lua
t/cli/cli.t

feat(cli): parse IPv6 resolver address

---

apisix/init.lua
doc/architecture-design.md
doc/zh-cn/architecture-design.md
t/plugin/ip-restriction.t

feat: log when request is blocked by a plugin

---

apisix/schema_def.lua

feat: allow empty object of nodes in upstream

---

.gitignore
CHANGELOG.md
CHANGELOG_CN.md
Makefile
apisix/core/version.lua
doc/how-to-build.md
doc/zh-cn/how-to-build.md
rockspec/apisix-2.2-0.rockspec

feat: release version 2.2

---

CHANGELOG.md
CHANGELOG_CN.md

docs: format CHANGELOG

---

t/admin/plugins-reload.t

test: make admin/plugins-reload.t stable

---

.github/workflows/build.yml

ci: simplify the if condition

---

t/plugin/http-logger-json.t

test: demonstrate http-logger works fine with JSON body

---

.markdownlint.yml

- First header should be a top level header
Standardizes the Markdown files

chore: enable Markdownlint rule MD002

---

apisix/admin/init.lua
apisix/plugins/grpc-transcode/request.lua
apisix/plugins/request-validation.lua
apisix/plugins/wolf-rbac.lua

Using local variables instead of global calls
```
ngx.req.read_body -> local req_read_body
```
ref:
https://github.com/apache/apisix/issues/3243

chore: Using local variables instead of global calls

---

CONTRIBUTING.md

Informs contributors to APISIX about the linting tools we are now using.
Helps standardize the Markdown and YAML files.

docs: update CONTRIBUTING to include more details on linters

---

doc/stand-alone.md
doc/zh-cn/stand-alone.md
t/config-center-yaml/plugin-metadata.t
t/config-center-yaml/stream-route.t

docs: enrich stand alone mode's doc

---

doc/plugins/batch-requests.md

docs: fix table of contents Markdown link

---

doc/https.md
doc/zh-cn/https.md

Standardizes the technical terms.

docs: fix case of Python

---

apisix/plugin.lua
apisix/plugins/error-log-logger.lua
apisix/schema_def.lua
t/admin/plugins.t
t/control/schema.t

Fix https://github.com/apache/apisix-dashboard/issues/1227

fix: always inject disable field into plugin schema

---

doc/plugins/request-id.md

Removes an unneeded TOC entry that does not link to anything.

docs: remove unneeded table of contents entry

---

doc/plugins/skywalking.md

Standardizes the Markdown headings.

docs: fix Markdown heading

---

doc/plugins/prometheus.md
doc/zh-cn/plugins/prometheus.md

docs: update prometheus docs

---

benchmark/run.sh

When we do benchmarks, upstream server counts usually need to take into consideration.
So I add the support for setting the upstream server count in this PR.
```
./benchmark/run.sh 1 4
```
```
➜  apisix git:(master) ✗ ./benchmark/run.sh 1 4
+ '[' -n 1 ']'
+ worker_cnt=1
+ '[' -n 4 ']'
+ upstream_cnt=4
+ mkdir -p benchmark/server/logs
+ mkdir -p benchmark/fake-apisix/logs
+ make init
./bin/apisix init
./bin/apisix init_etcd
+ trap onCtrlC INT
++ seq 1 4
+ for up_cnt in $(seq 1 $upstream_cnt)
+ port=1980
+ nginx_listen='listen 1980;'
+ upstream_nodes='"127.0.0.1:1980":1'
+ '[' 1 -lt 4 ']'
+ upstream_nodes='"127.0.0.1:1980":1,'
+ for up_cnt in $(seq 1 $upstream_cnt)
+ port=1981
+ nginx_listen='listen 1980;listen 1981;'
+ upstream_nodes='"127.0.0.1:1980":1,"127.0.0.1:1981":1'
+ '[' 2 -lt 4 …
```

feat: benchmark support specify upstream count

---

apisix/admin/upstreams.lua
apisix/balancer/chash.lua
apisix/schema_def.lua
doc/admin-api.md
t/node/chash-hashon.t

Support hash on vars_combinations, refer to #3261
* [Y] Did you explain what problem does this PR solve? Or what new features have been added?
* [Y] Have you added corresponding test cases?
* [Y] Have you modified the corresponding document?
* [Y] Is this PR backward compatible? **If it is not backward compatible, please discuss on the [mailing list](https://github.com/apache/apisix/tree/master#community) first**

feat: support hash on vars_combinations

---

.github/workflows/build.yml
.travis/linux_openresty_1_15_runner.sh

ci: add OpenResty 1.15.8.2

---

.markdownlint.yml
doc/install-dependencies.md
doc/zh-cn/install-dependencies.md

Use consistent heading style
Standardizes the Markdown files.

chore: enable Markdownlint rule MD003/heading-style

---

apisix/plugin.lua

chore: prometheus.exporter should init before plugins

---

.gitignore
Makefile
t/admin/consumers2.t
t/admin/upstream2.t
t/router/graphql.t
utils/check-test-code-style.sh

ci: lint test file

---

t/node/least_conn.t
t/node/upstream-discovery.t

test: fix least conn case

---

benchmark/run.sh

shell command `sed` should be compatible with OSX

fix: correct sed command in OSX

---

README.md
README_CN.md

docs: update to 2.2 for source code package.

---

doc/admin-api.md
doc/zh-cn/admin-api.md

docs: for global rule

---

apisix/core/utils.lua
t/core/utils.t

feat: resolve var supports `${...}` format

---

doc/architecture-design.md
doc/zh-cn/architecture-design.md

Standardizes the Markdown files

docs: use lowercase link anchors

---

doc/plugins/error-log-logger.md

Standardizes the Markdown files.

docs: fix Markdown link

---

utils/linux-install-openresty.sh

Should use secure HTTP if possible.

chore: fix missing HTTPS on link

---

doc/admin-api.md
doc/zh-cn/admin-api.md

docs: delete the `http` part to avoid ambiguity

---

doc/plugin-interceptors.md
doc/plugins/authz-keycloak.md
doc/plugins/request-id.md
doc/plugins/request-validation.md
doc/zh-cn/plugin-interceptors.md
doc/zh-cn/plugins/authz-keycloak.md
doc/zh-cn/plugins/request-id.md
doc/zh-cn/plugins/request-validation.md

fix some incomplete shell commands in the api examples.

docs: fix some incomplete shell commands in the examples

---

t/node/healthcheck-stop-checker.t

test: add more test to check if checker is stopped.

---

apisix/http/service.lua
apisix/router.lua
apisix/upstream.lua
t/admin/plugin-metadata.t
t/admin/upstream.t
t/admin/upstream2.t
t/node/upstream.t

test: make ci stable

---

t/admin/routes.t
t/admin/services-string-id.t
t/admin/services.t
t/plugin/skywalking.t
t/plugin/zipkin.t
utils/check-test-code-style.sh

Those test may mislead people.
Also add a check to prevent skipping test by accident.

test: clean unrun cases

---

doc/zh-cn/README.md

docs: add link of control-api.md to Chinese index.

---

apisix/admin/init.lua
apisix/plugins/request-validation.lua
apisix/plugins/wolf-rbac.lua
apisix/utils/log-util.lua

chore: ngx.req.get_body_data -> req_get_body_data

chore: ngx.req.get_body_data -> req_get_body_data

---

.github/workflows/lint.yml
README_CN.md

Caused by #3368, an extra blank is not removed in time, so markdownlint would keep failing

fix: markdownlint issue

---

doc/plugins/traffic-split.md
doc/zh-cn/plugins/traffic-split.md

docs(traffic-split): update the vars example of the docs

---

apisix/schema_def.lua
t/admin/routes2.t

feat: remove restriction of label pattern to support Chinese

---

t/node/healthcheck-stop-checker.t

Test cases from other files may still refer upstream 1.

test: avoid unstable case caused by delete upstream 1

---

NOTICE

chore: hi 2021

---

apisix/plugins/grpc-transcode.lua
t/plugin/grpc-transcode.t

* [] Did you explain what problem does this PR solve? Or what new features have been added?

fix(grpc-transcode): ienum_as_name to enum_as_name

---

apisix/admin/ssl.lua
t/admin/ssl2.t

fix: SSL resource supports PATCH with sub path

---

doc/plugins/mqtt-proxy.md

docs: fix table of contents links

---

.github/workflows/lint.yml
conf/config.yaml
kubernetes/deployment.yaml
kubernetes/service.yaml

ci: address yamllint warnings

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/request-help.md

* [] Have you added corresponding test cases?

chore: require more environment info

---

apisix/balancer.lua

For issues #3423
If we call `checker:get_target_status` got err, we should log it, helping find some hidden mistakes.

fix: when called checker:get_target_status got err, we should log it~

---

apisix/admin/init.lua

Let's use 'done' all the way to make tests happy.
Fix #3432.

chore: both 'done' & 'recursive' mean the event is delivered

---

.travis/apisix_cli_test/test_main.sh
apisix/cli/ops.lua

Fix #2948 
Fix #3202
Refer: #3208

fix: ignore stale nginx.pid

---

apisix/core/config_etcd.lua

chore: change the msg when compacted happened to make it more clear

---

apisix/plugins/consumer-restriction.lua

chore: fix indent

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/request-help.md

This ":" can be confusing in the middle of the sentence. 
Putting the ":" after the sentence can better distinguish the question from what the user filled in.
1. Unified sentence style.

chore: improve issue template file style

---

.travis/linux_apisix_master_luarocks_runner.sh
.travis/linux_openresty_common_runner.sh
bin/apisix

fix(cli): add missing entry 

---

.travis/linux_apisix_current_luarocks_runner.sh
.travis/linux_apisix_master_luarocks_runner.sh
utils/centos7-ci.sh
utils/linux-install-luarocks.sh

ci: add missing OPENRESTY_PREFIX env variable

---

doc/admin-api.md
doc/zh-cn/admin-api.md

docs: clarify the default value of Upstream.pass_host

---

Makefile

chore: should exclude utils/ from the release

---

apisix/core/log.lua
apisix/plugins/kafka-logger.lua

chore(kafka-logger): delay log partition_id

---

doc/plugin-develop.md

docs: fix table of contents link

---

apisix/cli/etcd.lua
apisix/cli/ops.lua

chore: add argument verbose to print init_etcd debug info

---

.travis/linux_apisix_master_luarocks_runner.sh
apisix/cli/apisix.lua
apisix/cli/ngx_tpl.lua
bin/apisix
utils/linux-install-luarocks.sh

change: don't hack the prefix of LuaRocks

---

Makefile
utils/linux-install-luarocks.sh

fix: `make deps` should not require root.

---

t/admin/consumers2.t
t/admin/global-rules.t
t/admin/plugin-metadata.t
t/admin/routes2.t
t/admin/services2.t
t/admin/ssl2.t
t/admin/stream-routes.t
t/admin/upstream2.t

test: make 'not unwanted data, GET' stable

---

doc/zh-cn/health-check.md

fixes #3507
Fixes a link in the Markdown.

docs: fix control-api.md link

---

doc/install-dependencies.md
doc/zh-cn/install-dependencies.md
utils/linux-install-luarocks.sh

close https://github.com/apache/apisix/issues/3529

chore: fixed install luarocks

---

README.md
README_CN.md
doc/admin-api.md
doc/discovery.md
doc/plugins/batch-requests.md
doc/plugins/cors.md
doc/plugins/dubbo-proxy.md
doc/plugins/response-rewrite.md
doc/plugins/skywalking.md

Standardizes the Markdown files.

docs: standardize link anchors to lower case

---

doc/admin-api.md

docs: fix grammar

---

doc/zh-cn/getting-started.md
doc/zh-cn/plugin-develop.md

docs: fix Markdown links

---

README.md
README_CN.md

fixes #3527
Updates the README

docs: add four more projects to the "Good first issue" section

---

doc/plugin-develop.md
doc/zh-cn/plugin-develop.md

docs: Markdown syntax exception

---

apisix/plugins/limit-count.lua
apisix/plugins/limit-count/limit-count-redis.lua
doc/plugins/limit-count.md
doc/zh-cn/plugins/limit-count.md
t/plugin/limit-count-redis.t
t/plugin/limit-count-redis2.t

Under normal circumstances, Redis deploys and uses more than one database, so this time we added select database related functions, hoping to make some contributions to `apisix`

feat: add select database for Redis related functions

---

.travis/linux_openresty_common_runner.sh
t/grpc-proxy-test.sh

test: detect if grpc_server_example starts

---

doc/zh-cn/install-dependencies.md

docs: fix unresolved merge conflicts

---

.github/workflows/misc-checker.yml

ci: add check to detect merge conflicts

---

.github/dependabot.yml

Check for updates to GitHub Actions every weekday.
https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot
Need to make sure the 'GitHub Actions' are up to date.
It looks like we have one action using the old version `actions/checkout@v1` so this should be updated automatically to `actions/checkout@v2` within the next day after this PR is merged.
https://github.com/apache/apisix/blob/0b6d35d965ea1a33a2ba30c0f042b41abeed3381/.github/workflows/misc-checker.yml#L11

ci: create dependabot config file

---

README.md
README_CN.md
doc/architecture-design.md
doc/plugins/echo.md
doc/zh-cn/architecture-design.md
doc/zh-cn/plugins/echo.md

fixes #3588
Fixes some spelling.

docs: fix spelling 'filer' should be 'filter'

---

.github/workflows/lint.yml
Makefile
t/lib/dubbo-backend/dubbo-backend-provider/pom.xml
t/lib/dubbo-backend/dubbo-backend-provider/src/main/resources/META-INF/spring/dubbo-demo-provider.xml
t/node/global-rule.t
t/node/least_conn.t
t/plugin/cors.t
t/plugin/dubbo-proxy/route.t
t/plugin/prometheus2.t
t/plugin/traffic-split.t

Standardizes the code by checking for trailing whitespace.

feat(CI): check for trailing whitespace

---

README.md
apisix/plugins/error-log-logger.lua
apisix/plugins/sls-logger.lua
t/plugin/ip-restriction.t

chore: fix grammar

---

.github/workflows/chaos.yml
t/chaos/kill-etcd_test.go
t/chaos/utils.go

Temporary trial to make CI works. The problem would be fixed in #3613

ci: use httpbin.org in chaos test to make CI works

---

apisix/core/utils.lua
conf/config-default.yaml
t/APISIX.pm
t/core/utils.t

Also disable it in the test to avoid occassional DNS query timeout.

feat: allow disabling search option in resolv.conf

---

t/plugin/plugin.t
t/stream-plugin/plugin.t

test: ensure all plugins have unique priority

---

apisix/core/utils.lua
apisix/upstream.lua
t/APISIX.pm
t/core/utils.t
t/node/grpc-proxy.t
t/node/https-proxy.t

fix: don't use port 80 for all schemes

---

.github/workflows/misc-checker.yml
README_ES.md

The Spanish translation work was done by Jorge > @summerhill5
refs #3587
Adds a README in Spanish the world's 4th most spoken language.  Helps market APISIX.

feat: translate the README to Spanish

---

FAQ.md
apisix/core/id.lua
kubernetes/README.md
t/plugin/echo.t

Standardizes the code base by removing unneeded whitespace.

chore: remove unneeded whitespace before commas

---

apisix/balancer.lua

chore: remove the obsolete TODO

---

.travis/apisix_cli_test/test_main.sh

test: clean up temporary files after CLI test

---

.travis/apisix_cli_test/test_dns.sh
apisix/cli/ngx_tpl.lua

fix: correct the template of dns_resolver_valid

---

doc/plugins.md

docs: Update plugins.md

---

doc/plugins/traffic-split.md
doc/zh-cn/plugins/traffic-split.md

Fix the example of traffic-split plugin documentation and delete useless request parameters.

chore: fix the traffic-split plugin doc

---

t/node/route-domain-with-local-dns.t
t/node/route-domain.t
t/plugin/key-auth-upstream-domain-node.t

ci: avoid requesting IPv6 address as GitHub Action doesn't support it

---

doc/zh-cn/plugins/sls-logger.md

docs: update sls-logger.md

---

doc/plugin-develop.md
doc/zh-cn/plugin-develop.md

docs: plugin-develop.md adds ctx and conf descriptions

---

Makefile

chore: no need to package documentation

---

apisix/init.lua
apisix/upstream.lua
apisix/utils/upstream.lua
t/node/upstream-discovery.t

fix: cache server picker for nodes without port

---

apisix/balancer/least_conn.lua
apisix/balancer/roundrobin.lua

chore: add safe limit to avoid infinite loop caused by bug

---

apisix/upstream.lua

See https://github.com/apache/apisix/pull/3629#discussion_r582423351

chore: capitalize the constant 

---

docs/en/latest/plugin-develop.md
docs/zh/latest/plugin-develop.md

Related issues: https://github.com/apache/apisix/issues/3652

docs: plugin-develop.md add to view all plugin priorities

---

.github/workflows/centos7-ci.yml
.travis/linux_openresty_common_runner.sh
docs/en/latest/plugins/skywalking.md
docs/zh/latest/plugins/skywalking.md

ci: use the specified version of `skywalking`.

---

bin/apisix

fix: error will be reported when try to start apisix without the which utility

---

docs/es/latest/README.md
docs/zh/latest/README.md

Fixed broken image links in `docs/es` and `docs/zh` for README.

docs: update the link to the failed image

---

apisix/admin/plugin_config.lua
apisix/schema_def.lua
docs/en/latest/admin-api.md
docs/zh/latest/admin-api.md
t/admin/plugin-configs.t

Also fix the schema validation.

feat: add labels to plugin_config

---

README.md
docs/es/latest/README.md
docs/zh/latest/README.md

docs: updated users image part in README.md

---

docs/en/latest/plugins/request-id.md
docs/zh/latest/plugins/request-id.md

Fix the configuration example uri of the request-id.md document is inconsistent with the test uri, and the response data of the test request is added with the `X-Request-Id` header.

docs: update request-id.md doc

---

Makefile

chore: only package this version's rockspec

---

docs/en/latest/config.json

Fix #3729 , Fix #3728
Fix the invalid link.

docs: fix invalid link

---

apisix/schema_def.lua

refactor: extract desc definition from the schema

---

t/plugin/request-id.t

test: improve the unique request id check

---

t/node/plugin-configs.t

test: clean up malformed etcd data

---

docs/en/latest/how-to-build.md
docs/zh/latest/how-to-build.md

docs: fix wrong dir when install from source code.

---

t/fuzzing/public.py

ci: ensure the fuzzing work under Python3

---

docs/en/latest/architecture-design.md
docs/en/latest/benchmark.md
docs/zh/latest/architecture-design.md
docs/zh/latest/benchmark.md

Fix #3730 
Change the img tag to markdown syntax.

docs: change the img tag to markdown syntax

---

docs/en/latest/config.json

docs: rewrite sidebar

---

apisix/core/config_yaml.lua
apisix/init.lua

perf(standalone): load configuration in the init phase

---

.travis/apisix_cli_test/test_main.sh
apisix/cli/etcd.lua

refactor: remove unused etcd key node_status

---

powered-by.md

updates the old users wall image by new.
no

docs: updated the users wall of powered-by.md

---

apisix/cli/ngx_tpl.lua
apisix/core/ctx.lua
apisix/plugins/proxy-cache.lua
t/APISIX.pm
t/plugin/proxy-cache.t

fix: don't override cache relative headers

---

docs/en/latest/FAQ.md
docs/zh/latest/FAQ.md

Update the content of `Does APISIX have a console interface` in the FAQ document.

docs: update the content of "Does APISIX have a console interface" in the FAQ doc

---

README.md

docs: added generated contributor over time service provider

---

apisix/core/config_etcd.lua
conf/config-default.yaml
t/core/etcd-sync.t

feat: add a safe exit to disable sync conf during start

---

docs/en/latest/how-to-build.md
docs/en/latest/plugins/dubbo-proxy.md
docs/zh/latest/how-to-build.md

docs: use the build script which is more up-to-date.

---

apisix/discovery/consul_kv.lua
apisix/init.lua
apisix/plugin.lua
apisix/plugins/api-breaker.lua
apisix/plugins/error-log-logger.lua
apisix/plugins/example-plugin.lua
apisix/plugins/log-rotate.lua
apisix/plugins/node-status.lua
apisix/plugins/prometheus/exporter.lua
apisix/plugins/response-rewrite.lua
apisix/plugins/server-info.lua
docs/en/latest/admin-api.md
docs/en/latest/discovery/consul_kv.md
docs/en/latest/discovery/dns.md
t/control/discovery.t
t/node/grpc-proxy.t
t/node/remote-addr-ipv6.t
t/node/upstream-ipv6.t
t/plugin/prometheus2.t
t/plugin/response-rewrite.t

chore: fix spelling, grammar and JSON example

---

apisix/cli/ops.lua
bin/apisix
rockspec/apisix-master-0.rockspec
t/cli/test_validate_config.sh

fix: correct the validation for ssl_trusted_certificate

---

docs/en/latest/FAQ.md
docs/zh/latest/FAQ.md

docs: added access to Dashboard through APISIX proxy in FAQ

---

t/lib/dubbo-backend/dubbo-backend-interface/src/main/java/org/apache/dubbo/backend/DemoService.java
t/lib/dubbo-backend/dubbo-backend-provider/src/main/java/org/apache/dubbo/backend/provider/DemoServiceImpl.java
t/plugin/dubbo-proxy/upstream.t

test: don't crash when dubbo upstream returns integer status code

---

docs/en/latest/FAQ.md
docs/zh/latest/FAQ.md

docs: fix broken link

---

docs/en/latest/mtls.md
docs/zh/latest/mtls.md

docs: fix mtls example

---

docs/en/latest/plugins/limit-count.md

Fix https://github.com/apache/apisix-website/issues/264
Fix the limit-count plugin typo.

docs: fix limit-count typo

---

apisix/init.lua
apisix/schema_def.lua

change: remove deprecated upstream.enable_websocket

---

docs/en/latest/plugin-develop.md
docs/zh/latest/plugin-develop.md

I still think we should try our best to prevent modifying APISIX itself.

docs: update plugin-develop.md

---

apisix/schema_def.lua
t/node/grpc-proxy.t

chore: remove unused consumer.id

---

t/core/utils.t
t/node/invalid-route.t
t/node/route-domain.t

test: use longer timeout for internet DNS query

---

docs/en/latest/discovery.md

docs: remove duplicated section from discovery.md

---

docs/en/latest/FAQ.md
docs/zh/latest/FAQ.md

docs: add route uri regular matching in the FAQ doc

---

README.md

Fix stand-alone doc link broken
Fix #3882

docs: fix stand-alone doc link broken

---

docs/en/latest/plugins/dubbo-proxy.md

docs(dubbo): describe the returned data requirement

---

.github/workflows/build.yml
.travis/linux_apisix_current_luarocks_runner.sh
apisix/cli/etcd.lua
bin/apisix
conf/config-default.yaml
t/cli/test_etcd_mtls.sh
utils/set-dns.sh

feat(cli): support etcd mTLS

---

apisix/discovery/dns.lua
docs/en/latest/discovery/dns.md
t/coredns/db.test.local
t/discovery/dns/sanity.t

feat: support priority in SRV record

---

t/config-center-yaml/ssl.t
t/plugin/redirect.t
t/router/multi-ssl-certs.t
t/router/radixtree-sni.t
t/router/radixtree-sni2.t
utils/linux-install-openresty.sh

ci: use build-apisix-openresty.sh instead

---

Makefile
docs/en/latest/FAQ.md
docs/zh/latest/FAQ.md

feat: show how to specify --server when installing the dependency

---

apisix/plugins/zipkin.lua
docs/en/latest/plugins/zipkin.md
docs/zh/latest/plugins/zipkin.md
t/lib/server.lua
t/plugin/zipkin.t
t/plugin/zipkin2.t

If you need to be compatible with the old one, you can set the
span_version to 1.
Fix #3827

change(zipkin): rearrange the child span

---

docs/en/latest/examples/plugins-hmac-auth-generate-signature.md
docs/en/latest/plugins/hmac-auth.md
docs/zh/latest/plugins/hmac-auth.md

chore: sort imports in the Markdown examples

---

apisix/core/dns/client.lua

fix: corrent SRV record priority

---

apisix/upstream.lua
t/stream-node/priority-balancer.t

fix: priority for nonarray upstream node in stream

---

docs/en/latest/config.json
docs/en/latest/discovery.md

docs: add missing index of discovery

---

apisix/cli/ngx_tpl.lua
apisix/cli/ops.lua
conf/config-default.yaml
t/cli/test_validate_config.sh

fix: allow addr:port format in stream_proxy

---

apisix/cli/ngx_tpl.lua
t/APISIX.pm

chore: remove unused shared dict

---

docs/en/latest/config.json

Please answer these questions before submitting a pull request
- Why submit this pull request?
___
- Description
tells users where they are in sidebar
- How to fix?
added a label of Apache Apisix to sidebar 
___
- Describe the details and related test reports.
___
- Why need to backport?
- Source branch
https://github.com/iamayushdas/apisix/tree/sidebar
- Related commits and pull requests
https://github.com/apache/apisix-website/issues/230
- Target branch
https://github.com/apache/apisix/tree/master

docs: tells users where they are

---

t/plugin/proxy-rewrite2.t

test: show how to bypass the ctx.var cache

---

docs/en/latest/getting-started.md
docs/en/latest/plugins/proxy-rewrite.md
docs/zh/latest/plugins/proxy-rewrite.md

change proxy rewrite to proxy-rewrite
In the proxy-rewrite.md document, some plugin names are proxy rewrite, which is a typo.
Fix #3145

docs: Improve proxy-rewrite plugin docs

---

apisix/debug.lua
apisix/plugins/skywalking.lua
apisix/timers.lua
t/APISIX.pm
t/admin/plugins-reload.t
t/config-center-yaml/plugin-configs.t
t/config-center-yaml/plugin.t
t/core/config_etcd.t
t/core/random.t
t/debug/debug-mode.t
t/discovery/dns/mix.t
t/discovery/dns/sanity.t
t/node/healthcheck-discovery.t
t/node/healthcheck-ipv6.t
t/node/healthcheck-multiple-worker.t
t/node/healthcheck-passive.t
t/node/healthcheck-stop-checker.t
t/node/healthcheck.t
t/node/healthcheck2.t
t/node/plugin-configs.t
t/node/route-delete.t
t/node/upstream-discovery.t
t/plugin/error-log-logger.t
t/plugin/fault-injection2.t
t/plugin/node-status.t
t/plugin/server-info.t
t/plugin/traffic-split2.t
t/stream-node/random.t

test: enable master-worker mode by default

---

t/discovery/consul_kv.t

test: make consul_kv stable

---

docs/es/latest/README.md

chore: fix Markdown links in the Spanish README

---

docs/zh/latest/README.md
docs/zh/latest/plugins/dubbo-proxy.md

docs: add chinese version of dubbo-proxy.md

---

docs/zh/latest/plugins/hmac-auth.md

docs(hmac-auth): fix the document link

---

docs/en/latest/FAQ.md
docs/zh/latest/FAQ.md

docs(FAQ.md): add a configuration example in How to modify the log level

---

README.md

docs: fixed grammer in readme.

---

t/plugin/log-rotate.t

test: make plugin/log-rotate.t stable

---

bin/apisix

chore(cli): tweak error msg

---

docs/en/latest/FAQ.md
t/cli/test_validate_config.sh
t/control/discovery.t

chore: fix spelling

---

apisix/cli/ngx_tpl.lua
t/APISIX.pm
t/cli/test_access_log.sh
t/node/https-proxy.t

Move the variables under locations to avoid being reset by proxy-mirror.
Fix #3864

fix: make sure SNI is changed with HTTP host

---

.github/workflows/build.yml
.github/workflows/centos7-ci.yml
.github/workflows/chaos.yml
.github/workflows/fuzzing-ci.yaml

* [] Have you added corresponding test cases?

ci: bypass test if the change is doc only

---

docs/en/latest/config.json
docs/en/latest/discovery/eureka.md

docs: add a placeholder for Eureka SD

---

docs/zh/latest/install-dependencies.md

Fixed spelling errors：gPRC ----> gRPC

doc: fix spelling error

---

t/APISIX.pm
t/lib/server.lua
t/node/upstream-websocket.t

test: add cases for wss

---

.github/workflows/lint.yml

ci: remove unused markdown-link-check

---

apisix/admin/ssl.lua
t/admin/ssl2.t

Fix https://github.com/apache/apisix-ingress-controller/issues/339

fix: PATCH ssl should encrypt key

---

apisix/schema_def.lua
t/admin/schema.t

refactor: ssl schema

---

apisix/cli/ngx_tpl.lua
apisix/cli/ops.lua
apisix/plugins/prometheus.lua
conf/config-default.yaml
docs/en/latest/plugins/prometheus.md
docs/zh/latest/plugins/prometheus.md
t/APISIX.pm
t/chaos/setup_chaos_utils.sh
t/cli/test_access_log.sh
t/cli/test_prometheus.sh

change(prometheus): don't expose metrics to internet

---

docs/en/latest/admin-api.md
docs/zh/latest/admin-api.md

docs: add more SSL confugration examples

---

.github/workflows/misc-checker.yml

ci: fix broken misspell check

---

apisix/plugins/serverless/init.lua
docs/en/latest/plugins/serverless.md
docs/zh/latest/plugins/serverless.md
t/plugin/serverless.t

feat(serverless): pass conf & ctx to the functions

---

docs/es/latest/FAQ.md

Translates the FAQ to Spanish.
refs #3587

feat: add Spanish translation of the FAQ

---

README.md
docs/es/latest/README.md
docs/zh/latest/README.md

Adds all the communication channels to the README's in the table.

docs: add Slack to the communication channels

---

t/core/ctx.t

test: show how to fetch special cookie which is not supported by Nginx

---

apisix/cli/ngx_tpl.lua
apisix/plugins/prometheus.lua
t/cli/test_prometheus.sh

fix(prometheus): collect nginx_status and return the body

---

t/discovery/consul_kv.t

Remove the flaky part. The rest of the test already checks the register/unregister scene.

test: rewrite flaky consul_kv case

---

apisix/admin/routes.lua
apisix/admin/services.lua
apisix/admin/upstreams.lua
apisix/http/service.lua
apisix/router.lua
apisix/schema_def.lua
apisix/ssl.lua
apisix/ssl/router/radixtree_sni.lua
apisix/upstream.lua
docs/en/latest/admin-api.md
docs/zh/latest/admin-api.md
t/APISIX.pm
t/config-center-yaml/route-upstream.t
t/node/upstream-mtls.t

feat: support upstream mTLS

---

apisix/core/ctx.lua
t/core/ctx2.t

feat: new way to cache ctx.var

---

ci/common.sh
ci/linux_apisix_current_luarocks_runner.sh
utils/centos7-ci.sh

ci: retry make deps

---

apisix/core/config_yaml.lua
apisix/init.lua
apisix/plugin.lua

fix(standalone): the conf should be available during start

---

.github/workflows/fuzzing-ci.yaml
ci/linux_apisix_master_luarocks_runner.sh
ci/linux_openresty_common_runner.sh
ci/linux_openresty_mtls_runner.sh
ci/linux_tengine_runner.sh
utils/install-apisix.sh

ci: more retry on fetching lua rocks

---

apisix/plugins/limit-count/limit-count-redis.lua

fix: add code which is removed in #3991 by mistake.

---

t/node/upstream-websocket.t
utils/check-test-code-style.sh

test: add FIRST to the forbidden directives

---

apisix/init.lua
apisix/upstream.lua
ci/centos7-ci.sh
ci/common.sh
ci/linux_openresty_common_runner.sh
t/grpc-proxy-test.sh

feat: upstream grpcs support mTLS

---

README.md

Update contributor over time charts with automatic update support.

docs: add dynamic contributor over time chart

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/request-help.md

chore: ask for luarocks version if user ask questions about installation

---

docs/en/latest/health-check.md
docs/zh/latest/health-check.md

docs(health-check): more notes

---

apisix/core/ctx.lua
t/core/ctx2.t

feat: support to fetch balancer ip/port from ctx.var

---

apisix/plugins/jwt-auth.lua
docs/en/latest/plugins/jwt-auth.md
docs/zh/latest/plugins/jwt-auth.md
t/plugin/jwt-auth.t

Make jwt-auth support extension payload.
Fix #3594

feat: jwt-auth support extension payload

---

docs/en/latest/FAQ.md
docs/en/latest/admin-api.md
docs/zh/latest/FAQ.md
docs/zh/latest/admin-api.md

docs: added X-API-KEY introduction

---

apisix/api_router.lua
apisix/init.lua
apisix/plugin.lua
t/node/global-rule.t

fix: avoid being taint by empty global rule

---

.github/workflows/centos7-ci.yml
ci/install-ext-services-via-docker.sh
ci/linux_openresty_common_runner.sh
ci/linux_tengine_runner.sh

ci: remove duplicate external services installation

---

apisix/plugins/batch-requests.lua
apisix/plugins/consumer-restriction.lua
apisix/plugins/proxy-cache.lua
apisix/schema_def.lua

refactor: remove duplicate HTTP method schema definition

---

docs/en/latest/plugins/openid-connect.md
docs/zh/latest/plugins/openid-connect.md

docs(openid-connect): mention the token cache mechanism

---

apisix/plugins/skywalking.lua
conf/config-default.yaml
docs/en/latest/plugins/skywalking.md
docs/zh/latest/plugins/skywalking.md

feat: optimize skywalking instancename

---

docs/en/latest/config.json
docs/zh/latest/config.json

fix: [#321](https://github.com/apache/apisix-website/issues/321)

docs: add  batch processor in sidebar

---

.github/workflows/fuzzing-ci.yaml
utils/linux-install-luarocks.sh

chore: improve the debug experimence of the luarocks install script

---

docs/en/latest/discovery.md
docs/zh/latest/discovery.md

docs: Json Format Error

---

CHANGELOG.md

add incompatible info in CHANGELOG for version 2.5

docs: add incompatible info in CHANGELOG for version 2.5

---

docs/en/latest/how-to-build.md
docs/zh/latest/how-to-build.md

See https://lists.apache.org/thread.html/rc3a939b32de90f8acf8a324a21be2d66b62c805143e13b5efa9cde0d%40%3Cdev.apisix.apache.org%3E

docs: remove unrecommended installation

---

docs/en/latest/FAQ.md
docs/en/latest/config.json

fix: [#321](https://github.com/apache/apisix-website/issues/321#issuecomment-826569178)

docs: add plugin develop to sidebar

---

docs/en/latest/config.json
docs/en/latest/plugins/batch-requests.md
docs/en/latest/plugins/grpc-transcode.md
docs/zh/latest/FAQ.md
docs/zh/latest/config.json
docs/zh/latest/plugins/batch-requests.md

update doc with correct custom ids

docs: update docs with correct id

---

apisix/cli/ngx_tpl.lua
apisix/constants.lua
apisix/init.lua
apisix/plugins/ext-plugin/init.lua
conf/config-default.yaml
t/APISIX.pm
t/lib/ext-plugin.lua
t/plugin/ext-plugin/runner.sh
t/plugin/ext-plugin/sanity.t

feat: step 3, manage the plugin runner

---

apisix/plugins/ext-plugin/init.lua
t/lib/ext-plugin.lua
t/plugin/ext-plugin/sanity.t

feat(ext-plugin): handle error response

---

CODE_STYLE.md
LICENSE
README.md
docs/es/latest/README.md
docs/zh/latest/README.md
kubernetes/README.md

Remove unneeded blank line
refs #3586 
Standardizes the codebase and the "alt" attributes help blind people

chore: fix capitalization and image alt attributes

---

docs/en/latest/plugins/limit-count.md
docs/zh/latest/plugins/limit-count.md

docs: update limit-count.md to add redis_password in `redis-cluster` policy

---

docs/zh/latest/plugins/prometheus.md

docs: fix argument name for prometheus

---

apisix/plugins/ext-plugin/init.lua

perf(ext-plugin): use a better API to create byte vector

---

apisix/admin/ssl.lua
apisix/ssl.lua
apisix/ssl/router/radixtree_sni.lua
t/config-center-yaml/ssl.t

feat: validate ssl certificate and more in the DP

---

.github/workflows/code-lint.yml
ci/linux_openresty_common_runner.sh
ci/linux_openresty_mtls_runner.sh
ci/linux_tengine_runner.sh

ci: move code lint to separate job

---

.github/workflows/lint.yml
t/lib/test_admin.lua
t/node/remote-addr-ipv6.t

ci: remove whitelist of whitespace check

---

apisix/admin/global_rules.lua
apisix/admin/plugin_config.lua

chore: correct typo in the error msg

---

apisix/plugins/ext-plugin/init.lua
t/plugin/ext-plugin/http-req-call.t
t/plugin/ext-plugin/sanity.t

Also refactor part of the code.

chore(ext-plugin): avoid creating lrucache twice

---

t/plugin/log-rotate.t

test: make t/plugin/log-rotate.t stable

---

docs/en/latest/FAQ.md
docs/zh/latest/FAQ.md

How to allow all IPs to access the Admin API is a frequently asked question by users. Therefore, it is necessary for us to record it in the FAQ document.

docs: FAQ Add allow all IPs to access Admin API

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/request-help.md

chore: require issue author to provide information

---

apisix/balancer.lua
apisix/init.lua
apisix/upstream.lua
t/admin/upstream.t
t/node/upstream.t

feat: support passing different host headers in multiple nodes

---

apisix/cli/ngx_tpl.lua
t/APISIX.pm

fix: avoid 'using uninitialized "from_error_page" variable'

---

ci/install-ext-services-via-docker.sh

Let's try to see what happened

ci: remove redirect error when create nacos docker network, to see what happend

---

apisix/upstream.lua

chore(traffic-split): remove unnecessary warn

---

docs/en/latest/plugins/response-rewrite.md
docs/zh/latest/plugins/response-rewrite.md

[https://github.com/apache/apisix/issues/4259](https://github.com/apache/apisix/issues/4259)

docs(response-rewrite): fixed type error

---

Makefile

chore: add missing PHONY marks

---

apisix/cli/ngx_tpl.lua
conf/config-default.yaml
t/cli/test_main.sh

feat: support the configuration of keepalive related parameters in upstream

---

apisix/cli/ngx_tpl.lua

chore: don't run *_phase for Admin/Control API

---

docs/en/latest/FAQ.md
docs/zh/latest/FAQ.md

used etcd.conf.yaml , how to open grpc

docs: added etcd.conf.yml enable grpc gateway

---

conf/apisix.yaml

chore: remove stale yamllint comment

---

apisix/plugins/ext-plugin/init.lua
t/plugin/ext-plugin/sanity.t

feat(ext-plugin): respawn with delay to avoid flushing error log

---

conf/config-default.yaml
docs/en/latest/plugin-develop.md
docs/zh/latest/plugin-develop.md
t/core/config.t

chore: sort plugin by priority and recommend priority for custom plugin

---

CHANGELOG.md
README.md
apisix/core/version.lua
docs/ar/README.md
docs/en/latest/config.json
docs/en/latest/how-to-build.md
docs/es/latest/README.md
docs/es/latest/config.json
docs/zh/latest/CHANGELOG.md
docs/zh/latest/README.md
docs/zh/latest/config.json
docs/zh/latest/how-to-build.md
rockspec/apisix-2.6-0.rockspec

feat: release 2.6

---

docs/en/latest/FAQ.md
docs/zh/latest/FAQ.md

docs: show how to auto renew SSL cert via acme.sh

---

CONTRIBUTING.md

docs: update `make lint` output

---

apisix/plugins/ext-plugin/init.lua

chore(ext-plugin): remove useless `extra_info` field

---

conf/config-default.yaml

chore: show priority of stream plugins

---

docs/zh/latest/admin-api.md

docs: fix link in zh docs

---

docs/en/latest/install-dependencies.md
docs/zh/latest/install-dependencies.md

There are some missing parts in install-dependencies, luarocks need make, and luafilesystem need gcc.

docs: update install-dependencies

---

apisix/discovery/nacos.lua
apisix/schema_def.lua
docs/en/latest/discovery/nacos.md
t/discovery/nacos.t

feat: nacos discovery support group

---

t/config-center-yaml/plugin.t

test: make t/config-center-yaml/plugin.t stable

---

apisix/discovery/nacos.lua
docs/en/latest/discovery/nacos.md
t/discovery/nacos.t

perf: use events optimize nacos service discovery

---

apisix/plugins/ext-plugin-post-req.lua
apisix/plugins/ext-plugin-pre-req.lua
apisix/plugins/ext-plugin/init.lua
t/plugin/ext-plugin/sanity.t

fix(ext-plugin): missing schema check

---

apisix/core/etcd.lua

fix(etcd): check res.body.error before accessing the data

---

t/control/healthcheck.t

test: add case for default health status

---

apisix/schema_def.lua

Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
change consumer name's max length to match with route name.
ref:  https://github.com/apache/apisix-ingress-controller/pull/529

chore: change consumer name max length match with route name

---

README.md
docs/zh/latest/README.md

This PR aims to update the Slack invitation link.

docs: update Slack invitation link

---

apisix/discovery/consul_kv.lua

fix(discovery): typo in the consul_kv schema

---

apisix/admin/plugin_metadata.lua
apisix/core/schema.lua
apisix/plugins/batch-requests.lua
apisix/plugins/example-plugin.lua
apisix/plugins/http-logger.lua
apisix/plugins/skywalking.lua
t/plugin/error-log-logger.t

Now the schema validation is united.

change: check metadata_schema with check_schema like the other schema

---

apisix/stream/router/ip_port.lua
t/APISIX.pm
t/stream-node/sanity.t

fix(stream): skip route configuration tombstone

---

apisix/cli/etcd.lua
t/cli/test_etcd.sh

Fix https://github.com/apache/apisix/issues/3953

feat: add etcd retry when init

---

t/plugin/ext-plugin/sanity.t

test: make t/plugin/ext-plugin/sanity.t stable

---

apisix/init.lua
t/stream-node/upstream-domain.t

feat(stream): support domain in the upstream

---

docs/en/latest/architecture-design/debug-mode.md

docs: fix debug-mode documentation

---

apisix/schema_def.lua

refactor: avoid repeating the host regex pattern

---

docs/en/latest/admin-api.md
docs/zh/latest/admin-api.md

docs: fix broken links

---

conf/config-default.yaml

This comment will confuse users, users do not understand why a physical machine cannot exceed 8 processes

docs: removed comment of worker_processes.

---

docs/en/latest/external-plugin.md

docs: fix broken image link

---

apisix/init.lua
apisix/schema_def.lua
apisix/ssl/router/radixtree_sni.lua
apisix/stream/router/ip_port.lua
docs/en/latest/admin-api.md
docs/en/latest/stream-proxy.md
docs/zh/latest/admin-api.md
docs/zh/latest/stream-proxy.md
t/stream-node/sni.t

feat(stream): match route with SNI

---

docs/en/latest/health-check.md
docs/zh/latest/health-check.md
t/node/healthcheck-passive.t

docs: clarify why we require active health check

---

Makefile
docs/en/latest/how-to-build.md
docs/zh/latest/how-to-build.md

docs: show the graceful way to stop

---

apisix/cli/ngx_tpl.lua

fix: move lua_ssl_trusted_certificate to work with background timer

---

docs/en/latest/plugins/http-logger.md
docs/zh/latest/plugins/http-logger.md

In slack, people are asking
> hello, i want to use http logger plugin, but i don't understand what should i put in the uri , and how to view the logs?
So try to make docs runnable for beginners.

docs: use mockbin to view http logs for guidance

---

apisix/init.lua
t/stream-node/mtls.t

feat(stream): support client certificate verification

---

README.md
docs/zh/latest/README.md

docs: make README up-to-date

---

README.md
docs/en/latest/router-radixtree.md
docs/zh/latest/README.md

Add `Support filter route by graphql attributes` to readme

docs: add GraphQL support to readme

---

docs/zh/latest/README.md

docs: ensure the wechat QR codes are under the title

---

README.md
docs/zh/latest/README.md

docs: add external plugin support to readme

---

apisix/control/v1.lua
docs/en/latest/control-api.md
t/control/gc.t

feat(control-api): add a way to trigger gc

---

docs/en/latest/plugins/openid-connect.md
docs/zh/latest/plugins/openid-connect.md

docs(openid-connect): fix public key format

---

apisix/plugins/ext-plugin-post-req.lua
apisix/plugins/ext-plugin-pre-req.lua
apisix/plugins/ext-plugin/init.lua
t/plugin/ext-plugin/sanity.t

fix(ext-plugin): should use separate tokens for {pre,post}-req

---

docs/en/latest/FAQ.md
docs/zh/latest/FAQ.md

docs: add 'how to remove route prefix' in FAQ

---

CHANGELOG.md
README.md
apisix/core/version.lua
apisix/plugins/ext-plugin-post-req.lua
apisix/plugins/ext-plugin-pre-req.lua
apisix/plugins/ext-plugin/init.lua
docs/ar/README.md
docs/en/latest/config.json
docs/en/latest/how-to-build.md
docs/es/latest/README.md
docs/es/latest/config.json
docs/zh/latest/CHANGELOG.md
docs/zh/latest/README.md
docs/zh/latest/config.json
docs/zh/latest/how-to-build.md
rockspec/apisix-2.7-0.rockspec
t/plugin/ext-plugin/sanity.t

feat: release 2.7

---

apisix/patch.lua
t/misc/patch.t

feat: patch UDP socket to resolve host by ourselves

---

apisix/stream/plugins/mqtt-proxy.lua

chore: standardlize the way to exit from a stream plugin
